import { defineConfig } from 'tsup'

export default defineConfig({
  entry: ['src/09_autogenerated_typescript_project/index.ts'],
  format: ['esm', 'cjs'],
  outDir: 'dist',
  platform: 'neutral',
  target: 'es2022',
  dts: true,
  sourcemap: true,
  clean: true,
  splitting: true,
  external: ['node:*', '@sovereignbase/bytecodec'],
  outExtension({ format }) {
    return { js: format === 'cjs' ? '.cjs' : '.js' }
  },
})
