export default {
  people: {
    firstNames: [
      'James',
      'John',
      'Robert',
      'Michael',
      'William',
      'David',
      'Daniel',
      'Joseph',
      'Thomas',
      'Charles',
      'Christopher',
      'Matthew',
      'Anthony',
      'Mark',
      'Donald',
      'Steven',
      'Paul',
      'Andrew',
      'Joshua',
      'Kenneth',
      'Kevin',
      'Brian',
      'George',
      'Edward',
      'Ronald',
      'Timothy',
      'Jason',
      'Jeffrey',
      'Ryan',
      'Jacob',
      'Gary',
      'Nicholas',
      'Eric',
      'Jonathan',
      'Stephen',
      'Larry',
      'Justin',
      'Scott',
      'Brandon',
      'Benjamin',
      'Samuel',
      'Mason',
      'Jack',
      'Noah',
      'Henry',
      'Lucas',
      'Alexander',
      'Aiden',
      'Nathan',
      'Caleb',
      'Emma',
      'Olivia',
      'Sophia',
      'Charlotte',
      'Amelia',
      'Isabella',
      'Mia',
      'Harper',
      'Evelyn',
      'Grace',
      'Ava',
      'Lily',
      'Emily',
      'Abigail',
      'Ella',
      'Sofia',
      'Scarlett',
      'Victoria',
      'Madison',
      'Aria',
      'Chloe',
      'Camila',
      'Penelope',
      'Layla',
      'Riley',
      'Zoey',
      'Nora',
      'Hannah',
      'Leah',
    ],
    lastNames: [
      'Smith',
      'Johnson',
      'Williams',
      'Brown',
      'Jones',
      'Miller',
      'Davis',
      'Garcia',
      'Rodriguez',
      'Wilson',
      'Anderson',
      'Thomas',
      'Taylor',
      'Moore',
      'Jackson',
      'Martin',
      'Lee',
      'Perez',
      'Thompson',
      'White',
      'Harris',
      'Sanchez',
      'Clark',
      'Lewis',
      'Robinson',
      'Walker',
      'Young',
      'King',
      'Wright',
      'Scott',
      'Torres',
      'Nguyen',
      'Hill',
      'Flores',
      'Green',
      'Adams',
      'Nelson',
      'Baker',
      'Hall',
      'Rivera',
      'Campbell',
      'Mitchell',
      'Carter',
      'Roberts',
      'Gomez',
      'Phillips',
      'Evans',
      'Turner',
      'Diaz',
      'Parker',
      'Cruz',
      'Edwards',
      'Collins',
      'Reyes',
      'Stewart',
      'Morris',
      'Morales',
      'Murphy',
      'Cook',
      'Rogers',
      'Gutierrez',
      'Ortiz',
      'Morgan',
      'Cooper',
      'Peterson',
      'Bailey',
      'Reed',
      'Kelly',
      'Howard',
      'Ramos',
      'Kim',
      'Cox',
      'Ward',
      'Richardson',
      'Watson',
      'Brooks',
      'Wood',
      'Bennett',
      'Gray',
      'James',
    ],
    middleInitials: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split(''),
  },
  companies: {
    prefixes: [
      'Blue',
      'Prime',
      'Urban',
      'Golden',
      'North',
      'Green',
      'Silver',
      'Modern',
      'Bright',
      'Fresh',
      'Summit',
      'Harbor',
      'Oak',
      'Maple',
      'True',
      'Clear',
      'Metro',
      'Central',
      'Pioneer',
      'Royal',
      'Ever',
      'Open',
      'Grand',
      'First',
      'Main',
      'River',
      'Sky',
      'Stone',
      'West',
      'East',
      'South',
      'Northwest',
      'Northstar',
      'Park',
      'Lake',
      'Cedar',
      'Birch',
      'Elm',
      'Peak',
      'Vista',
      'Vertex',
      'Nova',
      'Luma',
      'Swift',
      'Reliable',
      'Trusted',
      'Horizon',
      'Crown',
      'Unity',
      'Anchor',
    ],
    roots: [
      'Market',
      'Supply',
      'Depot',
      'Kitchen',
      'Studio',
      'Works',
      'Collective',
      'Center',
      'Hub',
      'Services',
      'Store',
      'Outfitters',
      'Corner',
      'House',
      'Goods',
      'Trading',
      'Commerce',
      'Solutions',
      'Retail',
      'Wholesale',
      'Shop',
      'Warehouse',
      'Direct',
      'Express',
      'Digital',
      'Systems',
      'Partners',
      'Point',
      'Mart',
      'Cafe',
      'Bakery',
      'Pharmacy',
      'Grocer',
      'Office',
      'Hardware',
      'Logistics',
      'Labs',
      'Media',
      'Travel',
      'Energy',
      'Network',
      'Outlet',
      'Factory',
      'Boutique',
      'Distributors',
      'Provisions',
      'Station',
      'Kitchenware',
      'Mobility',
      'Consulting',
    ],
    suffixes: [
      'Ltd',
      'Inc',
      'LLC',
      'Co',
      'Group',
      'Partners',
      'Shop',
      'Labs',
      'PLC',
      'Holdings',
      'Corp',
      'Company',
      'Collective',
      'Network',
      'International',
      'Global',
      'Systems',
      'Ventures',
    ],
    logisticsPrefixes: [
      'Swift',
      'Rapid',
      'Trusted',
      'North',
      'Express',
      'Global',
      'Prime',
      'Parcel',
      'Quick',
      'Direct',
      'Eagle',
      'Arrow',
      'Summit',
      'Blue',
      'Reliable',
      'Jet',
      'Cargo',
      'Fleet',
      'Urban',
      'Continental',
    ],
    logisticsRoots: [
      'Logistics',
      'Parcel',
      'Delivery',
      'Freight',
      'Courier',
      'Transport',
      'Shipping',
      'Fulfillment',
      'Cargo',
      'Dispatch',
      'Air',
      'Ground',
      'Express',
      'Mail',
      'Carrier',
      'Distribution',
      'LastMile',
      'Forwarding',
    ],
    logisticsSuffixes: [
      'Ltd',
      'Co',
      'Group',
      'Services',
      'Network',
      'Systems',
      'Line',
      'Partners',
    ],
    businessTypes: [
      'Retail',
      'Hospitality',
      'Software',
      'Consumer Electronics',
      'Food Service',
      'Professional Services',
      'Travel',
      'Health and Wellness',
      'Home Goods',
      'Office Supply',
      'Logistics',
      'E-commerce',
      'Subscription Services',
      'Entertainment',
      'Education',
      'Telecommunications',
      'Automotive Services',
      'Beauty and Personal Care',
      'Industrial Supply',
      'Specialty Grocery',
    ],
    domains: [
      '.com',
      '.co',
      '.shop',
      '.store',
      '.app',
      '.io',
      '.biz',
      '.online',
      '.market',
      '.group',
      '.solutions',
      '.global',
    ],
    suiteLabels: ['Suite', 'Unit', 'Floor', 'Level', 'Apt', 'Office'],
  },
  geography: {
    locales: [
      {
        countryName: 'United States',
        countryCode: 'US',
        currency: { code: 'USD', symbol: '$' },
        phoneFormats: ['+1 ###-###-####'],
        postalFormats: ['#####'],
        taxIdFormats: ['##-#######'],
        cities: [
          {
            name: 'New York',
            region: 'New York',
            streets: [
              'Broadway',
              'Fifth Avenue',
              'Madison Avenue',
              'Hudson Street',
              'Park Avenue',
              'Lexington Avenue',
            ],
          },
          {
            name: 'Chicago',
            region: 'Illinois',
            streets: [
              'Michigan Avenue',
              'Clark Street',
              'Lake Street',
              'Wabash Avenue',
              'State Street',
              'Randolph Street',
            ],
          },
          {
            name: 'Austin',
            region: 'Texas',
            streets: [
              'Congress Avenue',
              'Lamar Boulevard',
              'Riverside Drive',
              'Burnet Road',
              'Guadalupe Street',
              'Cesar Chavez Street',
            ],
          },
          {
            name: 'Seattle',
            region: 'Washington',
            streets: [
              'Pine Street',
              'Pike Street',
              'Aurora Avenue',
              'University Way',
              'Alaskan Way',
              'Rainier Avenue',
            ],
          },
        ],
      },
      {
        countryName: 'Canada',
        countryCode: 'CA',
        currency: { code: 'CAD', symbol: 'CA$' },
        phoneFormats: ['+1 ###-###-####'],
        postalFormats: ['A#A #A#'],
        taxIdFormats: ['#########RT####'],
        cities: [
          {
            name: 'Toronto',
            region: 'Ontario',
            streets: [
              'Queen Street',
              'King Street',
              'Bloor Street',
              'Spadina Avenue',
              'Dundas Street',
              'Front Street',
            ],
          },
          {
            name: 'Vancouver',
            region: 'British Columbia',
            streets: [
              'Granville Street',
              'Robson Street',
              'Main Street',
              'Broadway',
              'Georgia Street',
              'Cambie Street',
            ],
          },
          {
            name: 'Calgary',
            region: 'Alberta',
            streets: [
              'Stephen Avenue',
              'Centre Street',
              '17 Avenue',
              'Macleod Trail',
              'Kensington Road',
            ],
          },
        ],
      },
      {
        countryName: 'United Kingdom',
        countryCode: 'GB',
        currency: { code: 'GBP', symbol: 'GBP' },
        phoneFormats: ['+44 20 #### ####', '+44 1### ######'],
        postalFormats: ['AA# #AA', 'AA## #AA'],
        taxIdFormats: ['GB#########'],
        cities: [
          {
            name: 'London',
            region: 'England',
            streets: [
              'Baker Street',
              'Fleet Street',
              'Kings Road',
              'Piccadilly',
              'Oxford Street',
              'Regent Street',
            ],
          },
          {
            name: 'Manchester',
            region: 'England',
            streets: [
              'Deansgate',
              'Oxford Road',
              'Market Street',
              'Mosley Street',
              'Portland Street',
              'Whitworth Street',
            ],
          },
          {
            name: 'Edinburgh',
            region: 'Scotland',
            streets: [
              'Princes Street',
              'George Street',
              'Royal Mile',
              'Leith Walk',
              'Grassmarket',
              'Lothian Road',
            ],
          },
        ],
      },
      {
        countryName: 'Ireland',
        countryCode: 'IE',
        currency: { code: 'EUR', symbol: 'EUR' },
        phoneFormats: ['+353 1 ### ####', '+353 ## ### ####'],
        postalFormats: ['A## A###'],
        taxIdFormats: ['#######A'],
        cities: [
          {
            name: 'Dublin',
            region: 'Leinster',
            streets: [
              'Grafton Street',
              'Baggot Street',
              'OConnell Street',
              'Dawson Street',
              'Talbot Street',
              'Parnell Street',
            ],
          },
          {
            name: 'Cork',
            region: 'Munster',
            streets: [
              'Patrick Street',
              'Oliver Plunkett Street',
              'South Mall',
              'Grand Parade',
              'Washington Street',
            ],
          },
        ],
      },
      {
        countryName: 'Australia',
        countryCode: 'AU',
        currency: { code: 'AUD', symbol: 'A$' },
        phoneFormats: ['+61 # #### ####', '+61 2 #### ####'],
        postalFormats: ['####'],
        taxIdFormats: ['## ### ### ###'],
        cities: [
          {
            name: 'Sydney',
            region: 'New South Wales',
            streets: [
              'George Street',
              'Pitt Street',
              'Oxford Street',
              'Castlereagh Street',
              'Kent Street',
              'York Street',
            ],
          },
          {
            name: 'Melbourne',
            region: 'Victoria',
            streets: [
              'Collins Street',
              'Swanston Street',
              'Bourke Street',
              'Flinders Lane',
              'Lonsdale Street',
              'Elizabeth Street',
            ],
          },
          {
            name: 'Brisbane',
            region: 'Queensland',
            streets: [
              'Queen Street',
              'Adelaide Street',
              'George Street',
              'Boundary Street',
              'Roma Street',
            ],
          },
        ],
      },
      {
        countryName: 'New Zealand',
        countryCode: 'NZ',
        currency: { code: 'NZD', symbol: 'NZ$' },
        phoneFormats: ['+64 # ### ####', '+64 9 ### ####'],
        postalFormats: ['####'],
        taxIdFormats: ['###-###-###'],
        cities: [
          {
            name: 'Auckland',
            region: 'Auckland',
            streets: [
              'Queen Street',
              'Karangahape Road',
              'Ponsonby Road',
              'Symonds Street',
              'Dominion Road',
            ],
          },
          {
            name: 'Wellington',
            region: 'Wellington',
            streets: [
              'Lambton Quay',
              'Cuba Street',
              'Willis Street',
              'Courtenay Place',
              'The Terrace',
            ],
          },
        ],
      },
      {
        countryName: 'Singapore',
        countryCode: 'SG',
        currency: { code: 'SGD', symbol: 'S$' },
        phoneFormats: ['+65 #### ####'],
        postalFormats: ['######'],
        taxIdFormats: ['########A'],
        cities: [
          {
            name: 'Singapore',
            region: 'Central',
            streets: [
              'Orchard Road',
              'Raffles Place',
              'Serangoon Road',
              'Bencoolen Street',
              'Cecil Street',
              'Shenton Way',
            ],
          },
        ],
      },
      {
        countryName: 'India',
        countryCode: 'IN',
        currency: { code: 'INR', symbol: 'INR' },
        phoneFormats: ['+91 ##### #####'],
        postalFormats: ['######'],
        taxIdFormats: ['##AAAAA####A#Z#'],
        cities: [
          {
            name: 'Bengaluru',
            region: 'Karnataka',
            streets: [
              'MG Road',
              'Brigade Road',
              'Residency Road',
              'Church Street',
              'Koramangala Main Road',
              'Bannerghatta Road',
            ],
          },
          {
            name: 'Mumbai',
            region: 'Maharashtra',
            streets: [
              'Marine Drive',
              'Linking Road',
              'Hill Road',
              'SV Road',
              'Colaba Causeway',
              'Pedder Road',
            ],
          },
          {
            name: 'New Delhi',
            region: 'Delhi',
            streets: [
              'Connaught Place',
              'Janpath',
              'Lodhi Road',
              'Ring Road',
              'Nehru Place',
              'Karol Bagh Road',
            ],
          },
        ],
      },
    ],
  },
  commerce: {
    paymentMethods: [
      { display: 'Cash', schemaUrl: 'https://schema.org/Cash' },
      { display: 'Visa', schemaUrl: 'https://schema.org/CreditCard' },
      { display: 'Mastercard', schemaUrl: 'https://schema.org/CreditCard' },
      { display: 'American Express', schemaUrl: 'https://schema.org/CreditCard' },
      { display: 'Discover', schemaUrl: 'https://schema.org/CreditCard' },
      { display: 'Debit Card', schemaUrl: 'https://schema.org/CreditCard' },
      { display: 'Bank Transfer', schemaUrl: 'https://schema.org/ByBankTransferInAdvance' },
      { display: 'PayPal', schemaUrl: 'https://schema.org/ByBankTransferInAdvance' },
      { display: 'Apple Pay', schemaUrl: 'https://schema.org/CreditCard' },
      { display: 'Google Pay', schemaUrl: 'https://schema.org/CreditCard' },
      { display: 'Gift Card', schemaUrl: 'https://schema.org/PaymentMethod' },
      { display: 'Store Credit', schemaUrl: 'https://schema.org/PaymentMethod' },
    ],
    paymentStatuses: [
      { display: 'Paid', schemaUrl: 'https://schema.org/PaymentComplete' },
      { display: 'Due', schemaUrl: 'https://schema.org/PaymentDue' },
      { display: 'Payment Pending', schemaUrl: 'https://schema.org/PaymentDue' },
      { display: 'Partially Paid', schemaUrl: 'https://schema.org/PaymentDue' },
    ],
    orderStatuses: {
      default: [
        { display: 'Processing', schemaUrl: 'https://schema.org/OrderProcessing' },
        { display: 'Pickup Available', schemaUrl: 'https://schema.org/OrderPickupAvailable' },
        { display: 'Order Problem', schemaUrl: 'https://schema.org/OrderProblem' },
      ],
      shipping: [
        { display: 'In Transit', schemaUrl: 'https://schema.org/OrderInTransit' },
        { display: 'Delivered', schemaUrl: 'https://schema.org/OrderDelivered' },
        { display: 'Order Problem', schemaUrl: 'https://schema.org/OrderProblem' },
      ],
      service: [
        { display: 'Processing', schemaUrl: 'https://schema.org/OrderProcessing' },
        { display: 'Delivered', schemaUrl: 'https://schema.org/OrderDelivered' },
      ],
    },
    serviceModes: [
      'Dine In',
      'Takeaway',
      'Delivery',
      'Pickup',
      'Online',
      'Subscription',
      'Curbside',
      'In Store',
      'Remote',
      'Scheduled Service',
    ],
    receiptTypes: [
      'Sales Receipt',
      'Order Confirmation',
      'Checkout Summary',
      'Shipment Notice',
      'Service Confirmation',
      'Pickup Notice',
      'Subscription Renewal',
      'Tax Invoice',
      'Dispatch Summary',
      'Payment Receipt',
    ],
    ranges: {
      discountPercent: { min: 0, max: 100, decimals: 0 },
      promoPercent: { min: 1, max: 100, decimals: 0 },
      taxPercent: {
        default: { min: 0, max: 25, decimals: 2 },
        service: { min: 0, max: 30, decimals: 2 },
      },
      productQuantity: { min: 1, max: 8 },
      serviceQuantity: { min: 1, max: 2 },
    },
    promoPrefixes: [
      'SAVE',
      'DEAL',
      'PROMO',
      'WELCOME',
      'FIRST',
      'VIP',
      'SPRING',
      'SUMMER',
      'WINTER',
      'SHIP',
      'BUNDLE',
      'APP',
      'WEB',
      'FLASH',
      'HOT',
      'MEGA',
      'BONUS',
      'REWARD',
      'EARLY',
      'SMART',
    ],
    promoThemes: [
      'NOW',
      'FAST',
      'PLUS',
      'BOOST',
      'FREESHIP',
      'ONLINE',
      'CHECKOUT',
      'WELCOME',
      'LOYAL',
      'HOLIDAY',
      'LIMITED',
      'EXTRA',
      'DIRECT',
      'MEMBER',
      'STORE',
      'LAUNCH',
      'DELUXE',
      'WEEKEND',
      'NIGHT',
      'DROP',
    ],
    emailDomains: [
      'example.com',
      'example.co',
      'shop.example',
      'orders.example',
      'mail.example',
      'checkout.example',
      'billing.example',
      'support.example',
      'service.example',
      'receipts.example',
    ],
  },
}
