import firstnames from '../../shared/firstnames'
import lastnames from '../../shared/lastnames'

export default {
  people: {
    firstNames: firstnames,
    lastNames: lastnames,
    middleInitials: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split(''),
  },
  companies: {
    prefixes: [
      'Able',
      'Absolute',
      'Accurate',
      'Active',
      'Adaptive',
      'Advance',
      'Advanced',
      'Aero',
      'Agile',
      'Air',
      'Albion',
      'Alpha',
      'Alpine',
      'Amber',
      'American',
      'Anchor',
      'Ancient',
      'Apex',
      'Apollo',
      'Arc',
      'Arbor',
      'Arctic',
      'Arrow',
      'Ascent',
      'Aspen',
      'Atlas',
      'Atlantic',
      'Atomic',
      'Aurora',
      'Autumn',
      'Avenue',
      'Axis',
      'Baker',
      'Balanced',
      'Banner',
      'Beacon',
      'Bell',
      'Benchmark',
      'Best',
      'Better',
      'Beyond',
      'Big',
      'Birch',
      'Black',
      'Blue',
      'Bold',
      'Bonus',
      'Boost',
      'Border',
      'Brave',
      'Bright',
      'Brisk',
      'Broad',
      'Brook',
      'Build',
      'Busy',
      'Calm',
      'Capital',
      'Care',
      'Cargo',
      'Cedar',
      'Central',
      'Century',
      'Champion',
      'Channel',
      'Charter',
      'Chief',
      'Choice',
      'Cinder',
      'Circle',
      'Citi',
      'Civic',
      'Classic',
      'Clear',
      'Clearwater',
      'Clever',
      'Cloud',
      'Coastal',
      'Coastline',
      'Cold',
      'Colonial',
      'Comfort',
      'Common',
      'Compass',
      'Complete',
      'Concord',
      'Connect',
      'Continental',
      'Core',
      'Cornerstone',
      'Cosmic',
      'Country',
      'County',
      'Craft',
      'Crest',
      'Crown',
      'Crystal',
      'Current',
      'Daily',
      'Dawn',
      'Day',
      'Deep',
      'Delta',
      'Dependable',
      'Desert',
      'Direct',
      'Discovery',
      'Distinct',
      'Double',
      'Downtown',
      'Dynamic',
      'Eagle',
      'Early',
      'East',
      'Eastern',
      'Easy',
      'Echo',
      'Eco',
      'Edge',
      'Elite',
      'Elm',
      'Emerald',
      'Empire',
      'Endless',
      'Enduring',
      'Energy',
      'Epic',
      'Essential',
      'Ever',
      'Evergreen',
      'Excel',
      'Excellence',
      'Executive',
      'Express',
      'Fair',
      'Fairview',
      'Falcon',
      'Family',
      'Far',
      'Fast',
      'Federal',
      'Field',
      'Fine',
      'Finest',
      'First',
      'Five',
      'Fleet',
      'Flex',
      'Fluent',
      'Flying',
      'Focus',
      'Forest',
      'Forge',
      'Forward',
      'Foundry',
      'Four',
      'Fox',
      'Franchise',
      'Franklin',
      'Freedom',
      'Fresh',
      'Friendly',
      'Frontier',
      'Full',
      'Future',
      'Galaxy',
      'Gateway',
      'General',
      'Genuine',
      'Giant',
      'Global',
      'Globe',
      'Glow',
      'Gold',
      'Golden',
      'Good',
      'Grand',
      'Granite',
      'Great',
      'Green',
      'Greenwood',
      'Grey',
      'Ground',
      'Growing',
      'Harbor',
      'Harmony',
      'Harvest',
      'Haven',
      'Hawkeye',
      'Healthy',
      'Heartland',
      'Height',
      'Helix',
      'Heritage',
      'High',
      'Highland',
      'Hill',
      'Hillside',
      'Horizon',
      'Hudson',
      'Human',
      'Ideal',
      'Imperial',
      'Independent',
      'Infinity',
      'Initial',
      'Inner',
      'Insight',
      'Instant',
      'Integrated',
      'Integrity',
      'Intelligent',
      'Inter',
      'Interstate',
      'Iron',
      'Island',
      'Jet',
      'Joy',
      'Jubilee',
      'Junction',
      'Just',
      'Keystone',
      'Kind',
      'King',
      'Kingdom',
      'Lake',
      'Lakeside',
      'Landmark',
      'Lark',
      'Launch',
      'Lead',
      'Leading',
      'Legacy',
      'Level',
      'Liberty',
      'Light',
      'Lighthouse',
      'Linear',
      'Lion',
      'Little',
      'Live',
      'Living',
      'Local',
      'Lone',
      'Long',
      'Loyal',
      'Luma',
      'Lumen',
      'Lunar',
      'Lux',
      'Luxury',
      'Main',
      'Majestic',
      'Major',
      'Maple',
      'Marble',
      'Marine',
      'Master',
      'Matrix',
      'Maximum',
      'Meadow',
      'Mega',
      'Metro',
      'Mid',
      'Midland',
      'Mighty',
      'Mill',
      'Mindful',
      'Mission',
      'Modern',
      'Momentum',
      'Monarch',
      'Moon',
      'Morning',
      'Mountain',
      'National',
      'Native',
      'Natural',
      'Navy',
      'Near',
      'Neighborhood',
      'Neo',
      'Nest',
      'New',
      'Newtown',
      'Next',
      'Noble',
      'North',
      'Northeast',
      'Northern',
      'Northstar',
      'Northwest',
      'Nova',
      'Oak',
      'Ocean',
      'Old',
      'Olive',
      'Olympic',
      'Omni',
      'One',
      'Open',
      'Optimal',
      'Optimum',
      'Orange',
      'Orbit',
      'Original',
      'Outer',
      'Pacific',
      'Park',
      'Parkside',
      'Path',
      'Patriot',
      'Peak',
      'Pearl',
      'Perfect',
      'Pinnacle',
      'Pioneer',
      'Platinum',
      'Pleasant',
      'Plus',
      'Point',
      'Polar',
      'Popular',
      'Port',
      'Positive',
      'Power',
      'Prairie',
      'Precision',
      'Preferred',
      'Premier',
      'Premium',
      'Presence',
      'Prestige',
      'Prime',
      'Principal',
      'Priority',
      'Private',
      'Pro',
      'Progress',
      'Prosper',
      'Prosperity',
      'Proud',
      'Pure',
      'Purple',
      'Quick',
      'Quiet',
      'Radiant',
      'Rapid',
      'Raven',
      'Reach',
      'Ready',
      'Real',
      'Red',
      'Redwood',
      'Regional',
      'Reliable',
      'Renew',
      'Reserve',
      'Resolute',
      'Resource',
      'Responsive',
      'Rich',
      'Ridge',
      'River',
      'Riverside',
      'Road',
      'Robust',
      'Rock',
      'Rocky',
      'Royal',
      'Ruby',
      'Rural',
      'Sage',
      'Safe',
      'Sail',
      'Saint',
      'Sand',
      'Savvy',
      'Scale',
      'Sea',
      'Seaside',
      'Secure',
      'Select',
      'Seven',
      'Shadow',
      'Sharp',
      'Shield',
      'Shine',
      'Shore',
      'Shoreline',
      'Sierra',
      'Signal',
      'Silver',
      'Simple',
      'Sky',
      'Slate',
      'Smart',
      'Solid',
      'South',
      'Southeast',
      'Southern',
      'Southwest',
      'Spark',
      'Special',
      'Spectrum',
      'Speed',
      'Spirit',
      'Spring',
      'Springfield',
      'Spruce',
      'Stable',
      'Standard',
      'Star',
      'State',
      'Steady',
      'Steel',
      'Sterling',
      'Stillwater',
      'Stone',
      'Storm',
      'Strategic',
      'Strong',
      'Summit',
      'Sun',
      'Sunrise',
      'Sunset',
      'Superior',
      'Super',
      'Swift',
      'Table',
      'Tall',
      'Target',
      'Team',
      'Tech',
      'Ten',
      'Terra',
      'Thrive',
      'Thunder',
      'Timber',
      'Top',
      'Total',
      'Town',
      'Townline',
      'Trade',
      'Trail',
      'Trans',
      'Travel',
      'Tree',
      'True',
      'Trusted',
      'Twin',
      'Ultra',
      'Unified',
      'Union',
      'Unity',
      'Universal',
      'Urban',
      'Valley',
      'Value',
      'Vanguard',
      'Vector',
      'Velocity',
      'Venture',
      'Vertex',
      'Victory',
      'View',
      'Village',
      'Vintage',
      'Vista',
      'Vital',
      'Volt',
      'Wave',
      'Way',
      'Wealth',
      'West',
      'Western',
      'White',
      'Whole',
      'Wild',
      'Willow',
      'Wind',
      'Winter',
      'Wise',
      'Wonder',
      'Wood',
      'Woodland',
      'World',
      'Worth',
      'Yield',
      'Young',
      'Zenith',
      'Zero',
    ],
    roots: [
      'Accessories',
      'Accounting',
      'Advisors',
      'Agency',
      'Analytics',
      'Apparel',
      'Appliances',
      'Architects',
      'Architecture',
      'Artisans',
      'Atelier',
      'Automotive',
      'Bakery',
      'Bar',
      'Beauty',
      'Bistro',
      'Books',
      'Brands',
      'Brewing',
      'Builders',
      'Burgers',
      'Business',
      'Cafe',
      'Capital',
      'Care',
      'Catering',
      'Center',
      'Central',
      'Chocolates',
      'Cinema',
      'Clinic',
      'Clothing',
      'Coffee',
      'Collective',
      'Commerce',
      'Communications',
      'Concepts',
      'Concierge',
      'Consulting',
      'Corner',
      'Craft',
      'Creative',
      'Cuisine',
      'Cycles',
      'Data',
      'Decor',
      'Delivery',
      'Den',
      'Depot',
      'Design',
      'Desserts',
      'Developers',
      'Development',
      'Devices',
      'Digital',
      'Diner',
      'Dining',
      'Direct',
      'Distributors',
      'District',
      'Drinks',
      'Dynamics',
      'Eatery',
      'Electrics',
      'Electronics',
      'Emporium',
      'Energy',
      'Engineers',
      'Engineering',
      'Enterprises',
      'Essentials',
      'Estates',
      'Events',
      'Exchange',
      'Express',
      'Factory',
      'Fashion',
      'Finance',
      'Financial',
      'Fitness',
      'Foods',
      'Footwear',
      'Foundry',
      'Freight',
      'Fuels',
      'Furnishings',
      'Furniture',
      'Gallery',
      'Garden',
      'Gifts',
      'Global',
      'Goods',
      'Grocer',
      'Group',
      'Growers',
      'Hardware',
      'Health',
      'Home',
      'Hospitality',
      'Host',
      'House',
      'Hub',
      'Industries',
      'Informatics',
      'Innovations',
      'Insights',
      'Insurance',
      'Interiors',
      'Inventory',
      'Investment',
      'Investments',
      'Jewelry',
      'Joint',
      'Junction',
      'Kitchen',
      'Kitchenware',
      'Lab',
      'Labs',
      'Lifestyle',
      'Lighting',
      'Lines',
      'Living',
      'Logistics',
      'Lounge',
      'Machinery',
      'Maintenance',
      'Management',
      'Manufacturing',
      'Market',
      'Marketing',
      'Mart',
      'Materials',
      'Media',
      'Medical',
      'Merchants',
      'Merchandise',
      'Metals',
      'Mobility',
      'Motors',
      'Network',
      'Networks',
      'Nutrition',
      'Office',
      'Operations',
      'Optics',
      'Organics',
      'Outfitters',
      'Outlet',
      'Packaging',
      'Paint',
      'Pantry',
      'Paper',
      'Partners',
      'Patio',
      'Petcare',
      'Pets',
      'Pharmacy',
      'Phone',
      'Photo',
      'Pictures',
      'Pizza',
      'Place',
      'Platform',
      'Plaza',
      'Point',
      'Power',
      'Press',
      'Print',
      'Printing',
      'Produce',
      'Products',
      'Professionals',
      'Provisions',
      'Pub',
      'Publishing',
      'Realty',
      'Records',
      'Refreshments',
      'Remedies',
      'Rental',
      'Rentals',
      'Repair',
      'Research',
      'Reserve',
      'Resources',
      'Restaurant',
      'Retail',
      'Roasters',
      'Room',
      'Salon',
      'Sciences',
      'Services',
      'Shoes',
      'Shop',
      'Showroom',
      'Skincare',
      'Software',
      'Source',
      'Space',
      'Specialists',
      'Sports',
      'Station',
      'Store',
      'Strategies',
      'Strategy',
      'Streaming',
      'Studio',
      'Studios',
      'Style',
      'Supply',
      'Support',
      'Surplus',
      'Systems',
      'Table',
      'Tavern',
      'Technologies',
      'Technology',
      'Telecom',
      'Textiles',
      'Theater',
      'Threads',
      'Tools',
      'Tours',
      'Town',
      'Trade',
      'Trading',
      'Transit',
      'Transport',
      'Travel',
      'Treasures',
      'Trends',
      'Trucking',
      'Utilities',
      'Ventures',
      'Venue',
      'Vision',
      'Warehouse',
      'Warehousing',
      'Wellness',
      'Wholesale',
      'Wine',
      'Wireless',
      'Works',
      'Workshop',
      'World',
      'Zone',
    ],
    suffixes: [
      'Ltd',
      'Limited',
      'Inc',
      'Incorporated',
      'LLC',
      'L.L.C.',
      'LLP',
      'L.L.P.',
      'LP',
      'L.P.',
      'PLC',
      'P.L.C.',
      'Corp',
      'Corporation',
      'Co',
      'Co.',
      'Company',
      'Companies',
      'Group',
      'Partners',
      'Partnership',
      'Associates',
      'Alliance',
      'Brands',
      'Ventures',
      'Holdings',
      'Enterprises',
      'Industries',
      'International',
      'Global',
      'Worldwide',
      'World',
      'Network',
      'Networks',
      'Systems',
      'Solutions',
      'Services',
      'Consulting',
      'Consultants',
      'Advisors',
      'Capital',
      'Management',
      'Investments',
      'Trading',
      'Commerce',
      'Retail',
      'Wholesale',
      'Distribution',
      'Distributors',
      'Logistics',
      'Transport',
      'Shipping',
      'Express',
      'Direct',
      'Supply',
      'Supplies',
      'Outlet',
      'Mart',
      'Store',
      'Shop',
      'Depot',
      'Hub',
      'Center',
      'Centre',
      'Point',
      'House',
      'Works',
      'Studio',
      'Studios',
      'Lab',
      'Labs',
      'Collective',
      'Guild',
      'Office',
      'Agency',
      'Media',
      'Digital',
      'Technologies',
      'Technology',
      'Tech',
      'Software',
      'Data',
      'Analytics',
      'Dynamics',
      'Energy',
      'Power',
      'Mobility',
      'Travel',
      'Foods',
      'Bakery',
      'Cafe',
      'Kitchen',
      'Kitchenware',
      'Pharmacy',
      'Grocer',
      'Hardware',
      'Factory',
      'Station',
      'Provisions',
      'Goods',
      'Outfitters',
      'Boutique',
      'Warehouse',
      'Ventures International',
      'Global Group',
      'International Group',
      'Group International',
      'Network Solutions',
      'Business Solutions',
      'Business Services',
      'Professional Services',
      'Consumer Products',
      'Commercial Services',
      'Industrial Supply',
      'Trading Co',
      'Trading Co.',
      'Supply Co',
      'Supply Co.',
      'Holding Company',
      'Investment Group',
      'Capital Partners',
      'Equity Partners',
      'Advisory Group',
      'Consulting Group',
      'Services Group',
      'Solutions Group',
      'Systems Group',
      'Retail Group',
      'Wholesale Group',
      'Logistics Group',
      'Distribution Group',
      'Technology Group',
      'Media Group',
      'Digital Group',
      'Studio Group',
      'Lab Group',
      'Works Group',
      'House Group',
      'Brands Group',
      'Ventures Group',
      'Enterprises Group',
    ],
    logisticsPrefixes: [
      'Aero',
      'Air',
      'Alliance',
      'Alpha',
      'Anchor',
      'Apex',
      'Arrow',
      'Atlas',
      'Beacon',
      'Blue',
      'Bridge',
      'Cargo',
      'Carrier',
      'Central',
      'Continental',
      'Courier',
      'Crest',
      'Cross',
      'Delta',
      'Direct',
      'Eagle',
      'East',
      'Eastern',
      'Edge',
      'Elite',
      'Empire',
      'Ever',
      'Excel',
      'Express',
      'Falcon',
      'Fast',
      'First',
      'Fleet',
      'Flow',
      'Forward',
      'Frontline',
      'Gateway',
      'Global',
      'Gold',
      'Golden',
      'Grand',
      'Great',
      'Ground',
      'Harbor',
      'Horizon',
      'Inter',
      'Interstate',
      'Iron',
      'Jet',
      'Key',
      'Land',
      'Line',
      'Link',
      'Main',
      'Metro',
      'National',
      'Next',
      'North',
      'Northeast',
      'Northern',
      'Northstar',
      'Northwest',
      'Ocean',
      'Omega',
      'Pacific',
      'Parcel',
      'Peak',
      'Pioneer',
      'Prime',
      'Priority',
      'Pro',
      'Quick',
      'Rapid',
      'Regional',
      'Reliable',
      'Road',
      'Route',
      'Royal',
      'Rush',
      'Secure',
      'Silver',
      'Sky',
      'South',
      'Southeast',
      'Southern',
      'Southwest',
      'Speed',
      'Star',
      'State',
      'Stream',
      'Summit',
      'Swift',
      'Titan',
      'Total',
      'Transit',
      'True',
      'Trusted',
      'Turbo',
      'Union',
      'United',
      'Universal',
      'Urban',
      'Value',
      'Vector',
      'Velocity',
      'Venture',
      'Vertex',
      'Victory',
      'West',
      'Western',
      'World',
      'Worldwide',
    ],
    logisticsRoots: [
      'Air',
      'Airlift',
      'Cargo',
      'Carrier',
      'Carriers',
      'Courier',
      'Couriers',
      'Delivery',
      'Deliveries',
      'Dispatch',
      'Distribution',
      'Express',
      'Fleet',
      'Forwarding',
      'Freight',
      'Fulfillment',
      'Ground',
      'Haulage',
      'LastMile',
      'Linehaul',
      'Lines',
      'Link',
      'Links',
      'Logistics',
      'Mail',
      'Messenger',
      'Mobility',
      'Moving',
      'Parcel',
      'Parcels',
      'Post',
      'Road',
      'Routing',
      'Service',
      'Services',
      'Shipment',
      'Shipments',
      'Shipping',
      'Shuttle',
      'SupplyChain',
      'Transport',
      'Transportation',
      'Transit',
      'Trucking',
      'Van',
      'Warehousing',
    ],
    logisticsSuffixes: [
      'Ltd',
      'Limited',
      'Co',
      'Co.',
      'Company',
      'Companies',
      'Group',
      'Services',
      'Service',
      'Network',
      'Networks',
      'Systems',
      'System',
      'Line',
      'Lines',
      'Partners',
      'Partnership',
      'Associates',
      'Alliance',
      'Holdings',
      'Logistics',
      'Transport',
      'Transportation',
      'Shipping',
      'Freight',
      'Cargo',
      'Courier',
      'Delivery',
      'Distribution',
      'Dispatch',
      'Forwarding',
      'Fulfillment',
      'Carrier',
      'Carriers',
      'Express',
      'Transit',
      'Trucking',
      'Haulage',
      'Airlift',
      'Air',
      'Ground',
      'Mail',
      'Parcel',
      'Parcels',
      'Link',
      'Links',
      'Solutions',
      'Operations',
      'Worldwide',
      'International',
      'Global',
      'Connect',
      'Flow',
      'Route',
      'Routes',
      'Linehaul',
      'LastMile',
      'SupplyChain',
      'Warehousing',
      'Storage',
      'Terminal',
      'Terminals',
      'Hub',
      'Hubs',
      'Center',
      'Centre',
      'Depot',
      'Fleet',
      'Mobility',
      'Transport Group',
      'Logistics Group',
      'Freight Group',
      'Cargo Group',
      'Courier Group',
      'Delivery Group',
      'Shipping Group',
      'Distribution Group',
      'Services Group',
      'Systems Group',
      'Network Group',
      'Partners Group',
      'Express Group',
      'Transit Group',
      'Global Logistics',
      'Global Transport',
      'Global Shipping',
      'Global Freight',
      'International Logistics',
      'International Transport',
      'International Shipping',
      'Worldwide Logistics',
      'Worldwide Shipping',
      'Cargo Partners',
      'Freight Partners',
      'Logistics Partners',
      'Transport Partners',
      'Delivery Partners',
      'Courier Partners',
      'Shipping Partners',
      'Network Services',
      'Transport Services',
      'Logistics Services',
      'Freight Services',
      'Cargo Services',
      'Courier Services',
      'Delivery Services',
      'Shipping Services',
      'Transit Services',
      'Express Services',
      'Distribution Services',
      'Dispatch Services',
      'Forwarding Services',
      'Fulfillment Services',
      'Carrier Services',
      'Fleet Services',
      'Mail Services',
      'Parcel Services',
      'Transport Systems',
      'Logistics Systems',
      'Freight Systems',
      'Cargo Systems',
      'Courier Systems',
      'Delivery Systems',
      'Shipping Systems',
      'Transit Systems',
      'Distribution Systems',
      'Dispatch Systems',
      'Forwarding Systems',
      'Carrier Systems',
      'Parcel Systems',
      'Express Line',
      'Freight Line',
      'Cargo Line',
      'Transit Line',
      'Shipping Line',
      'Air Line',
      'Ground Line',
      'Parcel Line',
      'Delivery Line',
      'Courier Line',
      'Transport Line',
      'Logistics Line',
    ],
    businessTypes: [
      'Accounting',
      'Advertising',
      'Aerospace',
      'Agriculture',
      'Air Cargo',
      'Air Travel',
      'Analytics',
      'Apparel',
      'Architecture',
      'Art and Design',
      'Arts and Crafts',
      'Athletic Goods',
      'Auction Services',
      'Automotive',
      'Automotive Parts',
      'Automotive Repair',
      'Automotive Services',
      'Aviation',
      'Bakery',
      'Banking',
      'Bar and Beverage Service',
      'Beauty and Personal Care',
      'Beverage Distribution',
      'Biotechnology',
      'Books and Publishing',
      'Brand Management',
      'Broadcasting',
      'Building Materials',
      'Business Consulting',
      'Business Services',
      'Catering',
      'Childcare',
      'Cleaning Services',
      'Cloud Services',
      'Coffee and Tea',
      'Commercial Printing',
      'Communications',
      'Computer Hardware',
      'Construction',
      'Consulting',
      'Consumer Electronics',
      'Consumer Goods',
      'Content Production',
      'Courier Services',
      'Creative Services',
      'Cybersecurity',
      'Data Services',
      'Dental Services',
      'Department Store',
      'Design Services',
      'Digital Media',
      'Distribution',
      'E-commerce',
      'Education',
      'Electrical Services',
      'Electronics Repair',
      'Energy',
      'Engineering',
      'Entertainment',
      'Environmental Services',
      'Equipment Rental',
      'Event Services',
      'Facility Management',
      'Fashion',
      'Financial Services',
      'Fine Dining',
      'Fitness',
      'Floristry',
      'Food and Beverage',
      'Food Distribution',
      'Food Manufacturing',
      'Food Service',
      'Furniture',
      'Gaming',
      'Garden Supply',
      'General Merchandise',
      'Graphic Design',
      'Grocery',
      'Hardware',
      'Health and Wellness',
      'Healthcare',
      'Home Decor',
      'Home Goods',
      'Home Improvement',
      'Hospitality',
      'Human Resources',
      'Industrial Equipment',
      'Industrial Services',
      'Industrial Supply',
      'Insurance',
      'Interior Design',
      'Internet Services',
      'Investment Services',
      'IT Services',
      'Janitorial Services',
      'Jewelry',
      'Kitchenware',
      'Landscaping',
      'Laundry Services',
      'Legal Services',
      'Leisure',
      'Lifestyle Products',
      'Lighting',
      'Logistics',
      'Luxury Goods',
      'Manufacturing',
      'Marine Services',
      'Market Research',
      'Marketing',
      'Media',
      'Medical Devices',
      'Medical Services',
      'Mental Wellness',
      'Mobile Services',
      'Mortgage Services',
      'Movie and Theater',
      'Music and Audio',
      'Network Services',
      'Nonprofit Services',
      'Office Equipment',
      'Office Supply',
      'Online Education',
      'Online Marketplace',
      'Optical Services',
      'Outdoor Equipment',
      'Packaging',
      'Paint and Decor',
      'Payment Services',
      'Personal Services',
      'Pet Care',
      'Pet Supplies',
      'Pharmaceuticals',
      'Pharmacy',
      'Photography',
      'Plumbing Services',
      'Printing Services',
      'Private Security',
      'Professional Services',
      'Property Management',
      'Public Relations',
      'Publishing',
      'Real Estate',
      'Recruitment',
      'Recycling Services',
      'Rental Services',
      'Repair Services',
      'Research Services',
      'Restaurant',
      'Retail',
      'Safety Equipment',
      'Salon Services',
      'Scientific Services',
      'Security Services',
      'Skincare',
      'Small Appliances',
      'Social Media Services',
      'Software',
      'Specialty Grocery',
      'Specialty Retail',
      'Sporting Goods',
      'Sports and Recreation',
      'Staffing',
      'Storage Services',
      'Streaming Services',
      'Subscription Services',
      'Supply Chain Services',
      'Telecommunications',
      'Textiles',
      'Tourism',
      'Toy and Hobby',
      'Trade Services',
      'Training Services',
      'Transportation',
      'Travel',
      'Travel Services',
      'Utilities',
      'Veterinary Services',
      'Video Production',
      'Warehousing',
      'Waste Management',
      'Web Services',
      'Wellness Services',
      'Wholesale',
      'Wireless Services',
    ],
    domains: [
      '.com',
      '.net',
      '.org',
      '.co',
      '.io',
      '.ai',
      '.app',
      '.dev',
      '.biz',
      '.info',
      '.online',
      '.site',
      '.website',
      '.web',
      '.store',
      '.shop',
      '.market',
      '.mart',
      '.boutique',
      '.deals',
      '.sale',
      '.shopping',
      '.services',
      '.service',
      '.solutions',
      '.systems',
      '.support',
      '.center',
      '.centre',
      '.group',
      '.global',
      '.world',
      '.international',
      '.company',
      '.business',
      '.enterprises',
      '.ventures',
      '.capital',
      '.finance',
      '.financial',
      '.money',
      '.fund',
      '.funds',
      '.investments',
      '.partners',
      '.agency',
      '.media',
      '.digital',
      '.marketing',
      '.consulting',
      '.care',
      '.health',
      '.clinic',
      '.pharmacy',
      '.hospital',
      '.education',
      '.academy',
      '.training',
      '.school',
      '.institute',
      '.software',
      '.technology',
      '.tech',
      '.cloud',
      '.data',
      '.network',
      '.networks',
      '.email',
      '.live',
      '.today',
      '.news',
      '.press',
      '.studio',
      '.design',
      '.graphics',
      '.video',
      '.photo',
      '.photos',
      '.pictures',
      '.camera',
      '.gallery',
      '.art',
      '.audio',
      '.fm',
      '.tv',
      '.radio',
      '.show',
      '.events',
      '.event',
      '.tickets',
      '.travel',
      '.tours',
      '.voyage',
      '.flights',
      '.vacations',
      '.holiday',
      '.holidays',
      '.cruises',
      '.hotel',
      '.hotels',
      '.rentals',
      '.taxi',
      '.limo',
      '.cab',
      '.auto',
      '.autos',
      '.car',
      '.cars',
      '.motorcycles',
      '.parts',
      '.tools',
      '.equipment',
      '.supply',
      '.supplies',
      '.industries',
      '.manufacturing',
      '.engineer',
      '.engineering',
      '.builders',
      '.construction',
      '.contractors',
      '.plumbing',
      '.repair',
      '.cleaning',
      '.kitchen',
      '.coffee',
      '.cafe',
      '.restaurant',
      '.rest',
      '.bar',
      '.pub',
      '.pizza',
      '.food',
      '.foods',
      '.recipes',
      '.catering',
      '.bakery',
      '.beer',
      '.wine',
      '.farm',
      '.fyi',
      '.guide',
      '.help',
      '.directory',
      '.community',
      '.social',
      '.team',
      '.works',
      '.zone',
      '.place',
      '.space',
      '.city',
      '.town',
      '.express',
      '.direct',
      '.one',
      '.plus',
      '.pro',
      '.expert',
      '.networking',
      '.management',
      '.consultant',
      '.law',
      '.legal',
      '.attorney',
      '.accountant',
      '.accountants',
      '.tax',
      '.insurance',
      '.claims',
      '.broker',
      '.realty',
      '.realestate',
      '.properties',
      '.property',
      '.homes',
      '.house',
      '.apartments',
      '.land',
      '.garden',
      '.flowers',
      '.beauty',
      '.salon',
      '.spa',
      '.skin',
      '.makeup',
      '.style',
      '.fashion',
      '.clothing',
      '.shoes',
      '.watch',
      '.watches',
      '.jewelry',
      '.jewellery',
      '.gifts',
      '.toys',
      '.games',
      '.game',
      '.fun',
      '.fitness',
      '.gym',
      '.run',
      '.yoga',
      '.sports',
      '.sport',
      '.tennis',
      '.golf',
      '.football',
      '.basketball',
      '.surf',
      '.ski',
      '.bike',
      '.bikes',
      '.pet',
      '.pets',
      '.vet',
      '.delivery',
      '.courier',
      '.logistics',
      '.shipping',
      '.cargo',
      '.freight',
      '.express',
      '.mail',
      '.post',
      '.storage',
      '.moving',
      '.lease',
      '.trade',
      '.trading',
      '.exchange',
      '.energy',
      '.solar',
      '.green',
      '.recycling',
      '.bio',
      '.eco',
      '.foundation',
      '.charity',
      '.ngo',
      '.careers',
      '.jobs',
      '.works',
      '.chat',
      '.im',
      '.link',
      '.click',
      '.page',
      '.pages',
      '.tools',
      '.download',
      '.apparel',
      '.team',
      '.contact',
      '.cool',
      '.blue',
      '.red',
      '.black',
      '.gold',
      '.silver',
      '.pink',
      '.organic',
    ],
    suiteLabels: [
      'Apartment',
      'Apartments',
      'Apt',
      'Apt.',
      'Block',
      'Bldg',
      'Bldg.',
      'Building',
      'Building No',
      'Building Number',
      'Cabin',
      'Campus',
      'Complex',
      'Condo',
      'Department',
      'Dept',
      'Dept.',
      'Door',
      'Entrance',
      'Flat',
      'Flr',
      'Flr.',
      'Floor',
      'Front',
      'Hangar',
      'House',
      'Interior',
      'Level',
      'Line',
      'Lobby',
      'Lot',
      'Lower Level',
      'Maisonette',
      'Module',
      'No',
      'No.',
      'Number',
      'Office',
      'Penthouse',
      'Rear',
      'Room',
      'Rm',
      'Rm.',
      'Section',
      'Shop',
      'Side',
      'Space',
      'Stall',
      'Station',
      'Ste',
      'Ste.',
      'Stop',
      'Store',
      'Suite',
      'Tower',
      'Unit',
      'Upper Level',
      'Wing',
      '#',
    ],
  },
  geography: {
    locales: [
      {
        countryName: 'United States',
        countryCode: 'US',
        currency: { code: 'USD', symbol: '$' },
        phoneFormats: ['+1 ###-###-####'],
        postalFormats: ['#####', '#####-####'],
        taxIdFormats: ['##-#######'],
        cities: [
          {
            name: 'New York',
            region: 'New York',
            streets: [
              'Broadway',
              'Fifth Avenue',
              'Madison Avenue',
              'Hudson Street',
              'Park Avenue',
              'Lexington Avenue',
              'Wall Street',
              'Canal Street',
              'Houston Street',
              'Delancey Street',
              'Bowery',
              'West End Avenue',
              'Amsterdam Avenue',
              'Columbus Avenue',
              'Amsterdam Avenue',
              'Central Park West',
              'Riverside Drive',
              'Flatbush Avenue',
              'Atlantic Avenue',
              'Bedford Avenue',
              'Nostrand Avenue',
              'Queens Boulevard',
              'Roosevelt Avenue',
              'Northern Boulevard',
              'Tremont Avenue',
              'Fordham Road',
              'Jerome Avenue',
              'Grand Concourse',
              'Myrtle Avenue',
              'Lafayette Street',
            ],
          },
          {
            name: 'Chicago',
            region: 'Illinois',
            streets: [
              'Michigan Avenue',
              'Clark Street',
              'Lake Street',
              'Wabash Avenue',
              'State Street',
              'Randolph Street',
              'LaSalle Street',
              'Halsted Street',
              'Ashland Avenue',
              'Western Avenue',
              'Milwaukee Avenue',
              'Belmont Avenue',
              'Irving Park Road',
              'North Avenue',
              'Division Street',
              'Roosevelt Road',
              'Cermak Road',
              'Chicago Avenue',
              'Grand Avenue',
              'Fullerton Avenue',
              'Damen Avenue',
              'Kedzie Avenue',
              'Pulaski Road',
              'Cicero Avenue',
              '63rd Street',
              '95th Street',
              'Archer Avenue',
              'Madison Street',
              'Jackson Boulevard',
              'Ogden Avenue',
            ],
          },
          {
            name: 'Austin',
            region: 'Texas',
            streets: [
              'Congress Avenue',
              'Lamar Boulevard',
              'Riverside Drive',
              'Burnet Road',
              'Guadalupe Street',
              'Cesar Chavez Street',
              'South Congress Avenue',
              'South Lamar Boulevard',
              'Airport Boulevard',
              'Martin Luther King Jr Boulevard',
              'Koenig Lane',
              'Braker Lane',
              'Parmer Lane',
              'Anderson Lane',
              'Barton Springs Road',
              'Red River Street',
              'Manor Road',
              'Pleasant Valley Road',
              'William Cannon Drive',
              'Slaughter Lane',
              'Research Boulevard',
              'Duval Street',
              'Lavaca Street',
              'San Jacinto Boulevard',
              'Rainey Street',
              'Rundberg Lane',
              'Riverside Drive',
              'Bee Cave Road',
              'Exposition Boulevard',
              'Metric Boulevard',
            ],
          },
          {
            name: 'Seattle',
            region: 'Washington',
            streets: [
              'Pine Street',
              'Pike Street',
              'Aurora Avenue',
              'University Way',
              'Alaskan Way',
              'Rainier Avenue',
              '1st Avenue',
              '2nd Avenue',
              '3rd Avenue',
              '4th Avenue',
              '5th Avenue',
              '15th Avenue',
              '23rd Avenue',
              'Westlake Avenue',
              'Dexter Avenue',
              'Broadway',
              'Madison Street',
              'Yesler Way',
              'Jackson Street',
              'Mercer Street',
              'Denny Way',
              'Olive Way',
              'Lake City Way',
              'Roosevelt Way',
              'Greenwood Avenue',
              'Ballard Avenue',
              'Fremont Avenue',
              'Beacon Avenue',
              'California Avenue',
              'Elliott Avenue',
            ],
          },
          {
            name: 'Los Angeles',
            region: 'California',
            streets: [
              'Sunset Boulevard',
              'Hollywood Boulevard',
              'Wilshire Boulevard',
              'Santa Monica Boulevard',
              'Melrose Avenue',
              'Ventura Boulevard',
              'Figueroa Street',
              'Broadway',
              'Vermont Avenue',
              'Western Avenue',
              'Crenshaw Boulevard',
              'Sepulveda Boulevard',
              'Pico Boulevard',
              'Olympic Boulevard',
              'Venice Boulevard',
              'La Brea Avenue',
              'Fairfax Avenue',
              'Highland Avenue',
              'La Cienega Boulevard',
              'Rodeo Drive',
              'Century Boulevard',
              'Slauson Avenue',
              'San Vicente Boulevard',
              'Alameda Street',
              'Main Street',
              'Spring Street',
              '6th Street',
              '7th Street',
              '8th Street',
              '9th Street',
            ],
          },
          {
            name: 'Boston',
            region: 'Massachusetts',
            streets: [
              'Boylston Street',
              'Newbury Street',
              'Beacon Street',
              'Commonwealth Avenue',
              'Tremont Street',
              'Washington Street',
              'Summer Street',
              'Congress Street',
              'Atlantic Avenue',
              'Massachusetts Avenue',
              'Huntington Avenue',
              'Cambridge Street',
              'Causeway Street',
              'State Street',
              'Devonshire Street',
              'Hanover Street',
              'Seaport Boulevard',
              'Dorchester Avenue',
              'Blue Hill Avenue',
              'Columbus Avenue',
              'Centre Street',
              'Stuart Street',
              'Kneeland Street',
              'Arlington Street',
              'Charles Street',
              'Boylston Street',
              'Federal Street',
              'Broad Street',
              'Canal Street',
              'Park Street',
            ],
          },
        ],
      },
      {
        countryName: 'Canada',
        countryCode: 'CA',
        currency: { code: 'CAD', symbol: 'CA$' },
        phoneFormats: ['+1 ###-###-####'],
        postalFormats: ['A#A #A#'],
        taxIdFormats: ['#########RT####'],
        cities: [
          {
            name: 'Toronto',
            region: 'Ontario',
            streets: [
              'Queen Street',
              'King Street',
              'Bloor Street',
              'Spadina Avenue',
              'Dundas Street',
              'Front Street',
              'Yonge Street',
              'Bay Street',
              'College Street',
              'Carlton Street',
              'Bathurst Street',
              'Jarvis Street',
              'Church Street',
              'University Avenue',
              'St Clair Avenue',
              'Eglinton Avenue',
              'Lawrence Avenue',
              'Danforth Avenue',
              'Dupont Street',
              'Richmond Street',
              'Adelaide Street',
              'Parliament Street',
              'Sherbourne Street',
              'Broadview Avenue',
              'Roncesvalles Avenue',
              'Keele Street',
              'Dufferin Street',
              'Ossington Avenue',
              'Queen Street West',
              'King Street West',
            ],
          },
          {
            name: 'Vancouver',
            region: 'British Columbia',
            streets: [
              'Granville Street',
              'Robson Street',
              'Main Street',
              'Broadway',
              'Georgia Street',
              'Cambie Street',
              'Burrard Street',
              'Davie Street',
              'Denman Street',
              'Kingsway',
              'Commercial Drive',
              'Hastings Street',
              'Cordova Street',
              'Hornby Street',
              'Howe Street',
              'Seymour Street',
              'Oak Street',
              'Knight Street',
              'Fraser Street',
              'Marine Drive',
              '4th Avenue',
              '10th Avenue',
              '41st Avenue',
              '49th Avenue',
              'Granville Street',
              'Alberni Street',
              'Pender Street',
              'Water Street',
              'Arbutus Street',
              'Clark Drive',
            ],
          },
          {
            name: 'Calgary',
            region: 'Alberta',
            streets: [
              'Stephen Avenue',
              'Centre Street',
              '17 Avenue',
              'Macleod Trail',
              'Kensington Road',
              'Crowchild Trail',
              'Memorial Drive',
              'Bow Trail',
              'Sarcee Trail',
              'Deerfoot Trail',
              'Glenmore Trail',
              'Barlow Trail',
              '14 Street',
              '16 Avenue',
              '32 Avenue',
              '52 Street',
              '4 Street',
              '10 Street',
              'Elbow Drive',
              'Centre Avenue',
              'International Avenue',
              '9 Avenue',
              '11 Avenue',
              '5 Avenue',
              '1 Street',
              'Shaganappi Trail',
              'Anderson Road',
              'Heritage Drive',
              'Southland Drive',
              'McKnight Boulevard',
            ],
          },
          {
            name: 'Montreal',
            region: 'Quebec',
            streets: [
              'Saint Catherine Street',
              'Saint Laurent Boulevard',
              'Sherbrooke Street',
              'Notre Dame Street',
              'Peel Street',
              'Crescent Street',
              'Atwater Avenue',
              'Parc Avenue',
              'Papineau Avenue',
              'Saint Denis Street',
              'Rene Levesque Boulevard',
              'De Maisonneuve Boulevard',
              'Mount Royal Avenue',
              'Jean Talon Street',
              'Beaubien Street',
              'Ontario Street',
              'Hochelaga Street',
              'Guy Street',
              'University Street',
              'Berri Street',
              'Decarie Boulevard',
              'Pie IX Boulevard',
              'Rachel Street',
              'Bernard Avenue',
              'Wellington Street',
              'Saint Jacques Street',
              'Notre Dame Ouest',
              'Saint Hubert Street',
              'Cote des Neiges Road',
              'Lacordaire Boulevard',
            ],
          },
        ],
      },
      {
        countryName: 'United Kingdom',
        countryCode: 'GB',
        currency: { code: 'GBP', symbol: 'GBP' },
        phoneFormats: ['+44 20 #### ####', '+44 1### ######'],
        postalFormats: ['AA# #AA', 'AA## #AA'],
        taxIdFormats: ['GB#########'],
        cities: [
          {
            name: 'London',
            region: 'England',
            streets: [
              'Baker Street',
              'Fleet Street',
              'Kings Road',
              'Piccadilly',
              'Oxford Street',
              'Regent Street',
              'Bond Street',
              'Carnaby Street',
              'Tottenham Court Road',
              'Charing Cross Road',
              'Marylebone Road',
              'Euston Road',
              'Park Lane',
              'Bishopsgate',
              'Threadneedle Street',
              'Cheapside',
              'Strand',
              'Whitehall',
              'The Mall',
              'Pall Mall',
              'Downing Street',
              'Portobello Road',
              'Kensington High Street',
              'Notting Hill Gate',
              'Camden High Street',
              'Upper Street',
              'Old Street',
              'Brick Lane',
              'Tooley Street',
              'Lombard Street',
            ],
          },
          {
            name: 'Manchester',
            region: 'England',
            streets: [
              'Deansgate',
              'Oxford Road',
              'Market Street',
              'Mosley Street',
              'Portland Street',
              'Whitworth Street',
              'Piccadilly',
              'Oldham Road',
              'Great Ancoats Street',
              'Cheetham Hill Road',
              'Wilmslow Road',
              'Princess Street',
              'King Street',
              'Cross Street',
              'Corporation Street',
              'Lever Street',
              'Bridge Street',
              'Chapel Street',
              'Liverpool Road',
              'Ashton Old Road',
              'Bury New Road',
              'Hyde Road',
              'Oxford Street',
              'Stretford Road',
              'Blackfriars Street',
              'Quay Street',
              'John Dalton Street',
              'Tib Street',
              'Canal Street',
              'Peter Street',
            ],
          },
          {
            name: 'Edinburgh',
            region: 'Scotland',
            streets: [
              'Princes Street',
              'George Street',
              'Royal Mile',
              'Leith Walk',
              'Grassmarket',
              'Lothian Road',
              'Queen Street',
              'Rose Street',
              'Hanover Street',
              'Frederick Street',
              'Castle Terrace',
              'Morrison Street',
              'Dalry Road',
              'Bruntsfield Place',
              'Morningside Road',
              'Nicolson Street',
              'Clerk Street',
              'Canongate',
              'Holyrood Road',
              'York Place',
              'Broughton Street',
              'Dundas Street',
              'St Andrew Square',
              'South Bridge',
              'North Bridge',
              'Shandwick Place',
              'Lauriston Place',
              'Home Street',
              'Bread Street',
              'Fountainbridge',
            ],
          },
          {
            name: 'Birmingham',
            region: 'England',
            streets: [
              'New Street',
              'Broad Street',
              'Corporation Street',
              'Colmore Row',
              'Bristol Road',
              'Stratford Road',
              'Hagley Road',
              'Coventry Road',
              'Pershore Road',
              'Ladypool Road',
              'Alum Rock Road',
              'Soho Road',
              'Bromford Lane',
              'Moseley Road',
              'Digbeth High Street',
              'High Street',
              'Smallbrook Queensway',
              'Aston Expressway',
              'Dudley Road',
              'Warwick Road',
              'Church Street',
              'Temple Row',
              'Steelhouse Lane',
              'Snow Hill',
              'Moor Street',
              'Belgrave Middleway',
              'Great Charles Street',
              'Park Street',
              'York Road',
              'St Martins Queensway',
            ],
          },
        ],
      },
      {
        countryName: 'Ireland',
        countryCode: 'IE',
        currency: { code: 'EUR', symbol: 'EUR' },
        phoneFormats: ['+353 1 ### ####', '+353 ## ### ####'],
        postalFormats: ['A## A###'],
        taxIdFormats: ['#######A'],
        cities: [
          {
            name: 'Dublin',
            region: 'Leinster',
            streets: [
              'Grafton Street',
              'Baggot Street',
              'OConnell Street',
              'Dawson Street',
              'Talbot Street',
              'Parnell Street',
              'Henry Street',
              'Capel Street',
              'Abbey Street',
              'Gardiner Street',
              'Amiens Street',
              'Westmoreland Street',
              'Dame Street',
              'Pearse Street',
              'Thomas Street',
              'Aungier Street',
              'Leeson Street',
              'Merrion Square',
              'Fitzwilliam Street',
              'Camden Street',
              'Rathmines Road',
              'Phibsborough Road',
              'Drumcondra Road',
              'North Circular Road',
              'South Circular Road',
              'Clanbrassil Street',
              'George Street',
              'Nassau Street',
              'Kildare Street',
              'Harcourt Street',
            ],
          },
          {
            name: 'Cork',
            region: 'Munster',
            streets: [
              'Patrick Street',
              'Oliver Plunkett Street',
              'South Mall',
              'Grand Parade',
              'Washington Street',
              'MacCurtain Street',
              'North Main Street',
              'South Main Street',
              'Shandon Street',
              'Bandon Road',
              'Togher Road',
              'Douglas Street',
              'Western Road',
              'College Road',
              'Glanmire Road',
              'Horgan Quay',
              'Penrose Quay',
              'Albert Quay',
              'Monahan Road',
              'Lower Glanmire Road',
              'Andersons Quay',
              "Pope's Quay",
              'Emmet Place',
              'Parnell Place',
              'Bridge Street',
              'Cornmarket Street',
              'McCurtain Street',
              'Castle Street',
              'Princes Street',
              'Liberty Street',
            ],
          },
        ],
      },
      {
        countryName: 'Australia',
        countryCode: 'AU',
        currency: { code: 'AUD', symbol: 'A$' },
        phoneFormats: ['+61 # #### ####', '+61 2 #### ####'],
        postalFormats: ['####'],
        taxIdFormats: ['## ### ### ###'],
        cities: [
          {
            name: 'Sydney',
            region: 'New South Wales',
            streets: [
              'George Street',
              'Pitt Street',
              'Oxford Street',
              'Castlereagh Street',
              'Kent Street',
              'York Street',
              'Elizabeth Street',
              'Liverpool Street',
              'Bathurst Street',
              'William Street',
              'Crown Street',
              'King Street',
              'Parramatta Road',
              'Cleveland Street',
              'King Street Wharf',
              'Macquarie Street',
              'Sussex Street',
              'Harris Street',
              'Bourke Street',
              'Oxford Street',
              'Princes Highway',
              'Military Road',
              'Victoria Road',
              'Pacific Highway',
              'Liverpool Road',
              'New South Head Road',
              'Anzac Parade',
              'Botany Road',
              'Glebe Point Road',
              'George Street North',
            ],
          },
          {
            name: 'Melbourne',
            region: 'Victoria',
            streets: [
              'Collins Street',
              'Swanston Street',
              'Bourke Street',
              'Flinders Lane',
              'Lonsdale Street',
              'Elizabeth Street',
              'King Street',
              'Queen Street',
              'Exhibition Street',
              'Spring Street',
              'Russell Street',
              'Spencer Street',
              'La Trobe Street',
              'Little Collins Street',
              'Little Bourke Street',
              'Brunswick Street',
              'Smith Street',
              'Chapel Street',
              'Toorak Road',
              'St Kilda Road',
              'Victoria Parade',
              'Sydney Road',
              'Bridge Road',
              'Victoria Street',
              'High Street',
              'Hoddle Street',
              'Swan Street',
              'Lygon Street',
              'Johnston Street',
              'Gertrude Street',
            ],
          },
          {
            name: 'Brisbane',
            region: 'Queensland',
            streets: [
              'Queen Street',
              'Adelaide Street',
              'George Street',
              'Boundary Street',
              'Roma Street',
              'Edward Street',
              'Albert Street',
              'Ann Street',
              'Turbot Street',
              'Wickham Terrace',
              'Coronation Drive',
              'Kingsford Smith Drive',
              'Vulture Street',
              'Logan Road',
              'Old Cleveland Road',
              'Gympie Road',
              'Waterworks Road',
              'Sandgate Road',
              'Beaudesert Road',
              'Ipswich Road',
              'Milton Road',
              'Brunswick Street',
              'Stanley Street',
              'Charlotte Street',
              'Mary Street',
              'Margaret Street',
              'Creek Street',
              'Riverside Expressway',
              'Breakfast Creek Road',
              'New Farm Road',
            ],
          },
          {
            name: 'Perth',
            region: 'Western Australia',
            streets: [
              'St Georges Terrace',
              'Hay Street',
              'Murray Street',
              'Barrack Street',
              'William Street',
              'Beaufort Street',
              'Roe Street',
              'Wellington Street',
              'Adelaide Terrace',
              'Albany Highway',
              'Canning Highway',
              'Great Eastern Highway',
              'Scarborough Beach Road',
              'Charles Street',
              'Fitzgerald Street',
              'Guildford Road',
              'Riverside Drive',
              'Mounts Bay Road',
              'South Terrace',
              'Cambridge Street',
              'Oxford Street',
              'Stirling Highway',
              'Leach Highway',
              'Manning Road',
              'Thomas Street',
              'Mill Point Road',
              'Hampden Road',
              'Rokeby Road',
              'Lake Street',
              'James Street',
            ],
          },
        ],
      },
      {
        countryName: 'New Zealand',
        countryCode: 'NZ',
        currency: { code: 'NZD', symbol: 'NZ$' },
        phoneFormats: ['+64 # ### ####', '+64 9 ### ####'],
        postalFormats: ['####'],
        taxIdFormats: ['###-###-###'],
        cities: [
          {
            name: 'Auckland',
            region: 'Auckland',
            streets: [
              'Queen Street',
              'Karangahape Road',
              'Ponsonby Road',
              'Symonds Street',
              'Dominion Road',
              'Fanshawe Street',
              'Customs Street',
              'Quay Street',
              'Hobson Street',
              'Nelson Street',
              'Great North Road',
              'Great South Road',
              'New North Road',
              'Manukau Road',
              'Remuera Road',
              'Tamaki Drive',
              'Mt Eden Road',
              'Khyber Pass Road',
              'Parnell Road',
              'Victoria Street',
              'Albert Street',
              'Wellesley Street',
              'Queen Street East',
              'Manukau Station Road',
              'Pakuranga Road',
              'Lake Road',
              'Onewa Road',
              'Lincoln Road',
              'Te Irirangi Drive',
              'Ti Rakau Drive',
            ],
          },
          {
            name: 'Wellington',
            region: 'Wellington',
            streets: [
              'Lambton Quay',
              'Cuba Street',
              'Willis Street',
              'Courtenay Place',
              'The Terrace',
              'Featherston Street',
              'Taranaki Street',
              'Vivian Street',
              'Ghuznee Street',
              'Adelaide Road',
              'Kent Terrace',
              'Cambridge Terrace',
              'Thorndon Quay',
              'Manners Street',
              'Wakefield Street',
              'Jervois Quay',
              'Tinakori Road',
              'Karori Road',
              'Riddiford Street',
              'Constable Street',
              'Aro Street',
              'Brougham Street',
              'Bowen Street',
              'Molesworth Street',
              'Lyon Street',
              'Dixon Street',
              'Victoria Street',
              'Hill Street',
              'Murphy Street',
              'Majoribanks Street',
            ],
          },
        ],
      },
      {
        countryName: 'Singapore',
        countryCode: 'SG',
        currency: { code: 'SGD', symbol: 'S$' },
        phoneFormats: ['+65 #### ####'],
        postalFormats: ['######'],
        taxIdFormats: ['########A'],
        cities: [
          {
            name: 'Singapore',
            region: 'Central',
            streets: [
              'Orchard Road',
              'Raffles Place',
              'Serangoon Road',
              'Bencoolen Street',
              'Cecil Street',
              'Shenton Way',
              'Beach Road',
              'Victoria Street',
              'North Bridge Road',
              'South Bridge Road',
              'New Bridge Road',
              'River Valley Road',
              'Bukit Timah Road',
              'Changi Road',
              'Jurong Gateway Road',
              'Yishun Avenue 2',
              'Ang Mo Kio Avenue 3',
              'Tampines Avenue 5',
              'Upper Thomson Road',
              'Jalan Besar',
              'Tanjong Pagar Road',
              'Telok Ayer Street',
              'Bras Basah Road',
              'Lavender Street',
              'Kallang Road',
              'Alexandra Road',
              'Havelock Road',
              'Hougang Avenue 1',
              'Toa Payoh Lorong 6',
              'Pasir Ris Drive 3',
            ],
          },
        ],
      },
      {
        countryName: 'India',
        countryCode: 'IN',
        currency: { code: 'INR', symbol: 'INR' },
        phoneFormats: ['+91 ##### #####'],
        postalFormats: ['######'],
        taxIdFormats: ['##AAAAA####A#Z#'],
        cities: [
          {
            name: 'Bengaluru',
            region: 'Karnataka',
            streets: [
              'MG Road',
              'Brigade Road',
              'Residency Road',
              'Church Street',
              'Koramangala Main Road',
              'Bannerghatta Road',
              'Outer Ring Road',
              'Inner Ring Road',
              'Old Airport Road',
              'Old Madras Road',
              'Hosur Road',
              'Bellary Road',
              'Race Course Road',
              'Richmond Road',
              'Cunningham Road',
              'Commercial Street',
              'St Marks Road',
              'Lavelle Road',
              'Sarjapur Road',
              'Whitefield Main Road',
              '100 Feet Road',
              '80 Feet Road',
              'Tumkur Road',
              'Mysore Road',
              'Airport Road',
              'Vittal Mallya Road',
              'Jayanagar 4th Block Road',
              'Marathahalli Main Road',
              'HAL Airport Road',
              'CMH Road',
            ],
          },
          {
            name: 'Mumbai',
            region: 'Maharashtra',
            streets: [
              'Marine Drive',
              'Linking Road',
              'Hill Road',
              'SV Road',
              'Colaba Causeway',
              'Pedder Road',
              'JN Road',
              'Dr DN Road',
              'Lamington Road',
              'Cadel Road',
              'Veer Savarkar Marg',
              'LBS Marg',
              'P Dmello Road',
              'Senapati Bapat Marg',
              'Carter Road',
              'Cuffe Parade Road',
              'Napean Sea Road',
              'Nariman Point Drive',
              'Turner Road',
              'Ghodbunder Road',
              'Andheri Kurla Road',
              'Western Express Highway',
              'Eastern Express Highway',
              'Sion Trombay Road',
              'Pali Hill Road',
              'C S Road',
              'Grant Road',
              'Princess Street',
              'M G Road',
              'Bandra Reclamation Road',
            ],
          },
          {
            name: 'New Delhi',
            region: 'Delhi',
            streets: [
              'Connaught Place',
              'Janpath',
              'Lodhi Road',
              'Ring Road',
              'Nehru Place',
              'Karol Bagh Road',
              'Rajpath',
              'Barakhamba Road',
              'Parliament Street',
              'Ashoka Road',
              'Aurobindo Marg',
              'Africa Avenue',
              'Bhikaji Cama Place',
              'Mathura Road',
              'Rohtak Road',
              'Najafgarh Road',
              'Outer Ring Road',
              'Inner Ring Road',
              'Ajmal Khan Road',
              'Desh Bandhu Gupta Road',
              'Arya Samaj Road',
              'Pusa Road',
              'MG Road',
              'Ring Road South',
              'Nelson Mandela Road',
              'Vikas Marg',
              'Kasturba Gandhi Marg',
              'Shanti Path',
              'Mandir Marg',
              'Sansad Marg',
            ],
          },
          {
            name: 'Hyderabad',
            region: 'Telangana',
            streets: [
              'Banjara Hills Road No 1',
              'Road No 36',
              'Begumpet Road',
              'Tank Bund Road',
              'Necklace Road',
              'Hitech City Road',
              'Madhapur Main Road',
              'Gachibowli Miyapur Road',
              'Jubilee Hills Road No 45',
              'Abids Road',
              'Basheerbagh Road',
              'Nampally Road',
              'King Koti Road',
              'PV Narasimha Rao Expressway',
              'Inner Ring Road',
              'Outer Ring Road',
              'Charminar Road',
              'Koti Main Road',
              'Ameerpet Main Road',
              'Erragadda Road',
              'SR Nagar Main Road',
              'Kukatpally Main Road',
              'LB Nagar Road',
              'Dilsukhnagar Main Road',
              'M G Road',
              'SD Road',
              'Punjagutta Road',
              'Road No 12',
              'Road No 10',
              'Banjara Hills Main Road',
            ],
          },
        ],
      },
    ],
  },
  commerce: {
    paymentMethods: [
      { display: 'Cash', schemaUrl: 'https://schema.org/Cash' },
      { display: 'Visa', schemaUrl: 'https://schema.org/CreditCard' },
      { display: 'Mastercard', schemaUrl: 'https://schema.org/CreditCard' },
      {
        display: 'American Express',
        schemaUrl: 'https://schema.org/CreditCard',
      },
      { display: 'Discover', schemaUrl: 'https://schema.org/CreditCard' },
      { display: 'Debit Card', schemaUrl: 'https://schema.org/CreditCard' },
      {
        display: 'Bank Transfer',
        schemaUrl: 'https://schema.org/ByBankTransferInAdvance',
      },
      {
        display: 'PayPal',
        schemaUrl: 'https://schema.org/ByBankTransferInAdvance',
      },
      { display: 'Apple Pay', schemaUrl: 'https://schema.org/CreditCard' },
      { display: 'Google Pay', schemaUrl: 'https://schema.org/CreditCard' },
      { display: 'Gift Card', schemaUrl: 'https://schema.org/PaymentMethod' },
      {
        display: 'Store Credit',
        schemaUrl: 'https://schema.org/PaymentMethod',
      },
    ],
    paymentStatuses: [
      { display: 'Paid', schemaUrl: 'https://schema.org/PaymentComplete' },
      { display: 'Due', schemaUrl: 'https://schema.org/PaymentDue' },
      {
        display: 'Payment Pending',
        schemaUrl: 'https://schema.org/PaymentDue',
      },
      { display: 'Partially Paid', schemaUrl: 'https://schema.org/PaymentDue' },
    ],
    orderStatuses: {
      default: [
        {
          display: 'Processing',
          schemaUrl: 'https://schema.org/OrderProcessing',
        },
        {
          display: 'Pickup Available',
          schemaUrl: 'https://schema.org/OrderPickupAvailable',
        },
        {
          display: 'Order Problem',
          schemaUrl: 'https://schema.org/OrderProblem',
        },
      ],
      shipping: [
        {
          display: 'In Transit',
          schemaUrl: 'https://schema.org/OrderInTransit',
        },
        {
          display: 'Delivered',
          schemaUrl: 'https://schema.org/OrderDelivered',
        },
        {
          display: 'Order Problem',
          schemaUrl: 'https://schema.org/OrderProblem',
        },
      ],
      service: [
        {
          display: 'Processing',
          schemaUrl: 'https://schema.org/OrderProcessing',
        },
        {
          display: 'Delivered',
          schemaUrl: 'https://schema.org/OrderDelivered',
        },
      ],
    },
    serviceModes: [
      'Dine In',
      'Takeaway',
      'Delivery',
      'Pickup',
      'Online',
      'Subscription',
      'Curbside',
      'In Store',
      'Remote',
      'Scheduled Service',
    ],
    receiptTypes: [
      'Sales Receipt',
      'Order Confirmation',
      'Checkout Summary',
      'Shipment Notice',
      'Service Confirmation',
      'Pickup Notice',
      'Subscription Renewal',
      'Tax Invoice',
      'Dispatch Summary',
      'Payment Receipt',
    ],
    ranges: {
      discountPercent: { min: 0, max: 100, decimals: 0 },
      promoPercent: { min: 1, max: 100, decimals: 0 },
      taxPercent: {
        default: { min: 0, max: 25, decimals: 2 },
        service: { min: 0, max: 30, decimals: 2 },
      },
      productQuantity: { min: 1, max: 8 },
      serviceQuantity: { min: 1, max: 2 },
    },
    promoPrefixes: [
      'SAVE',
      'DEAL',
      'PROMO',
      'WELCOME',
      'FIRST',
      'VIP',
      'SPRING',
      'SUMMER',
      'WINTER',
      'SHIP',
      'BUNDLE',
      'APP',
      'WEB',
      'FLASH',
      'HOT',
      'MEGA',
      'BONUS',
      'REWARD',
      'EARLY',
      'SMART',
      'FALL',
      'AUTUMN',
      'HOLIDAY',
      'XMAS',
      'NEWYEAR',
      'NY',
      'JAN',
      'FEB',
      'MAR',
      'APR',
      'MAY',
      'JUNE',
      'JULY',
      'AUG',
      'SEPT',
      'OCT',
      'NOV',
      'BLACK',
      'CYBER',
      'GIFT',
      'FREE',
      'SUPER',
      'ULTRA',
      'TOP',
      'BEST',
      'MAX',
      'MORE',
      'EXTRA',
      'BOOST',
      'QUICK',
      'FAST',
      'GO',
      'SHOP',
      'STORE',
      'CART',
      'CHECKOUT',
      'ORDER',
      'BUY',
      'PAY',
      'CASH',
      'PRICE',
      'CUT',
      'DROP',
      'OFF',
      'LESS',
      'DISC',
      'DISCOUNT',
      'SALE',
      'CLEAR',
      'CLEARANCE',
      'FINAL',
      'LAST',
      'LIMITED',
      'DAILY',
      'WEEKLY',
      'WEEKEND',
      'MONTHLY',
      'NIGHT',
      'DAY',
      'TODAY',
      'NOW',
      'INSTANT',
      'DIRECT',
      'ONLINE',
      'MOBILE',
      'TEXT',
      'EMAIL',
      'PUSH',
      'CLICK',
      'TAP',
      'SCAN',
      'CODE',
      'COUPON',
      'VOUCHER',
      'PERK',
      'POINT',
      'POINTS',
      'LOYAL',
      'LOYALTY',
      'MEMBER',
      'CLUB',
      'FAN',
      'INSIDER',
      'ELITE',
      'GOLD',
      'SILVER',
      'BRONZE',
      'PREMIUM',
      'PLUS',
      'PRO',
      'PRIME',
      'START',
      'STARTER',
      'TRY',
      'TRIAL',
      'TEST',
      'BETA',
      'LAUNCH',
      'OPEN',
      'LIVE',
      'FRESH',
      'NEW',
      'NEXT',
      'AGAIN',
      'RETURN',
      'COMEBACK',
      'BACK',
      'REFER',
      'FRIEND',
      'SHARE',
      'SOCIAL',
      'LOCAL',
      'GLOBAL',
      'SITE',
      'DESK',
      'DESKTOP',
      'BROWSER',
      'TABLET',
      'PHONE',
      'IOS',
      'ANDROID',
      'DELIVERY',
      'PICKUP',
      'CURBSIDE',
      'SHIPFREE',
      'FREESHIP',
      'FASTSHIP',
      'BULK',
      'STACK',
      'DOUBLE',
      'TRIPLE',
      'MYSTERY',
      'SECRET',
      'SURPRISE',
      'LUCKY',
      'LUCK',
      'SPEND',
      'EARN',
      'REDEEM',
      'CLAIM',
      'GRAB',
      'SNAG',
      'STEAL',
      'VALUE',
      'SMARTBUY',
      'CHEAP',
      'BIG',
      'MINI',
      'MICRO',
      'POWER',
      'HAPPY',
      'JOY',
      'CHEER',
      'FESTIVE',
      'SEASON',
      'SEASONAL',
      'SUN',
      'HEAT',
      'BEACH',
      'SNOW',
      'COLD',
      'COZY',
      'LOVE',
      'HEART',
      'MOM',
      'DAD',
      'BIRTHDAY',
      'ANNIV',
      'ANNIVERSARY',
      'GRAD',
      'SCHOOL',
      'BACK2SCHOOL',
      'STUDENT',
      'TEACHER',
      'WORK',
      'OFFICE',
      'HOME',
      'MOVE',
      'TRAVEL',
      'TRIP',
      'VACAY',
      'GETAWAY',
    ],
    promoThemes: [
      'NOW',
      'FAST',
      'PLUS',
      'BOOST',
      'FREESHIP',
      'ONLINE',
      'CHECKOUT',
      'WELCOME',
      'LOYAL',
      'HOLIDAY',
      'LIMITED',
      'EXTRA',
      'DIRECT',
      'MEMBER',
      'STORE',
      'LAUNCH',
      'DELUXE',
      'WEEKEND',
      'NIGHT',
      'DROP',
      'DEAL',
      'SAVE',
      'SAVER',
      'DEALS',
      'SALE',
      'OFF',
      'PERCENT',
      '10',
      '15',
      '20',
      '25',
      '30',
      '40',
      '50',
      '60',
      '70',
      '75',
      '80',
      '90',
      '100',
      'SHIP',
      'SHIPFREE',
      'FREE',
      'BONUS',
      'GIFT',
      'REWARD',
      'POINTS',
      'CASHBACK',
      'CREDIT',
      'BUYNOW',
      'TODAY',
      'TONIGHT',
      'DAILY',
      'FLASH',
      'EARLY',
      'ACCESS',
      'VIP',
      'CLUB',
      'ELITE',
      'PREMIUM',
      'INSIDER',
      'FAN',
      'FIRST',
      'ORDER',
      'TRY',
      'TRIAL',
      'START',
      'STARTER',
      'NEW',
      'NEXT',
      'GO',
      'APP',
      'WEB',
      'MOBILE',
      'SITE',
      'DESKTOP',
      'PICKUP',
      'DELIVERY',
      'CURBSIDE',
      'BUNDLE',
      'STACK',
      'DOUBLE',
      'TRIPLE',
      'MEGA',
      'SUPER',
      'ULTRA',
      'MAX',
      'HOT',
      'TOP',
      'BEST',
      'SMART',
      'EASY',
      'QUICK',
      'EXPRESS',
      'PRIME',
      'PRO',
      'GOLD',
      'SILVER',
      'BRONZE',
      'VALUE',
      'CHEAP',
      'LOW',
      'LESS',
      'MORE',
      'OPEN',
      'LIVE',
      'FINAL',
      'LAST',
      'CHANCE',
      'CALL',
      'CLICK',
      'TAP',
      'SCAN',
      'CODE',
      'COUPON',
      'VOUCHER',
      'CHECK',
      'CART',
      'PAY',
      'BUY',
      'SHOP',
      'SPRING',
      'SUMMER',
      'AUTUMN',
      'FALL',
      'WINTER',
      'XMAS',
      'NEWYEAR',
      'BLACKFRIDAY',
      'CYBER',
      'BOXING',
      'WEEK',
      'MONTH',
      'SEASON',
      'SEASONAL',
      'WARM',
      'SUN',
      'SNOW',
      'COZY',
      'BEACH',
      'TRAVEL',
      'TRIP',
      'VACAY',
      'HOME',
      'OFFICE',
      'SCHOOL',
      'STUDENT',
      'FAMILY',
      'FRIEND',
      'REFER',
      'SHARE',
      'SOCIAL',
      'LOCAL',
      'GLOBAL',
      'SELECT',
      'SPECIAL',
      'SECRET',
      'MYSTERY',
      'SURPRISE',
      'FRESH',
      'BACK',
      'RETURN',
      'COMEBACK',
      'AGAIN',
      'JOY',
      'LOVE',
      'THANKS',
      'THANKYOU',
      'CHEER',
      'FESTIVE',
      'SAVEBIG',
      'SHIPNOW',
      'SHOPNOW',
      'ACTNOW',
      'JOINNOW',
      'EXCLUSIVE',
      'BOOSTED',
      'UPGRADE',
      'DELIGHT',
      'PERK',
      'ADVANTAGE',
      'DELIVERED',
      'ACTIVE',
      'READY',
    ],
    emailDomains: [
      'example.com',
      'example.co',
      'example.net',
      'example.org',
      'example.io',
      'example.app',
      'example.dev',
      'example.shop',
      'example.store',
      'example.online',
      'example.site',
      'example.biz',
      'example.global',
      'example.group',
      'example.solutions',
      'example.services',
      'example.support',
      'example.help',
      'example.market',
      'example.sale',
      'example.deals',
      'example.tech',
      'example.digital',
      'example.email',
      'example.cloud',
      'example.systems',
      'example.company',
      'example.business',
      'example.team',
      'example.world',
      'shop.example',
      'store.example',
      'orders.example',
      'mail.example',
      'checkout.example',
      'billing.example',
      'support.example',
      'service.example',
      'receipts.example',
      'invoice.example',
      'invoices.example',
      'sales.example',
      'hello.example',
      'contact.example',
      'help.example',
      'care.example',
      'team.example',
      'desk.example',
      'news.example',
      'promo.example',
      'offers.example',
      'deals.example',
      'discounts.example',
      'coupon.example',
      'coupons.example',
      'rewards.example',
      'loyalty.example',
      'vip.example',
      'member.example',
      'members.example',
      'club.example',
      'app.example',
      'web.example',
      'm.example',
      'mobile.example',
      'api.example',
      'auth.example',
      'secure.example',
      'account.example',
      'accounts.example',
      'login.example',
      'portal.example',
      'dashboard.example',
      'status.example',
      'noreply.example',
      'no-reply.example',
      'reply.example',
      'updates.example',
      'alerts.example',
      'notify.example',
      'notifications.example',
      'tracking.example',
      'track.example',
      'shipping.example',
      'ship.example',
      'delivery.example',
      'returns.example',
      'refunds.example',
      'exchange.example',
      'storefront.example',
      'marketplace.example',
      'partners.example',
      'partner.example',
      'vendor.example',
      'suppliers.example',
      'supply.example',
      'warehouse.example',
      'fulfillment.example',
      'payments.example',
      'pay.example',
      'paynow.example',
      'cashier.example',
      'register.example',
      'pos.example',
      'orders.example.com',
      'mail.example.com',
      'checkout.example.com',
      'billing.example.com',
      'support.example.com',
      'service.example.com',
      'receipts.example.com',
      'invoice.example.com',
      'invoices.example.com',
      'sales.example.com',
      'hello.example.com',
      'contact.example.com',
      'help.example.com',
      'care.example.com',
      'team.example.com',
      'desk.example.com',
      'news.example.com',
      'promo.example.com',
      'offers.example.com',
      'deals.example.com',
      'discounts.example.com',
      'coupon.example.com',
      'coupons.example.com',
      'rewards.example.com',
      'loyalty.example.com',
      'vip.example.com',
      'member.example.com',
      'members.example.com',
      'club.example.com',
      'app.example.com',
      'web.example.com',
      'm.example.com',
      'mobile.example.com',
      'api.example.com',
      'auth.example.com',
      'secure.example.com',
      'account.example.com',
      'accounts.example.com',
      'login.example.com',
      'portal.example.com',
      'dashboard.example.com',
      'status.example.com',
      'noreply.example.com',
      'no-reply.example.com',
      'reply.example.com',
      'updates.example.com',
      'alerts.example.com',
      'notify.example.com',
      'notifications.example.com',
      'tracking.example.com',
      'track.example.com',
      'shipping.example.com',
      'ship.example.com',
      'delivery.example.com',
      'returns.example.com',
      'refunds.example.com',
      'exchange.example.com',
      'storefront.example.com',
      'marketplace.example.com',
      'partners.example.com',
      'partner.example.com',
      'vendor.example.com',
      'suppliers.example.com',
      'supply.example.com',
      'warehouse.example.com',
      'fulfillment.example.com',
      'payments.example.com',
      'pay.example.com',
      'paynow.example.com',
      'cashier.example.com',
      'register.example.com',
      'pos.example.com',
      'examplemail.com',
      'examplestore.com',
      'exampleshop.com',
      'exampleorders.com',
      'examplereceipts.com',
      'examplesupport.com',
      'examplebilling.com',
      'examplecheckout.com',
      'exampleservice.com',
      'examplehelp.com',
      'exampledeals.com',
      'exampleoffers.com',
      'examplepromo.com',
      'examplepay.com',
      'exampleshipping.com',
      'exampledelivery.com',
      'examplerewards.com',
      'exampleloyalty.com',
      'examplemarket.com',
      'examplewarehouse.com',
      'examplefulfillment.com',
    ],
  },
}
