export default {
  offers: {
    electronics: [
      'Wireless Mouse',
      'USB-C Cable',
      'Mechanical Keyboard',
      'Noise Cancelling Headphones',
      '27-inch Monitor',
      'Portable SSD',
      'Phone Charger',
      'Bluetooth Speaker',
      'Smart Watch',
      'Wi-Fi Extender',
      'Laptop Stand',
      'USB Dock',
      'Webcam',
      'Power Bank',
      'Tablet Case',
    ],
    home: [
      'Desk Lamp',
      'Office Chair',
      'Standing Desk',
      'Air Purifier Filter',
      'LED Light Bulb',
      'Tool Kit',
      'Cordless Drill',
      'Garden Hose',
      'Indoor Plant',
      'Cookware Set',
      'Storage Bin Set',
      'Vacuum Filter',
      'Wall Shelf',
      'Throw Blanket',
      'Water Bottle Set',
    ],
    grocery: [
      'Coffee Beans',
      'Green Tea Pack',
      'Organic Honey',
      'Protein Powder',
      'Vitamin C Tablets',
      'Daily Multivitamin',
      'Hand Soap',
      'Shampoo',
      'Laundry Detergent',
      'Paper Towels',
      'Olive Oil',
      'Pasta Pack',
      'Sparkling Water',
      'Granola Bars',
      'Dish Soap',
    ],
    apparel: [
      'T-shirt',
      'Jeans',
      'Sneakers',
      'Jacket',
      'Winter Coat',
      'Dress Shirt',
      'Socks Pack',
      'Hat',
      'Sunglasses',
      'Wallet',
      'Running Shorts',
      'Hoodie',
      'Backpack',
      'Belt',
      'Canvas Shoes',
    ],
    food: [
      'Cheeseburger',
      'French Fries',
      'Pepperoni Pizza',
      'Veggie Burger',
      'Caesar Salad',
      'Breakfast Burrito',
      'Pancake Stack',
      'Cappuccino',
      'Latte',
      'Orange Juice',
      'Chicken Wrap',
      'Iced Coffee',
      'Soup Bowl',
      'Sandwich Combo',
      'Lemonade',
    ],
    services: [
      'Assembly Service',
      'Installation Service',
      'Technical Support Session',
      'Home Cleaning Service',
      'Oil Change',
      'Massage Session',
      'Dental Cleaning',
      'General Consultation',
      'Personal Training Session',
      'Accounting Service',
      'Website Development',
      'Design Package',
      'Repair Visit',
      'Inspection Service',
      'Remote Setup Session',
    ],
    subscriptions: [
      'Monthly Membership',
      'Premium Subscription',
      'Pro Subscription',
      'Cloud Storage Plan',
      'Email Hosting',
      'Software License',
      'Developer Tool Subscription',
      'Coffee Subscription',
      'Tea Subscription',
      'Magazine Subscription',
      'Streaming Membership',
      'Support Plan',
      'Analytics Add-on',
      'Backup Plan',
      'Newsletter Bundle',
    ],
    travel: [
      'Round Trip Flight',
      'One Way Flight',
      'Hotel Stay',
      'Room Reservation',
      'Car Rental',
      'Airport Transfer',
      'Travel Insurance',
      'Extra Baggage',
      'Priority Boarding',
      'Seat Selection',
      'Train Ticket',
      'Shuttle Transfer',
      'Lounge Access',
      'Resort Booking',
      'Parking Reservation',
    ],
    events: [
      'Conference Ticket',
      'VIP Pass',
      'General Admission Ticket',
      'Museum Entry',
      'Concert Ticket',
      'Cinema Ticket',
      'Theater Ticket',
      'Theme Park Pass',
      'Workshop Registration',
      'Festival Pass',
      'Expo Badge',
      'Seminar Seat',
      'Masterclass Entry',
      'Virtual Event Pass',
      'Meetup Ticket',
    ],
    bundles: [
      'Family Meal Bundle',
      'Starter Bundle',
      'Essentials Bundle',
      'Premium Bundle',
      'Home Office Bundle',
      'Gaming Bundle',
      'Travel Bundle',
      'Wellness Bundle',
      'Beauty Bundle',
      'Custom Package',
      'Smart Home Bundle',
      'Starter Kit',
      'Office Setup Bundle',
      'Maintenance Bundle',
      'Care Package',
    ],
  },
  composedOffers: {
    electronics: {
      adjectives: ['Wireless', 'Portable', 'Smart', 'Premium', 'Compact', 'Fast', 'Rechargeable', 'Dual', 'Ultra', 'Mini'],
      nouns: ['Keyboard', 'Mouse', 'Charger', 'Cable', 'Hub', 'Speaker', 'Headset', 'Webcam', 'Monitor', 'Dock', 'SSD', 'Router'],
      qualifiers: ['Kit', 'Bundle', 'Pack', 'Stand', 'Station', 'Edition'],
      formats: ['{adj} {noun}', '{adj} {noun} {qual}', '{noun} {qual}'],
      priceRange: { min: 8, max: 420 },
      quantityRange: { min: 1, max: 4 },
    },
    home: {
      adjectives: ['Modern', 'Adjustable', 'Deluxe', 'Compact', 'Classic', 'Heavy Duty', 'Soft', 'Reusable', 'Minimal', 'Indoor'],
      nouns: ['Lamp', 'Chair', 'Shelf', 'Storage Bin', 'Organizer', 'Cookware Set', 'Blanket', 'Tool Set', 'Bottle', 'Tray'],
      qualifiers: ['Set', 'Collection', 'Pack', 'Bundle', 'Series'],
      formats: ['{adj} {noun}', '{adj} {noun} {qual}', '{noun} {qual}'],
      priceRange: { min: 5, max: 260 },
      quantityRange: { min: 1, max: 6 },
    },
    grocery: {
      adjectives: ['Organic', 'Fresh', 'Roasted', 'Natural', 'Classic', 'Daily', 'Premium', 'Family', 'Citrus', 'Herbal'],
      nouns: ['Coffee Blend', 'Tea Pack', 'Granola Mix', 'Honey Jar', 'Protein Shake', 'Vitamin Pack', 'Soap Refill', 'Detergent Bottle', 'Snack Box', 'Oil Bottle'],
      qualifiers: ['Pack', 'Refill', 'Bundle', 'Case'],
      formats: ['{adj} {noun}', '{adj} {noun} {qual}', '{noun} {qual}'],
      priceRange: { min: 2, max: 80 },
      quantityRange: { min: 1, max: 8 },
    },
    apparel: {
      adjectives: ['Classic', 'Slim', 'Relaxed', 'Everyday', 'Premium', 'Sport', 'Winter', 'Lightweight', 'Cotton', 'Canvas'],
      nouns: ['Tee', 'Jeans', 'Sneakers', 'Jacket', 'Hoodie', 'Shorts', 'Backpack', 'Cap', 'Shirt', 'Socks'],
      qualifiers: ['Pack', 'Edition', 'Set'],
      formats: ['{adj} {noun}', '{adj} {noun} {qual}', '{noun} {qual}'],
      priceRange: { min: 6, max: 180 },
      quantityRange: { min: 1, max: 5 },
    },
    food: {
      adjectives: ['Spicy', 'Classic', 'Grilled', 'Large', 'Double', 'Fresh', 'Iced', 'House', 'Signature', 'Breakfast'],
      nouns: ['Burger', 'Pizza', 'Salad', 'Wrap', 'Coffee', 'Tea', 'Juice', 'Combo', 'Meal', 'Sandwich'],
      qualifiers: ['Meal', 'Combo', 'Set'],
      formats: ['{adj} {noun}', '{adj} {noun} {qual}', '{noun} {qual}'],
      priceRange: { min: 3, max: 40 },
      quantityRange: { min: 1, max: 6 },
    },
    services: {
      adjectives: ['Remote', 'Priority', 'Professional', 'Standard', 'Extended', 'Onsite', 'Annual', 'Express', 'Scheduled', 'Preventive'],
      nouns: ['Consultation', 'Installation', 'Repair', 'Inspection', 'Session', 'Support', 'Cleaning', 'Tune-Up', 'Audit', 'Service'],
      qualifiers: ['Visit', 'Package', 'Plan'],
      formats: ['{adj} {noun}', '{adj} {noun} {qual}', '{noun} {qual}'],
      priceRange: { min: 18, max: 600 },
      quantityRange: { min: 1, max: 2 },
    },
    subscriptions: {
      adjectives: ['Monthly', 'Premium', 'Pro', 'Annual', 'Family', 'Advanced', 'Cloud', 'Creator', 'Business', 'Starter'],
      nouns: ['Membership', 'Subscription', 'Plan', 'License', 'Add-on', 'Bundle', 'Access', 'Pass'],
      qualifiers: ['Plan', 'Tier', 'Package'],
      formats: ['{adj} {noun}', '{adj} {noun} {qual}', '{noun} {qual}'],
      priceRange: { min: 4, max: 160 },
      quantityRange: { min: 1, max: 3 },
    },
    travel: {
      adjectives: ['Round Trip', 'One Way', 'Priority', 'Flexible', 'Economy', 'Business', 'Airport', 'Resort', 'Express', 'City'],
      nouns: ['Flight', 'Transfer', 'Reservation', 'Booking', 'Ticket', 'Rental', 'Pass', 'Stay'],
      qualifiers: ['Package', 'Upgrade', 'Option'],
      formats: ['{adj} {noun}', '{adj} {noun} {qual}', '{noun} {qual}'],
      priceRange: { min: 12, max: 980 },
      quantityRange: { min: 1, max: 2 },
    },
    events: {
      adjectives: ['VIP', 'General', 'Premium', 'Weekend', 'All-Access', 'Evening', 'Morning', 'Virtual', 'Live', 'Front Row'],
      nouns: ['Ticket', 'Pass', 'Entry', 'Registration', 'Badge', 'Seat', 'Access'],
      qualifiers: ['Package', 'Bundle', 'Upgrade'],
      formats: ['{adj} {noun}', '{adj} {noun} {qual}', '{noun} {qual}'],
      priceRange: { min: 8, max: 420 },
      quantityRange: { min: 1, max: 4 },
    },
    bundles: {
      adjectives: ['Starter', 'Premium', 'Family', 'Travel', 'Office', 'Wellness', 'Gaming', 'Home', 'Beauty', 'Seasonal'],
      nouns: ['Bundle', 'Package', 'Kit', 'Collection', 'Set'],
      qualifiers: ['Pack', 'Edition', 'Series'],
      formats: ['{adj} {noun}', '{adj} {noun} {qual}', '{noun} {qual}'],
      priceRange: { min: 10, max: 320 },
      quantityRange: { min: 1, max: 3 },
    },
  },
  itemCategories: [
    'Electronics',
    'Home',
    'Food',
    'Apparel',
    'Software',
    'Travel',
    'Services',
    'Tickets',
    'Subscriptions',
    'Grocery',
    'Logistics',
    'Household',
  ],
}
