export default {
  offers: {
    electronics: [
      'Wireless Mouse',
      'USB-C Cable',
      'Mechanical Keyboard',
      'Noise Cancelling Headphones',
      '27-inch Monitor',
      'Portable SSD',
      'Phone Charger',
      'Bluetooth Speaker',
      'Smart Watch',
      'Wi-Fi Extender',
      'Laptop Stand',
      'USB Dock',
      'Webcam',
      'Power Bank',
      'Tablet Case',
      'Wireless Keyboard',
      'Gaming Mouse',
      'Mouse Pad',
      'USB Flash Drive',
      'External Hard Drive',
      'Desktop Microphone',
      'Ring Light',
      'Monitor Arm',
      'HDMI Cable',
      'DisplayPort Cable',
      'Ethernet Cable',
      'Surge Protector',
      'Charging Station',
      'Wireless Charger',
      'Screen Protector',
      'Phone Case',
      'Tablet Screen Guard',
      'Laptop Sleeve',
      'Graphics Tablet',
      'USB Hub',
      'Docking Station',
      'Portable Monitor',
      'Ink Cartridge',
      'Toner Cartridge',
      'Label Printer',
      'Receipt Printer',
      'Barcode Scanner',
      'POS Terminal',
      'Card Reader',
      'Printer Paper',
      'All-in-One Printer',
      'Document Scanner',
      'Photo Printer',
      'Action Camera',
      'Digital Camera',
      'Camera Lens',
      'Tripod',
      'Memory Card',
      'Router',
      'Mesh Wi-Fi Node',
      'Smart Plug',
      'Smart Bulb',
      'Smart Thermostat',
      'Video Doorbell',
      'Streaming Device',
      'Media Player',
      'Game Controller',
      'Console Charging Dock',
      'VR Headset',
      'E-reader',
      'Mini Projector',
      'Projector Screen',
      'Desktop Speakers',
      'Soundbar',
      'Home Security Camera',
      'Portable Fan',
      'Desktop Fan',
      'AirTag Holder',
      'Cable Organizer',
      'Battery Pack',
      'Rechargeable Batteries',
      'Travel Adapter',
      'Power Adapter',
      'Laptop Charger',
      'Replacement Stylus',
      'Drawing Pen',
      'NAS Storage Unit',
      'Network Switch',
      'Server Rack Shelf',
      'Thermal Label Roll',
      'Phone Stand',
      'Tablet Stand',
      'Monitor Privacy Filter',
      'Blue Light Glasses',
      'PC Case Fan',
      'CPU Cooler',
      'Graphics Card',
      'Motherboard',
      'RAM Kit',
      'Processor',
      'Computer Case',
      'Mechanical Numpad',
      'Portable DVD Drive',
      'USB Microphone',
    ],

    home: [
      'Desk Lamp',
      'Office Chair',
      'Standing Desk',
      'Air Purifier Filter',
      'LED Light Bulb',
      'Tool Kit',
      'Cordless Drill',
      'Garden Hose',
      'Indoor Plant',
      'Cookware Set',
      'Storage Bin Set',
      'Vacuum Filter',
      'Wall Shelf',
      'Throw Blanket',
      'Water Bottle Set',
      'Floor Lamp',
      'Table Lamp',
      'Ceiling Light',
      'Curtain Set',
      'Blackout Curtains',
      'Area Rug',
      'Doormat',
      'Bed Sheet Set',
      'Pillow Set',
      'Mattress Protector',
      'Laundry Basket',
      'Clothes Hangers',
      'Shoe Rack',
      'Bookcase',
      'Coffee Table',
      'Side Table',
      'TV Stand',
      'Dining Chair',
      'Bar Stool',
      'Folding Chair',
      'Step Ladder',
      'Storage Cabinet',
      'Drawer Organizer',
      'Bathroom Shelf',
      'Shower Curtain',
      'Bath Towel Set',
      'Hand Towel Set',
      'Kitchen Towels',
      'Dish Rack',
      'Drying Mat',
      'Cutlery Tray',
      'Knife Set',
      'Cutting Board',
      'Mixing Bowl Set',
      'Food Storage Container Set',
      'Trash Can',
      'Trash Bags',
      'Broom Set',
      'Mop Bucket Set',
      'Robot Vacuum',
      'Vacuum Cleaner',
      'Steam Mop',
      'Humidifier',
      'Dehumidifier',
      'Space Heater',
      'Tower Fan',
      'Air Fryer',
      'Toaster',
      'Electric Kettle',
      'Blender',
      'Coffee Maker',
      'Espresso Machine',
      'Rice Cooker',
      'Slow Cooker',
      'Pressure Cooker',
      'Microwave Oven',
      'Portable Heater',
      'Extension Cord',
      'Wall Mirror',
      'Picture Frame Set',
      'Laundry Hamper',
      'Closet Organizer',
      'Under Bed Storage Box',
      'Blanket Basket',
      'Planter Pot',
      'Plant Stand',
      'Garden Gloves',
      'Pruning Shears',
      'Watering Can',
      'Patio Chair',
      'Outdoor Table',
      'Grill Cover',
      'Fire Pit Cover',
      'Curtain Rod',
      'Shelf Bracket',
      'Adhesive Hooks',
      'Door Stop',
      'Window Cleaner',
      'Glass Cleaner',
      'All Purpose Cleaner',
      'Disinfecting Wipes',
      'Paper Napkin Set',
      'Reusable Food Wrap',
      'Ice Cube Tray',
      'Laundry Drying Rack',
    ],

    grocery: [
      'Coffee Beans',
      'Green Tea Pack',
      'Organic Honey',
      'Protein Powder',
      'Vitamin C Tablets',
      'Daily Multivitamin',
      'Hand Soap',
      'Shampoo',
      'Laundry Detergent',
      'Paper Towels',
      'Olive Oil',
      'Pasta Pack',
      'Sparkling Water',
      'Granola Bars',
      'Dish Soap',
      'Ground Coffee',
      'Instant Coffee',
      'Herbal Tea Pack',
      'Black Tea Pack',
      'Oat Milk',
      'Almond Milk',
      'Whole Milk',
      'Greek Yogurt',
      'Butter',
      'Cheddar Cheese',
      'Eggs',
      'Brown Bread',
      'Bagels',
      'Croissant Pack',
      'Breakfast Cereal',
      'Rolled Oats',
      'Peanut Butter',
      'Fruit Jam',
      'Chocolate Spread',
      'White Rice',
      'Brown Rice',
      'Quinoa Pack',
      'Dry Lentils',
      'Canned Beans',
      'Tomato Sauce',
      'Pasta Sauce',
      'Canned Tuna',
      'Frozen Vegetables',
      'Frozen Pizza',
      'Chicken Breast Pack',
      'Ground Beef Pack',
      'Salmon Fillet',
      'Bacon Pack',
      'Sausage Pack',
      'Apples',
      'Bananas',
      'Orange Bag',
      'Lemon Bag',
      'Avocados',
      'Tomatoes',
      'Cucumber',
      'Carrots',
      'Potatoes',
      'Onions',
      'Garlic',
      'Leafy Greens',
      'Salad Mix',
      'Bell Pepper Pack',
      'Broccoli',
      'Mushrooms',
      'Snack Crackers',
      'Potato Chips',
      'Mixed Nuts',
      'Trail Mix',
      'Dark Chocolate Bar',
      'Cookies Pack',
      'Ice Cream Tub',
      'Bottled Water',
      'Energy Drink',
      'Soft Drink Pack',
      'Orange Juice Carton',
      'Apple Juice Carton',
      'Coconut Water',
      'Maple Syrup',
      'Flour Bag',
      'Sugar Bag',
      'Sea Salt',
      'Black Pepper',
      'Spice Mix',
      'Ketchup',
      'Mayonnaise',
      'Mustard',
      'Vinegar',
      'Dishwasher Tablets',
      'Toilet Paper',
      'Facial Tissues',
      'Body Wash',
      'Conditioner',
      'Toothpaste',
      'Mouthwash',
      'Dental Floss',
      'Shaving Cream',
      'Razor Pack',
      'Deodorant',
    ],

    apparel: [
      'T-shirt',
      'Jeans',
      'Sneakers',
      'Jacket',
      'Winter Coat',
      'Dress Shirt',
      'Socks Pack',
      'Hat',
      'Sunglasses',
      'Wallet',
      'Running Shorts',
      'Hoodie',
      'Backpack',
      'Belt',
      'Canvas Shoes',
      'Polo Shirt',
      'Long Sleeve Shirt',
      'Tank Top',
      'Blouse',
      'Sweater',
      'Cardigan',
      'Zip Hoodie',
      'Joggers',
      'Chinos',
      'Cargo Pants',
      'Leggings',
      'Skirt',
      'Dress',
      'Suit Jacket',
      'Blazer',
      'Dress Pants',
      'Tie',
      'Bow Tie',
      'Scarf',
      'Beanie',
      'Baseball Cap',
      'Gloves',
      'Winter Gloves',
      'Rain Jacket',
      'Puffer Jacket',
      'Windbreaker',
      'Pajama Set',
      'Bathrobe',
      'Slippers',
      'Sandals',
      'Boots',
      'Chelsea Boots',
      'Running Shoes',
      'Training Shoes',
      'Dress Shoes',
      'Loafers',
      'Work Boots',
      'Flip Flops',
      'Swimwear',
      'Swim Trunks',
      'Bikini Set',
      'Sports Bra',
      'Bra',
      'Underwear Pack',
      'Boxer Briefs',
      'Thermal Top',
      'Thermal Bottoms',
      'Compression Shirt',
      'Compression Shorts',
      'Denim Jacket',
      'Leather Jacket',
      'Vest',
      'Fleece Jacket',
      'Apron',
      'Uniform Shirt',
      'Uniform Pants',
      'Workwear Jacket',
      'Tote Bag',
      'Crossbody Bag',
      'Handbag',
      'Duffel Bag',
      'Luggage Set',
      'Carry On Suitcase',
      'Umbrella',
      'Watch Strap',
      'Fashion Watch',
      'Earrings',
      'Necklace',
      'Bracelet',
      'Ring',
      'Hair Accessories Set',
      'Hair Tie Pack',
      'Capri Pants',
      'Ankle Socks Pack',
      'Crew Socks Pack',
      'Dress Socks Pack',
      'Sun Hat',
      'Workout Tank',
      'Track Jacket',
      'Track Pants',
      'School Backpack',
    ],

    food: [
      'Cheeseburger',
      'French Fries',
      'Pepperoni Pizza',
      'Veggie Burger',
      'Caesar Salad',
      'Breakfast Burrito',
      'Pancake Stack',
      'Cappuccino',
      'Latte',
      'Orange Juice',
      'Chicken Wrap',
      'Iced Coffee',
      'Soup Bowl',
      'Sandwich Combo',
      'Lemonade',
      'Espresso',
      'Americano',
      'Mocha',
      'Hot Chocolate',
      'Tea',
      'Iced Tea',
      'Matcha Latte',
      'Bagel Sandwich',
      'Breakfast Sandwich',
      'Omelette',
      'Scrambled Eggs Plate',
      'Waffle Plate',
      'French Toast',
      'Hash Browns',
      'Fruit Cup',
      'Yogurt Parfait',
      'Grilled Cheese',
      'Turkey Sandwich',
      'Ham Sandwich',
      'Club Sandwich',
      'Tuna Sandwich',
      'Chicken Caesar Wrap',
      'Falafel Wrap',
      'Rice Bowl',
      'Chicken Bowl',
      'Beef Bowl',
      'Noodle Bowl',
      'Pasta Alfredo',
      'Spaghetti Bolognese',
      'Mac and Cheese',
      'Chicken Tenders',
      'Fried Chicken Meal',
      'Fish and Chips',
      'Grilled Salmon Plate',
      'Steak Plate',
      'Roasted Vegetables',
      'Garlic Bread',
      'Mashed Potatoes',
      'Coleslaw',
      'Side Salad',
      'Tomato Soup',
      'Chicken Noodle Soup',
      'Minestrone Soup',
      'Sushi Roll',
      'Burrito Bowl',
      'Taco Plate',
      'Quesadilla',
      'Nachos',
      'Margherita Pizza',
      'BBQ Chicken Pizza',
      'Veggie Pizza',
      'Ice Cream Cone',
      'Brownie',
      'Cheesecake Slice',
      'Cookie',
      'Muffin',
      'Croissant',
      'Donut',
      'Milkshake',
      'Smoothie',
      'Bottled Water',
      'Soft Drink',
      'Sparkling Water',
      'Meal Deal',
      'Lunch Combo',
      'Dinner Combo',
      'Kids Meal',
      'Family Meal',
      'Extra Sauce',
      'Side of Rice',
      'Extra Cheese',
      'Add Bacon',
      'Add Avocado',
      'Gluten Free Option',
      'Vegan Option',
      'Catering Tray',
      'Boxed Lunch',
      'Party Platter',
      'Coffee Traveler',
      'Dessert Box',
      'Snack Box',
    ],

    services: [
      'Assembly Service',
      'Installation Service',
      'Technical Support Session',
      'Home Cleaning Service',
      'Oil Change',
      'Massage Session',
      'Dental Cleaning',
      'General Consultation',
      'Personal Training Session',
      'Accounting Service',
      'Website Development',
      'Design Package',
      'Repair Visit',
      'Inspection Service',
      'Remote Setup Session',
      'On-site Setup',
      'Delivery Service',
      'Express Delivery Service',
      'White Glove Delivery',
      'Furniture Assembly',
      'Appliance Installation',
      'TV Mounting Service',
      'Network Setup Service',
      'Device Migration Service',
      'Data Recovery Service',
      'Virus Removal Service',
      'Software Configuration',
      'System Audit',
      'Cloud Setup Service',
      'Backup Configuration',
      'Home Visit Consultation',
      'Virtual Consultation',
      'Video Editing Service',
      'Photo Editing Service',
      'Translation Service',
      'Proofreading Service',
      'Resume Review',
      'Tutoring Session',
      'Language Lesson',
      'Music Lesson',
      'Cleaning Add-on',
      'Deep Cleaning Service',
      'Window Cleaning Service',
      'Carpet Cleaning Service',
      'Pressure Washing Service',
      'Lawn Care Service',
      'Garden Maintenance',
      'Snow Removal Service',
      'Pest Control Visit',
      'Locksmith Service',
      'Plumbing Service',
      'Electrical Service',
      'HVAC Service Call',
      'Roof Inspection',
      'Handyman Visit',
      'Painting Service',
      'Drywall Repair',
      'Auto Detailing',
      'Tire Rotation',
      'Brake Inspection',
      'Battery Replacement Service',
      'Car Wash Package',
      'Wellness Consultation',
      'Therapy Session',
      'Coaching Session',
      'Legal Consultation',
      'Tax Preparation Service',
      'Bookkeeping Service',
      'Payroll Service',
      'Brand Strategy Session',
      'SEO Audit',
      'Advertising Campaign Setup',
      'Content Writing Service',
      'Social Media Management',
      'Hosting Setup Service',
      'Domain Registration Service',
      'Training Workshop',
      'Certification Exam Fee',
      'Maintenance Visit',
      'Service Plan Enrollment',
      'Extended Warranty Registration',
      'Calibration Service',
      'Equipment Rental',
      'Pickup Service',
      'Courier Service',
      'Gift Wrapping Service',
      'Custom Engraving Service',
      'Monogram Service',
      'Priority Processing',
      'Emergency Support',
      'After Hours Support',
      'Monthly Retainer',
      'Consulting Package',
      'Project Management Service',
      'UI Review Session',
      'Code Review Service',
      'Security Assessment',
    ],

    subscriptions: [
      'Monthly Membership',
      'Premium Subscription',
      'Pro Subscription',
      'Cloud Storage Plan',
      'Email Hosting',
      'Software License',
      'Developer Tool Subscription',
      'Coffee Subscription',
      'Tea Subscription',
      'Magazine Subscription',
      'Streaming Membership',
      'Support Plan',
      'Analytics Add-on',
      'Backup Plan',
      'Newsletter Bundle',
      'Annual Membership',
      'Basic Subscription',
      'Standard Subscription',
      'Enterprise Subscription',
      'Family Plan',
      'Student Plan',
      'Team Plan',
      'Business Plan',
      'Starter Plan',
      'Plus Plan',
      'Unlimited Plan',
      'Monthly Software License',
      'Annual Software License',
      'Antivirus Subscription',
      'VPN Subscription',
      'Password Manager Subscription',
      'Website Hosting Plan',
      'Managed Hosting Plan',
      'Domain Renewal',
      'SSL Certificate Renewal',
      'Productivity Suite License',
      'CRM Subscription',
      'Accounting Software Plan',
      'Marketing Automation Plan',
      'Email Marketing Plan',
      'Customer Support Seat',
      'Help Desk Plan',
      'Chat Support Subscription',
      'Monitoring Plan',
      'Incident Response Plan',
      'Data Plan',
      'Mobile Plan',
      'Internet Plan',
      'TV Package',
      'News Subscription',
      'Digital Newspaper Subscription',
      'Research Access Subscription',
      'Learning Platform Subscription',
      'Course Membership',
      'Gym Membership',
      'Yoga Membership',
      'Meal Plan Subscription',
      'Vitamin Subscription',
      'Pet Food Subscription',
      'Diaper Subscription',
      'Cleaning Supplies Subscription',
      'Shaving Subscription',
      'Beauty Box Subscription',
      'Book Club Subscription',
      'Audiobook Subscription',
      'Music Streaming Subscription',
      'Video Streaming Subscription',
      'Gaming Membership',
      'Server Hosting Plan',
      'API Access Plan',
      'Developer Seat License',
      'Collaboration Suite Plan',
      'Document Storage Plan',
      'Cloud Compute Plan',
      'Database Hosting Plan',
      'Object Storage Plan',
      'Security Add-on',
      'Compliance Add-on',
      'Priority Support Plan',
      'Maintenance Contract',
      'Extended Coverage Plan',
      'Warranty Subscription',
      'Device Protection Plan',
      'Roadside Assistance Plan',
      'Travel Membership',
      'Lounge Membership',
      'Rewards Membership',
      'VIP Membership',
      'Auto Refill Subscription',
      'Print Subscription',
      'Fax Line Subscription',
      'Virtual Mailbox Plan',
      'Remote Backup Service',
      'Team Analytics Add-on',
      'Premium Content Access',
      'Class Pass',
      'Season Membership',
    ],

    travel: [
      'Round Trip Flight',
      'One Way Flight',
      'Hotel Stay',
      'Room Reservation',
      'Car Rental',
      'Airport Transfer',
      'Travel Insurance',
      'Extra Baggage',
      'Priority Boarding',
      'Seat Selection',
      'Train Ticket',
      'Shuttle Transfer',
      'Lounge Access',
      'Resort Booking',
      'Parking Reservation',
      'Bus Ticket',
      'Ferry Ticket',
      'Cruise Booking',
      'Tour Package',
      'City Pass',
      'Metro Pass',
      'Day Pass',
      'Rail Pass',
      'Sleeper Cabin Upgrade',
      'Premium Economy Upgrade',
      'Business Class Upgrade',
      'Hotel Breakfast Add-on',
      'Late Checkout',
      'Early Check-in',
      'Room Upgrade',
      'Sea View Upgrade',
      'Mountain View Upgrade',
      'Cabin Upgrade',
      'Travel SIM Card',
      'eSIM Data Plan',
      'Visa Processing Fee',
      'Border Transfer',
      'Private Transfer',
      'Shared Transfer',
      'Boat Excursion',
      'Guided Tour',
      'Museum Pass',
      'Attraction Bundle',
      'Ski Pass',
      'Lift Ticket',
      'Equipment Rental',
      'Bike Rental',
      'Scooter Rental',
      'Camper Van Rental',
      'Fuel Package',
      'Road Toll Pass',
      'Child Seat Rental',
      'GPS Rental',
      'Additional Driver Fee',
      'Pet Travel Fee',
      'Cabin Baggage',
      'Checked Baggage',
      'Oversized Baggage',
      'Sports Equipment Fee',
      'Travel Meal',
      'In-flight Wi-Fi',
      'Window Seat Upgrade',
      'Aisle Seat Upgrade',
      'Extra Legroom Seat',
      'Airport Fast Track',
      'Boarding Pass Reprint Fee',
      'Port Fee',
      'Resort Fee',
      'City Tax',
      'Service Charge',
      'Booking Amendment Fee',
      'Cancellation Protection',
      'Flexible Fare Add-on',
      'Hop-on Hop-off Pass',
      'Camping Pitch Reservation',
      'Cabin Stay',
      'Hostel Stay',
      'Vacation Rental',
      'Apartment Stay',
      'Travel Voucher',
      'Excursion Ticket',
      'Theme Park Transfer',
      'Parking Pass',
      'Rail Seat Reservation',
      'Travel Adapter Pack',
      'Trip Protection Plan',
      'Baggage Protection Plan',
      'Airport Hotel Stay',
      'Meet and Greet Service',
      'Fast Ferry Ticket',
      'Scenic Train Ticket',
      'Charter Flight',
      'Destination Package',
      'Weekend Getaway Package',
      'Honeymoon Package',
      'Family Travel Package',
      'Adventure Package',
    ],

    events: [
      'Conference Ticket',
      'VIP Pass',
      'General Admission Ticket',
      'Museum Entry',
      'Concert Ticket',
      'Cinema Ticket',
      'Theater Ticket',
      'Theme Park Pass',
      'Workshop Registration',
      'Festival Pass',
      'Expo Badge',
      'Seminar Seat',
      'Masterclass Entry',
      'Virtual Event Pass',
      'Meetup Ticket',
      'Webinar Registration',
      'Trade Show Pass',
      'Speaker Dinner Ticket',
      'Networking Event Ticket',
      'After Party Pass',
      'Backstage Pass',
      'Early Access Pass',
      'Student Ticket',
      'Child Ticket',
      'Adult Ticket',
      'Senior Ticket',
      'Season Ticket',
      'Day Ticket',
      'Weekend Pass',
      'Multi-Day Pass',
      'Reserved Seat Ticket',
      'Front Row Ticket',
      'Balcony Seat Ticket',
      'Box Seat Ticket',
      'Parking Pass',
      'Coat Check Fee',
      'Merchandise Voucher',
      'Drink Voucher',
      'Meal Voucher',
      'Photo Package',
      'Meet and Greet Pass',
      'Competition Entry',
      'Tournament Entry Fee',
      'Race Registration',
      'Charity Gala Ticket',
      'Fundraiser Ticket',
      'Award Ceremony Ticket',
      'Sports Match Ticket',
      'Hospitality Package',
      'Press Pass',
      'Vendor Booth Fee',
      'Exhibitor Package',
      'Sponsor Package',
      'Booth Upgrade',
      'Table Reservation',
      'Banquet Ticket',
      'Lunch Session Ticket',
      'Breakfast Session Ticket',
      'Closing Party Ticket',
      'Opening Ceremony Ticket',
      'Guided Experience Ticket',
      'Audio Guide Rental',
      'Locker Rental',
      'Equipment Rental',
      'Virtual Workshop Seat',
      'Digital Replay Access',
      'Certificate Fee',
      'Admission Bundle',
      'Fan Zone Pass',
      'Premium Lounge Pass',
      'Fast Entry Pass',
      'Queue Skip Pass',
      'Event Insurance',
      'Badge Reprint Fee',
      'Companion Ticket',
      'Group Ticket',
      'Family Ticket',
      'School Group Ticket',
      'Photo Booth Package',
      'Signed Poster Add-on',
      'Commemorative Program',
      'Merch Bundle',
      'Streaming Access Pass',
      'Hybrid Event Access',
      'Panel Session Ticket',
      'Training Day Pass',
      'VIP Dinner Ticket',
      'Workshop Materials Fee',
      'Exhibition Catalog',
      'Arena Floor Ticket',
      'Standing Ticket',
      'Seated Ticket',
      'Fan Club Pre-sale Ticket',
      'Community Event Ticket',
      'Private Screening Ticket',
      'Launch Event Ticket',
    ],

    bundles: [
      'Family Meal Bundle',
      'Starter Bundle',
      'Essentials Bundle',
      'Premium Bundle',
      'Home Office Bundle',
      'Gaming Bundle',
      'Travel Bundle',
      'Wellness Bundle',
      'Beauty Bundle',
      'Custom Package',
      'Smart Home Bundle',
      'Starter Kit',
      'Office Setup Bundle',
      'Maintenance Bundle',
      'Care Package',
      'Work From Home Bundle',
      'Back to School Bundle',
      'Holiday Bundle',
      'Weekend Bundle',
      'New Customer Bundle',
      'Gift Bundle',
      'Seasonal Bundle',
      'Kitchen Bundle',
      'Bathroom Bundle',
      'Bedroom Bundle',
      'Living Room Bundle',
      'Cleaning Bundle',
      'Laundry Bundle',
      'Snack Bundle',
      'Breakfast Bundle',
      'Coffee Bundle',
      'Tea Bundle',
      'Movie Night Bundle',
      'Party Bundle',
      'BBQ Bundle',
      'Picnic Bundle',
      'Baby Care Bundle',
      'Pet Care Bundle',
      'Travel Essentials Kit',
      'Charging Bundle',
      'Creator Bundle',
      'Streaming Bundle',
      'Photography Bundle',
      'Fitness Bundle',
      'Recovery Bundle',
      'Camping Bundle',
      'Hiking Bundle',
      'Office Supply Bundle',
      'Study Bundle',
      'Remote Team Bundle',
      'Security Bundle',
      'Network Bundle',
      'Storage Bundle',
      'Backup Bundle',
      'Productivity Bundle',
      'Developer Bundle',
      'Launch Bundle',
      'Business Starter Pack',
      'Repair Kit',
      'Cleaning Kit',
      'Welcome Pack',
      'Loyalty Bundle',
      'Subscription Bundle',
      'Meal Prep Bundle',
      'Family Value Pack',
      'Party Pack',
      'Trial Pack',
      'Sample Pack',
      'Premium Care Package',
      'Refill Bundle',
      'Replacement Bundle',
      'Accessory Bundle',
      'Protection Bundle',
      'Travel Comfort Bundle',
      'Commuter Bundle',
      'Starter Set',
      'Gift Set',
      'Value Set',
      'Complete Kit',
      'Holiday Gift Set',
      'Event Starter Pack',
      'Business Essentials Bundle',
      'Home Maintenance Kit',
      'Office Productivity Kit',
      'Wellness Starter Kit',
      'Beauty Essentials Set',
      'Tech Essentials Kit',
      'Creator Starter Pack',
      'Conference Bundle',
      'Training Bundle',
      'Onboarding Package',
      'Upgrade Bundle',
      'Family Essentials Bundle',
      'Home Refresh Bundle',
      'Desk Setup Kit',
      'Kitchen Starter Set',
      'Bathroom Essentials Set',
      'Care Essentials Kit',
    ],

    beauty: [
      'Face Cleanser',
      'Moisturizer',
      'Sunscreen',
      'Serum',
      'Lip Balm',
      'Hand Cream',
      'Body Lotion',
      'Body Scrub',
      'Face Mask',
      'Eye Cream',
      'Makeup Remover',
      'Micellar Water',
      'Foundation',
      'Concealer',
      'Powder',
      'Blush',
      'Bronzer',
      'Highlighter',
      'Mascara',
      'Eyeliner',
      'Eyeshadow Palette',
      'Brow Pencil',
      'Lipstick',
      'Lip Gloss',
      'Lip Liner',
      'Nail Polish',
      'Nail Care Set',
      'Shampoo Bar',
      'Conditioner Bar',
      'Hair Mask',
      'Hair Oil',
      'Heat Protectant Spray',
      'Dry Shampoo',
      'Hair Brush',
      'Makeup Brush Set',
      'Beauty Sponge Pack',
      'Perfume',
      'Fragrance Mist',
      'Bath Bomb Set',
      'Soap Bar Set',
      'Body Wash',
      'Shaving Gel',
      'Razor Set',
      'Cotton Pads',
      'Cotton Swabs',
      'Travel Beauty Kit',
      'Skincare Set',
      'Makeup Set',
      'Grooming Kit',
      'Beard Oil',
      'Beard Trimmer',
      'Aftershave Balm',
      'Facial Roller',
      'Cleansing Balm',
      'Toner',
      'Hydrating Mist',
      'Acne Patch Pack',
      'Pimple Treatment',
      'Foot Cream',
      'Cuticle Oil',
    ],

    baby: [
      'Diapers Pack',
      'Baby Wipes',
      'Baby Formula',
      'Baby Bottle Set',
      'Bottle Brush',
      'Pacifier Pack',
      'Baby Blanket',
      'Swaddle Set',
      'Baby Towels',
      'Baby Shampoo',
      'Baby Wash',
      'Diaper Cream',
      'Changing Pad',
      'Changing Pad Cover',
      'Baby Monitor',
      'Stroller',
      'Car Seat',
      'Booster Seat',
      'High Chair',
      'Baby Carrier',
      'Teething Toy',
      'Rattle Set',
      'Baby Socks',
      'Baby Bodysuit',
      'Sleep Sack',
      'Crib Sheet Set',
      'Bassinet',
      'Nursery Organizer',
      'Baby Food Pouches',
      'Sippy Cup',
      'Training Cup',
      'Burp Cloth Set',
      'Bib Set',
      'Nursing Pillow',
      'Milk Storage Bags',
      'Breast Pump Accessory',
      'Toddler Snack Cup',
      'Baby Bath Tub',
      'Baby Nail Kit',
      'Baby Thermometer',
      'Stroller Rain Cover',
      'Pacifier Clip',
      'Baby Toy Set',
      'Activity Gym',
      'Play Mat',
      'Baby Gate',
      'Outlet Cover Pack',
      'Cabinet Lock Set',
      'Crib Mobile',
      'Toddler Plate Set',
    ],

    pet: [
      'Dog Food',
      'Cat Food',
      'Pet Treats',
      'Dog Leash',
      'Dog Collar',
      'Cat Litter',
      'Litter Box',
      'Pet Bed',
      'Pet Carrier',
      'Pet Shampoo',
      'Grooming Brush',
      'Pet Nail Clippers',
      'Pet Bowl Set',
      'Water Fountain',
      'Dog Toy',
      'Cat Toy',
      'Chew Toy',
      'Scratch Post',
      'Pet Blanket',
      'Waste Bag Roll',
      'Training Pad Pack',
      'Pet Stain Remover',
      'Flea Treatment',
      'Tick Treatment',
      'Pet Vitamins',
      'Pet Harness',
      'Car Seat Cover for Pets',
      'Pet Travel Bowl',
      'Pet Crate',
      'Aquarium Filter',
      'Fish Food',
      'Bird Seed',
      'Small Pet Bedding',
      'Hamster Wheel',
      'Pet Cooling Mat',
      'Pet Jacket',
      'Pet Tag',
      'Pet Gate',
      'Pet Toothbrush',
      'Pet Toothpaste',
    ],

    office: [
      'Notebook',
      'Planner',
      'Desk Calendar',
      'Pens Pack',
      'Pencils Pack',
      'Highlighter Set',
      'Marker Set',
      'Sticky Notes',
      'Printer Paper',
      'Copy Paper',
      'Binder',
      'Binder Dividers',
      'Folder Set',
      'File Organizer',
      'Desk Organizer',
      'Stapler',
      'Staples Pack',
      'Tape Dispenser',
      'Packing Tape',
      'Scissors',
      'Paper Clips',
      'Binder Clips',
      'Label Maker Tape',
      'Whiteboard',
      'Whiteboard Markers',
      'Flip Chart Pad',
      'Laminating Pouches',
      'Laminator',
      'Desk Pad',
      'Calculator',
      'Shipping Labels',
      'Envelopes Pack',
      'Bubble Mailers',
      'Padded Envelopes',
      'Shipping Box Set',
      'Mailing Tube',
      'Document Folder',
      'Clipboards',
      'Name Badge Holders',
      'Business Card Holder',
      'Receipt Book',
      'Cash Box',
      'Time Clock',
      'Paper Shredder',
      'Desk Tray',
      'Bookends',
      'Rolling Cart',
      'Conference Speakerphone',
      'Headset',
      'Office Supply Kit',
    ],

    books: [
      'Hardcover Book',
      'Paperback Book',
      'Ebook Download',
      'Audiobook Download',
      'Workbook',
      'Study Guide',
      'Notebook Journal',
      'Sketchbook',
      'Coloring Book',
      'Recipe Book',
      'Travel Guide',
      'Reference Manual',
      'Technical Manual',
      'Training Handbook',
      'Course Workbook',
      'Exam Prep Book',
      'Children Book',
      'Young Adult Novel',
      'Mystery Novel',
      'Science Fiction Novel',
      'Fantasy Novel',
      'Biography',
      'Memoir',
      'Self Help Book',
      'Business Book',
      'Language Learning Book',
      'Dictionary',
      'Thesaurus',
      'Magazine Issue',
      'Comic Book',
    ],

    health: [
      'Pain Relief Tablets',
      'Cold and Flu Relief',
      'Allergy Tablets',
      'Cough Syrup',
      'Throat Lozenges',
      'Nasal Spray',
      'First Aid Kit',
      'Bandage Pack',
      'Gauze Pads',
      'Antiseptic Wipes',
      'Thermometer',
      'Blood Pressure Monitor',
      'Pulse Oximeter',
      'Face Masks Pack',
      'Hand Sanitizer',
      'Disinfectant Spray',
      'Electrolyte Drink Mix',
      'Protein Shake',
      'Meal Replacement Shake',
      'Fiber Supplement',
      'Omega 3 Capsules',
      'Magnesium Tablets',
      'Vitamin D Tablets',
      'Sleep Support Tablets',
      'Joint Support Supplement',
      'Heating Pad',
      'Ice Pack',
      'Compression Socks',
      'Foam Roller',
      'Resistance Band Set',
      'Yoga Mat',
      'Water Bottle',
      'Pill Organizer',
      'Contact Lens Solution',
      'Eye Drops',
      'Toothbrush',
      'Electric Toothbrush Head',
      'Mouth Guard',
      'Prenatal Vitamins',
      'Digestive Support Capsules',
    ],

    automotive: [
      'Motor Oil',
      'Oil Filter',
      'Air Filter',
      'Cabin Air Filter',
      'Windshield Wiper Blades',
      'Car Wash Soap',
      'Microfiber Towel Set',
      'Tire Inflator',
      'Jump Starter',
      'Battery Charger',
      'Phone Mount',
      'Dash Camera',
      'Seat Cover Set',
      'Floor Mat Set',
      'Trunk Organizer',
      'Car Vacuum',
      'Emergency Road Kit',
      'Reflective Warning Triangle',
      'Ice Scraper',
      'Snow Brush',
      'Car Charger',
      'USB Car Adapter',
      'Tire Pressure Gauge',
      'Brake Fluid',
      'Coolant',
      'Windshield Washer Fluid',
      'Fuel Additive',
      'Touch Up Paint',
      'Polish and Wax Kit',
      'Headlight Restoration Kit',
      'Portable Cooler',
      'Roof Rack Accessory',
      'Cargo Net',
      'Sunshade',
      'Steering Wheel Cover',
      'Air Freshener',
      'Key Fob Battery',
      'OBD Scanner',
      'Tire Repair Kit',
      'License Plate Frame',
    ],

    sports: [
      'Yoga Mat',
      'Dumbbell Set',
      'Kettlebell',
      'Resistance Band Set',
      'Foam Roller',
      'Exercise Ball',
      'Jump Rope',
      'Pull Up Bar',
      'Fitness Tracker',
      'Running Belt',
      'Water Bottle',
      'Gym Bag',
      'Tennis Racket',
      'Tennis Balls',
      'Soccer Ball',
      'Basketball',
      'Volleyball',
      'Baseball Cap',
      'Baseball Glove',
      'Golf Balls',
      'Golf Glove',
      'Bike Helmet',
      'Cycling Gloves',
      'Bike Light Set',
      'Camping Chair',
      'Tent',
      'Sleeping Bag',
      'Hiking Backpack',
      'Trekking Poles',
      'Cooler Bag',
      'Fishing Rod',
      'Tackle Box',
      'Swim Goggles',
      'Swim Cap',
      'Pool Towel',
      'Ski Goggles',
      'Snow Gloves',
      'Protein Shaker Bottle',
      'Ankle Weights',
      'Agility Ladder',
    ],

    toys: [
      'Building Block Set',
      'Puzzle Set',
      'Board Game',
      'Card Game',
      'Action Figure',
      'Stuffed Animal',
      'Doll Set',
      'Toy Car',
      'Remote Control Car',
      'Toy Train Set',
      'Craft Kit',
      'Coloring Set',
      'Paint Set',
      'Play Dough Set',
      'Science Kit',
      'Learning Toy',
      'Stacking Toy',
      'Musical Toy',
      'Baby Rattle',
      'Outdoor Toy Set',
      'Bubble Machine',
      'Water Blaster',
      'Kite',
      'Scooter',
      'Helmet',
      'Basketball Hoop Toy',
      'Play Kitchen Set',
      'Pretend Tool Set',
      'Toy Dinosaur',
      'Toy Animal Set',
    ],

    software: [
      'Desktop App License',
      'Mobile App License',
      'Single User License',
      'Multi User License',
      'Team Seat License',
      'Annual Renewal',
      'One Time License',
      'API Credits',
      'Usage Pack',
      'Automation Add-on',
      'Reporting Add-on',
      'Export Add-on',
      'Security Module',
      'Compliance Module',
      'Priority Support Add-on',
      'Training Credits',
      'Implementation Package',
      'Data Migration Package',
      'Sandbox Environment',
      'Staging Environment',
      'Extra User Seat',
      'Admin Seat',
      'Viewer Seat',
      'Developer Seat',
      'Connector Add-on',
      'Integration Pack',
      'SSO Add-on',
      'Audit Log Add-on',
      'White Label Add-on',
      'Custom Domain Add-on',
    ],
  },
  composedOffers: {
    electronics: {
      adjectives: [
        'Wireless',
        'Portable',
        'Smart',
        'Premium',
        'Compact',
        'Fast',
        'Rechargeable',
        'Dual',
        'Ultra',
        'Mini',
        'Advanced',
        'High Speed',
        'High Power',
        'Heavy Duty',
        'Slim',
        'Ergonomic',
        'Adjustable',
        'Multi-Port',
        'Bluetooth',
        'USB',
        'USB-C',
        'Lightning',
        'Magnetic',
        'Travel',
        'Desktop',
        'Gaming',
        'Professional',
        'HD',
        '4K',
        '1080p',
        'Noise Cancelling',
        'Surround Sound',
        'Waterproof',
        'Rugged',
        'Secure',
        'Encrypted',
        'Network',
        'Mesh',
        'Intelligent',
        'Automatic',
        'Quick Charge',
        'Rapid Charge',
        'Long Range',
        'Low Latency',
        'RGB',
        'Mechanical',
        'Silent',
        'Wired',
        'Cordless',
        'Universal',
        'Sync',
        'Digital',
        'Touch',
        'High Capacity',
        'Backup',
        'External',
        'Hybrid',
        'Pro',
        'Max',
        'Essential',
      ],
      nouns: [
        'Keyboard',
        'Mouse',
        'Charger',
        'Cable',
        'Hub',
        'Speaker',
        'Headset',
        'Webcam',
        'Monitor',
        'Dock',
        'SSD',
        'Router',
        'Docking Station',
        'Charging Station',
        'Power Bank',
        'Battery Pack',
        'Adapter',
        'Power Adapter',
        'Laptop Stand',
        'Monitor Arm',
        'Microphone',
        'USB Microphone',
        'Headphones',
        'Earbuds',
        'Phone Stand',
        'Tablet Stand',
        'Tablet Case',
        'Phone Case',
        'Screen Protector',
        'Privacy Filter',
        'USB Drive',
        'Flash Drive',
        'Hard Drive',
        'External Drive',
        'NAS Unit',
        'Wi-Fi Extender',
        'Mesh Node',
        'Smart Plug',
        'Smart Bulb',
        'Thermostat',
        'Security Camera',
        'Video Doorbell',
        'Streaming Device',
        'Media Player',
        'Projector',
        'Mini Projector',
        'Printer',
        'Scanner',
        'Receipt Printer',
        'Label Printer',
        'Barcode Scanner',
        'Card Reader',
        'POS Terminal',
        'Ring Light',
        'Tripod',
        'Memory Card',
        'Network Switch',
        'Ethernet Adapter',
        'Cooling Pad',
        'Case Fan',
        'Controller',
        'Gamepad',
        'VR Headset',
        'Stylus',
        'Graphics Tablet',
        'Drawing Tablet',
        'Portable Monitor',
        'Desktop Dock',
        'Cable Organizer',
        'Travel Adapter',
        'Power Strip',
        'Surge Protector',
        'Wireless Charger',
        'Charging Pad',
        'Sync Cable',
        'Extension Cable',
        'HDMI Cable',
        'Display Cable',
        'Audio Interface',
        'Webcam Cover',
        'Lens Kit',
        'Camera',
        'Action Camera',
        'E-reader',
        'Smart Watch',
        'Fitness Tracker',
        'Home Assistant',
        'USB Dock',
        'Laptop Charger',
        'Signal Booster',
        'Bluetooth Receiver',
        'Bluetooth Transmitter',
        'Server Rack Shelf',
        'Thermal Printer',
        'Desktop Speaker',
        'Soundbar',
        'Portable Fan',
        'Device Mount',
        'Charging Cable',
      ],
      qualifiers: [
        'Kit',
        'Bundle',
        'Pack',
        'Stand',
        'Station',
        'Edition',
        'Set',
        'Series',
        'Collection',
        'Combo',
        'System',
        'Module',
        'Upgrade',
        'Accessory',
        'Adapter',
        'Mount',
        'Dock',
        'Base',
        'Case',
        'Cover',
        'Shield',
        'Replacement',
        'Refill',
        'Pro',
        'Plus',
        'Max',
        'Mini',
        'Lite',
        'Starter',
        'Essentials',
        'Travel',
        'Desktop',
        'Office',
        'Gaming',
        'Professional',
        'Home',
        'Portable',
        'Support',
        'Storage',
        'Protection',
      ],
      formats: [
        '{adj} {noun}',
        '{adj} {noun} {qual}',
        '{noun} {qual}',
        '{adj} {qual} {noun}',
        '{adj} {noun} - {qual}',
        '{noun} - {qual}',
        '{adj} {noun} ({qual})',
        '{noun} ({qual})',
        '{adj} {noun} Set',
        '{adj} {noun} Bundle',
        '{adj} {noun} Pack',
        '{adj} {noun} Edition',
        '{adj} {noun} Upgrade',
        '{qual} {noun}',
        '{adj} {qual} for {noun}',
      ],
      priceRange: { min: 8, max: 420 },
      quantityRange: { min: 1, max: 4 },
    },

    home: {
      adjectives: [
        'Modern',
        'Adjustable',
        'Deluxe',
        'Compact',
        'Classic',
        'Heavy Duty',
        'Soft',
        'Reusable',
        'Minimal',
        'Indoor',
        'Outdoor',
        'Foldable',
        'Stackable',
        'Decorative',
        'Everyday',
        'Premium',
        'Rustic',
        'Contemporary',
        'Natural',
        'Eco',
        'Multi-Purpose',
        'Space Saving',
        'Wall Mounted',
        'Free Standing',
        'Insulated',
        'Vacuum',
        'Non-Slip',
        'Machine Washable',
        'Soft Touch',
        'Textured',
        'Portable',
        'Lightweight',
        'Sturdy',
        'Delicate',
        'Kitchen',
        'Bathroom',
        'Bedroom',
        'Living Room',
        'Laundry',
        'Garden',
        'Patio',
        'Utility',
        'Storage',
        'Organized',
        'Slim',
        'Wide',
        'Tall',
        'Low Profile',
        'Easy Clean',
        'Refillable',
        'Ceramic',
        'Glass',
        'Wooden',
        'Metal',
        'Cotton',
        'Linen',
        'Bamboo',
        'Plush',
        'Premium Quality',
        'Essential',
      ],
      nouns: [
        'Lamp',
        'Chair',
        'Shelf',
        'Storage Bin',
        'Organizer',
        'Cookware Set',
        'Blanket',
        'Tool Set',
        'Bottle',
        'Tray',
        'Floor Lamp',
        'Desk Lamp',
        'Table Lamp',
        'Wall Shelf',
        'Bookcase',
        'Cabinet',
        'Drawer Organizer',
        'Closet Organizer',
        'Laundry Basket',
        'Laundry Hamper',
        'Drying Rack',
        'Trash Can',
        'Doormat',
        'Area Rug',
        'Curtain Set',
        'Blackout Curtain',
        'Rod Set',
        'Mirror',
        'Picture Frame',
        'Wall Hook',
        'Shelf Bracket',
        'Storage Basket',
        'Storage Box',
        'Food Container',
        'Bottle Set',
        'Mug Set',
        'Plate Set',
        'Bowl Set',
        'Cutlery Tray',
        'Knife Set',
        'Cutting Board',
        'Mixing Bowl',
        'Dish Rack',
        'Drying Mat',
        'Coffee Maker',
        'Kettle',
        'Toaster',
        'Blender',
        'Air Fryer',
        'Rice Cooker',
        'Slow Cooker',
        'Pressure Cooker',
        'Humidifier',
        'Dehumidifier',
        'Air Purifier',
        'Filter',
        'Vacuum Filter',
        'Water Filter',
        'Vacuum Cleaner',
        'Robot Vacuum',
        'Steam Mop',
        'Broom Set',
        'Mop Set',
        'Cleaning Caddy',
        'Tool Kit',
        'Step Ladder',
        'Extension Cord',
        'Power Strip',
        'LED Bulb',
        'Bulb Pack',
        'Throw Pillow',
        'Pillow Cover',
        'Bed Sheet Set',
        'Mattress Protector',
        'Towel Set',
        'Bath Mat',
        'Shower Curtain',
        'Soap Dispenser',
        'Toilet Brush',
        'Planter Pot',
        'Plant Stand',
        'Watering Can',
        'Garden Hose',
        'Garden Gloves',
        'Patio Chair',
        'Outdoor Table',
        'Grill Cover',
        'Fire Pit Cover',
        'Shoe Rack',
        'Entry Bench',
        'Side Table',
        'Coffee Table',
        'TV Stand',
        'Desk Organizer',
        'Pantry Bin',
        'Spice Rack',
        'Paper Towel Holder',
        'Glass Cleaner',
        'Cleaning Spray',
      ],
      qualifiers: [
        'Set',
        'Collection',
        'Pack',
        'Bundle',
        'Series',
        'Kit',
        'Tray',
        'Rack',
        'Stand',
        'Holder',
        'Organizer',
        'System',
        'Cover',
        'Refill',
        'Assortment',
        'Selection',
        'Edition',
        'Essentials',
        'Starter',
        'Upgrade',
        'Storage',
        'Care',
        'Comfort',
        'Decor',
        'Utility',
        'Household',
        'Kitchen',
        'Bathroom',
        'Bedroom',
        'Garden',
        'Laundry',
        'Indoor',
        'Outdoor',
      ],
      formats: [
        '{adj} {noun}',
        '{adj} {noun} {qual}',
        '{noun} {qual}',
        '{adj} {qual} {noun}',
        '{adj} {noun} - {qual}',
        '{noun} - {qual}',
        '{adj} {noun} ({qual})',
        '{noun} ({qual})',
        '{adj} {noun} Set',
        '{adj} {noun} Bundle',
        '{adj} {noun} Collection',
        '{adj} {noun} Pack',
        '{qual} {noun}',
        '{adj} {qual} for {noun}',
        '{adj} Home {noun}',
      ],
      priceRange: { min: 5, max: 260 },
      quantityRange: { min: 1, max: 6 },
    },

    grocery: {
      adjectives: [
        'Organic',
        'Fresh',
        'Roasted',
        'Natural',
        'Classic',
        'Daily',
        'Premium',
        'Family',
        'Citrus',
        'Herbal',
        'Whole Bean',
        'Ground',
        'Dark Roast',
        'Medium Roast',
        'Light Roast',
        'Unscented',
        'Gentle',
        'Rich',
        'Pure',
        'Raw',
        'Wildflower',
        'Creamy',
        'Crunchy',
        'Low Sugar',
        'Sugar Free',
        'Gluten Free',
        'Dairy Free',
        'Plant Based',
        'High Protein',
        'Low Sodium',
        'Sparkling',
        'Still',
        'Extra Virgin',
        'Cold Pressed',
        'Refined',
        'Unfiltered',
        'Multipurpose',
        'Household',
        'Bulk',
        'Value',
        'Single Serve',
        'Travel',
        'Family Size',
        'Mini',
        'Mixed',
        'Seasonal',
        'Fragrant',
        'Classic Blend',
        'Honey Roasted',
        'Natural Care',
        'Concentrated',
        'Sensitive',
        'Botanical',
        'Fortified',
        'Daily Use',
        'Pantry',
        'Breakfast',
        'Snack',
        'Essential',
        'Refill',
      ],
      nouns: [
        'Coffee Blend',
        'Tea Pack',
        'Granola Mix',
        'Honey Jar',
        'Protein Shake',
        'Vitamin Pack',
        'Soap Refill',
        'Detergent Bottle',
        'Snack Box',
        'Oil Bottle',
        'Ground Coffee',
        'Coffee Beans',
        'Coffee Pods',
        'Black Tea',
        'Green Tea',
        'Herbal Tea',
        'Oat Mix',
        'Cereal Box',
        'Nut Mix',
        'Trail Mix',
        'Fruit Bar',
        'Energy Bar',
        'Protein Bar',
        'Cookie Pack',
        'Cracker Box',
        'Pasta Pack',
        'Rice Bag',
        'Flour Bag',
        'Sugar Bag',
        'Salt Pack',
        'Spice Blend',
        'Sauce Bottle',
        'Pasta Sauce',
        'Tomato Sauce',
        'Soup Can',
        'Bean Can',
        'Tuna Can',
        'Sparkling Water',
        'Still Water',
        'Juice Carton',
        'Milk Carton',
        'Yogurt Pack',
        'Cheese Pack',
        'Butter Pack',
        'Egg Carton',
        'Bread Loaf',
        'Bagel Pack',
        'Muffin Pack',
        'Fruit Cup',
        'Salad Mix',
        'Olive Oil',
        'Cooking Oil',
        'Vinegar Bottle',
        'Ketchup Bottle',
        'Mustard Bottle',
        'Mayonnaise Jar',
        'Peanut Butter Jar',
        'Jam Jar',
        'Dish Soap',
        'Hand Soap',
        'Shampoo Bottle',
        'Conditioner Bottle',
        'Body Wash',
        'Laundry Pods',
        'Paper Towels',
        'Toilet Paper',
        'Tissue Box',
        'Cleaning Wipes',
        'Soap Bar',
        'Vitamin Bottle',
        'Supplement Bottle',
        'Electrolyte Mix',
        'Protein Powder',
        'Cooking Spray',
        'Syrup Bottle',
        'Chocolate Spread',
        'Snack Pack',
        'Refill Pouch',
        'Dishwasher Tablets',
        'Mouthwash Bottle',
        'Toothpaste Tube',
        'Shaving Cream',
        'Razor Pack',
        'Honey Bottle',
        'Nut Butter Jar',
        'Coconut Water',
        'Energy Drink',
        'Soft Drink',
        'Frozen Meal',
        'Frozen Vegetables',
        'Frozen Pizza',
        'Ice Cream Tub',
        'Granola Pack',
        'Tea Sachets',
        'Coffee Refill',
        'Soap Bottle',
        'Detergent Refill',
        'Cleaning Refill',
      ],
      qualifiers: [
        'Pack',
        'Refill',
        'Bundle',
        'Case',
        'Box',
        'Bottle',
        'Jar',
        'Bag',
        'Carton',
        'Pouch',
        'Can',
        'Set',
        'Tray',
        'Size',
        'Assortment',
        'Selection',
        'Value Pack',
        'Family Pack',
        'Travel Pack',
        'Daily Pack',
        'Starter Pack',
        'Variety Pack',
        'Household Pack',
        'Pantry Pack',
        'Refill Pack',
        'Reserve',
        'Supply',
        'Stock',
        'Care Pack',
        'Essentials',
      ],
      formats: [
        '{adj} {noun}',
        '{adj} {noun} {qual}',
        '{noun} {qual}',
        '{adj} {qual} {noun}',
        '{adj} {noun} - {qual}',
        '{noun} - {qual}',
        '{adj} {noun} ({qual})',
        '{noun} ({qual})',
        '{adj} {noun} Pack',
        '{adj} {noun} Bundle',
        '{adj} {noun} Case',
        '{adj} {noun} Refill',
        '{qual} {noun}',
        '{adj} Grocery {noun}',
        '{adj} Household {noun}',
      ],
      priceRange: { min: 2, max: 80 },
      quantityRange: { min: 1, max: 8 },
    },

    apparel: {
      adjectives: [
        'Classic',
        'Slim',
        'Relaxed',
        'Everyday',
        'Premium',
        'Sport',
        'Winter',
        'Lightweight',
        'Cotton',
        'Canvas',
        'Casual',
        'Formal',
        'Stretch',
        'Soft',
        'Heavyweight',
        'Oversized',
        'Tailored',
        'Athletic',
        'Running',
        'Training',
        'Thermal',
        'Insulated',
        'Water Resistant',
        'Windproof',
        'Breathable',
        'Quick Dry',
        'Crew',
        'V-Neck',
        'Long Sleeve',
        'Short Sleeve',
        'Vintage',
        'Modern',
        'Basic',
        'Essential',
        'Layered',
        'Performance',
        'Outdoor',
        'Urban',
        'Ribbed',
        'Fleece',
        'Padded',
        'Denim',
        'Leather',
        'Wool',
        'Linen',
        'Relaxed Fit',
        'Slim Fit',
        'Regular Fit',
        'Straight Leg',
        'High Rise',
        'Mid Rise',
        'Low Top',
        'High Top',
        'Crew Neck',
        'Zip',
        'Pullover',
        'Travel',
        'Commuter',
        'Signature',
        'Deluxe',
      ],
      nouns: [
        'Tee',
        'Jeans',
        'Sneakers',
        'Jacket',
        'Hoodie',
        'Shorts',
        'Backpack',
        'Cap',
        'Shirt',
        'Socks',
        'T-Shirt',
        'Polo',
        'Sweater',
        'Cardigan',
        'Blazer',
        'Dress Shirt',
        'Dress',
        'Skirt',
        'Leggings',
        'Joggers',
        'Chinos',
        'Pants',
        'Cargo Pants',
        'Sweatpants',
        'Tank',
        'Top',
        'Long Sleeve Tee',
        'Button Shirt',
        'Coat',
        'Puffer Jacket',
        'Rain Jacket',
        'Windbreaker',
        'Vest',
        'Beanie',
        'Sun Hat',
        'Scarf',
        'Gloves',
        'Belt',
        'Wallet',
        'Crossbody Bag',
        'Duffel Bag',
        'Tote Bag',
        'Handbag',
        'Suitcase',
        'Carry On',
        'Boots',
        'Dress Shoes',
        'Running Shoes',
        'Training Shoes',
        'Canvas Shoes',
        'Sandals',
        'Slippers',
        'Socks Pack',
        'Underwear Pack',
        'Bra',
        'Sports Bra',
        'Swimwear',
        'Swim Trunks',
        'Pajama Set',
        'Robe',
        'Uniform Shirt',
        'Uniform Pants',
        'Apron',
        'Watch',
        'Sunglasses',
        'Jewelry Set',
        'Necklace',
        'Bracelet',
        'Ring',
        'Earrings',
        'Hair Accessory',
        'Hair Tie',
        'Crew Sock',
        'Ankle Sock',
        'Dress Sock',
        'Thermal Top',
        'Thermal Bottom',
        'Compression Shirt',
        'Compression Shorts',
        'Track Jacket',
        'Track Pants',
        'School Backpack',
        'Travel Backpack',
        'Waist Bag',
        'Capri Pants',
        'Relaxed Tee',
        'Oxford Shirt',
        'Henley',
        'Pullover',
        'Zip Hoodie',
        'Winter Gloves',
        'Fleece Jacket',
        'Leather Jacket',
        'Denim Jacket',
        'Workwear Jacket',
        'Canvas Backpack',
        'Buckle Belt',
        'Beanie Hat',
        'Crew Tee',
      ],
      qualifiers: [
        'Pack',
        'Edition',
        'Set',
        'Collection',
        'Bundle',
        'Series',
        'Fit',
        'Style',
        'Cut',
        'Pair',
        'Assortment',
        'Wardrobe',
        'Essentials',
        'Starter',
        'Travel',
        'Seasonal',
        'Everyday',
        'Performance',
        'Training',
        'Outdoor',
        'Indoor',
        'Premium',
        'Basic',
        'Deluxe',
        'Combo',
        'Kit',
        'Value Pack',
        'Twin Pack',
        '3-Pack',
        '2-Pack',
      ],
      formats: [
        '{adj} {noun}',
        '{adj} {noun} {qual}',
        '{noun} {qual}',
        '{adj} {qual} {noun}',
        '{adj} {noun} - {qual}',
        '{noun} - {qual}',
        '{adj} {noun} ({qual})',
        '{noun} ({qual})',
        '{adj} {noun} Pack',
        '{adj} {noun} Set',
        '{adj} {noun} Collection',
        '{adj} Apparel {noun}',
        '{qual} {noun}',
        '{adj} Fit {noun}',
        '{adj} Everyday {noun}',
      ],
      priceRange: { min: 6, max: 180 },
      quantityRange: { min: 1, max: 5 },
    },

    food: {
      adjectives: [
        'Spicy',
        'Classic',
        'Grilled',
        'Large',
        'Double',
        'Fresh',
        'Iced',
        'House',
        'Signature',
        'Breakfast',
        'Deluxe',
        'Crispy',
        'Cheesy',
        'Loaded',
        'Roasted',
        'Smoked',
        'Hot',
        'Cold',
        'Premium',
        'Family',
        'Kids',
        'Mini',
        'Jumbo',
        'Veggie',
        'Vegan',
        'Gluten Free',
        'Combo',
        'Meal',
        'Lunch',
        'Dinner',
        'Morning',
        'Evening',
        'Sweet',
        'Savory',
        'House Special',
        'Chef',
        'Garden',
        'Chicken',
        'Beef',
        'Turkey',
        'Italian',
        'Mexican',
        'Mediterranean',
        'Crisp',
        'Golden',
        'Toasted',
        'Buttery',
        'Creamy',
        'Iced Cold',
        'Frozen',
        'Fresh Squeezed',
        'Herbal',
        'House Blend',
        'Extra',
        'Triple',
        'Stacked',
        'Baked',
        'Stone Baked',
        'Seasonal',
        'Signature Blend',
      ],
      nouns: [
        'Burger',
        'Pizza',
        'Salad',
        'Wrap',
        'Coffee',
        'Tea',
        'Juice',
        'Combo',
        'Meal',
        'Sandwich',
        'Latte',
        'Espresso',
        'Cappuccino',
        'Mocha',
        'Hot Chocolate',
        'Smoothie',
        'Milkshake',
        'Breakfast Sandwich',
        'Bagel',
        'Burrito',
        'Burrito Bowl',
        'Rice Bowl',
        'Noodle Bowl',
        'Pasta',
        'Soup',
        'Soup Bowl',
        'Fries',
        'Chicken Tenders',
        'Taco Plate',
        'Quesadilla',
        'Nachos',
        'Sushi Roll',
        'Boxed Lunch',
        'Snack Box',
        'Dessert Box',
        'Cookie',
        'Brownie',
        'Muffin',
        'Croissant',
        'Donut',
        'Waffle',
        'Pancake Stack',
        'French Toast',
        'Omelette',
        'Hash Browns',
        'Fruit Cup',
        'Yogurt Parfait',
        'Family Meal',
        'Kids Meal',
        'Lunch Combo',
        'Dinner Combo',
        'Party Platter',
        'Catering Tray',
        'Sandwich Combo',
        'Tea Set',
        'Coffee Traveler',
        'Lemonade',
        'Soft Drink',
        'Sparkling Water',
        'Bottled Water',
        'Iced Coffee',
        'Iced Tea',
        'Chicken Wrap',
        'Veggie Burger',
        'Cheeseburger',
        'Caesar Salad',
        'Breakfast Burrito',
        'Sandwich Box',
        'Meal Box',
        'Sharing Platter',
        'Bakery Box',
        'Dessert Tray',
        'Side Salad',
        'Rice Side',
        'Sauce Cup',
        'Extra Cheese',
        'Add-on',
        'Combo Set',
        'Meal Set',
        'Wrap Combo',
        'Pizza Slice',
        'Whole Pizza',
        'Tea Pot',
        'Coffee Pot',
        'Brunch Plate',
        'Chicken Bowl',
        'Beef Bowl',
        'Pasta Bowl',
        'Steak Plate',
        'Fish Plate',
        'Grilled Plate',
        'Roasted Bowl',
        'Fresh Juice',
        'Juice Bottle',
        'Smoothie Bowl',
        'Snack Tray',
        'Party Box',
        'Breakfast Box',
        'Lunch Box',
        'Dinner Box',
      ],
      qualifiers: [
        'Meal',
        'Combo',
        'Set',
        'Plate',
        'Box',
        'Tray',
        'Pack',
        'Bundle',
        'Deal',
        'Special',
        'Upgrade',
        'Option',
        'Side',
        'Add-on',
        'Family Pack',
        'Kids Pack',
        'Lunch Set',
        'Dinner Set',
        'Breakfast Set',
        'Snack Pack',
        'Value Meal',
        'Meal Deal',
        'Party Pack',
        'Sharing Box',
        'Deluxe',
        'Large',
        'Regular',
        'Single',
        'Double',
        'Platter',
      ],
      formats: [
        '{adj} {noun}',
        '{adj} {noun} {qual}',
        '{noun} {qual}',
        '{adj} {qual} {noun}',
        '{adj} {noun} - {qual}',
        '{noun} - {qual}',
        '{adj} {noun} ({qual})',
        '{noun} ({qual})',
        '{adj} {noun} Meal',
        '{adj} {noun} Combo',
        '{adj} {noun} Set',
        '{adj} House {noun}',
        '{qual} {noun}',
        '{adj} Chef {noun}',
        '{adj} Signature {noun}',
      ],
      priceRange: { min: 3, max: 40 },
      quantityRange: { min: 1, max: 6 },
    },

    services: {
      adjectives: [
        'Remote',
        'Priority',
        'Professional',
        'Standard',
        'Extended',
        'Onsite',
        'Annual',
        'Express',
        'Scheduled',
        'Preventive',
        'Emergency',
        'Routine',
        'Detailed',
        'Certified',
        'Premium',
        'Basic',
        'Comprehensive',
        'Advanced',
        'Digital',
        'Virtual',
        'Home',
        'Office',
        'Residential',
        'Commercial',
        'Technical',
        'Managed',
        'Dedicated',
        'Personal',
        'Custom',
        'Compliant',
        'Safety',
        'Diagnostic',
        'Repair',
        'Installation',
        'Follow-Up',
        'Maintenance',
        'Monthly',
        'Quarterly',
        'One-Time',
        'Same Day',
        'Next Day',
        'Field',
        'Mobile',
        'After Hours',
        'Weekend',
        'Quick',
        'Fast Track',
        'Deep',
        'Thorough',
        'Consultative',
        'Strategic',
        'Operational',
        'Planning',
        'Executive',
        'Core',
        'Essential',
        'Premium Care',
        'Support',
        'Inspection',
        'Service',
      ],
      nouns: [
        'Consultation',
        'Installation',
        'Repair',
        'Inspection',
        'Session',
        'Support',
        'Cleaning',
        'Tune-Up',
        'Audit',
        'Service',
        'Assessment',
        'Review',
        'Visit',
        'Maintenance',
        'Setup',
        'Configuration',
        'Migration',
        'Optimization',
        'Calibration',
        'Testing',
        'Training',
        'Workshop',
        'Monitoring',
        'Troubleshooting',
        'Upgrade',
        'Replacement',
        'Deployment',
        'Implementation',
        'Enrollment',
        'Registration',
        'Verification',
        'Evaluation',
        'Diagnostic',
        'Check',
        'Checkup',
        'Screening',
        'Planning',
        'Project Review',
        'Code Review',
        'Security Review',
        'Site Survey',
        'Deep Clean',
        'Pressure Wash',
        'Service Call',
        'Repair Call',
        'Support Call',
        'Home Visit',
        'Field Visit',
        'Wellness Session',
        'Therapy Session',
        'Massage Session',
        'Dental Cleaning',
        'Oil Change',
        'Tire Rotation',
        'Brake Check',
        'HVAC Service',
        'Plumbing Service',
        'Electrical Service',
        'Pest Control',
        'Garden Maintenance',
        'Window Cleaning',
        'Carpet Cleaning',
        'Locksmith Service',
        'Tax Preparation',
        'Bookkeeping',
        'Payroll Service',
        'SEO Audit',
        'Design Review',
        'Website Development',
        'Content Service',
        'Translation Service',
        'Proofreading Service',
        'Tutoring Session',
        'Coaching Session',
        'Legal Consultation',
        'Accounting Service',
        'Calibration Service',
        'Inspection Visit',
        'Repair Visit',
        'Setup Session',
        'Technical Session',
        'Cloud Setup',
        'Backup Setup',
        'Migration Service',
        'Data Recovery',
        'Virus Removal',
        'Remote Setup',
        'Onboarding',
        'Training Session',
        'Compliance Audit',
        'Safety Inspection',
        'Support Plan',
        'Maintenance Plan',
        'Consulting Package',
        'Managed Service',
        'Monitoring Service',
        'Response Service',
        'Inspection Package',
        'Repair Package',
        'Cleaning Package',
        'Support Package',
      ],
      qualifiers: [
        'Visit',
        'Package',
        'Plan',
        'Bundle',
        'Session',
        'Call',
        'Review',
        'Assessment',
        'Audit',
        'Check',
        'Program',
        'Enrollment',
        'Coverage',
        'Support',
        'Care',
        'Maintenance',
        'Upgrade',
        'Extension',
        'Contract',
        'Subscription',
        'Retainer',
        'Option',
        'Add-on',
        'Follow-Up',
        'Inspection',
        'Implementation',
        'Onboarding',
        'Pro',
        'Plus',
        'Max',
      ],
      formats: [
        '{adj} {noun}',
        '{adj} {noun} {qual}',
        '{noun} {qual}',
        '{adj} {qual} {noun}',
        '{adj} {noun} - {qual}',
        '{noun} - {qual}',
        '{adj} {noun} ({qual})',
        '{noun} ({qual})',
        '{adj} {noun} Package',
        '{adj} {noun} Plan',
        '{adj} {noun} Visit',
        '{adj} Service {noun}',
        '{qual} {noun}',
        '{adj} Professional {noun}',
        '{adj} Managed {noun}',
      ],
      priceRange: { min: 18, max: 600 },
      quantityRange: { min: 1, max: 2 },
    },

    subscriptions: {
      adjectives: [
        'Monthly',
        'Premium',
        'Pro',
        'Annual',
        'Family',
        'Advanced',
        'Cloud',
        'Creator',
        'Business',
        'Starter',
        'Basic',
        'Standard',
        'Enterprise',
        'Unlimited',
        'Team',
        'Student',
        'Personal',
        'Professional',
        'Digital',
        'Managed',
        'Secure',
        'Hosted',
        'Remote',
        'Backup',
        'Analytics',
        'Monitoring',
        'Streaming',
        'Learning',
        'Productivity',
        'Collaboration',
        'Developer',
        'Email',
        'Storage',
        'Data',
        'Compute',
        'Managed Support',
        'Priority',
        'VIP',
        'Rewards',
        'Seasonal',
        'Content',
        'Plus',
        'Max',
        'Essential',
        'Growth',
        'Scale',
        'Flexible',
        'Seat-Based',
        'Licensed',
        'All-Access',
        'Full Access',
        'Cloud Hosted',
        'Auto Renew',
        'Multi User',
        'Single User',
        'Shared',
        'Secure Access',
        'Power',
        'Platform',
        'Core',
      ],
      nouns: [
        'Membership',
        'Subscription',
        'Plan',
        'License',
        'Add-on',
        'Bundle',
        'Access',
        'Pass',
        'Seat',
        'Seat License',
        'Software License',
        'Cloud Storage',
        'Backup Plan',
        'Analytics Plan',
        'Support Plan',
        'Hosting Plan',
        'Domain Plan',
        'SSL Plan',
        'Learning Pass',
        'Streaming Pass',
        'Content Pass',
        'Class Pass',
        'Gym Membership',
        'Rewards Membership',
        'VIP Membership',
        'Roadside Plan',
        'Protection Plan',
        'Coverage Plan',
        'Device Plan',
        'Maintenance Contract',
        'Service Contract',
        'Team License',
        'Admin Seat',
        'Viewer Seat',
        'Developer Seat',
        'Workspace',
        'Workspace Plan',
        'Email Hosting',
        'Object Storage',
        'Compute Plan',
        'Database Plan',
        'API Access',
        'Monitoring Add-on',
        'Security Add-on',
        'Compliance Add-on',
        'Integration Pack',
        'Connector Pack',
        'Bundle Access',
        'Platform Access',
        'Premium Access',
        'Business Access',
        'Family Pass',
        'Season Pass',
        'Annual Pass',
        'Monthly Pass',
        'Creator Plan',
        'Pro Plan',
        'Business Plan',
        'Starter Plan',
        'Cloud Plan',
        'Personal Plan',
        'Team Plan',
        'Enterprise Plan',
        'Support Access',
        'Priority Support',
        'Backup Service',
        'Storage Service',
        'Content Subscription',
        'Digital Subscription',
        'Course Subscription',
        'Magazine Subscription',
        'Newsletter Bundle',
        'Tool Subscription',
        'Software Bundle',
        'License Pack',
        'Seat Pack',
        'Feature Pack',
        'Usage Pack',
        'Credit Pack',
        'Access Tier',
        'Subscription Tier',
        'Membership Tier',
        'License Tier',
        'Protection Pass',
        'Travel Membership',
        'Lounge Membership',
        'Care Membership',
        'Auto Refill',
        'Refill Plan',
        'Premium Bundle',
        'Access Bundle',
        'Cloud License',
        'Support Bundle',
        'Analytics Add-on',
        'Backup Add-on',
        'Streaming Membership',
        'Service Plan',
        'Hosting Subscription',
        'Digital Pass',
      ],
      qualifiers: [
        'Plan',
        'Tier',
        'Package',
        'Bundle',
        'Access',
        'Pass',
        'Seat',
        'License',
        'Coverage',
        'Support',
        'Upgrade',
        'Add-on',
        'Extension',
        'Renewal',
        'Option',
        'Contract',
        'Program',
        'Membership',
        'Subscription',
        'Edition',
        'Series',
        'Selection',
        'Essentials',
        'Starter',
        'Professional',
        'Business',
        'Enterprise',
        'Family',
        'Annual',
        'Monthly',
      ],
      formats: [
        '{adj} {noun}',
        '{adj} {noun} {qual}',
        '{noun} {qual}',
        '{adj} {qual} {noun}',
        '{adj} {noun} - {qual}',
        '{noun} - {qual}',
        '{adj} {noun} ({qual})',
        '{noun} ({qual})',
        '{adj} {noun} Plan',
        '{adj} {noun} Tier',
        '{adj} {noun} Package',
        '{adj} Subscription {noun}',
        '{qual} {noun}',
        '{adj} Access {noun}',
        '{adj} Cloud {noun}',
      ],
      priceRange: { min: 4, max: 160 },
      quantityRange: { min: 1, max: 3 },
    },

    travel: {
      adjectives: [
        'Round Trip',
        'One Way',
        'Priority',
        'Flexible',
        'Economy',
        'Business',
        'Airport',
        'Resort',
        'Express',
        'City',
        'Premium',
        'Standard',
        'Shared',
        'Private',
        'Direct',
        'Scenic',
        'Weekend',
        'Holiday',
        'Seasonal',
        'Adventure',
        'Family',
        'Couple',
        'Luxury',
        'Budget',
        'Fast Track',
        'Reserved',
        'Confirmed',
        'Prepaid',
        'Advance',
        'Last Minute',
        'Night',
        'Day',
        'Morning',
        'Evening',
        'Travel',
        'Tour',
        'Guided',
        'Island',
        'Mountain',
        'Beach',
        'Metro',
        'Rail',
        'Train',
        'Cruise',
        'Car',
        'Hotel',
        'Shuttle',
        'Transfer',
        'Lounge',
        'VIP',
        'Extra Legroom',
        'Window',
        'Aisle',
        'Checked',
        'Carry-On',
        'Premium Economy',
        'First Class',
        'All Inclusive',
        'Flexible Fare',
        'Protected',
      ],
      nouns: [
        'Flight',
        'Transfer',
        'Reservation',
        'Booking',
        'Ticket',
        'Rental',
        'Pass',
        'Stay',
        'Hotel Stay',
        'Room Booking',
        'Room Reservation',
        'Suite Upgrade',
        'Car Rental',
        'Train Ticket',
        'Bus Ticket',
        'Ferry Ticket',
        'Cruise Booking',
        'Tour Package',
        'Excursion Ticket',
        'City Pass',
        'Metro Pass',
        'Rail Pass',
        'Travel Pass',
        'Airport Transfer',
        'Shuttle Transfer',
        'Private Transfer',
        'Shared Transfer',
        'Travel Insurance',
        'Trip Protection',
        'Baggage Option',
        'Extra Baggage',
        'Seat Selection',
        'Priority Boarding',
        'Fast Track',
        'Lounge Access',
        'Parking Reservation',
        'Parking Pass',
        'Visa Processing',
        'Resort Booking',
        'Apartment Stay',
        'Vacation Rental',
        'Hostel Stay',
        'Cabin Stay',
        'Camping Reservation',
        'Ski Pass',
        'Lift Ticket',
        'Equipment Rental',
        'Bike Rental',
        'Scooter Rental',
        'GPS Rental',
        'Child Seat Rental',
        'Additional Driver',
        'Fuel Package',
        'Road Toll Pass',
        'Meal Option',
        'In-flight Wi-Fi',
        'Travel SIM',
        'eSIM Plan',
        'Travel Voucher',
        'Boarding Upgrade',
        'Cabin Upgrade',
        'Class Upgrade',
        'Seat Upgrade',
        'Hotel Breakfast',
        'Late Checkout',
        'Early Check-in',
        'Room Upgrade',
        'Sea View Upgrade',
        'Mountain View Upgrade',
        'Port Fee',
        'Resort Fee',
        'City Tax',
        'Service Charge',
        'Booking Amendment',
        'Cancellation Protection',
        'Flexible Fare',
        'Trip Package',
        'Weekend Package',
        'Honeymoon Package',
        'Family Package',
        'Adventure Package',
        'Travel Add-on',
        'Airport Hotel',
        'Meet and Greet',
        'Scenic Train',
        'Fast Ferry',
        'Destination Package',
        'Travel Adapter Pack',
        'Baggage Protection',
        'Travel Coverage',
        'Rail Seat Reservation',
        'Hop-on Hop-off Pass',
        'Attraction Bundle',
        'Museum Pass',
        'Theme Park Transfer',
        'Travel Credit',
        'Booking Credit',
        'Rental Protection',
        'Check-in Option',
      ],
      qualifiers: [
        'Package',
        'Upgrade',
        'Option',
        'Pass',
        'Bundle',
        'Selection',
        'Reservation',
        'Protection',
        'Coverage',
        'Plan',
        'Seat',
        'Class',
        'Fare',
        'Transfer',
        'Booking',
        'Stay',
        'Rental',
        'Add-on',
        'Extension',
        'Voucher',
        'Ticket',
        'Access',
        'Flex',
        'Plus',
        'Premium',
        'Economy',
        'Business',
        'Deluxe',
        'Express',
        'VIP',
      ],
      formats: [
        '{adj} {noun}',
        '{adj} {noun} {qual}',
        '{noun} {qual}',
        '{adj} {qual} {noun}',
        '{adj} {noun} - {qual}',
        '{noun} - {qual}',
        '{adj} {noun} ({qual})',
        '{noun} ({qual})',
        '{adj} {noun} Package',
        '{adj} {noun} Upgrade',
        '{adj} {noun} Option',
        '{adj} Travel {noun}',
        '{qual} {noun}',
        '{adj} Airport {noun}',
        '{adj} Resort {noun}',
      ],
      priceRange: { min: 12, max: 980 },
      quantityRange: { min: 1, max: 2 },
    },

    events: {
      adjectives: [
        'VIP',
        'General',
        'Premium',
        'Weekend',
        'All-Access',
        'Evening',
        'Morning',
        'Virtual',
        'Live',
        'Front Row',
        'Reserved',
        'Priority',
        'Early Access',
        'Backstage',
        'General Admission',
        'Deluxe',
        'Student',
        'Child',
        'Adult',
        'Senior',
        'Speaker',
        'Exhibitor',
        'Sponsor',
        'Press',
        'Fan',
        'Streaming',
        'Hybrid',
        'Multi-Day',
        'Single Day',
        'Full Day',
        'Half Day',
        'Closing',
        'Opening',
        'Private',
        'Community',
        'Launch',
        'Festival',
        'Concert',
        'Theater',
        'Cinema',
        'Expo',
        'Seminar',
        'Workshop',
        'Masterclass',
        'Training',
        'Networking',
        'Hospitality',
        'Fast Entry',
        'Queue Skip',
        'Premium Lounge',
        'Gold',
        'Silver',
        'Bronze',
        'Fan Club',
        'Partner',
        'Media',
        'Arena Floor',
        'Standing',
        'Seated',
        'Commemorative',
      ],
      nouns: [
        'Ticket',
        'Pass',
        'Entry',
        'Registration',
        'Badge',
        'Seat',
        'Access',
        'Admission',
        'Badge Pass',
        'Event Pass',
        'Conference Ticket',
        'Concert Ticket',
        'Cinema Ticket',
        'Theater Ticket',
        'Festival Pass',
        'Workshop Registration',
        'Masterclass Entry',
        'Seminar Seat',
        'Expo Badge',
        'Meetup Ticket',
        'Webinar Registration',
        'Trade Show Pass',
        'After Party Pass',
        'Backstage Pass',
        'Meet and Greet',
        'Photo Package',
        'Drink Voucher',
        'Meal Voucher',
        'Parking Pass',
        'Coat Check',
        'Merchandise Voucher',
        'Competition Entry',
        'Tournament Entry',
        'Race Registration',
        'Gala Ticket',
        'Fundraiser Ticket',
        'Award Ceremony Ticket',
        'Sports Match Ticket',
        'Hospitality Package',
        'Vendor Booth',
        'Exhibitor Package',
        'Sponsor Package',
        'Booth Upgrade',
        'Table Reservation',
        'Banquet Ticket',
        'Lunch Session',
        'Breakfast Session',
        'Closing Party Ticket',
        'Opening Ceremony Ticket',
        'Guided Experience',
        'Audio Guide',
        'Locker Rental',
        'Equipment Rental',
        'Digital Replay Access',
        'Certificate Fee',
        'Admission Bundle',
        'Fan Zone Pass',
        'Lounge Pass',
        'Fast Entry Pass',
        'Queue Skip Pass',
        'Event Insurance',
        'Badge Reprint',
        'Companion Ticket',
        'Group Ticket',
        'Family Ticket',
        'School Group Ticket',
        'Photo Booth Package',
        'Signed Poster Add-on',
        'Program Book',
        'Merch Bundle',
        'Streaming Access',
        'Hybrid Event Access',
        'Panel Session',
        'Training Day Pass',
        'VIP Dinner Ticket',
        'Materials Fee',
        'Exhibition Catalog',
        'Front Row Seat',
        'Arena Floor Ticket',
        'Standing Ticket',
        'Seated Ticket',
        'Community Event Ticket',
        'Private Screening Ticket',
        'Launch Event Ticket',
        'Virtual Pass',
        'Registration Fee',
        'Admission Ticket',
        'Entry Pass',
        'Seat Upgrade',
        'Access Upgrade',
        'Bundle Access',
        'Event Bundle',
        'Event Upgrade',
        'Session Pass',
        'Badge Upgrade',
        'Replay Pass',
        'Program Add-on',
      ],
      qualifiers: [
        'Package',
        'Bundle',
        'Upgrade',
        'Pass',
        'Add-on',
        'Access',
        'Seat',
        'Admission',
        'Entry',
        'Registration',
        'Voucher',
        'Option',
        'Selection',
        'Upgrade Pass',
        'Day Pass',
        'Weekend Pass',
        'VIP Upgrade',
        'Premium Access',
        'Fast Entry',
        'Replay Access',
        'Ticket Package',
        'Event Package',
        'Front Row',
        'Lounge Access',
        'Hospitality',
        'Certificate',
        'Materials',
        'Booth',
        'Sponsor',
        'Partner',
      ],
      formats: [
        '{adj} {noun}',
        '{adj} {noun} {qual}',
        '{noun} {qual}',
        '{adj} {qual} {noun}',
        '{adj} {noun} - {qual}',
        '{noun} - {qual}',
        '{adj} {noun} ({qual})',
        '{noun} ({qual})',
        '{adj} {noun} Package',
        '{adj} {noun} Bundle',
        '{adj} {noun} Upgrade',
        '{adj} Event {noun}',
        '{qual} {noun}',
        '{adj} Access {noun}',
        '{adj} Admission {noun}',
      ],
      priceRange: { min: 8, max: 420 },
      quantityRange: { min: 1, max: 4 },
    },

    bundles: {
      adjectives: [
        'Starter',
        'Premium',
        'Family',
        'Travel',
        'Office',
        'Wellness',
        'Gaming',
        'Home',
        'Beauty',
        'Seasonal',
        'Essential',
        'Ultimate',
        'Basic',
        'Standard',
        'Deluxe',
        'Holiday',
        'Weekend',
        'Business',
        'Creator',
        'Student',
        'Kids',
        'Household',
        'Kitchen',
        'Bathroom',
        'Bedroom',
        'Living Room',
        'Desk',
        'Remote Work',
        'Work From Home',
        'Back to School',
        'Party',
        'BBQ',
        'Picnic',
        'Coffee',
        'Tea',
        'Snack',
        'Breakfast',
        'Lunch',
        'Dinner',
        'Fitness',
        'Recovery',
        'Camping',
        'Hiking',
        'Pet Care',
        'Baby Care',
        'Tech',
        'Creator Studio',
        'Photography',
        'Streaming',
        'Security',
        'Charging',
        'Travel Comfort',
        'Commuter',
        'Cleaning',
        'Laundry',
        'Gift',
        'Welcome',
        'Loyalty',
        'Launch',
        'Upgrade',
      ],
      nouns: [
        'Bundle',
        'Package',
        'Kit',
        'Collection',
        'Set',
        'Starter Kit',
        'Care Package',
        'Gift Set',
        'Value Pack',
        'Essentials Kit',
        'Starter Pack',
        'Accessory Kit',
        'Protection Pack',
        'Travel Kit',
        'Desk Setup',
        'Office Setup',
        'Home Setup',
        'Gaming Setup',
        'Conference Pack',
        'Training Bundle',
        'Onboarding Package',
        'Family Pack',
        'Party Pack',
        'Meal Pack',
        'Snack Box',
        'Coffee Pack',
        'Tea Pack',
        'Wellness Set',
        'Beauty Set',
        'Tech Kit',
        'Charging Bundle',
        'Storage Bundle',
        'Backup Bundle',
        'Productivity Kit',
        'Developer Bundle',
        'Creator Pack',
        'Security Kit',
        'Maintenance Kit',
        'Cleaning Kit',
        'Laundry Kit',
        'Kitchen Set',
        'Bathroom Set',
        'Bedroom Set',
        'Work Kit',
        'Travel Pack',
        'Commuter Pack',
        'Holiday Set',
        'Seasonal Set',
        'Business Essentials',
        'Office Essentials',
        'Home Essentials',
        'Starter Collection',
        'Premium Collection',
        'Family Collection',
        'Comfort Kit',
        'Refresh Kit',
        'Care Kit',
        'Gift Bundle',
        'Value Bundle',
        'Complete Kit',
        'Sample Pack',
        'Trial Pack',
        'Refill Bundle',
        'Replacement Pack',
        'Accessory Pack',
        'Essentials Bundle',
        'Starter Bundle',
        'Premium Bundle',
        'Upgrade Bundle',
        'Launch Bundle',
        'School Pack',
        'Remote Team Pack',
        'Meeting Pack',
        'Conference Bundle',
        'Travel Essentials',
        'Recovery Kit',
        'Fitness Pack',
        'Beauty Bundle',
        'Season Pack',
        'Home Refresh',
        'Desk Kit',
        'Kitchen Starter',
        'Bathroom Essentials',
        'Bedroom Essentials',
        'Loyalty Pack',
        'Welcome Pack',
        'Holiday Gift Set',
        'Event Starter Pack',
        'Business Starter Pack',
        'Wellness Starter Kit',
        'Beauty Essentials Set',
        'Tech Essentials Kit',
        'Creator Starter Pack',
        'Family Essentials',
        'Care Essentials',
        'Comfort Bundle',
        'Premium Pack',
        'Series Set',
      ],
      qualifiers: [
        'Pack',
        'Edition',
        'Series',
        'Set',
        'Bundle',
        'Collection',
        'Kit',
        'Box',
        'Package',
        'Assortment',
        'Selection',
        'Essentials',
        'Starter',
        'Premium',
        'Family',
        'Travel',
        'Office',
        'Home',
        'Wellness',
        'Beauty',
        'Gaming',
        'Business',
        'Deluxe',
        'Value',
        'Holiday',
        'Seasonal',
        'Launch',
        'Upgrade',
        'Combo',
        'Complete',
      ],
      formats: [
        '{adj} {noun}',
        '{adj} {noun} {qual}',
        '{noun} {qual}',
        '{adj} {qual} {noun}',
        '{adj} {noun} - {qual}',
        '{noun} - {qual}',
        '{adj} {noun} ({qual})',
        '{noun} ({qual})',
        '{adj} {noun} Pack',
        '{adj} {noun} Bundle',
        '{adj} {noun} Set',
        '{adj} Bundle {noun}',
        '{qual} {noun}',
        '{adj} Essentials {noun}',
        '{adj} Starter {noun}',
      ],
      priceRange: { min: 10, max: 320 },
      quantityRange: { min: 1, max: 3 },
    },
  },
  itemCategories: [
    'Electronics',
    'Home',
    'Food',
    'Apparel',
    'Software',
    'Travel',
    'Services',
    'Tickets',
    'Subscriptions',
    'Grocery',
    'Logistics',
    'Household',
    'Home Goods',
    'Home Decor',
    'Home Improvement',
    'Kitchen',
    'Kitchenware',
    'Kitchen Appliances',
    'Dining',
    'Diningware',
    'Furniture',
    'Office Furniture',
    'Office Supplies',
    'Office Equipment',
    'Stationery',
    'Cleaning Supplies',
    'Laundry',
    'Bathroom',
    'Bedroom',
    'Living Room',
    'Garden',
    'Patio',
    'Outdoor',
    'Outdoor Living',
    'Tools',
    'Hardware',
    'Building Supplies',
    'Electrical',
    'Lighting',
    'Plumbing',
    'Storage',
    'Organization',
    'Appliances',
    'Small Appliances',
    'Major Appliances',
    'Consumer Electronics',
    'Computers',
    'Computer Accessories',
    'Computer Components',
    'Networking',
    'Mobile Devices',
    'Mobile Accessories',
    'Tablets',
    'Phone Accessories',
    'Audio',
    'Video',
    'Cameras',
    'Photography',
    'Wearables',
    'Gaming',
    'Gaming Accessories',
    'Smart Home',
    'Security',
    'Printers',
    'Printer Supplies',
    'Batteries',
    'Cables',
    'Chargers',
    'Storage Devices',
    'Peripherals',
    'Monitors',
    'POS Equipment',
    'Books',
    'Magazines',
    'Printed Media',
    'Digital Goods',
    'Digital Services',
    'Digital Products',
    'Digital Downloads',
    'Media',
    'Music',
    'Movies',
    'Entertainment',
    'Streaming',
    'Apps',
    'SaaS',
    'Cloud Services',
    'Hosting',
    'Domain Services',
    'Licenses',
    'Add-ons',
    'Extensions',
    'Support Plans',
    'Maintenance Plans',
    'Professional Services',
    'Consulting',
    'Technical Services',
    'Installation',
    'Repair',
    'Maintenance',
    'Cleaning Services',
    'Health Services',
    'Wellness Services',
    'Beauty Services',
    'Automotive Services',
    'Education',
    'Training',
    'Events',
    'Event Access',
    'Admissions',
    'Registrations',
    'Passes',
    'Reservations',
    'Bookings',
    'Experiences',
    'Memberships',
    'Plans',
    'Insurance',
    'Protection Plans',
    'Warranties',
    'Travel Services',
    'Flights',
    'Hotels',
    'Accommodation',
    'Transportation',
    'Transfers',
    'Car Rental',
    'Rail',
    'Bus Travel',
    'Cruises',
    'Tours',
    'Attractions',
    'Luggage',
    'Travel Accessories',
    'Baggage',
    'Parking',
    'Fuel',
    'Automotive',
    'Auto Parts',
    'Car Care',
    'Motorcycle',
    'Sports',
    'Fitness',
    'Outdoor Recreation',
    'Camping',
    'Cycling',
    'Fishing',
    'Team Sports',
    'Water Sports',
    'Winter Sports',
    'Toys',
    'Games',
    'Hobbies',
    'Crafts',
    'Art Supplies',
    'Collectibles',
    'Baby',
    'Kids',
    'Children',
    'Maternity',
    'Pet',
    'Pet Supplies',
    'Pet Care',
    'Health',
    'Personal Care',
    'Beauty',
    'Cosmetics',
    'Skincare',
    'Hair Care',
    'Fragrance',
    'Pharmacy',
    'Medical Supplies',
    'Nutrition',
    'Supplements',
    'Gifts',
    'Gift Cards',
    'Gift Wrap',
    'Seasonal',
    'Holiday',
    'Party Supplies',
    'Floral',
    'Flowers',
    'Gourmet',
    'Snacks',
    'Beverages',
    'Coffee',
    'Tea',
    'Bakery',
    'Fresh Food',
    'Frozen Food',
    'Pantry',
    'Produce',
    'Dairy',
    'Meat',
    'Seafood',
    'Meal Kits',
    'Prepared Food',
    'Restaurant',
    'Cafe',
    'Fast Food',
    'Alcohol',
    'Housewares',
    'Daily Essentials',
    'Essentials',
    'General Merchandise',
    'Retail',
    'Wholesale',
    'Commercial Supplies',
    'Industrial',
    'Industrial Supplies',
    'Janitorial',
    'Safety Equipment',
    'Packaging',
    'Shipping Supplies',
    'Mailing',
    'Fulfillment',
    'Delivery',
    'Courier',
    'Freight',
    'Warehouse',
    'Inventory',
    'Supply Chain',
    'Procurement',
    'Business Supplies',
    'Merchant Supplies',
    'Checkout Supplies',
    'Restaurant Supplies',
    'Hospitality',
    'Facility Supplies',
    'Utilities',
    'Energy',
    'Water',
    'Telecom',
    'Internet Services',
    'Communication Services',
    'Financial Services',
    'Banking',
    'Payments',
    'Billing',
    'Tax',
    'Fees',
    'Surcharges',
    'Discounts',
    'Promotions',
    'Bundles',
    'Kits',
    'Starter Kits',
    'Care Packages',
    'Value Packs',
    'Refills',
    'Replacements',
    'Accessories',
    'Parts',
    'Components',
    'Supplies',
    'Consumables',
    'Rental',
    'Leasing',
    'Deposits',
    'Custom Orders',
    'Made to Order',
    'Special Order',
    'Miscellaneous',
    'Other',
  ],
}
