export default {
  personNameFormats: [
    '{first} {last}',
    '{first} {middle}. {last}',
  ],
  companyNameFormats: [
    '{prefix} {root} {suffix}',
    '{prefix} {root}',
    '{family} {root}',
    '{family} {root} {suffix}',
    '{prefix} {family} {root}',
    '{prefix} {root} & Co',
    '{family} and {family2} {root}',
    '{prefix} {root} Global',
    '{prefix} {root} Direct',
    '{family} {prefix} {root}',
  ],
  logisticsCompanyFormats: [
    '{prefix} {root} {suffix}',
    '{prefix} {root}',
    '{prefix} {root} Express',
    '{prefix} {root} Network',
    '{prefix} {root} Global',
  ],
  orderNumberFormats: [
    'AA-####-####',
    'WEB-########',
    'SO-######',
    'ORD########',
    'PO-######-AA',
    'INV-########',
    'RCP-######',
    'TXN-##########',
    'AA####AA####',
  ],
  trackingNumberFormats: [
    'TRK-####-####-####',
    'SHIP##########',
    '1Z****************',
    'PKG-AAA-########',
    'AWB###########',
    'XP-####-####-####-##',
  ],
  customerIdFormats: [
    'CUST-######',
    'BUYER#####',
    'MEM-########',
    'ACC-####-####',
    'CLI-######AA',
    'USR########',
  ],
  skuFormats: [
    'AAA-####',
    'AA-AA-####',
    '########',
    'AAA-##-##',
    'SKU-######',
    'PRD-AAA-###',
    'CAT-####-AA',
  ],
  registerNumberFormats: [
    '#',
    '##',
    '###',
    'POS-#',
    'POS-##',
    'REG-##',
    'REG-###',
    'LANE-#',
  ],
  promoCodeFormats: [
    '{prefix}{percent}',
    '{prefix}-{percent}',
    '{prefix}_{percent}',
    '{prefix}{theme}{percent}',
    '{prefix}-{theme}-{percent}',
    '{theme}{percent}{year2}',
    '{prefix}{theme}{year2}',
    '{theme}-{prefix}-{percent}',
    '{prefix}{percent}OFF',
    '{theme}{percent}X',
  ],
  emailLocalFormats: [
    '{first}.{last}',
    '{merchant}',
    '{merchant}{nn}',
    '{first}{nn}',
    'orders',
    'billing',
    'support',
    '{first}.{last}{nn}',
    '{merchant}.store',
    '{merchant}.team',
  ],
  websiteHostFormats: [
    '{merchant}',
    'shop.{merchant}',
    'orders.{merchant}',
    '{merchant}-store',
    '{merchant}-online',
    'checkout.{merchant}',
    'billing.{merchant}',
    '{merchant}-direct',
  ],
  blueprintCatalogs: {
    'retail-receipt': ['electronics', 'home', 'grocery', 'food', 'apparel'],
    'online-confirmation': ['electronics', 'home', 'apparel', 'bundles', 'subscriptions'],
    'shipping-notice': ['electronics', 'home', 'bundles', 'travel'],
    'service-confirmation': ['services', 'subscriptions', 'travel', 'events'],
  },
}
