export default {
  acceptedOffer: [
    'accepted offer',
    'accepted offers',
    'offer',
    'offers',
    'order items',
    'ordered items',
    'items ordered',
    'items purchased',
    'purchased items',
    'products ordered',
    'services ordered',
    'line items',
    'basket items',
    'cart items',
    'order summary',
    'purchase summary',
  ],

  billingAddress: [
    'billing address',
    'bill to',
    'billed to',
    'bill-to',
    'invoice address',
    'billing details',
    'billing information',
    'customer billing address',
    'billing contact address',
    'billing destination',
  ],

  broker: [
    'broker',
    'agent',
    'booking agent',
    'intermediary',
    'facilitator',
    'facilitated by',
    'arranged by',
    'brokered by',
    'sales agent',
    'account broker',
  ],

  confirmationNumber: [
    'confirmation number',
    'confirmation no',
    'confirmation #',
    'conf no',
    'conf #',
    'confirmation code',
    'confirmation id',
    'booking confirmation',
    'payment confirmation number',
    'receipt confirmation',
  ],

  customer: [
    'customer',
    'customer name',
    'buyer',
    'buyer name',
    'purchaser',
    'purchased by',
    'client',
    'client name',
    'account name',
    'sold to',
    'bill to',
    'billed to',
    'recipient',
    'ordered by',
  ],

  discount: [
    'discount',
    'discount amount',
    'discounts',
    'less discount',
    'promo discount',
    'promotion discount',
    'coupon discount',
    'voucher discount',
    'rebate',
    'markdown',
    'savings',
    'you saved',
    'total savings',
  ],

  discountCode: [
    'discount code',
    'promo code',
    'promotion code',
    'coupon code',
    'voucher code',
    'redeem code',
    'offer code',
    'promotion id',
    'coupon id',
  ],

  discountCurrency: [
    'discount currency',
    'discount curr',
    'discount curr.',
    'savings currency',
    'currency of discount',
    'rebate currency',
  ],

  isGift: [
    'gift',
    'gift order',
    'gift purchase',
    'marked as gift',
    'gift option',
    'gift flag',
    'is gift',
    'this is a gift',
    'gift item',
    'gift receipt',
  ],

  orderDate: [
    'order date',
    'date ordered',
    'ordered on',
    'purchase date',
    'transaction date',
    'sale date',
    'date of order',
    'created at',
    'created on',
    'order created',
    'placed on',
    'date',
    'invoice date',
  ],

  orderDelivery: [
    'order delivery',
    'delivery',
    'delivery details',
    'delivery information',
    'shipping',
    'shipping details',
    'shipment',
    'shipment details',
    'shipping information',
    'fulfillment',
    'dispatch',
    'parcel delivery',
  ],

  orderNumber: [
    'order number',
    'order no',
    'order no.',
    'order #',
    'order id',
    'sales order',
    'sales order no',
    'sales order #',
    'purchase id',
    'transaction id',
    'reference number',
    'ref no',
    'document no',
    'doc no',
  ],

  orderStatus: [
    'order status',
    'status',
    'current status',
    'purchase status',
    'transaction status',
    'fulfillment status',
    'processing status',
    'delivery status',
    'shipment status',
    'state',
  ],

  orderedItem: [
    'ordered item',
    'ordered items',
    'item',
    'items',
    'item ordered',
    'purchase item',
    'purchased item',
    'product',
    'products',
    'service',
    'services',
    'description',
    'item description',
    'line item',
    'line items',
  ],

  partOfInvoice: [
    'part of invoice',
    'invoice',
    'invoice reference',
    'invoice ref',
    'invoice no',
    'invoice #',
    'billed under',
    'invoiced under',
    'included in invoice',
    'invoice linkage',
  ],

  paymentDueDate: [
    'payment due date',
    'due date',
    'payment due',
    'due on',
    'amount due by',
    'pay by',
    'pay before',
    'payable by',
    'due by',
    'date due',
    'payment deadline',
  ],

  paymentMethod: [
    'payment method',
    'method of payment',
    'payment type',
    'payment mode',
    'paid by',
    'paid via',
    'tender type',
    'tender',
    'payment',
    'settlement method',
    'mode of payment',
  ],

  paymentMethodId: [
    'payment method id',
    'payment id',
    'payment reference',
    'payment ref',
    'transaction reference',
    'transaction ref',
    'card ending',
    'card ending in',
    'last 4 digits',
    'account ending',
    'token',
    'auth id',
    'authorization id',
  ],

  paymentUrl: [
    'payment url',
    'payment link',
    'pay now',
    'pay online',
    'pay here',
    'complete payment',
    'payment page',
    'checkout link',
    'payment portal',
    'settlement link',
  ],

  seller: [
    'seller',
    'sold by',
    'merchant',
    'vendor',
    'supplier',
    'retailer',
    'store',
    'shop',
    'business',
    'merchant name',
    'seller name',
    'vendor name',
  ],

  additionalType: [
    'additional type',
    'type',
    'subtype',
    'category',
    'classification',
    'document type',
    'order type',
    'record type',
    'item type',
    'service type',
  ],

  alternateName: [
    'alternate name',
    'alternative name',
    'alt name',
    'alias',
    'also known as',
    'aka',
    'display name',
    'short name',
    'other name',
  ],

  description: [
    'description',
    'details',
    'item description',
    'product description',
    'service description',
    'summary',
    'remarks',
    'memo',
    'note',
    'notes',
    'particulars',
  ],

  disambiguatingDescription: [
    'disambiguating description',
    'distinguishing description',
    'qualifier',
    'subtitle',
    'clarification',
    'clarifying description',
    'short description',
    'descriptor',
    'distinguishing note',
  ],

  identifier: [
    'identifier',
    'id',
    'reference',
    'reference id',
    'record id',
    'unique id',
    'external id',
    'internal id',
    'ref no',
    'ref #',
    'code',
  ],

  image: [
    'image',
    'photo',
    'picture',
    'product image',
    'item image',
    'thumbnail',
    'logo',
    'visual',
    'product photo',
  ],

  mainEntityOfPage: [
    'main entity of page',
    'source page',
    'page',
    'page url',
    'source url',
    'canonical page',
    'listing page',
    'product page',
    'service page',
    'reference page',
  ],

  name: [
    'name',
    'title',
    'label',
    'display name',
    'item name',
    'product name',
    'service name',
    'merchant name',
    'customer name',
    'designation',
  ],

  owner: [
    'owner',
    'owned by',
    'account owner',
    'record owner',
    'store owner',
    'merchant owner',
    'property owner',
  ],

  potentialAction: [
    'potential action',
    'action',
    'next action',
    'next step',
    'available action',
    'available actions',
    'follow-up action',
    'what you can do',
    'available options',
  ],

  sameAs: [
    'same as',
    'official page',
    'official url',
    'equivalent url',
    'reference url',
    'matching page',
    'external reference',
    'same entity',
    'see also',
  ],

  subjectOf: [
    'subject of',
    'subject',
    'about',
    'related document',
    'related page',
    'covered by',
    'referenced in',
    'document subject',
    'topic',
  ],

  url: [
    'url',
    'link',
    'website',
    'webpage',
    'page url',
    'source link',
    'web link',
    'page link',
    'site',
  ],

  // Invoice / offer / delivery / item / address / party / product / service carry-over

  accountId: [
    'account id',
    'account',
    'account no',
    'account no.',
    'account number',
    'acct no',
    'acct no.',
    'acct #',
    'account #',
    'customer account',
    'customer account no',
    'customer account number',
    'member account',
    'billing account',
    'account reference',
    'account ref',
    'account code',
    'client account',
    'payer account',
  ],

  billingPeriod: [
    'billing period',
    'bill period',
    'billing cycle',
    'billing range',
    'service period',
    'period covered',
    'period',
    'statement period',
    'invoice period',
    'coverage period',
    'for period',
    'period from',
    'period to',
    'billing from',
    'billing to',
    'service from',
    'service to',
    'cycle period',
  ],

  minimumPaymentDue: [
    'minimum payment due',
    'minimum payment',
    'minimum due',
    'min payment due',
    'min payment',
    'min due',
    'minimum amount due',
    'minimum payable',
    'minimum amount payable',
    'least amount due',
    'amount due minimum',
    'minimum balance due',
    'min. payment due',
    'min. due',
  ],

  paymentStatus: [
    'payment status',
    'status',
    'payment state',
    'settlement status',
    'settlement state',
    'paid status',
    'transaction status',
    'invoice status',
    'balance status',
    'payment result',
    'payment complete',
    'paid',
    'unpaid',
    'payment pending',
    'payment received',
    'settled',
    'not paid',
  ],

  provider: [
    'provider',
    'service provider',
    'provided by',
    'supplied by',
    'fulfilled by',
    'vendor',
    'supplier',
    'seller',
    'merchant',
    'issuer',
    'carrier',
    'operator',
    'performer',
    'service company',
    'company',
    'organization',
  ],

  referencesOrder: [
    'references order',
    'reference order',
    'referenced order',
    'related order',
    'linked order',
    'order reference',
    'order ref',
    'ref order',
    'source order',
    'original order',
    'parent order',
    'sales order ref',
    'customer order ref',
    'associated order',
    'connected order',
  ],

  scheduledPaymentDate: [
    'scheduled payment date',
    'scheduled payment',
    'scheduled pay date',
    'scheduled pay on',
    'autopay date',
    'auto pay date',
    'auto-payment date',
    'payment scheduled for',
    'scheduled settlement date',
    'next payment date',
    'next due date',
    'planned payment date',
    'debit date',
  ],

  totalPaymentDue: [
    'total payment due',
    'total due',
    'amount due',
    'total amount due',
    'total payable',
    'amount payable',
    'balance due',
    'grand total',
    'final total',
    'invoice total',
    'total payment',
    'payment due',
    'net payable',
    'total outstanding',
    'amount owing',
    'total bill',
    'bill total',
  ],

  orderItemNumber: [
    'order item number',
    'order item no',
    'item number',
    'item no',
    'item #',
    'line item no',
    'line number',
    'line no',
    'row number',
    'sequence',
    'sequence no',
    'product line',
    'entry no',
    'detail no',
    'position no',
  ],

  orderItemStatus: [
    'order item status',
    'item status',
    'line item status',
    'line status',
    'product status',
    'fulfillment status',
    'shipment status',
    'delivery status',
    'state',
    'item state',
    'current status',
    'status',
    'line state',
    'availability status',
  ],

  orderQuantity: [
    'order quantity',
    'ordered quantity',
    'quantity ordered',
    'quantity',
    'qty',
    'qty ordered',
    'order qty',
    'units',
    'unit qty',
    'item qty',
    'items',
    'count',
    'ordered units',
    'purchase quantity',
    'requested quantity',
  ],

  acceptedPaymentMethod: [
    'accepted payment method',
    'accepted payment methods',
    'payment methods accepted',
    'we accept',
    'accepted tender',
    'accepted tenders',
    'payment types accepted',
    'mode of payment accepted',
    'accepted cards',
    'accepted payments',
    'payment options',
    'ways to pay',
    'pay with',
    'supported payment methods',
  ],

  addOn: [
    'add-on',
    'add on',
    'addon',
    'extra',
    'extras',
    'additional item',
    'additional items',
    'optional add-on',
    'upgrade',
    'upsell',
    'supplement',
    'attachment',
    'bundle add-on',
    'extra option',
    'option',
  ],

  additionalProperty: [
    'additional property',
    'additional properties',
    'additional info',
    'additional information',
    'extra info',
    'extra information',
    'details',
    'other details',
    'more details',
    'metadata',
    'attributes',
    'characteristics',
    'specifications',
    'notes',
    'remarks',
    'misc',
    'other information',
  ],

  availability: [
    'availability',
    'stock status',
    'in stock',
    'stock',
    'availability status',
    'item availability',
    'current availability',
    'status',
    'inventory status',
    'ready to ship',
    'available',
    'sold out',
    'backorder',
    'backordered',
    'out of stock',
    'ships in',
  ],

  businessFunction: [
    'business function',
    'function',
    'transaction type',
    'service type',
    'sale type',
    'business type',
    'purpose',
    'commercial function',
    'operation',
    'order type',
    'activity',
    'engagement type',
  ],

  itemCondition: [
    'item condition',
    'condition',
    'product condition',
    'goods condition',
    'state',
    'quality',
    'item state',
    'condition status',
    'new/used',
    'condition grade',
    'physical condition',
  ],

  itemOffered: [
    'item offered',
    'items offered',
    'offered item',
    'offered items',
    'product offered',
    'service offered',
    'item',
    'items',
    'product',
    'products',
    'service',
    'services',
    'description',
    'item description',
    'goods',
    'merchandise',
    'article',
  ],

  price: [
    'price',
    'unit price',
    'amount',
    'cost',
    'charge',
    'value',
    'rate',
    'price each',
    'selling price',
    'sale price',
    'retail price',
    'item price',
    'unit cost',
    'amount due',
    'amount',
    'total price',
  ],

  priceCurrency: [
    'price currency',
    'currency',
    'curr',
    'curr.',
    'currency code',
    'payment currency',
    'billing currency',
    'settlement currency',
    'price curr',
    'price curr.',
    'amount currency',
    'transaction currency',
  ],

  priceSpecification: [
    'price specification',
    'pricing',
    'pricing details',
    'price details',
    'rate details',
    'unit pricing',
    'price breakdown',
    'cost breakdown',
    'pricing structure',
    'price info',
    'price information',
    'specification',
    'pricing spec',
  ],

  priceValidUntil: [
    'price valid until',
    'valid until',
    'offer valid until',
    'price expires',
    'valid thru',
    'valid through',
    'expires on',
    'expiry date',
    'expiration date',
    'offer expiry',
    'promo valid until',
    'good until',
    'price effective until',
  ],

  sku: [
    'sku',
    'sku no',
    'sku no.',
    'sku #',
    'stock keeping unit',
    'stock code',
    'item code',
    'product code',
    'inventory code',
    'catalog code',
    'catalog no',
    'part code',
    'article number',
    'article no',
    'item id',
  ],

  serialNumber: [
    'serial number',
    'serial no',
    'serial no.',
    'serial #',
    's/n',
    'sn',
    'device serial',
    'unit serial',
    'machine serial',
    'product serial',
    'asset serial',
    'equipment serial',
    'serial id',
  ],

  deliveryAddress: [
    'delivery address',
    'ship to',
    'ship-to',
    'shipping address',
    'deliver to',
    'delivery details',
    'delivery destination',
    'shipping destination',
    'consignee address',
    'drop-off address',
    'recipient address',
    'send to',
  ],

  deliveryStatus: [
    'delivery status',
    'shipment status',
    'shipping status',
    'fulfillment status',
    'dispatch status',
    'carrier status',
    'parcel status',
    'delivery state',
    'shipment state',
    'current delivery status',
    'tracking status',
    'status',
  ],

  expectedArrivalFrom: [
    'expected arrival from',
    'expected from',
    'arrival window starts',
    'delivery starts',
    'estimated arrival from',
    'estimated from',
    'arrives from',
    'from date',
    'window opens',
    'delivery window from',
  ],

  expectedArrivalUntil: [
    'expected arrival until',
    'expected until',
    'arrival window ends',
    'delivery until',
    'estimated arrival until',
    'estimated until',
    'arrives by',
    'to date',
    'window closes',
    'delivery window to',
    'latest arrival',
  ],

  hasDeliveryMethod: [
    'delivery method',
    'shipping method',
    'ship via',
    'delivery via',
    'method',
    'fulfillment method',
    'dispatch method',
    'carrier method',
    'service level',
    'shipping service',
    'delivery option',
    'shipping option',
  ],

  itemShipped: [
    'item shipped',
    'items shipped',
    'shipped item',
    'shipped items',
    'goods shipped',
    'products shipped',
    'shipment contents',
    'contents',
    'parcel contents',
    'delivered item',
    'dispatched item',
    'goods in shipment',
  ],

  originAddress: [
    'origin address',
    'ship from',
    'ship-from',
    'shipping origin',
    'sender address',
    'dispatch address',
    'from address',
    'warehouse address',
    'origin',
    'source address',
    'fulfillment center',
    'return address',
  ],

  partOfOrder: [
    'part of order',
    'belongs to order',
    'included in order',
    'order reference',
    'related order',
    'parent order',
    'source order',
    'main order',
    'master order',
    'order link',
    'part of sales order',
  ],

  trackingNumber: [
    'tracking number',
    'tracking no',
    'tracking no.',
    'tracking #',
    'shipment tracking',
    'tracking id',
    'parcel tracking',
    'awb',
    'air waybill',
    'consignment no',
    'consignment number',
    'waybill number',
    'shipment no',
  ],

  trackingUrl: [
    'tracking url',
    'tracking link',
    'track shipment',
    'track package',
    'track order',
    'parcel tracking url',
    'shipment tracking url',
    'tracking page',
    'track here',
    'tracking website',
    'tracking portal',
  ],

  addressCountry: [
    'country',
    'address country',
    'country/region',
    'nation',
    'country name',
    'destination country',
    'billing country',
    'shipping country',
    'country code',
  ],

  addressLocality: [
    'city',
    'town',
    'locality',
    'address locality',
    'municipality',
    'suburb',
    'district',
    'city/town',
    'billing city',
    'shipping city',
    'local area',
  ],

  addressRegion: [
    'state',
    'province',
    'region',
    'address region',
    'county',
    'territory',
    'area',
    'state/province',
    'district',
    'prefecture',
    'billing region',
    'shipping region',
  ],

  extendedAddress: [
    'address 2',
    'address line 2',
    'address line 3',
    'extended address',
    'apt',
    'apartment',
    'suite',
    'unit',
    'floor',
    'building',
    'block',
    'room',
    'department',
    'care of',
    'c/o',
  ],

  postOfficeBoxNumber: [
    'po box',
    'p.o. box',
    'post office box',
    'box number',
    'po box number',
    'pobox',
    'postal box',
    'mailbox',
  ],

  postalCode: [
    'postal code',
    'postcode',
    'post code',
    'zip',
    'zip code',
    'pin',
    'pin code',
    'area code',
    'routing code',
    'postal / zip code',
    'code postal',
  ],

  streetAddress: [
    'street address',
    'street',
    'address line 1',
    'address 1',
    'street line',
    'road',
    'house address',
    'billing street',
    'shipping street',
    'delivery street',
    'location address',
  ],

  address: [
    'address',
    'full address',
    'mailing address',
    'postal address',
    'contact address',
    'registered address',
    'billing address',
    'shipping address',
    'location',
    'premises',
    'place',
  ],

  email: [
    'email',
    'e-mail',
    'email address',
    'e-mail address',
    'contact email',
    'mail',
    'mail address',
    'electronic mail',
    'customer email',
    'merchant email',
    'support email',
  ],

  legalName: [
    'legal name',
    'registered name',
    'company legal name',
    'entity name',
    'registered business name',
    'corporate name',
    'official name',
    'legal entity',
    'legal entity name',
    'trading as',
    'business legal name',
  ],

  taxID: [
    'tax id',
    'tax id no',
    'tax id number',
    'tax no',
    'tax no.',
    'tax number',
    'taxpayer id',
    'tin',
    'vat id',
    'vat number',
    'gst id',
    'gst number',
    'registration tax no',
    'fiscal id',
    'fiscal number',
  ],

  telephone: [
    'telephone',
    'tel',
    'tel.',
    'phone',
    'phone no',
    'phone number',
    'contact no',
    'contact number',
    'mobile',
    'mobile no',
    'call us',
    'landline',
    'contact phone',
  ],

  familyName: [
    'family name',
    'last name',
    'surname',
    'lname',
    'family/surname',
    'customer surname',
    'recipient surname',
    'buyer surname',
  ],

  givenName: [
    'given name',
    'first name',
    'forename',
    'fname',
    'customer first name',
    'recipient first name',
    'buyer first name',
    'personal name',
  ],

  brand: [
    'brand',
    'brand name',
    'maker',
    'manufacturer brand',
    'label',
    'product brand',
    'brand / make',
    'make',
    'house brand',
    'brand line',
  ],

  category: [
    'category',
    'product category',
    'item category',
    'service category',
    'type',
    'classification',
    'class',
    'department',
    'section',
    'group',
    'segment',
    'product type',
    'category name',
  ],

  gtin: [
    'gtin',
    'gtin-8',
    'gtin-12',
    'gtin-13',
    'gtin-14',
    'ean',
    'ean code',
    'upc',
    'upc code',
    'barcode',
    'barcode no',
    'barcode number',
    'global trade item number',
  ],

  model: [
    'model',
    'model no',
    'model no.',
    'model #',
    'product model',
    'model number',
    'series',
    'variant',
    'style',
    'design',
    'type',
    'model name',
  ],

  mpn: [
    'mpn',
    'mfr part no',
    'manufacturer part no',
    'manufacturer part number',
    'part no',
    'part no.',
    'part #',
    'part number',
    'mfg code',
    'manufacturer code',
    'product code',
  ],

  offers: [
    'offers',
    'available offers',
    'promotions',
    'deals',
    'special offers',
    'promotional offers',
    'related offers',
    'current offers',
    'available deals',
    'bundle offers',
    'pricing offers',
    'discount offers',
  ],

  areaServed: [
    'area served',
    'service area',
    'coverage area',
    'delivery area',
    'region served',
    'areas covered',
    'service region',
    'coverage region',
    'territory served',
    'available in',
    'serving area',
  ],

  availableChannel: [
    'available channel',
    'service channel',
    'sales channel',
    'support channel',
    'available via',
    'channel',
    'contact channel',
    'delivery channel',
    'purchase channel',
    'access channel',
    'order channel',
  ],

  hoursAvailable: [
    'hours available',
    'opening hours',
    'business hours',
    'store hours',
    'operating hours',
    'available hours',
    'service hours',
    'office hours',
    'working hours',
    'open',
    'available from',
    'available to',
  ],

  serviceOutput: [
    'service output',
    'output',
    'deliverable',
    'result',
    'service result',
    'work product',
    'generated item',
    'delivered result',
    'outcome',
    'service deliverable',
  ],

  serviceType: [
    'service type',
    'service',
    'type of service',
    'service category',
    'service class',
    'work type',
    'job type',
    'support type',
    'delivery type',
    'appointment type',
    'task type',
  ],

  termsOfService: [
    'terms of service',
    'terms',
    'terms & conditions',
    'terms and conditions',
    'conditions',
    'service terms',
    'purchase terms',
    'sale terms',
    'agreement',
    'customer terms',
    'merchant terms',
    'tos',
    'policies',
    'conditions of sale',
  ],

  // Document identity / numbering variants

  invoiceNumber: [
    'invoice number',
    'invoice no',
    'invoice no.',
    'invoice #',
    'invoice id',
    'invoice reference',
    'invoice ref',
    'invoice ref.',
    'tax invoice number',
    'tax invoice no',
    'tax invoice #',
    'sales invoice number',
    'sales invoice no',
    'inv number',
    'inv num',
    'inv #',
    'invoice code',
    'invoice identifier',
    'invoice record',
    'invoice serial',
  ],

  receiptNumber: [
    'receipt number',
    'receipt no',
    'receipt no.',
    'receipt #',
    'receipt id',
    'receipt reference',
    'receipt ref',
    'sales receipt number',
    'payment receipt number',
    'official receipt number',
    'receipt code',
    'receipt identifier',
    'receipt serial',
    'receipt document number',
    'rec number',
    'rec no',
    'rec #',
  ],

  billNumber: [
    'bill number',
    'bill no',
    'bill no.',
    'bill #',
    'bill id',
    'bill reference',
    'bill ref',
    'bill code',
    'billing number',
    'billing no',
    'statement number',
    'statement no',
    'statement #',
    'customer bill number',
    'restaurant bill number',
  ],

  cashDocNumber: [
    'cash doc number',
    'cash doc no',
    'cash doc no.',
    'cash document number',
    'cash document no',
    'cash document #',
    'cash doc #',
    'cash transaction number',
    'cash transaction no',
    'cash voucher number',
    'cash voucher no',
    'cash note number',
    'cash memo number',
    'cash memo no',
    'cash receipt doc number',
  ],

  cashSaleNumber: [
    'cash sale number',
    'cash sale no',
    'cash sale no.',
    'cash sale #',
    'cash sales number',
    'cash sales no',
    'cash sales #',
    'cash invoice number',
    'cash invoice no',
    'cash transaction no',
    'point of sale number',
    'pos sale number',
    'sale number',
    'sale no',
    'sale #',
  ],

  cashReceiptNumber: [
    'cash receipt number',
    'cash receipt no',
    'cash receipt no.',
    'cash receipt #',
    'cash rec no',
    'cash rec #',
    'cash payment receipt number',
    'cash collection receipt no',
    'cash received receipt no',
    'official receipt no',
    'or number',
    'or no',
    'or #',
    'receipt cash no',
  ],

  checkNumber: [
    'check number',
    'check no',
    'check no.',
    'check #',
    'cheque number',
    'cheque no',
    'cheque #',
    'guest check number',
    'check id',
    'restaurant check number',
    'table check number',
    'bill check number',
    'chk no',
    'chk #',
    'guest check #',
  ],

  ticketNumber: [
    'ticket number',
    'ticket no',
    'ticket no.',
    'ticket #',
    'ticket id',
    'order ticket number',
    'service ticket number',
    'support ticket number',
    'job ticket number',
    'kitchen ticket number',
    'queue ticket number',
    'stub number',
    'ticket ref',
    'ticket code',
    'ticket identifier',
  ],

  documentNumber: [
    'document number',
    'document no',
    'document no.',
    'document #',
    'doc number',
    'doc #',
    'document id',
    'document reference',
    'document ref',
    'record number',
    'record no',
    'record id',
    'form number',
    'form no',
    'form #',
  ],

  docNo: [
    'doc no',
    'doc no.',
    'doc #',
    'document no',
    'document no.',
    'document #',
    'doc number',
    'document number',
    'doc ref',
    'doc code',
    'record no',
    'record #',
    'ref doc no',
  ],

  billNo: [
    'bill no',
    'bill no.',
    'bill #',
    'bill number',
    'billing no',
    'billing no.',
    'billing #',
    'customer bill no',
    'restaurant bill no',
    'table bill no',
    'guest bill no',
    'statement no',
    'statement #',
  ],

  invNo: [
    'inv no',
    'inv no.',
    'inv #',
    'invoice no',
    'invoice no.',
    'invoice #',
    'invoice number',
    'inv number',
    'tax inv no',
    'tax inv #',
    'sales inv no',
    'sales inv #',
    'invoice ref no',
  ],

  receiptNo: [
    'receipt no',
    'receipt no.',
    'receipt #',
    'receipt number',
    'receipt ref no',
    'sales receipt no',
    'payment receipt no',
    'official receipt no',
    'official receipt #',
    'rec no',
    'rec no.',
    'rec #',
    'cash receipt no',
  ],

  invoiceNo: [
    'invoice no',
    'invoice no.',
    'invoice #',
    'invoice number',
    'invoice ref no',
    'tax invoice no',
    'tax invoice no.',
    'tax invoice #',
    'sales invoice no',
    'sales invoice #',
    'inv no',
    'inv no.',
    'inv #',
  ],

  transactionNumber: [
    'transaction number',
    'transaction no',
    'transaction no.',
    'transaction #',
    'txn number',
    'txn no',
    'txn #',
    'payment transaction number',
    'pos transaction number',
    'sale transaction number',
    'transaction ref no',
    'transaction identifier',
    'transaction serial',
    'trans number',
    'trans no',
  ],

  transactionId: [
    'transaction id',
    'txn id',
    'trans id',
    'transaction identifier',
    'payment id',
    'payment transaction id',
    'transaction token',
    'gateway transaction id',
    'processor transaction id',
    'sale id',
    'purchase id',
    'order transaction id',
    'transaction uid',
  ],

  transactionCode: [
    'transaction code',
    'txn code',
    'trans code',
    'payment code',
    'reference code',
    'sale code',
    'transaction type code',
    'transaction auth code',
    'processor code',
    'approval code',
    'authorization code',
    'transaction token',
    'event code',
  ],

  transactionReference: [
    'transaction reference',
    'transaction ref',
    'transaction ref.',
    'txn reference',
    'txn ref',
    'trans reference',
    'trans ref',
    'reference transaction',
    'payment reference',
    'payment ref',
    'gateway reference',
    'processor reference',
    'merchant reference',
    'customer reference',
    'reference no',
  ],

  paymentReference: [
    'payment reference',
    'payment ref',
    'payment ref.',
    'payment reference number',
    'payment reference no',
    'payment reference #',
    'pay ref',
    'settlement reference',
    'settlement ref',
    'remittance reference',
    'remittance ref',
    'receipt reference',
    'bank reference',
    'transfer reference',
    'reference for payment',
  ],

  referenceNumber: [
    'reference number',
    'reference no',
    'reference no.',
    'reference #',
    'ref number',
    'ref no',
    'ref no.',
    'ref #',
    'customer reference number',
    'merchant reference number',
    'document reference number',
    'external reference number',
    'internal reference number',
    'control number',
    'tracking reference number',
  ],

  referenceCode: [
    'reference code',
    'ref code',
    'ref. code',
    'customer code',
    'merchant code',
    'document code',
    'control code',
    'record code',
    'payment code',
    'lookup code',
    'verification code',
    'external code',
    'internal code',
  ],

  approvalNumber: [
    'approval number',
    'approval no',
    'approval no.',
    'approval #',
    'approval id',
    'approved no',
    'approved #',
    'bank approval number',
    'card approval number',
    'payment approval number',
    'auth approval number',
    'authorization number',
    'approval code',
    'processor approval no',
  ],

  authorizationCode: [
    'authorization code',
    'authorisation code',
    'authorization no',
    'authorization #',
    'auth code',
    'auth no',
    'auth #',
    'approval code',
    'card auth code',
    'bank auth code',
    'payment auth code',
    'processor auth code',
    'authorization id',
    'authorisation no',
  ],

  authCode: [
    'auth code',
    'auth. code',
    'auth no',
    'auth no.',
    'auth #',
    'authorization code',
    'authorisation code',
    'approval code',
    'card auth',
    'bank auth',
    'payment auth',
    'processor auth',
    'approval ref',
  ],

  serialNo: [
    'serial no',
    'serial no.',
    'serial #',
    'serial number',
    's/n',
    'sn',
    'record serial no',
    'document serial no',
    'invoice serial no',
    'receipt serial no',
    'print serial no',
    'device serial no',
    'terminal serial no',
  ],

  sequenceNumber: [
    'sequence number',
    'sequence no',
    'sequence no.',
    'sequence #',
    'seq number',
    'seq no',
    'seq #',
    'line sequence',
    'print sequence',
    'batch sequence',
    'running number',
    'running no',
    'counter number',
    'entry sequence',
  ],

  version: [
    'version',
    'ver',
    'ver.',
    'version no',
    'version no.',
    'version #',
    'document version',
    'print version',
    'form version',
    'software version',
    'system version',
    'template version',
    'layout version',
  ],

  // Merchant / business / outlet info

  merchantName: [
    'merchant',
    'merchant name',
    'merchant:',
    'merchant name:',
    'merchant details',
    'merchant information',
    'merchant info',
    'merchant account',
    'merchant profile',
    'merchant legal name',
    'merchant trading name',
    'merchant display name',
    'merchant title',
    'merchant store name',
    'merchant business name',
    'from',
    'from:',
    'sold by',
    'sold by:',
    'seller',
    'seller:',
    'store',
    'store:',
    'shop',
    'shop:',
    'retailer',
    'retailer:',
    'business',
    'business:',
    'company',
    'company:',
    'merchant / seller',
    'merchant/seller',
    'seller name',
    'seller name:',
    'vendor',
    'vendor:',
    'vendor name',
    'vendor name:',
    'issued by',
    'issued by:',
    'provided by',
    'provided by:',
  ],

  merchantId: [
    'merchant id',
    'merchant id:',
    'merchant identifier',
    'merchant identifier:',
    'merchant no',
    'merchant no.',
    'merchant no:',
    'merchant #',
    'merchant #:',
    'merchant code',
    'merchant code:',
    'merchant account id',
    'merchant account id:',
    'merchant number',
    'merchant number:',
    'merchant ref',
    'merchant ref:',
    'merchant reference',
    'merchant reference:',
    'seller id',
    'seller id:',
    'store id',
    'store id:',
    'vendor id',
    'vendor id:',
  ],

  sellerName: [
    'seller',
    'seller:',
    'seller name',
    'seller name:',
    'sold by',
    'sold by:',
    'merchant',
    'merchant:',
    'merchant name',
    'merchant name:',
    'vendor',
    'vendor:',
    'vendor name',
    'vendor name:',
    'supplier',
    'supplier:',
    'supplier name',
    'supplier name:',
    'retailer',
    'retailer:',
    'shop',
    'shop:',
    'store',
    'store:',
    'business name',
    'business name:',
    'company name',
    'company name:',
  ],

  sellerId: [
    'seller id',
    'seller id:',
    'seller identifier',
    'seller identifier:',
    'seller no',
    'seller no.',
    'seller no:',
    'seller #',
    'seller #:',
    'seller code',
    'seller code:',
    'merchant id',
    'merchant id:',
    'vendor id',
    'vendor id:',
    'supplier id',
    'supplier id:',
    'store id',
    'store id:',
    'seller ref',
    'seller ref:',
    'seller reference',
    'seller reference:',
  ],

  vendorName: [
    'vendor',
    'vendor:',
    'vendor name',
    'vendor name:',
    'supplier',
    'supplier:',
    'supplier name',
    'supplier name:',
    'merchant',
    'merchant:',
    'seller',
    'seller:',
    'provider',
    'provider:',
    'provider name',
    'provider name:',
    'business name',
    'business name:',
    'company name',
    'company name:',
    'sold by',
    'sold by:',
  ],

  vendorId: [
    'vendor id',
    'vendor id:',
    'vendor identifier',
    'vendor identifier:',
    'vendor no',
    'vendor no.',
    'vendor no:',
    'vendor #',
    'vendor #:',
    'vendor code',
    'vendor code:',
    'supplier id',
    'supplier id:',
    'supplier code',
    'supplier code:',
    'merchant id',
    'merchant id:',
    'seller id',
    'seller id:',
    'provider id',
    'provider id:',
  ],

  businessName: [
    'business name',
    'business name:',
    'business',
    'business:',
    'registered business name',
    'registered business name:',
    'trading name',
    'trading name:',
    'trade name',
    'trade name:',
    'company name',
    'company name:',
    'merchant name',
    'merchant name:',
    'store name',
    'store name:',
    'seller name',
    'seller name:',
    'vendor name',
    'vendor name:',
    'legal business name',
    'legal business name:',
  ],

  companyName: [
    'company name',
    'company name:',
    'company',
    'company:',
    'registered company name',
    'registered company name:',
    'legal company name',
    'legal company name:',
    'corporate name',
    'corporate name:',
    'entity name',
    'entity name:',
    'business name',
    'business name:',
    'merchant company',
    'merchant company:',
    'seller company',
    'seller company:',
    'vendor company',
    'vendor company:',
  ],

  companyRegistrationNumber: [
    'company registration number',
    'company registration number:',
    'company registration no',
    'company registration no.',
    'company registration no:',
    'company reg no',
    'company reg no.',
    'company reg no:',
    'company reg #',
    'company reg #:',
    'company number',
    'company number:',
    'registered company number',
    'registered company number:',
    'registration number',
    'registration number:',
    'registration no',
    'registration no.',
    'registration no:',
    'reg no',
    'reg no.',
    'reg no:',
    'reg #',
    'reg #:',
    'co. reg. no.',
    'co reg no',
    'co reg no:',
    'company id',
    'company id:',
    'business registration no',
    'business registration no:',
    'business registration number',
    'business registration number:',
  ],

  businessRegistrationNumber: [
    'business registration number',
    'business registration number:',
    'business registration no',
    'business registration no.',
    'business registration no:',
    'business reg no',
    'business reg no.',
    'business reg no:',
    'business reg #',
    'business reg #:',
    'business number',
    'business number:',
    'registered business no',
    'registered business no:',
    'registration number',
    'registration number:',
    'registration no',
    'registration no.',
    'registration no:',
    'reg no',
    'reg no.',
    'reg no:',
    'reg #',
    'reg #:',
    'biz reg no',
    'biz reg no:',
    'business id',
    'business id:',
    'company registration number',
    'company registration number:',
  ],

  registrationNumber: [
    'registration number',
    'registration number:',
    'registration no',
    'registration no.',
    'registration no:',
    'registration #',
    'registration #:',
    'reg no',
    'reg no.',
    'reg no:',
    'reg #',
    'reg #:',
    'registered number',
    'registered number:',
    'record number',
    'record number:',
    'business registration number',
    'business registration number:',
    'company registration number',
    'company registration number:',
  ],

  registrationNo: [
    'registration no',
    'registration no.',
    'registration no:',
    'reg no',
    'reg no.',
    'reg no:',
    'reg #',
    'reg #:',
    'registration #',
    'registration #:',
    'registered no',
    'registered no:',
    'company reg no',
    'company reg no:',
    'business reg no',
    'business reg no:',
    'co reg no',
    'co reg no:',
    'co. reg. no.',
    'license no',
    'license no:',
  ],

  gstId: [
    'gst id',
    'gst id:',
    'gst id no',
    'gst id no:',
    'gst identification number',
    'gst identification number:',
    'goods and services tax id',
    'goods and services tax id:',
    'gst registration id',
    'gst registration id:',
    'gst reg id',
    'gst reg id:',
    'gst registered id',
    'gst no',
    'gst no:',
    'gst number',
    'gst number:',
  ],

  gstNumber: [
    'gst number',
    'gst number:',
    'gst no',
    'gst no.',
    'gst no:',
    'gst #',
    'gst #:',
    'gst reg no',
    'gst reg no.',
    'gst reg no:',
    'gst registration number',
    'gst registration number:',
    'goods and services tax number',
    'goods and services tax number:',
    'gst id',
    'gst id:',
    'tax invoice gst no',
    'tax invoice gst no:',
  ],

  gstRegistrationNumber: [
    'gst registration number',
    'gst registration number:',
    'gst registration no',
    'gst registration no.',
    'gst registration no:',
    'gst reg number',
    'gst reg number:',
    'gst reg no',
    'gst reg no.',
    'gst reg no:',
    'gst registered number',
    'gst registered number:',
    'goods and services tax registration number',
    'goods and services tax registration number:',
    'gst number',
    'gst number:',
  ],

  vatId: [
    'vat id',
    'vat id:',
    'vat identification number',
    'vat identification number:',
    'value added tax id',
    'value added tax id:',
    'vat registration id',
    'vat registration id:',
    'vat tax id',
    'vat tax id:',
    'vat no',
    'vat no:',
    'vat number',
    'vat number:',
  ],

  vatNumber: [
    'vat number',
    'vat number:',
    'vat no',
    'vat no.',
    'vat no:',
    'vat #',
    'vat #:',
    'vat registration number',
    'vat registration number:',
    'vat reg no',
    'vat reg no:',
    'value added tax number',
    'value added tax number:',
    'tax number',
    'tax number:',
    'tax id',
    'tax id:',
  ],

  branch: [
    'branch',
    'branch:',
    'branch office',
    'branch office:',
    'branch location',
    'branch location:',
    'outlet',
    'outlet:',
    'store branch',
    'store branch:',
    'branch / outlet',
    'branch/outlet',
    'branch name',
    'branch name:',
    'shop branch',
    'shop branch:',
    'location',
    'location:',
  ],

  branchCode: [
    'branch code',
    'branch code:',
    'branch id',
    'branch id:',
    'branch no',
    'branch no.',
    'branch no:',
    'branch #',
    'branch #:',
    'branch identifier',
    'branch identifier:',
    'outlet code',
    'outlet code:',
    'store code',
    'store code:',
    'location code',
    'location code:',
    'shop code',
    'shop code:',
  ],

  branchName: [
    'branch name',
    'branch name:',
    'branch',
    'branch:',
    'outlet name',
    'outlet name:',
    'store name',
    'store name:',
    'location name',
    'location name:',
    'shop name',
    'shop name:',
    'branch location',
    'branch location:',
    'branch title',
    'branch title:',
  ],

  branchNumber: [
    'branch number',
    'branch number:',
    'branch no',
    'branch no.',
    'branch no:',
    'branch #',
    'branch #:',
    'branch id',
    'branch id:',
    'outlet number',
    'outlet number:',
    'outlet no',
    'outlet no:',
    'store number',
    'store number:',
    'location number',
    'location number:',
  ],

  outletName: [
    'outlet name',
    'outlet name:',
    'outlet',
    'outlet:',
    'branch name',
    'branch name:',
    'store name',
    'store name:',
    'location name',
    'location name:',
    'shop name',
    'shop name:',
    'retail outlet',
    'retail outlet:',
    'sales outlet',
    'sales outlet:',
  ],

  outletCode: [
    'outlet code',
    'outlet code:',
    'outlet id',
    'outlet id:',
    'outlet no',
    'outlet no.',
    'outlet no:',
    'outlet #',
    'outlet #:',
    'branch code',
    'branch code:',
    'store code',
    'store code:',
    'location code',
    'location code:',
    'shop code',
    'shop code:',
  ],

  storeName: [
    'store name',
    'store name:',
    'store',
    'store:',
    'shop name',
    'shop name:',
    'outlet name',
    'outlet name:',
    'branch name',
    'branch name:',
    'retail store',
    'retail store:',
    'store title',
    'store title:',
    'merchant store',
    'merchant store:',
  ],

  storeNumber: [
    'store number',
    'store number:',
    'store no',
    'store no.',
    'store no:',
    'store #',
    'store #:',
    'store id',
    'store id:',
    'branch number',
    'branch number:',
    'outlet number',
    'outlet number:',
    'shop number',
    'shop number:',
    'location number',
    'location number:',
    'site no',
    'site no:',
  ],

  storeCode: [
    'store code',
    'store code:',
    'store id',
    'store id:',
    'store no',
    'store no.',
    'store no:',
    'store #',
    'store #:',
    'shop code',
    'shop code:',
    'branch code',
    'branch code:',
    'outlet code',
    'outlet code:',
    'location code',
    'location code:',
    'site code',
    'site code:',
  ],

  locationName: [
    'location name',
    'location name:',
    'location',
    'location:',
    'store location',
    'store location:',
    'branch location',
    'branch location:',
    'outlet location',
    'outlet location:',
    'site name',
    'site name:',
    'place name',
    'place name:',
    'venue',
    'venue:',
  ],

  locationLabel: [
    'location label',
    'location label:',
    'location',
    'location:',
    'site label',
    'site label:',
    'branch label',
    'branch label:',
    'outlet label',
    'outlet label:',
    'counter label',
    'counter label:',
    'table + counter',
    'store label',
    'store label:',
  ],

  website: [
    'website',
    'website:',
    'web site',
    'web site:',
    'site',
    'site:',
    'url',
    'url:',
    'web',
    'web:',
    'homepage',
    'homepage:',
    'company website',
    'company website:',
    'merchant website',
    'merchant website:',
    'visit us',
    'visit us:',
    'online',
    'online:',
  ],

  faxNumber: [
    'fax number',
    'fax number:',
    'fax no',
    'fax no.',
    'fax no:',
    'fax #',
    'fax #:',
    'fax',
    'fax:',
    'facsimile',
    'facsimile:',
    'fax line',
    'fax line:',
    'company fax',
    'company fax:',
  ],

  contactNumber: [
    'contact number',
    'contact number:',
    'contact no',
    'contact no.',
    'contact no:',
    'contact #',
    'contact #:',
    'contact',
    'contact:',
    'phone',
    'phone:',
    'telephone',
    'telephone:',
    'tel',
    'tel:',
    'mobile',
    'mobile:',
    'hotline',
    'hotline:',
    'customer service no',
    'customer service no:',
  ],

  socialUrl: [
    'social url',
    'social url:',
    'social link',
    'social link:',
    'social media',
    'social media:',
    'facebook',
    'facebook:',
    'instagram',
    'instagram:',
    'twitter',
    'twitter:',
    'follow us',
    'follow us:',
    'find us on',
    'find us on:',
    'social page',
    'social page:',
  ],

  socialHandle: [
    'social handle',
    'social handle:',
    'handle',
    'handle:',
    '@handle',
    'username',
    'username:',
    'social username',
    'social username:',
    'facebook handle',
    'facebook handle:',
    'instagram handle',
    'instagram handle:',
    'twitter handle',
    'twitter handle:',
  ],

  loyaltyProgram: [
    'loyalty program',
    'loyalty program:',
    'loyalty programme',
    'loyalty programme:',
    'rewards program',
    'rewards program:',
    'rewards programme',
    'rewards programme:',
    'membership program',
    'membership program:',
    'member program',
    'member program:',
    'points program',
    'points program:',
    'loyalty scheme',
    'loyalty scheme:',
    'reward scheme',
    'reward scheme:',
  ],

  memberNumber: [
    'member number',
    'member number:',
    'member no',
    'member no.',
    'member no:',
    'member #',
    'member #:',
    'member id',
    'member id:',
    'membership no',
    'membership no:',
    'membership #',
    'membership #:',
    'customer member no',
    'customer member no:',
    'member code',
    'member code:',
  ],

  membershipNumber: [
    'membership number',
    'membership number:',
    'membership no',
    'membership no.',
    'membership no:',
    'membership #',
    'membership #:',
    'membership id',
    'membership id:',
    'member number',
    'member number:',
    'member no',
    'member no:',
    'loyalty number',
    'loyalty number:',
    'rewards number',
    'rewards number:',
  ],

  loyaltyCard: [
    'loyalty card',
    'loyalty card:',
    'member card',
    'member card:',
    'membership card',
    'membership card:',
    'rewards card',
    'rewards card:',
    'points card',
    'points card:',
    'club card',
    'club card:',
    'privilege card',
    'privilege card:',
    'loyalty account',
    'loyalty account:',
  ],

  loyaltyCardNumber: [
    'loyalty card number',
    'loyalty card number:',
    'loyalty card no',
    'loyalty card no.',
    'loyalty card no:',
    'member card number',
    'member card number:',
    'membership card number',
    'membership card number:',
    'rewards card number',
    'rewards card number:',
    'points card number',
    'points card number:',
    'loyalty number',
    'loyalty number:',
    'member number',
    'member number:',
  ],

  pointsAwarded: [
    'points awarded',
    'points awarded:',
    'points earned',
    'points earned:',
    'earned points',
    'earned points:',
    'reward points',
    'reward points:',
    'loyalty points earned',
    'loyalty points earned:',
    'points added',
    'points added:',
    'points credited',
    'points credited:',
    'awarded points',
    'awarded points:',
  ],

  pointsBalance: [
    'points balance',
    'points balance:',
    'balance points',
    'balance points:',
    'available points',
    'available points:',
    'reward points balance',
    'reward points balance:',
    'loyalty balance',
    'loyalty balance:',
    'loyalty points balance',
    'loyalty points balance:',
    'current points',
    'current points:',
    'remaining points',
    'remaining points:',
    'points total',
    'points total:',
  ],

  // Merchant / customer / ship-to addresses

  shippingAddress: [],
  shipToAddress: [],
  shipFromAddress: [],
  shipName: [],
  shipToName: [],
  customerAddress: [],
  merchantAddress: [],
  addressLine1: [],
  addressLine2: [],
  addressLine3: [],
  city: [],
  district: [],
  locality: [],
  region: [],
  state: [],
  province: [],
  county: [],
  country: [],
  countryCode: [],
  zip: [],
  zipCode: [],
  building: [],
  floor: [],
  unit: [],
  suite: [],

  // Customer / shipper / relationship info

  customerId: [],
  customerName: [],
  customerNumber: [],
  customerCode: [],
  customerReference: [],
  buyerName: [],
  buyerId: [],
  shipperId: [],
  shipperName: [],
  shipperCode: [],
  carrier: [],
  carrierName: [],
  carrierCode: [],
  deliveryProvider: [],
  courier: [],
  courierName: [],
  employeeName: [],
  salesperson: [],
  salespersonId: [],
  salespersonReference: [],

  // POS / cashier / terminal / operator context

  cashier: [],
  cashierName: [],
  cashierId: [],
  cashierNumber: [],
  operator: [],
  operatorName: [],
  operatorId: [],
  operatorNumber: [],
  clerk: [],
  clerkId: [],
  clerkNumber: [],
  server: [],
  serverName: [],
  serverId: [],
  serverNumber: [],
  waiter: [],
  waitress: [],
  register: [],
  registerNumber: [],
  registerId: [],
  registerLabel: [],
  regNumber: [],
  terminalNumber: [],
  terminalId: [],
  terminalCode: [],
  posId: [],
  posLocation: [],
  posNumber: [],
  station: [],
  stationId: [],
  stationNumber: [],
  stationName: [],
  machineNumber: [],
  machineId: [],
  counter: [],
  counterLabel: [],
  laneNumber: [],
  laneId: [],
  tillNumber: [],
  tillId: [],
  drawerNumber: [],
  device: [],
  deviceNumber: [],
  shift: [],
  shiftNumber: [],
  sessionId: [],
  sessionNumber: [],

  // Time / date fields

  date: [],
  time: [],
  dateTime: [],
  businessDate: [],
  businessTime: [],
  openedTime: [],
  openedAt: [],
  closedTime: [],
  closedAt: [],
  printedTime: [],
  printTime: [],
  printDate: [],
  settlementTime: [],
  serviceDate: [],
  dueDate: [],
  shippedDate: [],
  deliveryDate: [],

  // Service mode / venue context

  serviceMode: [],
  serviceTypeLabel: [],
  orderType: [],
  diningMode: [],
  dineIn: [],
  takeAway: [],
  takeaway: [],
  takeOut: [],
  eatIn: [],
  walkIn: [],
  onlineOrder: [],
  onlineStatus: [],
  pickup: [],
  curbsidePickup: [],
  deliveryMode: [],
  channel: [],
  salesChannel: [],
  sourcePlatform: [],
  diningRoom: [],
  section: [],
  room: [],
  area: [],
  table: [],
  tableNumber: [],
  tableName: [],
  seat: [],
  seatNumber: [],
  guestCount: [],
  guestNumber: [],
  guests: [],
  partySize: [],
  covers: [],
  pax: [],
  personNumber: [],
  guestReference: [],
  orderNote: [],
  note: [],
  remarks: [],

  // Payment / tender / card / settlement

  paymentMode: [],
  paymentTender: [],
  paymentProvider: [],
  tenderType: [],
  tenderedAmount: [],
  paidAmount: [],
  totalPaid: [],
  amountPaid: [],
  paymentAmount: [],
  amountReceived: [],
  received: [],
  receivedAmount: [],
  balanceDue: [],
  cashTendered: [],
  cashReceived: [],
  cash: [],
  change: [],
  changeDue: [],
  voucherAmount: [],
  chequeAmount: [],
  debitAmount: [],
  debitCardAmount: [],
  creditAmount: [],
  creditCardAmount: [],
  cardAmount: [],
  cardType: [],
  cardBrand: [],
  cardScheme: [],
  paymentCardNetwork: [],
  accountTailDigits: [],
  cardLast4: [],
  maskedPan: [],
  rrn: [],
  aid: [],
  entryMethod: [],
  tip: [],
  gratuity: [],
  suggestedGratuity: [],
  serviceCharge: [],

  // Totals / money / adjustments

  subtotal: [],
  subTotal: [],
  grossAmount: [],
  netAmount: [],
  grandTotal: [],
  total: [],
  finalTotal: [],
  amountDue: [],
  payable: [],
  totalAmount: [],
  totalAmountDue: [],
  totalExcludingTax: [],
  totalIncludingTax: [],
  totalExcludingGst: [],
  totalIncludingGst: [],
  totalSalesExcludingGst: [],
  totalSalesIncludingGst: [],
  totalSalesInclusive: [],
  totalSalesExclusive: [],
  minimumPayment: [],
  receivedTotal: [],
  netSales: [],
  grossSales: [],
  amountTendered: [],
  totalSaving: [],
  savings: [],
  savingAmount: [],
  discountAmount: [],
  discountSummary: [],
  lineDiscountAmount: [],
  rounding: [],
  roundAdjustment: [],
  roundingAdjustment: [],
  roundOff: [],

  // Tax fields / tax buckets

  tax: [],
  taxAmount: [],
  taxTotal: [],
  taxRate: [],
  taxPercent: [],
  taxCode: [],
  taxLabel: [],
  taxSummary: [],
  taxSummaryLabel: [],
  taxableAmount: [],
  taxIncluded: [],
  taxExcluded: [],
  gst: [],
  gstAmount: [],
  gstRate: [],
  gstPercent: [],
  gstIncluded: [],
  gstPayable: [],
  gstRegistrationId: [],
  gstSummaryAmount: [],
  gstSummaryTax: [],
  vat: [],
  vatAmount: [],
  vatRate: [],
  vatPercent: [],
  serviceTax: [],
  salesTax: [],
  foodTax: [],
  liquorTax: [],
  otherTaxes: [],
  taxBucket: [],
  taxBucketLabel: [],
  standardRatedAmount: [],
  zeroRatedAmount: [],
  reducedRatedAmount: [],
  nonTaxableAmount: [],
  inclusiveTaxAmount: [],
  exclusiveTaxAmount: [],

  // Quantity / count / measurement fields

  quantity: [],
  qty: [],
  itemCount: [],
  itemsCount: [],
  totalItems: [],
  totalItemCount: [],
  totalQuantity: [],
  totalQty: [],
  quantityUnit: [],
  unit: [],
  unitText: [],
  unitCode: [],
  unitPrice: [],
  uPrice: [],
  pricePerUnit: [],
  pricePerItem: [],
  linePrice: [],
  lineAmount: [],
  lineTotal: [],
  lineSubtotal: [],
  lineTaxAmount: [],
  basePrice: [],
  discountedPrice: [],
  priceBeforeDiscount: [],
  priceAfterDiscount: [],
  weightedQuantity: [],
  measuredQuantity: [],
  weight: [],
  weightUnit: [],
  weighedItem: [],
  volume: [],
  volumeUnit: [],
  litres: [],
  liters: [],
  pricePerKg: [],
  pricePerLb: [],
  pricePerLitre: [],
  pricePerLiter: [],
  eligibleQuantity: [],
  referenceQuantity: [],
  referenceUnit: [],
  minPrice: [],
  maxPrice: [],
  currencySymbol: [],

  // Item / line item / product detail

  itemCode: [],
  itemId: [],
  itemNumber: [],
  itemName: [],
  itemDescription: [],
  itemVariant: [],
  itemModifier: [],
  itemCategory: [],
  itemGroup: [],
  itemEntityType: [],
  itemLabel: [],
  barcode: [],
  plu: [],
  stockCode: [],
  catalogCode: [],
  productCode: [],
  productId: [],
  productName: [],
  productDescription: [],
  productLabel: [],
  menuItemName: [],
  serviceName: [],
  modifierText: [],
  modifierPrice: [],
  modifierGroup: [],
  size: [],
  color: [],
  flavor: [],
  modelNumber: [],
  batchNumber: [],
  lotNumber: [],
  serialCode: [],
  comboName: [],
  comboComponent: [],
  bundleLabel: [],
  bundleName: [],
  includedItem: [],
  addOnItem: [],
  complimentary: [],
  isFreeItem: [],
  freeItem: [],
  discountPercent: [],
  lineNote: [],

  // Fuel / weighed goods / specialty receipt fields

  pumpNumber: [],
  pumpId: [],
  nozzleNumber: [],
  fuelType: [],
  fuelGrade: [],
  octane: [],
  odometer: [],
  mileage: [],

  // Shipping / fulfillment / logistics

  shipmentNumber: [],
  shipmentId: [],
  shippingMethod: [],
  shippingMode: [],
  shippingCost: [],
  shippingFee: [],
  handlingFee: [],
  dispatchDate: [],
  expectedDeliveryDate: [],
  expectedShipDate: [],
  pickupDate: [],
  pickupTime: [],

  // Misc document content commonly seen on receipts / orders

  receiptType: [],
  documentType: [],
  copyType: [],
  customerCopy: [],
  merchantCopy: [],
  footerNote: [],
  headerNote: [],
  policyNote: [],
  refundPolicy: [],
  exchangePolicy: [],
  returnPolicy: [],
  promotionalMessage: [],
  campaignMessage: [],
  surveyMessage: [],
  surveyUrl: [],
  onlineOrderUrl: [],
  paymentLink: [],
  qrCodeValue: [],
  barcodeValue: [],
  couponCode: [],
  promoCode: [],
  promoDescription: [],
  branchTelephone: [],
  contactEmail: [],
  websiteUrl: [],
  socialPage: [],
  manager: [],
  managerName: [],
  attendant: [],
  attendantName: [],
  clerkName: [],
  openedBy: [],
  closedBy: [],
  preparedBy: [],
  fulfilledBy: [],
  servedBy: [],

  // High-level flat business info that still appears on orders

  merchantType: [],
  storeType: [],
  businessType: [],
  receiptLanguage: [],
  locale: [],
  regionCode: [],
  countryName: [],
}
