export default {
  acceptedOffer: [
    'accepted offer',
    'accepted offers',
    'offer',
    'offers',
    'order items',
    'ordered items',
    'items ordered',
    'items purchased',
    'purchased items',
    'products ordered',
    'services ordered',
    'line items',
    'basket items',
    'cart items',
    'order summary',
    'purchase summary',
  ],

  billingAddress: [
    'billing address',
    'bill to',
    'billed to',
    'bill-to',
    'invoice address',
    'billing details',
    'billing information',
    'customer billing address',
    'billing contact address',
    'billing destination',
  ],

  broker: [
    'broker',
    'agent',
    'booking agent',
    'intermediary',
    'facilitator',
    'facilitated by',
    'arranged by',
    'brokered by',
    'sales agent',
    'account broker',
  ],

  confirmationNumber: [
    'confirmation number',
    'confirmation no',
    'confirmation #',
    'conf no',
    'conf #',
    'confirmation code',
    'confirmation id',
    'booking confirmation',
    'payment confirmation number',
    'receipt confirmation',
  ],

  customer: [
    'customer',
    'customer name',
    'buyer',
    'buyer name',
    'purchaser',
    'purchased by',
    'client',
    'client name',
    'account name',
    'sold to',
    'bill to',
    'billed to',
    'recipient',
    'ordered by',
  ],

  discount: [
    'discount',
    'discount amount',
    'discounts',
    'less discount',
    'promo discount',
    'promotion discount',
    'coupon discount',
    'voucher discount',
    'rebate',
    'markdown',
    'savings',
    'you saved',
    'total savings',
  ],

  discountCode: [
    'discount code',
    'promo code',
    'promotion code',
    'coupon code',
    'voucher code',
    'redeem code',
    'offer code',
    'promotion id',
    'coupon id',
  ],

  discountCurrency: [
    'discount currency',
    'discount curr',
    'discount curr.',
    'savings currency',
    'currency of discount',
    'rebate currency',
  ],

  isGift: [
    'gift',
    'gift order',
    'gift purchase',
    'marked as gift',
    'gift option',
    'gift flag',
    'is gift',
    'this is a gift',
    'gift item',
    'gift receipt',
  ],

  orderDate: [
    'order date',
    'date ordered',
    'ordered on',
    'purchase date',
    'transaction date',
    'sale date',
    'date of order',
    'created at',
    'created on',
    'order created',
    'placed on',
    'date',
    'invoice date',
  ],

  orderDelivery: [
    'order delivery',
    'delivery',
    'delivery details',
    'delivery information',
    'shipping',
    'shipping details',
    'shipment',
    'shipment details',
    'shipping information',
    'fulfillment',
    'dispatch',
    'parcel delivery',
  ],

  orderNumber: [
    'order number',
    'order no',
    'order no.',
    'order #',
    'order id',
    'sales order',
    'sales order no',
    'sales order #',
    'purchase id',
    'transaction id',
    'reference number',
    'ref no',
    'document no',
    'doc no',
  ],

  orderStatus: [
    'order status',
    'status',
    'current status',
    'purchase status',
    'transaction status',
    'fulfillment status',
    'processing status',
    'delivery status',
    'shipment status',
    'state',
  ],

  orderedItem: [
    'ordered item',
    'ordered items',
    'item',
    'items',
    'item ordered',
    'purchase item',
    'purchased item',
    'product',
    'products',
    'service',
    'services',
    'description',
    'item description',
    'line item',
    'line items',
  ],

  partOfInvoice: [
    'part of invoice',
    'invoice',
    'invoice reference',
    'invoice ref',
    'invoice no',
    'invoice #',
    'billed under',
    'invoiced under',
    'included in invoice',
    'invoice linkage',
  ],

  paymentDueDate: [
    'payment due date',
    'due date',
    'payment due',
    'due on',
    'amount due by',
    'pay by',
    'pay before',
    'payable by',
    'due by',
    'date due',
    'payment deadline',
  ],

  paymentMethod: [
    'payment method',
    'method of payment',
    'payment type',
    'payment mode',
    'paid by',
    'paid via',
    'tender type',
    'tender',
    'payment',
    'settlement method',
    'mode of payment',
  ],

  paymentMethodId: [
    'payment method id',
    'payment id',
    'payment reference',
    'payment ref',
    'transaction reference',
    'transaction ref',
    'card ending',
    'card ending in',
    'last 4 digits',
    'account ending',
    'token',
    'auth id',
    'authorization id',
  ],

  paymentUrl: [
    'payment url',
    'payment link',
    'pay now',
    'pay online',
    'pay here',
    'complete payment',
    'payment page',
    'checkout link',
    'payment portal',
    'settlement link',
  ],

  seller: [
    'seller',
    'sold by',
    'merchant',
    'vendor',
    'supplier',
    'retailer',
    'store',
    'shop',
    'business',
    'merchant name',
    'seller name',
    'vendor name',
  ],

  additionalType: [
    'additional type',
    'type',
    'subtype',
    'category',
    'classification',
    'document type',
    'order type',
    'record type',
    'item type',
    'service type',
  ],

  alternateName: [
    'alternate name',
    'alternative name',
    'alt name',
    'alias',
    'also known as',
    'aka',
    'display name',
    'short name',
    'other name',
  ],

  description: [
    'description',
    'details',
    'item description',
    'product description',
    'service description',
    'summary',
    'remarks',
    'memo',
    'note',
    'notes',
    'particulars',
  ],

  disambiguatingDescription: [
    'disambiguating description',
    'distinguishing description',
    'qualifier',
    'subtitle',
    'clarification',
    'clarifying description',
    'short description',
    'descriptor',
    'distinguishing note',
  ],

  identifier: [
    'identifier',
    'id',
    'reference',
    'reference id',
    'record id',
    'unique id',
    'external id',
    'internal id',
    'ref no',
    'ref #',
    'code',
  ],

  image: [
    'image',
    'photo',
    'picture',
    'product image',
    'item image',
    'thumbnail',
    'logo',
    'visual',
    'product photo',
  ],

  mainEntityOfPage: [
    'main entity of page',
    'source page',
    'page',
    'page url',
    'source url',
    'canonical page',
    'listing page',
    'product page',
    'service page',
    'reference page',
  ],

  name: [
    'name',
    'title',
    'label',
    'display name',
    'item name',
    'product name',
    'service name',
    'merchant name',
    'customer name',
    'designation',
  ],

  owner: [
    'owner',
    'owned by',
    'account owner',
    'record owner',
    'store owner',
    'merchant owner',
    'property owner',
  ],

  potentialAction: [
    'potential action',
    'action',
    'next action',
    'next step',
    'available action',
    'available actions',
    'follow-up action',
    'what you can do',
    'available options',
  ],

  sameAs: [
    'same as',
    'official page',
    'official url',
    'equivalent url',
    'reference url',
    'matching page',
    'external reference',
    'same entity',
    'see also',
  ],

  subjectOf: [
    'subject of',
    'subject',
    'about',
    'related document',
    'related page',
    'covered by',
    'referenced in',
    'document subject',
    'topic',
  ],

  url: [
    'url',
    'link',
    'website',
    'webpage',
    'page url',
    'source link',
    'web link',
    'page link',
    'site',
  ],

  // Invoice / offer / delivery / item / address / party / product / service carry-over

  accountId: [
    'account id',
    'account',
    'account no',
    'account no.',
    'account number',
    'acct no',
    'acct no.',
    'acct #',
    'account #',
    'customer account',
    'customer account no',
    'customer account number',
    'member account',
    'billing account',
    'account reference',
    'account ref',
    'account code',
    'client account',
    'payer account',
  ],

  billingPeriod: [
    'billing period',
    'bill period',
    'billing cycle',
    'billing range',
    'service period',
    'period covered',
    'period',
    'statement period',
    'invoice period',
    'coverage period',
    'for period',
    'period from',
    'period to',
    'billing from',
    'billing to',
    'service from',
    'service to',
    'cycle period',
  ],

  minimumPaymentDue: [
    'minimum payment due',
    'minimum payment',
    'minimum due',
    'min payment due',
    'min payment',
    'min due',
    'minimum amount due',
    'minimum payable',
    'minimum amount payable',
    'least amount due',
    'amount due minimum',
    'minimum balance due',
    'min. payment due',
    'min. due',
  ],

  paymentStatus: [
    'payment status',
    'status',
    'payment state',
    'settlement status',
    'settlement state',
    'paid status',
    'transaction status',
    'invoice status',
    'balance status',
    'payment result',
    'payment complete',
    'paid',
    'unpaid',
    'payment pending',
    'payment received',
    'settled',
    'not paid',
  ],

  provider: [
    'provider',
    'service provider',
    'provided by',
    'supplied by',
    'fulfilled by',
    'vendor',
    'supplier',
    'seller',
    'merchant',
    'issuer',
    'carrier',
    'operator',
    'performer',
    'service company',
    'company',
    'organization',
  ],

  referencesOrder: [
    'references order',
    'reference order',
    'referenced order',
    'related order',
    'linked order',
    'order reference',
    'order ref',
    'ref order',
    'source order',
    'original order',
    'parent order',
    'sales order ref',
    'customer order ref',
    'associated order',
    'connected order',
  ],

  scheduledPaymentDate: [
    'scheduled payment date',
    'scheduled payment',
    'scheduled pay date',
    'scheduled pay on',
    'autopay date',
    'auto pay date',
    'auto-payment date',
    'payment scheduled for',
    'scheduled settlement date',
    'next payment date',
    'next due date',
    'planned payment date',
    'debit date',
  ],

  totalPaymentDue: [
    'total payment due',
    'total due',
    'amount due',
    'total amount due',
    'total payable',
    'amount payable',
    'balance due',
    'grand total',
    'final total',
    'invoice total',
    'total payment',
    'payment due',
    'net payable',
    'total outstanding',
    'amount owing',
    'total bill',
    'bill total',
  ],

  orderItemNumber: [
    'order item number',
    'order item no',
    'item number',
    'item no',
    'item #',
    'line item no',
    'line number',
    'line no',
    'row number',
    'sequence',
    'sequence no',
    'product line',
    'entry no',
    'detail no',
    'position no',
  ],

  orderItemStatus: [
    'order item status',
    'item status',
    'line item status',
    'line status',
    'product status',
    'fulfillment status',
    'shipment status',
    'delivery status',
    'state',
    'item state',
    'current status',
    'status',
    'line state',
    'availability status',
  ],

  orderQuantity: [
    'order quantity',
    'ordered quantity',
    'quantity ordered',
    'quantity',
    'qty',
    'qty ordered',
    'order qty',
    'units',
    'unit qty',
    'item qty',
    'items',
    'count',
    'ordered units',
    'purchase quantity',
    'requested quantity',
  ],

  acceptedPaymentMethod: [
    'accepted payment method',
    'accepted payment methods',
    'payment methods accepted',
    'we accept',
    'accepted tender',
    'accepted tenders',
    'payment types accepted',
    'mode of payment accepted',
    'accepted cards',
    'accepted payments',
    'payment options',
    'ways to pay',
    'pay with',
    'supported payment methods',
  ],

  addOn: [
    'add-on',
    'add on',
    'addon',
    'extra',
    'extras',
    'additional item',
    'additional items',
    'optional add-on',
    'upgrade',
    'upsell',
    'supplement',
    'attachment',
    'bundle add-on',
    'extra option',
    'option',
  ],

  additionalProperty: [
    'additional property',
    'additional properties',
    'additional info',
    'additional information',
    'extra info',
    'extra information',
    'details',
    'other details',
    'more details',
    'metadata',
    'attributes',
    'characteristics',
    'specifications',
    'notes',
    'remarks',
    'misc',
    'other information',
  ],

  availability: [
    'availability',
    'stock status',
    'in stock',
    'stock',
    'availability status',
    'item availability',
    'current availability',
    'status',
    'inventory status',
    'ready to ship',
    'available',
    'sold out',
    'backorder',
    'backordered',
    'out of stock',
    'ships in',
  ],

  businessFunction: [
    'business function',
    'function',
    'transaction type',
    'service type',
    'sale type',
    'business type',
    'purpose',
    'commercial function',
    'operation',
    'order type',
    'activity',
    'engagement type',
  ],

  itemCondition: [
    'item condition',
    'condition',
    'product condition',
    'goods condition',
    'state',
    'quality',
    'item state',
    'condition status',
    'new/used',
    'condition grade',
    'physical condition',
  ],

  itemOffered: [
    'item offered',
    'items offered',
    'offered item',
    'offered items',
    'product offered',
    'service offered',
    'item',
    'items',
    'product',
    'products',
    'service',
    'services',
    'description',
    'item description',
    'goods',
    'merchandise',
    'article',
  ],

  price: [
    'price',
    'unit price',
    'amount',
    'cost',
    'charge',
    'value',
    'rate',
    'price each',
    'selling price',
    'sale price',
    'retail price',
    'item price',
    'unit cost',
    'amount due',
    'amount',
    'total price',
  ],

  priceCurrency: [
    'price currency',
    'currency',
    'curr',
    'curr.',
    'currency code',
    'payment currency',
    'billing currency',
    'settlement currency',
    'price curr',
    'price curr.',
    'amount currency',
    'transaction currency',
  ],

  priceSpecification: [
    'price specification',
    'pricing',
    'pricing details',
    'price details',
    'rate details',
    'unit pricing',
    'price breakdown',
    'cost breakdown',
    'pricing structure',
    'price info',
    'price information',
    'specification',
    'pricing spec',
  ],

  priceValidUntil: [
    'price valid until',
    'valid until',
    'offer valid until',
    'price expires',
    'valid thru',
    'valid through',
    'expires on',
    'expiry date',
    'expiration date',
    'offer expiry',
    'promo valid until',
    'good until',
    'price effective until',
  ],

  sku: [
    'sku',
    'sku no',
    'sku no.',
    'sku #',
    'stock keeping unit',
    'stock code',
    'item code',
    'product code',
    'inventory code',
    'catalog code',
    'catalog no',
    'part code',
    'article number',
    'article no',
    'item id',
  ],

  serialNumber: [
    'serial number',
    'serial no',
    'serial no.',
    'serial #',
    's/n',
    'sn',
    'device serial',
    'unit serial',
    'machine serial',
    'product serial',
    'asset serial',
    'equipment serial',
    'serial id',
  ],

  deliveryAddress: [
    'delivery address',
    'ship to',
    'ship-to',
    'shipping address',
    'deliver to',
    'delivery details',
    'delivery destination',
    'shipping destination',
    'consignee address',
    'drop-off address',
    'recipient address',
    'send to',
  ],

  deliveryStatus: [
    'delivery status',
    'shipment status',
    'shipping status',
    'fulfillment status',
    'dispatch status',
    'carrier status',
    'parcel status',
    'delivery state',
    'shipment state',
    'current delivery status',
    'tracking status',
    'status',
  ],

  expectedArrivalFrom: [
    'expected arrival from',
    'expected from',
    'arrival window starts',
    'delivery starts',
    'estimated arrival from',
    'estimated from',
    'arrives from',
    'from date',
    'window opens',
    'delivery window from',
  ],

  expectedArrivalUntil: [
    'expected arrival until',
    'expected until',
    'arrival window ends',
    'delivery until',
    'estimated arrival until',
    'estimated until',
    'arrives by',
    'to date',
    'window closes',
    'delivery window to',
    'latest arrival',
  ],

  hasDeliveryMethod: [
    'delivery method',
    'shipping method',
    'ship via',
    'delivery via',
    'method',
    'fulfillment method',
    'dispatch method',
    'carrier method',
    'service level',
    'shipping service',
    'delivery option',
    'shipping option',
  ],

  itemShipped: [
    'item shipped',
    'items shipped',
    'shipped item',
    'shipped items',
    'goods shipped',
    'products shipped',
    'shipment contents',
    'contents',
    'parcel contents',
    'delivered item',
    'dispatched item',
    'goods in shipment',
  ],

  originAddress: [
    'origin address',
    'ship from',
    'ship-from',
    'shipping origin',
    'sender address',
    'dispatch address',
    'from address',
    'warehouse address',
    'origin',
    'source address',
    'fulfillment center',
    'return address',
  ],

  partOfOrder: [
    'part of order',
    'belongs to order',
    'included in order',
    'order reference',
    'related order',
    'parent order',
    'source order',
    'main order',
    'master order',
    'order link',
    'part of sales order',
  ],

  trackingNumber: [
    'tracking number',
    'tracking no',
    'tracking no.',
    'tracking #',
    'shipment tracking',
    'tracking id',
    'parcel tracking',
    'awb',
    'air waybill',
    'consignment no',
    'consignment number',
    'waybill number',
    'shipment no',
  ],

  trackingUrl: [
    'tracking url',
    'tracking link',
    'track shipment',
    'track package',
    'track order',
    'parcel tracking url',
    'shipment tracking url',
    'tracking page',
    'track here',
    'tracking website',
    'tracking portal',
  ],

  addressCountry: [
    'country',
    'address country',
    'country/region',
    'nation',
    'country name',
    'destination country',
    'billing country',
    'shipping country',
    'country code',
  ],

  addressLocality: [
    'city',
    'town',
    'locality',
    'address locality',
    'municipality',
    'suburb',
    'district',
    'city/town',
    'billing city',
    'shipping city',
    'local area',
  ],

  addressRegion: [
    'state',
    'province',
    'region',
    'address region',
    'county',
    'territory',
    'area',
    'state/province',
    'district',
    'prefecture',
    'billing region',
    'shipping region',
  ],

  extendedAddress: [
    'address 2',
    'address line 2',
    'address line 3',
    'extended address',
    'apt',
    'apartment',
    'suite',
    'unit',
    'floor',
    'building',
    'block',
    'room',
    'department',
    'care of',
    'c/o',
  ],

  postOfficeBoxNumber: [
    'po box',
    'p.o. box',
    'post office box',
    'box number',
    'po box number',
    'pobox',
    'postal box',
    'mailbox',
  ],

  postalCode: [
    'postal code',
    'postcode',
    'post code',
    'zip',
    'zip code',
    'pin',
    'pin code',
    'area code',
    'routing code',
    'postal / zip code',
    'code postal',
  ],

  streetAddress: [
    'street address',
    'street',
    'address line 1',
    'address 1',
    'street line',
    'road',
    'house address',
    'billing street',
    'shipping street',
    'delivery street',
    'location address',
  ],

  address: [
    'address',
    'full address',
    'mailing address',
    'postal address',
    'contact address',
    'registered address',
    'billing address',
    'shipping address',
    'location',
    'premises',
    'place',
  ],

  email: [
    'email',
    'e-mail',
    'email address',
    'e-mail address',
    'contact email',
    'mail',
    'mail address',
    'electronic mail',
    'customer email',
    'merchant email',
    'support email',
  ],

  legalName: [
    'legal name',
    'registered name',
    'company legal name',
    'entity name',
    'registered business name',
    'corporate name',
    'official name',
    'legal entity',
    'legal entity name',
    'trading as',
    'business legal name',
  ],

  taxID: [
    'tax id',
    'tax id no',
    'tax id number',
    'tax no',
    'tax no.',
    'tax number',
    'taxpayer id',
    'tin',
    'vat id',
    'vat number',
    'gst id',
    'gst number',
    'registration tax no',
    'fiscal id',
    'fiscal number',
  ],

  telephone: [
    'telephone',
    'tel',
    'tel.',
    'phone',
    'phone no',
    'phone number',
    'contact no',
    'contact number',
    'mobile',
    'mobile no',
    'call us',
    'landline',
    'contact phone',
  ],

  familyName: [
    'family name',
    'last name',
    'surname',
    'lname',
    'family/surname',
    'customer surname',
    'recipient surname',
    'buyer surname',
  ],

  givenName: [
    'given name',
    'first name',
    'forename',
    'fname',
    'customer first name',
    'recipient first name',
    'buyer first name',
    'personal name',
  ],

  brand: [
    'brand',
    'brand name',
    'maker',
    'manufacturer brand',
    'label',
    'product brand',
    'brand / make',
    'make',
    'house brand',
    'brand line',
  ],

  category: [
    'category',
    'product category',
    'item category',
    'service category',
    'type',
    'classification',
    'class',
    'department',
    'section',
    'group',
    'segment',
    'product type',
    'category name',
  ],

  gtin: [
    'gtin',
    'gtin-8',
    'gtin-12',
    'gtin-13',
    'gtin-14',
    'ean',
    'ean code',
    'upc',
    'upc code',
    'barcode',
    'barcode no',
    'barcode number',
    'global trade item number',
  ],

  model: [
    'model',
    'model no',
    'model no.',
    'model #',
    'product model',
    'model number',
    'series',
    'variant',
    'style',
    'design',
    'type',
    'model name',
  ],

  mpn: [
    'mpn',
    'mfr part no',
    'manufacturer part no',
    'manufacturer part number',
    'part no',
    'part no.',
    'part #',
    'part number',
    'mfg code',
    'manufacturer code',
    'product code',
  ],

  offers: [
    'offers',
    'available offers',
    'promotions',
    'deals',
    'special offers',
    'promotional offers',
    'related offers',
    'current offers',
    'available deals',
    'bundle offers',
    'pricing offers',
    'discount offers',
  ],

  areaServed: [
    'area served',
    'service area',
    'coverage area',
    'delivery area',
    'region served',
    'areas covered',
    'service region',
    'coverage region',
    'territory served',
    'available in',
    'serving area',
  ],

  availableChannel: [
    'available channel',
    'service channel',
    'sales channel',
    'support channel',
    'available via',
    'channel',
    'contact channel',
    'delivery channel',
    'purchase channel',
    'access channel',
    'order channel',
  ],

  hoursAvailable: [
    'hours available',
    'opening hours',
    'business hours',
    'store hours',
    'operating hours',
    'available hours',
    'service hours',
    'office hours',
    'working hours',
    'open',
    'available from',
    'available to',
  ],

  serviceOutput: [
    'service output',
    'output',
    'deliverable',
    'result',
    'service result',
    'work product',
    'generated item',
    'delivered result',
    'outcome',
    'service deliverable',
  ],

  serviceType: [
    'service type',
    'service',
    'type of service',
    'service category',
    'service class',
    'work type',
    'job type',
    'support type',
    'delivery type',
    'appointment type',
    'task type',
  ],

  termsOfService: [
    'terms of service',
    'terms',
    'terms & conditions',
    'terms and conditions',
    'conditions',
    'service terms',
    'purchase terms',
    'sale terms',
    'agreement',
    'customer terms',
    'merchant terms',
    'tos',
    'policies',
    'conditions of sale',
  ],

  // Document identity / numbering variants

  invoiceNumber: [
    'invoice number',
    'invoice no',
    'invoice no.',
    'invoice #',
    'invoice id',
    'invoice reference',
    'invoice ref',
    'invoice ref.',
    'tax invoice number',
    'tax invoice no',
    'tax invoice #',
    'sales invoice number',
    'sales invoice no',
    'inv number',
    'inv num',
    'inv #',
    'invoice code',
    'invoice identifier',
    'invoice record',
    'invoice serial',
  ],

  receiptNumber: [
    'receipt number',
    'receipt no',
    'receipt no.',
    'receipt #',
    'receipt id',
    'receipt reference',
    'receipt ref',
    'sales receipt number',
    'payment receipt number',
    'official receipt number',
    'receipt code',
    'receipt identifier',
    'receipt serial',
    'receipt document number',
    'rec number',
    'rec no',
    'rec #',
  ],

  billNumber: [
    'bill number',
    'bill no',
    'bill no.',
    'bill #',
    'bill id',
    'bill reference',
    'bill ref',
    'bill code',
    'billing number',
    'billing no',
    'statement number',
    'statement no',
    'statement #',
    'customer bill number',
    'restaurant bill number',
  ],

  cashDocNumber: [
    'cash doc number',
    'cash doc no',
    'cash doc no.',
    'cash document number',
    'cash document no',
    'cash document #',
    'cash doc #',
    'cash transaction number',
    'cash transaction no',
    'cash voucher number',
    'cash voucher no',
    'cash note number',
    'cash memo number',
    'cash memo no',
    'cash receipt doc number',
  ],

  cashSaleNumber: [
    'cash sale number',
    'cash sale no',
    'cash sale no.',
    'cash sale #',
    'cash sales number',
    'cash sales no',
    'cash sales #',
    'cash invoice number',
    'cash invoice no',
    'cash transaction no',
    'point of sale number',
    'pos sale number',
    'sale number',
    'sale no',
    'sale #',
  ],

  cashReceiptNumber: [
    'cash receipt number',
    'cash receipt no',
    'cash receipt no.',
    'cash receipt #',
    'cash rec no',
    'cash rec #',
    'cash payment receipt number',
    'cash collection receipt no',
    'cash received receipt no',
    'official receipt no',
    'or number',
    'or no',
    'or #',
    'receipt cash no',
  ],

  checkNumber: [
    'check number',
    'check no',
    'check no.',
    'check #',
    'cheque number',
    'cheque no',
    'cheque #',
    'guest check number',
    'check id',
    'restaurant check number',
    'table check number',
    'bill check number',
    'chk no',
    'chk #',
    'guest check #',
  ],

  ticketNumber: [
    'ticket number',
    'ticket no',
    'ticket no.',
    'ticket #',
    'ticket id',
    'order ticket number',
    'service ticket number',
    'support ticket number',
    'job ticket number',
    'kitchen ticket number',
    'queue ticket number',
    'stub number',
    'ticket ref',
    'ticket code',
    'ticket identifier',
  ],

  documentNumber: [
    'document number',
    'document no',
    'document no.',
    'document #',
    'doc number',
    'doc #',
    'document id',
    'document reference',
    'document ref',
    'record number',
    'record no',
    'record id',
    'form number',
    'form no',
    'form #',
  ],

  docNo: [
    'doc no',
    'doc no.',
    'doc #',
    'document no',
    'document no.',
    'document #',
    'doc number',
    'document number',
    'doc ref',
    'doc code',
    'record no',
    'record #',
    'ref doc no',
  ],

  billNo: [
    'bill no',
    'bill no.',
    'bill #',
    'bill number',
    'billing no',
    'billing no.',
    'billing #',
    'customer bill no',
    'restaurant bill no',
    'table bill no',
    'guest bill no',
    'statement no',
    'statement #',
  ],

  invNo: [
    'inv no',
    'inv no.',
    'inv #',
    'invoice no',
    'invoice no.',
    'invoice #',
    'invoice number',
    'inv number',
    'tax inv no',
    'tax inv #',
    'sales inv no',
    'sales inv #',
    'invoice ref no',
  ],

  receiptNo: [
    'receipt no',
    'receipt no.',
    'receipt #',
    'receipt number',
    'receipt ref no',
    'sales receipt no',
    'payment receipt no',
    'official receipt no',
    'official receipt #',
    'rec no',
    'rec no.',
    'rec #',
    'cash receipt no',
  ],

  invoiceNo: [
    'invoice no',
    'invoice no.',
    'invoice #',
    'invoice number',
    'invoice ref no',
    'tax invoice no',
    'tax invoice no.',
    'tax invoice #',
    'sales invoice no',
    'sales invoice #',
    'inv no',
    'inv no.',
    'inv #',
  ],

  transactionNumber: [
    'transaction number',
    'transaction no',
    'transaction no.',
    'transaction #',
    'txn number',
    'txn no',
    'txn #',
    'payment transaction number',
    'pos transaction number',
    'sale transaction number',
    'transaction ref no',
    'transaction identifier',
    'transaction serial',
    'trans number',
    'trans no',
  ],

  transactionId: [
    'transaction id',
    'txn id',
    'trans id',
    'transaction identifier',
    'payment id',
    'payment transaction id',
    'transaction token',
    'gateway transaction id',
    'processor transaction id',
    'sale id',
    'purchase id',
    'order transaction id',
    'transaction uid',
  ],

  transactionCode: [
    'transaction code',
    'txn code',
    'trans code',
    'payment code',
    'reference code',
    'sale code',
    'transaction type code',
    'transaction auth code',
    'processor code',
    'approval code',
    'authorization code',
    'transaction token',
    'event code',
  ],

  transactionReference: [
    'transaction reference',
    'transaction ref',
    'transaction ref.',
    'txn reference',
    'txn ref',
    'trans reference',
    'trans ref',
    'reference transaction',
    'payment reference',
    'payment ref',
    'gateway reference',
    'processor reference',
    'merchant reference',
    'customer reference',
    'reference no',
  ],

  paymentReference: [
    'payment reference',
    'payment ref',
    'payment ref.',
    'payment reference number',
    'payment reference no',
    'payment reference #',
    'pay ref',
    'settlement reference',
    'settlement ref',
    'remittance reference',
    'remittance ref',
    'receipt reference',
    'bank reference',
    'transfer reference',
    'reference for payment',
  ],

  referenceNumber: [
    'reference number',
    'reference no',
    'reference no.',
    'reference #',
    'ref number',
    'ref no',
    'ref no.',
    'ref #',
    'customer reference number',
    'merchant reference number',
    'document reference number',
    'external reference number',
    'internal reference number',
    'control number',
    'tracking reference number',
  ],

  referenceCode: [
    'reference code',
    'ref code',
    'ref. code',
    'customer code',
    'merchant code',
    'document code',
    'control code',
    'record code',
    'payment code',
    'lookup code',
    'verification code',
    'external code',
    'internal code',
  ],

  approvalNumber: [
    'approval number',
    'approval no',
    'approval no.',
    'approval #',
    'approval id',
    'approved no',
    'approved #',
    'bank approval number',
    'card approval number',
    'payment approval number',
    'auth approval number',
    'authorization number',
    'approval code',
    'processor approval no',
  ],

  authorizationCode: [
    'authorization code',
    'authorisation code',
    'authorization no',
    'authorization #',
    'auth code',
    'auth no',
    'auth #',
    'approval code',
    'card auth code',
    'bank auth code',
    'payment auth code',
    'processor auth code',
    'authorization id',
    'authorisation no',
  ],

  authCode: [
    'auth code',
    'auth. code',
    'auth no',
    'auth no.',
    'auth #',
    'authorization code',
    'authorisation code',
    'approval code',
    'card auth',
    'bank auth',
    'payment auth',
    'processor auth',
    'approval ref',
  ],

  serialNo: [
    'serial no',
    'serial no.',
    'serial #',
    'serial number',
    's/n',
    'sn',
    'record serial no',
    'document serial no',
    'invoice serial no',
    'receipt serial no',
    'print serial no',
    'device serial no',
    'terminal serial no',
  ],

  sequenceNumber: [
    'sequence number',
    'sequence no',
    'sequence no.',
    'sequence #',
    'seq number',
    'seq no',
    'seq #',
    'line sequence',
    'print sequence',
    'batch sequence',
    'running number',
    'running no',
    'counter number',
    'entry sequence',
  ],

  version: [
    'version',
    'ver',
    'ver.',
    'version no',
    'version no.',
    'version #',
    'document version',
    'print version',
    'form version',
    'software version',
    'system version',
    'template version',
    'layout version',
  ],

  // Merchant / business / outlet info

  merchantName: [
    'merchant',
    'merchant name',
    'merchant:',
    'merchant name:',
    'merchant details',
    'merchant information',
    'merchant info',
    'merchant account',
    'merchant profile',
    'merchant legal name',
    'merchant trading name',
    'merchant display name',
    'merchant title',
    'merchant store name',
    'merchant business name',
    'from',
    'from:',
    'sold by',
    'sold by:',
    'seller',
    'seller:',
    'store',
    'store:',
    'shop',
    'shop:',
    'retailer',
    'retailer:',
    'business',
    'business:',
    'company',
    'company:',
    'merchant / seller',
    'merchant/seller',
    'seller name',
    'seller name:',
    'vendor',
    'vendor:',
    'vendor name',
    'vendor name:',
    'issued by',
    'issued by:',
    'provided by',
    'provided by:',
  ],

  merchantId: [
    'merchant id',
    'merchant id:',
    'merchant identifier',
    'merchant identifier:',
    'merchant no',
    'merchant no.',
    'merchant no:',
    'merchant #',
    'merchant #:',
    'merchant code',
    'merchant code:',
    'merchant account id',
    'merchant account id:',
    'merchant number',
    'merchant number:',
    'merchant ref',
    'merchant ref:',
    'merchant reference',
    'merchant reference:',
    'seller id',
    'seller id:',
    'store id',
    'store id:',
    'vendor id',
    'vendor id:',
  ],

  sellerName: [
    'seller',
    'seller:',
    'seller name',
    'seller name:',
    'sold by',
    'sold by:',
    'merchant',
    'merchant:',
    'merchant name',
    'merchant name:',
    'vendor',
    'vendor:',
    'vendor name',
    'vendor name:',
    'supplier',
    'supplier:',
    'supplier name',
    'supplier name:',
    'retailer',
    'retailer:',
    'shop',
    'shop:',
    'store',
    'store:',
    'business name',
    'business name:',
    'company name',
    'company name:',
  ],

  sellerId: [
    'seller id',
    'seller id:',
    'seller identifier',
    'seller identifier:',
    'seller no',
    'seller no.',
    'seller no:',
    'seller #',
    'seller #:',
    'seller code',
    'seller code:',
    'merchant id',
    'merchant id:',
    'vendor id',
    'vendor id:',
    'supplier id',
    'supplier id:',
    'store id',
    'store id:',
    'seller ref',
    'seller ref:',
    'seller reference',
    'seller reference:',
  ],

  vendorName: [
    'vendor',
    'vendor:',
    'vendor name',
    'vendor name:',
    'supplier',
    'supplier:',
    'supplier name',
    'supplier name:',
    'merchant',
    'merchant:',
    'seller',
    'seller:',
    'provider',
    'provider:',
    'provider name',
    'provider name:',
    'business name',
    'business name:',
    'company name',
    'company name:',
    'sold by',
    'sold by:',
  ],

  vendorId: [
    'vendor id',
    'vendor id:',
    'vendor identifier',
    'vendor identifier:',
    'vendor no',
    'vendor no.',
    'vendor no:',
    'vendor #',
    'vendor #:',
    'vendor code',
    'vendor code:',
    'supplier id',
    'supplier id:',
    'supplier code',
    'supplier code:',
    'merchant id',
    'merchant id:',
    'seller id',
    'seller id:',
    'provider id',
    'provider id:',
  ],

  businessName: [
    'business name',
    'business name:',
    'business',
    'business:',
    'registered business name',
    'registered business name:',
    'trading name',
    'trading name:',
    'trade name',
    'trade name:',
    'company name',
    'company name:',
    'merchant name',
    'merchant name:',
    'store name',
    'store name:',
    'seller name',
    'seller name:',
    'vendor name',
    'vendor name:',
    'legal business name',
    'legal business name:',
  ],

  companyName: [
    'company name',
    'company name:',
    'company',
    'company:',
    'registered company name',
    'registered company name:',
    'legal company name',
    'legal company name:',
    'corporate name',
    'corporate name:',
    'entity name',
    'entity name:',
    'business name',
    'business name:',
    'merchant company',
    'merchant company:',
    'seller company',
    'seller company:',
    'vendor company',
    'vendor company:',
  ],

  companyRegistrationNumber: [
    'company registration number',
    'company registration number:',
    'company registration no',
    'company registration no.',
    'company registration no:',
    'company reg no',
    'company reg no.',
    'company reg no:',
    'company reg #',
    'company reg #:',
    'company number',
    'company number:',
    'registered company number',
    'registered company number:',
    'registration number',
    'registration number:',
    'registration no',
    'registration no.',
    'registration no:',
    'reg no',
    'reg no.',
    'reg no:',
    'reg #',
    'reg #:',
    'co. reg. no.',
    'co reg no',
    'co reg no:',
    'company id',
    'company id:',
    'business registration no',
    'business registration no:',
    'business registration number',
    'business registration number:',
  ],

  businessRegistrationNumber: [
    'business registration number',
    'business registration number:',
    'business registration no',
    'business registration no.',
    'business registration no:',
    'business reg no',
    'business reg no.',
    'business reg no:',
    'business reg #',
    'business reg #:',
    'business number',
    'business number:',
    'registered business no',
    'registered business no:',
    'registration number',
    'registration number:',
    'registration no',
    'registration no.',
    'registration no:',
    'reg no',
    'reg no.',
    'reg no:',
    'reg #',
    'reg #:',
    'biz reg no',
    'biz reg no:',
    'business id',
    'business id:',
    'company registration number',
    'company registration number:',
  ],

  registrationNumber: [
    'registration number',
    'registration number:',
    'registration no',
    'registration no.',
    'registration no:',
    'registration #',
    'registration #:',
    'reg no',
    'reg no.',
    'reg no:',
    'reg #',
    'reg #:',
    'registered number',
    'registered number:',
    'record number',
    'record number:',
    'business registration number',
    'business registration number:',
    'company registration number',
    'company registration number:',
  ],

  registrationNo: [
    'registration no',
    'registration no.',
    'registration no:',
    'reg no',
    'reg no.',
    'reg no:',
    'reg #',
    'reg #:',
    'registration #',
    'registration #:',
    'registered no',
    'registered no:',
    'company reg no',
    'company reg no:',
    'business reg no',
    'business reg no:',
    'co reg no',
    'co reg no:',
    'co. reg. no.',
    'license no',
    'license no:',
  ],

  gstId: [
    'gst id',
    'gst id:',
    'gst id no',
    'gst id no:',
    'gst identification number',
    'gst identification number:',
    'goods and services tax id',
    'goods and services tax id:',
    'gst registration id',
    'gst registration id:',
    'gst reg id',
    'gst reg id:',
    'gst registered id',
    'gst no',
    'gst no:',
    'gst number',
    'gst number:',
  ],

  gstNumber: [
    'gst number',
    'gst number:',
    'gst no',
    'gst no.',
    'gst no:',
    'gst #',
    'gst #:',
    'gst reg no',
    'gst reg no.',
    'gst reg no:',
    'gst registration number',
    'gst registration number:',
    'goods and services tax number',
    'goods and services tax number:',
    'gst id',
    'gst id:',
    'tax invoice gst no',
    'tax invoice gst no:',
  ],

  gstRegistrationNumber: [
    'gst registration number',
    'gst registration number:',
    'gst registration no',
    'gst registration no.',
    'gst registration no:',
    'gst reg number',
    'gst reg number:',
    'gst reg no',
    'gst reg no.',
    'gst reg no:',
    'gst registered number',
    'gst registered number:',
    'goods and services tax registration number',
    'goods and services tax registration number:',
    'gst number',
    'gst number:',
  ],

  vatId: [
    'vat id',
    'vat id:',
    'vat identification number',
    'vat identification number:',
    'value added tax id',
    'value added tax id:',
    'vat registration id',
    'vat registration id:',
    'vat tax id',
    'vat tax id:',
    'vat no',
    'vat no:',
    'vat number',
    'vat number:',
  ],

  vatNumber: [
    'vat number',
    'vat number:',
    'vat no',
    'vat no.',
    'vat no:',
    'vat #',
    'vat #:',
    'vat registration number',
    'vat registration number:',
    'vat reg no',
    'vat reg no:',
    'value added tax number',
    'value added tax number:',
    'tax number',
    'tax number:',
    'tax id',
    'tax id:',
  ],

  branch: [
    'branch',
    'branch:',
    'branch office',
    'branch office:',
    'branch location',
    'branch location:',
    'outlet',
    'outlet:',
    'store branch',
    'store branch:',
    'branch / outlet',
    'branch/outlet',
    'branch name',
    'branch name:',
    'shop branch',
    'shop branch:',
    'location',
    'location:',
  ],

  branchCode: [
    'branch code',
    'branch code:',
    'branch id',
    'branch id:',
    'branch no',
    'branch no.',
    'branch no:',
    'branch #',
    'branch #:',
    'branch identifier',
    'branch identifier:',
    'outlet code',
    'outlet code:',
    'store code',
    'store code:',
    'location code',
    'location code:',
    'shop code',
    'shop code:',
  ],

  branchName: [
    'branch name',
    'branch name:',
    'branch',
    'branch:',
    'outlet name',
    'outlet name:',
    'store name',
    'store name:',
    'location name',
    'location name:',
    'shop name',
    'shop name:',
    'branch location',
    'branch location:',
    'branch title',
    'branch title:',
  ],

  branchNumber: [
    'branch number',
    'branch number:',
    'branch no',
    'branch no.',
    'branch no:',
    'branch #',
    'branch #:',
    'branch id',
    'branch id:',
    'outlet number',
    'outlet number:',
    'outlet no',
    'outlet no:',
    'store number',
    'store number:',
    'location number',
    'location number:',
  ],

  outletName: [
    'outlet name',
    'outlet name:',
    'outlet',
    'outlet:',
    'branch name',
    'branch name:',
    'store name',
    'store name:',
    'location name',
    'location name:',
    'shop name',
    'shop name:',
    'retail outlet',
    'retail outlet:',
    'sales outlet',
    'sales outlet:',
  ],

  outletCode: [
    'outlet code',
    'outlet code:',
    'outlet id',
    'outlet id:',
    'outlet no',
    'outlet no.',
    'outlet no:',
    'outlet #',
    'outlet #:',
    'branch code',
    'branch code:',
    'store code',
    'store code:',
    'location code',
    'location code:',
    'shop code',
    'shop code:',
  ],

  storeName: [
    'store name',
    'store name:',
    'store',
    'store:',
    'shop name',
    'shop name:',
    'outlet name',
    'outlet name:',
    'branch name',
    'branch name:',
    'retail store',
    'retail store:',
    'store title',
    'store title:',
    'merchant store',
    'merchant store:',
  ],

  storeNumber: [
    'store number',
    'store number:',
    'store no',
    'store no.',
    'store no:',
    'store #',
    'store #:',
    'store id',
    'store id:',
    'branch number',
    'branch number:',
    'outlet number',
    'outlet number:',
    'shop number',
    'shop number:',
    'location number',
    'location number:',
    'site no',
    'site no:',
  ],

  storeCode: [
    'store code',
    'store code:',
    'store id',
    'store id:',
    'store no',
    'store no.',
    'store no:',
    'store #',
    'store #:',
    'shop code',
    'shop code:',
    'branch code',
    'branch code:',
    'outlet code',
    'outlet code:',
    'location code',
    'location code:',
    'site code',
    'site code:',
  ],

  locationName: [
    'location name',
    'location name:',
    'location',
    'location:',
    'store location',
    'store location:',
    'branch location',
    'branch location:',
    'outlet location',
    'outlet location:',
    'site name',
    'site name:',
    'place name',
    'place name:',
    'venue',
    'venue:',
  ],

  locationLabel: [
    'location label',
    'location label:',
    'location',
    'location:',
    'site label',
    'site label:',
    'branch label',
    'branch label:',
    'outlet label',
    'outlet label:',
    'counter label',
    'counter label:',
    'table + counter',
    'store label',
    'store label:',
  ],

  website: [
    'website',
    'website:',
    'web site',
    'web site:',
    'site',
    'site:',
    'url',
    'url:',
    'web',
    'web:',
    'homepage',
    'homepage:',
    'company website',
    'company website:',
    'merchant website',
    'merchant website:',
    'visit us',
    'visit us:',
    'online',
    'online:',
  ],

  faxNumber: [
    'fax number',
    'fax number:',
    'fax no',
    'fax no.',
    'fax no:',
    'fax #',
    'fax #:',
    'fax',
    'fax:',
    'facsimile',
    'facsimile:',
    'fax line',
    'fax line:',
    'company fax',
    'company fax:',
  ],

  contactNumber: [
    'contact number',
    'contact number:',
    'contact no',
    'contact no.',
    'contact no:',
    'contact #',
    'contact #:',
    'contact',
    'contact:',
    'phone',
    'phone:',
    'telephone',
    'telephone:',
    'tel',
    'tel:',
    'mobile',
    'mobile:',
    'hotline',
    'hotline:',
    'customer service no',
    'customer service no:',
  ],

  socialUrl: [
    'social url',
    'social url:',
    'social link',
    'social link:',
    'social media',
    'social media:',
    'facebook',
    'facebook:',
    'instagram',
    'instagram:',
    'twitter',
    'twitter:',
    'follow us',
    'follow us:',
    'find us on',
    'find us on:',
    'social page',
    'social page:',
  ],

  socialHandle: [
    'social handle',
    'social handle:',
    'handle',
    'handle:',
    '@handle',
    'username',
    'username:',
    'social username',
    'social username:',
    'facebook handle',
    'facebook handle:',
    'instagram handle',
    'instagram handle:',
    'twitter handle',
    'twitter handle:',
  ],

  loyaltyProgram: [
    'loyalty program',
    'loyalty program:',
    'loyalty programme',
    'loyalty programme:',
    'rewards program',
    'rewards program:',
    'rewards programme',
    'rewards programme:',
    'membership program',
    'membership program:',
    'member program',
    'member program:',
    'points program',
    'points program:',
    'loyalty scheme',
    'loyalty scheme:',
    'reward scheme',
    'reward scheme:',
  ],

  memberNumber: [
    'member number',
    'member number:',
    'member no',
    'member no.',
    'member no:',
    'member #',
    'member #:',
    'member id',
    'member id:',
    'membership no',
    'membership no:',
    'membership #',
    'membership #:',
    'customer member no',
    'customer member no:',
    'member code',
    'member code:',
  ],

  membershipNumber: [
    'membership number',
    'membership number:',
    'membership no',
    'membership no.',
    'membership no:',
    'membership #',
    'membership #:',
    'membership id',
    'membership id:',
    'member number',
    'member number:',
    'member no',
    'member no:',
    'loyalty number',
    'loyalty number:',
    'rewards number',
    'rewards number:',
  ],

  loyaltyCard: [
    'loyalty card',
    'loyalty card:',
    'member card',
    'member card:',
    'membership card',
    'membership card:',
    'rewards card',
    'rewards card:',
    'points card',
    'points card:',
    'club card',
    'club card:',
    'privilege card',
    'privilege card:',
    'loyalty account',
    'loyalty account:',
  ],

  loyaltyCardNumber: [
    'loyalty card number',
    'loyalty card number:',
    'loyalty card no',
    'loyalty card no.',
    'loyalty card no:',
    'member card number',
    'member card number:',
    'membership card number',
    'membership card number:',
    'rewards card number',
    'rewards card number:',
    'points card number',
    'points card number:',
    'loyalty number',
    'loyalty number:',
    'member number',
    'member number:',
  ],

  pointsAwarded: [
    'points awarded',
    'points awarded:',
    'points earned',
    'points earned:',
    'earned points',
    'earned points:',
    'reward points',
    'reward points:',
    'loyalty points earned',
    'loyalty points earned:',
    'points added',
    'points added:',
    'points credited',
    'points credited:',
    'awarded points',
    'awarded points:',
  ],

  pointsBalance: [
    'points balance',
    'points balance:',
    'balance points',
    'balance points:',
    'available points',
    'available points:',
    'reward points balance',
    'reward points balance:',
    'loyalty balance',
    'loyalty balance:',
    'loyalty points balance',
    'loyalty points balance:',
    'current points',
    'current points:',
    'remaining points',
    'remaining points:',
    'points total',
    'points total:',
  ],

  // Merchant / customer / ship-to addresses

  shippingAddress: [
    'shipping address',
    'shipping address:',
    'ship address',
    'ship address:',
    'delivery address',
    'delivery address:',
    'ship to address',
    'ship to address:',
    'ship-to address',
    'ship-to address:',
    'send to',
    'send to:',
    'deliver to',
    'deliver to:',
    'delivery details',
    'delivery details:',
    'shipping details',
    'shipping details:',
    'consignee address',
    'consignee address:',
    'destination address',
    'destination address:',
    'dispatch to',
    'dispatch to:',
    'ship destination',
    'ship destination:',
  ],

  shipToAddress: [
    'ship to address',
    'ship to address:',
    'ship-to address',
    'ship-to address:',
    'ship to',
    'ship to:',
    'deliver to',
    'deliver to:',
    'send to',
    'send to:',
    'recipient address',
    'recipient address:',
    'consignee address',
    'consignee address:',
    'delivery address',
    'delivery address:',
    'destination address',
    'destination address:',
    'shipping address',
    'shipping address:',
    'customer shipping address',
    'customer shipping address:',
  ],

  shipFromAddress: [
    'ship from address',
    'ship from address:',
    'ship-from address',
    'ship-from address:',
    'ship from',
    'ship from:',
    'from address',
    'from address:',
    'sender address',
    'sender address:',
    'dispatch address',
    'dispatch address:',
    'origin address',
    'origin address:',
    'warehouse address',
    'warehouse address:',
    'return address',
    'return address:',
    'fulfillment address',
    'fulfillment address:',
    'source address',
    'source address:',
  ],

  shipName: [
    'ship name',
    'ship name:',
    'shipping name',
    'shipping name:',
    'delivery name',
    'delivery name:',
    'ship contact',
    'ship contact:',
    'recipient name',
    'recipient name:',
    'consignee',
    'consignee:',
    'deliver to',
    'deliver to:',
    'ship to name',
    'ship to name:',
    'ship-to name',
    'ship-to name:',
    'attention',
    'attention:',
    'attn',
    'attn:',
  ],

  shipToName: [
    'ship to name',
    'ship to name:',
    'ship-to name',
    'ship-to name:',
    'ship to',
    'ship to:',
    'deliver to',
    'deliver to:',
    'recipient name',
    'recipient name:',
    'consignee name',
    'consignee name:',
    'customer name',
    'customer name:',
    'delivery contact',
    'delivery contact:',
    'shipping contact',
    'shipping contact:',
    'attention',
    'attention:',
    'attn',
    'attn:',
  ],

  customerAddress: [
    'customer address',
    'customer address:',
    'customer details',
    'customer details:',
    'customer location',
    'customer location:',
    'buyer address',
    'buyer address:',
    'client address',
    'client address:',
    'bill to address',
    'bill to address:',
    'bill-to address',
    'bill-to address:',
    'customer billing address',
    'customer billing address:',
    'customer shipping address',
    'customer shipping address:',
    'sold to address',
    'sold to address:',
  ],

  merchantAddress: [
    'merchant address',
    'merchant address:',
    'seller address',
    'seller address:',
    'vendor address',
    'vendor address:',
    'supplier address',
    'supplier address:',
    'store address',
    'store address:',
    'shop address',
    'shop address:',
    'business address',
    'business address:',
    'company address',
    'company address:',
    'registered address',
    'registered address:',
    'branch address',
    'branch address:',
    'location address',
    'location address:',
  ],

  addressLine1: [
    'address line 1',
    'address line 1:',
    'address 1',
    'address 1:',
    'line 1',
    'line 1:',
    'street address',
    'street address:',
    'street',
    'street:',
    'house address',
    'house address:',
    'primary address',
    'primary address:',
    'main address',
    'main address:',
  ],

  addressLine2: [
    'address line 2',
    'address line 2:',
    'address 2',
    'address 2:',
    'line 2',
    'line 2:',
    'address continuation',
    'address continuation:',
    'secondary address',
    'secondary address:',
    'apt / suite',
    'apt / suite:',
    'apartment / suite',
    'apartment / suite:',
    'unit / floor',
    'unit / floor:',
  ],

  addressLine3: [
    'address line 3',
    'address line 3:',
    'address 3',
    'address 3:',
    'line 3',
    'line 3:',
    'additional address',
    'additional address:',
    'tertiary address',
    'tertiary address:',
    'extra address line',
    'extra address line:',
    'address continuation 2',
    'address continuation 2:',
  ],

  city: [
    'city',
    'city:',
    'town',
    'town:',
    'city / town',
    'city / town:',
    'municipality',
    'municipality:',
    'address city',
    'address city:',
    'billing city',
    'billing city:',
    'shipping city',
    'shipping city:',
    'delivery city',
    'delivery city:',
    'ship city',
    'ship city:',
  ],

  district: [
    'district',
    'district:',
    'district name',
    'district name:',
    'administrative district',
    'administrative district:',
    'sub-district',
    'sub-district:',
    'sub district',
    'sub district:',
    'borough',
    'borough:',
    'zone',
    'zone:',
    'sector',
    'sector:',
    'ward',
    'ward:',
  ],

  locality: [
    'locality',
    'locality:',
    'address locality',
    'address locality:',
    'suburb',
    'suburb:',
    'neighborhood',
    'neighborhood:',
    'neighbourhood',
    'neighbourhood:',
    'area',
    'area:',
    'local area',
    'local area:',
    'village',
    'village:',
    'barangay',
    'barangay:',
  ],

  region: [
    'region',
    'region:',
    'address region',
    'address region:',
    'geographic region',
    'geographic region:',
    'area region',
    'area region:',
    'shipping region',
    'shipping region:',
    'billing region',
    'billing region:',
    'delivery region',
    'delivery region:',
    'ship region',
    'ship region:',
  ],

  state: [
    'state',
    'state:',
    'state / territory',
    'state / territory:',
    'state or territory',
    'state or territory:',
    'address state',
    'address state:',
    'billing state',
    'billing state:',
    'shipping state',
    'shipping state:',
    'ship state',
    'ship state:',
    'st',
    'st:',
  ],

  province: [
    'province',
    'province:',
    'address province',
    'address province:',
    'billing province',
    'billing province:',
    'shipping province',
    'shipping province:',
    'ship province',
    'ship province:',
    'province / state',
    'province / state:',
    'state / province',
    'state / province:',
    'prov',
    'prov:',
  ],

  county: [
    'county',
    'county:',
    'address county',
    'address county:',
    'billing county',
    'billing county:',
    'shipping county',
    'shipping county:',
    'delivery county',
    'delivery county:',
    'parish',
    'parish:',
    'prefecture',
    'prefecture:',
    'department',
    'department:',
  ],

  country: [
    'country',
    'country:',
    'nation',
    'nation:',
    'country / region',
    'country / region:',
    'address country',
    'address country:',
    'billing country',
    'billing country:',
    'shipping country',
    'shipping country:',
    'ship country',
    'ship country:',
    'destination country',
    'destination country:',
  ],

  countryCode: [
    'country code',
    'country code:',
    'country / region code',
    'country / region code:',
    'nation code',
    'nation code:',
    'iso country code',
    'iso country code:',
    'country abbreviation',
    'country abbreviation:',
    'country alpha-2',
    'country alpha-2:',
    'country alpha-3',
    'country alpha-3:',
  ],

  zip: [
    'zip',
    'zip:',
    'zip code',
    'zip code:',
    'zipcode',
    'zipcode:',
    'zip / postal code',
    'zip / postal code:',
    'postal / zip code',
    'postal / zip code:',
    'billing zip',
    'billing zip:',
    'shipping zip',
    'shipping zip:',
  ],

  zipCode: [
    'zip code',
    'zip code:',
    'zipcode',
    'zipcode:',
    'zip',
    'zip:',
    'postal code',
    'postal code:',
    'post code',
    'post code:',
    'postal / zip code',
    'postal / zip code:',
    'zip / postal code',
    'zip / postal code:',
    'ship postal code',
    'ship postal code:',
  ],

  building: [
    'building',
    'building:',
    'building name',
    'building name:',
    'building no',
    'building no.',
    'building no:',
    'building number',
    'building number:',
    'blk',
    'blk:',
    'block',
    'block:',
    'tower',
    'tower:',
    'premises',
    'premises:',
    'property',
    'property:',
  ],

  floor: [
    'floor',
    'floor:',
    'level',
    'level:',
    'fl',
    'fl:',
    'storey',
    'storey:',
    'story',
    'story:',
    'upper floor',
    'upper floor:',
    'ground floor',
    'ground floor:',
    '1st floor',
    '1st floor:',
    '2nd floor',
    '2nd floor:',
  ],

  unit: [
    'unit',
    'unit:',
    'unit no',
    'unit no.',
    'unit no:',
    'unit number',
    'unit number:',
    'apt',
    'apt:',
    'apartment',
    'apartment:',
    'room',
    'room:',
    'room no',
    'room no:',
    'flat',
    'flat:',
    'lot',
    'lot:',
  ],

  suite: [
    'suite',
    'suite:',
    'suite no',
    'suite no.',
    'suite no:',
    'suite number',
    'suite number:',
    'ste',
    'ste:',
    'office suite',
    'office suite:',
    'apt / suite',
    'apt / suite:',
    'apartment / suite',
    'apartment / suite:',
    'unit / suite',
    'unit / suite:',
  ],

  // Customer / shipper / relationship info

  customerId: [
    'customer id',
    'customer id:',
    'customer identifier',
    'customer identifier:',
    'customer no',
    'customer no.',
    'customer no:',
    'customer #',
    'customer #:',
    'customer number',
    'customer number:',
    'customer code',
    'customer code:',
    'client id',
    'client id:',
    'client number',
    'client number:',
    'buyer id',
    'buyer id:',
    'account id',
    'account id:',
    'account number',
    'account number:',
    'account code',
    'account code:',
    'member id',
    'member id:',
    'customer ref',
    'customer ref:',
  ],

  customerName: [
    'customer name',
    'customer name:',
    'customer',
    'customer:',
    'client name',
    'client name:',
    'client',
    'client:',
    'buyer name',
    'buyer name:',
    'buyer',
    'buyer:',
    'account name',
    'account name:',
    'sold to',
    'sold to:',
    'bill to',
    'bill to:',
    'billed to',
    'billed to:',
    'ship to',
    'ship to:',
    'recipient',
    'recipient:',
    'recipient name',
    'recipient name:',
    'customer details',
    'customer details:',
  ],

  customerNumber: [
    'customer number',
    'customer number:',
    'customer no',
    'customer no.',
    'customer no:',
    'customer #',
    'customer #:',
    'customer id',
    'customer id:',
    'client number',
    'client number:',
    'client no',
    'client no:',
    'account number',
    'account number:',
    'buyer number',
    'buyer number:',
    'customer ref no',
    'customer ref no:',
    'cust no',
    'cust no:',
  ],

  customerCode: [
    'customer code',
    'customer code:',
    'customer id',
    'customer id:',
    'customer ref',
    'customer ref:',
    'customer reference',
    'customer reference:',
    'client code',
    'client code:',
    'account code',
    'account code:',
    'buyer code',
    'buyer code:',
    'customer key',
    'customer key:',
    'cust code',
    'cust code:',
  ],

  customerReference: [
    'customer reference',
    'customer reference:',
    'customer ref',
    'customer ref:',
    'customer ref.',
    'customer ref.:',
    'customer reference number',
    'customer reference number:',
    'buyer reference',
    'buyer reference:',
    'buyer ref',
    'buyer ref:',
    'client reference',
    'client reference:',
    'client ref',
    'client ref:',
    'account reference',
    'account reference:',
    'reference',
    'reference:',
    'ref no',
    'ref no:',
  ],

  buyerName: [
    'buyer name',
    'buyer name:',
    'buyer',
    'buyer:',
    'purchaser',
    'purchaser:',
    'purchased by',
    'purchased by:',
    'customer name',
    'customer name:',
    'customer',
    'customer:',
    'client name',
    'client name:',
    'ordered by',
    'ordered by:',
    'payer name',
    'payer name:',
    'billing name',
    'billing name:',
  ],

  buyerId: [
    'buyer id',
    'buyer id:',
    'buyer identifier',
    'buyer identifier:',
    'buyer no',
    'buyer no.',
    'buyer no:',
    'buyer #',
    'buyer #:',
    'buyer number',
    'buyer number:',
    'buyer code',
    'buyer code:',
    'purchaser id',
    'purchaser id:',
    'customer id',
    'customer id:',
    'client id',
    'client id:',
  ],

  shipperId: [
    'shipper id',
    'shipper id:',
    'shipper identifier',
    'shipper identifier:',
    'shipper no',
    'shipper no.',
    'shipper no:',
    'shipper #',
    'shipper #:',
    'shipper number',
    'shipper number:',
    'shipper code',
    'shipper code:',
    'carrier id',
    'carrier id:',
    'carrier number',
    'carrier number:',
    'courier id',
    'courier id:',
    'delivery provider id',
    'delivery provider id:',
  ],

  shipperName: [
    'shipper name',
    'shipper name:',
    'shipper',
    'shipper:',
    'shipping company',
    'shipping company:',
    'carrier name',
    'carrier name:',
    'carrier',
    'carrier:',
    'courier name',
    'courier name:',
    'courier',
    'courier:',
    'delivery provider',
    'delivery provider:',
    'delivery company',
    'delivery company:',
    'transport company',
    'transport company:',
  ],

  shipperCode: [
    'shipper code',
    'shipper code:',
    'shipper id',
    'shipper id:',
    'shipper ref',
    'shipper ref:',
    'shipper reference',
    'shipper reference:',
    'carrier code',
    'carrier code:',
    'carrier id',
    'carrier id:',
    'courier code',
    'courier code:',
    'delivery code',
    'delivery code:',
    'shipper key',
    'shipper key:',
  ],

  carrier: [
    'carrier',
    'carrier:',
    'shipping carrier',
    'shipping carrier:',
    'freight carrier',
    'freight carrier:',
    'transport carrier',
    'transport carrier:',
    'delivery carrier',
    'delivery carrier:',
    'shipper',
    'shipper:',
    'courier',
    'courier:',
    'service provider',
    'service provider:',
    'transport company',
    'transport company:',
  ],

  carrierName: [
    'carrier name',
    'carrier name:',
    'carrier',
    'carrier:',
    'shipping carrier',
    'shipping carrier:',
    'freight carrier',
    'freight carrier:',
    'logistics provider',
    'logistics provider:',
    'transport company',
    'transport company:',
    'delivery company',
    'delivery company:',
    'shipper name',
    'shipper name:',
    'courier name',
    'courier name:',
  ],

  carrierCode: [
    'carrier code',
    'carrier code:',
    'carrier id',
    'carrier id:',
    'carrier no',
    'carrier no.',
    'carrier no:',
    'carrier #',
    'carrier #:',
    'carrier number',
    'carrier number:',
    'shipping code',
    'shipping code:',
    'logistics code',
    'logistics code:',
    'transport code',
    'transport code:',
    'shipper code',
    'shipper code:',
  ],

  deliveryProvider: [
    'delivery provider',
    'delivery provider:',
    'provider',
    'provider:',
    'service provider',
    'service provider:',
    'shipping provider',
    'shipping provider:',
    'fulfillment provider',
    'fulfillment provider:',
    'delivery service',
    'delivery service:',
    'carrier',
    'carrier:',
    'courier',
    'courier:',
    'shipper',
    'shipper:',
  ],

  courier: [
    'courier',
    'courier:',
    'courier service',
    'courier service:',
    'delivery courier',
    'delivery courier:',
    'express courier',
    'express courier:',
    'messenger',
    'messenger:',
    'delivery service',
    'delivery service:',
    'carrier',
    'carrier:',
    'shipper',
    'shipper:',
  ],

  courierName: [
    'courier name',
    'courier name:',
    'courier',
    'courier:',
    'courier service',
    'courier service:',
    'delivery courier',
    'delivery courier:',
    'messenger name',
    'messenger name:',
    'carrier name',
    'carrier name:',
    'shipper name',
    'shipper name:',
    'delivery company',
    'delivery company:',
  ],

  employeeName: [
    'employee name',
    'employee name:',
    'employee',
    'employee:',
    'staff name',
    'staff name:',
    'staff',
    'staff:',
    'handled by',
    'handled by:',
    'processed by',
    'processed by:',
    'served by',
    'served by:',
    'attended by',
    'attended by:',
    'operator name',
    'operator name:',
    'cashier name',
    'cashier name:',
    'salesperson name',
    'salesperson name:',
  ],

  salesperson: [
    'salesperson',
    'salesperson:',
    'sales person',
    'sales person:',
    'sales rep',
    'sales rep:',
    'sales representative',
    'sales representative:',
    'sales agent',
    'sales agent:',
    'sold by',
    'sold by:',
    'handled by',
    'handled by:',
    'served by',
    'served by:',
    'staff',
    'staff:',
    'associate',
    'associate:',
  ],

  salespersonId: [
    'salesperson id',
    'salesperson id:',
    'sales person id',
    'sales person id:',
    'sales rep id',
    'sales rep id:',
    'sales representative id',
    'sales representative id:',
    'salesperson no',
    'salesperson no.',
    'salesperson no:',
    'salesperson #',
    'salesperson #:',
    'staff id',
    'staff id:',
    'associate id',
    'associate id:',
    'employee id',
    'employee id:',
  ],

  salespersonReference: [
    'salesperson reference',
    'salesperson reference:',
    'salesperson ref',
    'salesperson ref:',
    'salesperson ref.',
    'salesperson ref.:',
    'sales rep reference',
    'sales rep reference:',
    'sales rep ref',
    'sales rep ref:',
    'sales reference',
    'sales reference:',
    'sales ref',
    'sales ref:',
    'associate reference',
    'associate reference:',
    'staff reference',
    'staff reference:',
    'sales code',
    'sales code:',
  ],

  // POS / cashier / terminal / operator context

  cashier: [
    'cashier',
    'cashier:',
    'cashier name',
    'cashier name:',
    'cashier id',
    'cashier id:',
    'cashier no',
    'cashier no.',
    'cashier no:',
    'cashier #',
    'cashier #:',
    'served by',
    'served by:',
    'handled by',
    'handled by:',
    'processed by',
    'processed by:',
    'operator',
    'operator:',
    'operator cashier',
    'operator cashier:',
    'cashier code',
    'cashier code:',
    'counter staff',
    'counter staff:',
  ],

  cashierName: [
    'cashier name',
    'cashier name:',
    'cashier',
    'cashier:',
    'cashier staff',
    'cashier staff:',
    'served by',
    'served by:',
    'handled by',
    'handled by:',
    'processed by',
    'processed by:',
    'counter staff',
    'counter staff:',
    'operator name',
    'operator name:',
    'clerk name',
    'clerk name:',
  ],

  cashierId: [
    'cashier id',
    'cashier id:',
    'cashier identifier',
    'cashier identifier:',
    'cashier code',
    'cashier code:',
    'cashier ref',
    'cashier ref:',
    'cashier no',
    'cashier no.',
    'cashier no:',
    'cashier #',
    'cashier #:',
    'cashier number',
    'cashier number:',
    'staff id',
    'staff id:',
    'employee id',
    'employee id:',
  ],

  cashierNumber: [
    'cashier number',
    'cashier number:',
    'cashier no',
    'cashier no.',
    'cashier no:',
    'cashier #',
    'cashier #:',
    'cashier id',
    'cashier id:',
    'cashier code',
    'cashier code:',
    'cashier ref',
    'cashier ref:',
    'staff number',
    'staff number:',
    'employee number',
    'employee number:',
  ],

  operator: [
    'operator',
    'operator:',
    'operator name',
    'operator name:',
    'operator id',
    'operator id:',
    'operator no',
    'operator no.',
    'operator no:',
    'operator #',
    'operator #:',
    'operated by',
    'operated by:',
    'processed by',
    'processed by:',
    'cashier',
    'cashier:',
    'terminal operator',
    'terminal operator:',
    'pos operator',
    'pos operator:',
  ],

  operatorName: [
    'operator name',
    'operator name:',
    'operator',
    'operator:',
    'operated by',
    'operated by:',
    'pos operator',
    'pos operator:',
    'terminal operator',
    'terminal operator:',
    'cashier name',
    'cashier name:',
    'staff name',
    'staff name:',
    'employee name',
    'employee name:',
  ],

  operatorId: [
    'operator id',
    'operator id:',
    'operator identifier',
    'operator identifier:',
    'operator code',
    'operator code:',
    'operator ref',
    'operator ref:',
    'operator no',
    'operator no.',
    'operator no:',
    'operator #',
    'operator #:',
    'operator number',
    'operator number:',
    'cashier id',
    'cashier id:',
    'staff id',
    'staff id:',
  ],

  operatorNumber: [
    'operator number',
    'operator number:',
    'operator no',
    'operator no.',
    'operator no:',
    'operator #',
    'operator #:',
    'operator id',
    'operator id:',
    'operator code',
    'operator code:',
    'operator ref',
    'operator ref:',
    'cashier number',
    'cashier number:',
    'staff number',
    'staff number:',
  ],

  clerk: [
    'clerk',
    'clerk:',
    'clerk name',
    'clerk name:',
    'sales clerk',
    'sales clerk:',
    'store clerk',
    'store clerk:',
    'desk clerk',
    'desk clerk:',
    'attended by',
    'attended by:',
    'processed by',
    'processed by:',
    'cashier',
    'cashier:',
    'staff',
    'staff:',
  ],

  clerkId: [
    'clerk id',
    'clerk id:',
    'clerk identifier',
    'clerk identifier:',
    'clerk code',
    'clerk code:',
    'clerk ref',
    'clerk ref:',
    'clerk no',
    'clerk no.',
    'clerk no:',
    'clerk #',
    'clerk #:',
    'clerk number',
    'clerk number:',
    'staff id',
    'staff id:',
  ],

  clerkNumber: [
    'clerk number',
    'clerk number:',
    'clerk no',
    'clerk no.',
    'clerk no:',
    'clerk #',
    'clerk #:',
    'clerk id',
    'clerk id:',
    'clerk code',
    'clerk code:',
    'staff number',
    'staff number:',
    'employee number',
    'employee number:',
  ],

  server: [
    'server',
    'server:',
    'server name',
    'server name:',
    'server #',
    'server #:',
    'server no',
    'server no.',
    'server no:',
    'served by',
    'served by:',
    'waitstaff',
    'waitstaff:',
    'host',
    'host:',
    'service staff',
    'service staff:',
    'table server',
    'table server:',
  ],

  serverName: [
    'server name',
    'server name:',
    'server',
    'server:',
    'served by',
    'served by:',
    'waitstaff',
    'waitstaff:',
    'service staff',
    'service staff:',
    'table server',
    'table server:',
    'attendant',
    'attendant:',
    'host',
    'host:',
  ],

  serverId: [
    'server id',
    'server id:',
    'server identifier',
    'server identifier:',
    'server code',
    'server code:',
    'server ref',
    'server ref:',
    'server no',
    'server no.',
    'server no:',
    'server #',
    'server #:',
    'server number',
    'server number:',
    'staff id',
    'staff id:',
  ],

  serverNumber: [
    'server number',
    'server number:',
    'server no',
    'server no.',
    'server no:',
    'server #',
    'server #:',
    'server id',
    'server id:',
    'server code',
    'server code:',
    'server ref',
    'server ref:',
    'staff number',
    'staff number:',
  ],

  waiter: [
    'waiter',
    'waiter:',
    'server',
    'server:',
    'served by',
    'served by:',
    'attendant',
    'attendant:',
    'service staff',
    'service staff:',
    'table attendant',
    'table attendant:',
    'host',
    'host:',
  ],

  waitress: [
    'waitress',
    'waitress:',
    'server',
    'server:',
    'served by',
    'served by:',
    'attendant',
    'attendant:',
    'service staff',
    'service staff:',
    'table attendant',
    'table attendant:',
    'host',
    'host:',
  ],

  register: [
    'register',
    'register:',
    'reg',
    'reg:',
    'register no',
    'register no.',
    'register no:',
    'register #',
    'register #:',
    'cash register',
    'cash register:',
    'till',
    'till:',
    'pos register',
    'pos register:',
    'lane register',
    'lane register:',
  ],

  registerNumber: [
    'register number',
    'register number:',
    'register no',
    'register no.',
    'register no:',
    'register #',
    'register #:',
    'reg number',
    'reg number:',
    'reg no',
    'reg no.',
    'reg no:',
    'cash register no',
    'cash register no:',
    'till number',
    'till number:',
    'pos register no',
    'pos register no:',
  ],

  registerId: [
    'register id',
    'register id:',
    'register identifier',
    'register identifier:',
    'register code',
    'register code:',
    'register ref',
    'register ref:',
    'reg id',
    'reg id:',
    'reg code',
    'reg code:',
    'cash register id',
    'cash register id:',
    'till id',
    'till id:',
  ],

  registerLabel: [
    'register label',
    'register label:',
    'register',
    'register:',
    'reg',
    'reg:',
    'lane label',
    'lane label:',
    'till label',
    'till label:',
    'counter label',
    'counter label:',
    'pos label',
    'pos label:',
  ],

  regNumber: [
    'reg number',
    'reg number:',
    'reg no',
    'reg no.',
    'reg no:',
    'reg #',
    'reg #:',
    'register number',
    'register number:',
    'register no',
    'register no:',
    'register #',
    'register #:',
    'registration number',
    'registration number:',
  ],

  terminalNumber: [
    'terminal number',
    'terminal number:',
    'terminal no',
    'terminal no.',
    'terminal no:',
    'terminal #',
    'terminal #:',
    'term no',
    'term no.',
    'term no:',
    'term #',
    'term #:',
    'pos terminal number',
    'pos terminal number:',
    'device number',
    'device number:',
  ],

  terminalId: [
    'terminal id',
    'terminal id:',
    'terminal identifier',
    'terminal identifier:',
    'terminal code',
    'terminal code:',
    'terminal ref',
    'terminal ref:',
    'term id',
    'term id:',
    'pos terminal id',
    'pos terminal id:',
    'device id',
    'device id:',
  ],

  terminalCode: [
    'terminal code',
    'terminal code:',
    'terminal id',
    'terminal id:',
    'terminal ref',
    'terminal ref:',
    'term code',
    'term code:',
    'pos terminal code',
    'pos terminal code:',
    'machine code',
    'machine code:',
    'device code',
    'device code:',
  ],

  posId: [
    'pos id',
    'pos id:',
    'p.o.s. id',
    'p.o.s. id:',
    'pos identifier',
    'pos identifier:',
    'point of sale id',
    'point of sale id:',
    'pos code',
    'pos code:',
    'pos ref',
    'pos ref:',
    'pos terminal id',
    'pos terminal id:',
  ],

  posLocation: [
    'pos location',
    'pos location:',
    'point of sale location',
    'point of sale location:',
    'pos loc',
    'pos loc:',
    'terminal location',
    'terminal location:',
    'register location',
    'register location:',
    'counter location',
    'counter location:',
    'location',
    'location:',
  ],

  posNumber: [
    'pos number',
    'pos number:',
    'pos no',
    'pos no.',
    'pos no:',
    'pos #',
    'pos #:',
    'point of sale number',
    'point of sale number:',
    'pos terminal number',
    'pos terminal number:',
    'terminal number',
    'terminal number:',
  ],

  station: [
    'station',
    'station:',
    'station no',
    'station no.',
    'station no:',
    'station #',
    'station #:',
    'station name',
    'station name:',
    'service station',
    'service station:',
    'workstation',
    'workstation:',
    'prep station',
    'prep station:',
    'pos station',
    'pos station:',
  ],

  stationId: [
    'station id',
    'station id:',
    'station identifier',
    'station identifier:',
    'station code',
    'station code:',
    'station ref',
    'station ref:',
    'station no',
    'station no.',
    'station no:',
    'station #',
    'station #:',
    'workstation id',
    'workstation id:',
  ],

  stationNumber: [
    'station number',
    'station number:',
    'station no',
    'station no.',
    'station no:',
    'station #',
    'station #:',
    'station id',
    'station id:',
    'workstation number',
    'workstation number:',
    'service station no',
    'service station no:',
  ],

  stationName: [
    'station name',
    'station name:',
    'station',
    'station:',
    'workstation name',
    'workstation name:',
    'service station name',
    'service station name:',
    'prep station name',
    'prep station name:',
    'counter station',
    'counter station:',
  ],

  machineNumber: [
    'machine number',
    'machine number:',
    'machine no',
    'machine no.',
    'machine no:',
    'machine #',
    'machine #:',
    'machine id',
    'machine id:',
    'device number',
    'device number:',
    'equipment number',
    'equipment number:',
    'terminal number',
    'terminal number:',
  ],

  machineId: [
    'machine id',
    'machine id:',
    'machine identifier',
    'machine identifier:',
    'machine code',
    'machine code:',
    'machine ref',
    'machine ref:',
    'device id',
    'device id:',
    'equipment id',
    'equipment id:',
    'terminal id',
    'terminal id:',
  ],

  counter: [
    'counter',
    'counter:',
    'sales counter',
    'sales counter:',
    'service counter',
    'service counter:',
    'checkout counter',
    'checkout counter:',
    'counter no',
    'counter no.',
    'counter no:',
    'counter #',
    'counter #:',
    'counter name',
    'counter name:',
  ],

  counterLabel: [
    'counter label',
    'counter label:',
    'counter',
    'counter:',
    'counter name',
    'counter name:',
    'counter tag',
    'counter tag:',
    'counter identifier',
    'counter identifier:',
    'lane label',
    'lane label:',
    'desk label',
    'desk label:',
  ],

  laneNumber: [
    'lane number',
    'lane number:',
    'lane no',
    'lane no.',
    'lane no:',
    'lane #',
    'lane #:',
    'checkout lane',
    'checkout lane:',
    'pos lane',
    'pos lane:',
    'lane id',
    'lane id:',
  ],

  laneId: [
    'lane id',
    'lane id:',
    'lane identifier',
    'lane identifier:',
    'lane code',
    'lane code:',
    'lane ref',
    'lane ref:',
    'checkout lane id',
    'checkout lane id:',
    'lane number',
    'lane number:',
  ],

  tillNumber: [
    'till number',
    'till number:',
    'till no',
    'till no.',
    'till no:',
    'till #',
    'till #:',
    'cash till number',
    'cash till number:',
    'drawer number',
    'drawer number:',
    'register number',
    'register number:',
  ],

  tillId: [
    'till id',
    'till id:',
    'till identifier',
    'till identifier:',
    'till code',
    'till code:',
    'till ref',
    'till ref:',
    'cash till id',
    'cash till id:',
    'register id',
    'register id:',
  ],

  drawerNumber: [
    'drawer number',
    'drawer number:',
    'drawer no',
    'drawer no.',
    'drawer no:',
    'drawer #',
    'drawer #:',
    'cash drawer number',
    'cash drawer number:',
    'drawer id',
    'drawer id:',
    'till drawer number',
    'till drawer number:',
  ],

  device: [
    'device',
    'device:',
    'device name',
    'device name:',
    'device id',
    'device id:',
    'device no',
    'device no.',
    'device no:',
    'device #',
    'device #:',
    'terminal',
    'terminal:',
    'machine',
    'machine:',
    'equipment',
    'equipment:',
    'handheld',
    'handheld:',
  ],

  deviceNumber: [
    'device number',
    'device number:',
    'device no',
    'device no.',
    'device no:',
    'device #',
    'device #:',
    'device id',
    'device id:',
    'terminal number',
    'terminal number:',
    'machine number',
    'machine number:',
    'equipment number',
    'equipment number:',
  ],

  shift: [
    'shift',
    'shift:',
    'shift name',
    'shift name:',
    'work shift',
    'work shift:',
    'sales shift',
    'sales shift:',
    'cashier shift',
    'cashier shift:',
    'operator shift',
    'operator shift:',
    'session shift',
    'session shift:',
  ],

  shiftNumber: [
    'shift number',
    'shift number:',
    'shift no',
    'shift no.',
    'shift no:',
    'shift #',
    'shift #:',
    'shift id',
    'shift id:',
    'work shift no',
    'work shift no:',
    'cashier shift no',
    'cashier shift no:',
  ],

  sessionId: [
    'session id',
    'session id:',
    'session identifier',
    'session identifier:',
    'session code',
    'session code:',
    'session ref',
    'session ref:',
    'login session id',
    'login session id:',
    'pos session id',
    'pos session id:',
    'operator session id',
    'operator session id:',
  ],

  sessionNumber: [
    'session number',
    'session number:',
    'session no',
    'session no.',
    'session no:',
    'session #',
    'session #:',
    'session id',
    'session id:',
    'pos session number',
    'pos session number:',
    'work session number',
    'work session number:',
  ],

  // Time / date fields

  date: [
    'date',
    'date:',
    'transaction date',
    'transaction date:',
    'sale date',
    'sale date:',
    'purchase date',
    'purchase date:',
    'order date',
    'order date:',
    'invoice date',
    'invoice date:',
    'receipt date',
    'receipt date:',
    'document date',
    'document date:',
    'billing date',
    'billing date:',
    'posting date',
    'posting date:',
    'issue date',
    'issue date:',
    'issued on',
    'issued on:',
    'created on',
    'created on:',
    'dated',
    'dated:',
  ],

  time: [
    'time',
    'time:',
    'transaction time',
    'transaction time:',
    'sale time',
    'sale time:',
    'purchase time',
    'purchase time:',
    'order time',
    'order time:',
    'invoice time',
    'invoice time:',
    'receipt time',
    'receipt time:',
    'document time',
    'document time:',
    'billing time',
    'billing time:',
    'posted at',
    'posted at:',
    'created at',
    'created at:',
    'issued at',
    'issued at:',
    'hour',
    'hour:',
  ],

  dateTime: [
    'date/time',
    'date/time:',
    'date & time',
    'date & time:',
    'date and time',
    'date and time:',
    'transaction date/time',
    'transaction date/time:',
    'transaction datetime',
    'transaction datetime:',
    'sale date/time',
    'sale date/time:',
    'purchase date/time',
    'purchase date/time:',
    'order date/time',
    'order date/time:',
    'invoice date/time',
    'invoice date/time:',
    'receipt date/time',
    'receipt date/time:',
    'created at',
    'created at:',
    'timestamp',
    'timestamp:',
    'date time',
    'date time:',
  ],

  businessDate: [
    'business date',
    'business date:',
    'trading date',
    'trading date:',
    'store date',
    'store date:',
    'operating date',
    'operating date:',
    'work date',
    'work date:',
    'accounting date',
    'accounting date:',
    'ledger date',
    'ledger date:',
    'posting date',
    'posting date:',
    'service date',
    'service date:',
    'terminal date',
    'terminal date:',
  ],

  businessTime: [
    'business time',
    'business time:',
    'trading time',
    'trading time:',
    'store time',
    'store time:',
    'operating time',
    'operating time:',
    'work time',
    'work time:',
    'accounting time',
    'accounting time:',
    'posting time',
    'posting time:',
    'service time',
    'service time:',
    'terminal time',
    'terminal time:',
  ],

  openedTime: [
    'opened time',
    'opened time:',
    'opened at',
    'opened at:',
    'check opened',
    'check opened:',
    'opened',
    'opened:',
    'start time',
    'start time:',
    'started at',
    'started at:',
    'order opened',
    'order opened:',
    'ticket opened',
    'ticket opened:',
    'table opened',
    'table opened:',
    'session opened',
    'session opened:',
  ],

  openedAt: [
    'opened at',
    'opened at:',
    'opened time',
    'opened time:',
    'opened',
    'opened:',
    'start at',
    'start at:',
    'started at',
    'started at:',
    'created at',
    'created at:',
    'check opened at',
    'check opened at:',
    'order opened at',
    'order opened at:',
    'ticket opened at',
    'ticket opened at:',
  ],

  closedTime: [
    'closed time',
    'closed time:',
    'closed at',
    'closed at:',
    'closed',
    'closed:',
    'end time',
    'end time:',
    'ended at',
    'ended at:',
    'completed at',
    'completed at:',
    'check closed',
    'check closed:',
    'order closed',
    'order closed:',
    'ticket closed',
    'ticket closed:',
    'session closed',
    'session closed:',
  ],

  closedAt: [
    'closed at',
    'closed at:',
    'closed time',
    'closed time:',
    'closed',
    'closed:',
    'ended at',
    'ended at:',
    'end at',
    'end at:',
    'completed at',
    'completed at:',
    'finalized at',
    'finalized at:',
    'settled at',
    'settled at:',
    'check closed at',
    'check closed at:',
  ],

  printedTime: [
    'printed time',
    'printed time:',
    'print time',
    'print time:',
    'printed at',
    'printed at:',
    'reprint time',
    'reprint time:',
    'copy printed at',
    'copy printed at:',
    'printed',
    'printed:',
    'receipt printed time',
    'receipt printed time:',
    'print timestamp',
    'print timestamp:',
  ],

  printTime: [
    'print time',
    'print time:',
    'printed time',
    'printed time:',
    'printed at',
    'printed at:',
    'receipt print time',
    'receipt print time:',
    'invoice print time',
    'invoice print time:',
    'copy time',
    'copy time:',
    'output time',
    'output time:',
  ],

  printDate: [
    'print date',
    'print date:',
    'printed date',
    'printed date:',
    'date printed',
    'date printed:',
    'receipt print date',
    'receipt print date:',
    'invoice print date',
    'invoice print date:',
    'copy date',
    'copy date:',
    'reprint date',
    'reprint date:',
  ],

  settlementTime: [
    'settlement time',
    'settlement time:',
    'settled at',
    'settled at:',
    'settled time',
    'settled time:',
    'payment settled at',
    'payment settled at:',
    'settlement timestamp',
    'settlement timestamp:',
    'batch close time',
    'batch close time:',
    'closing time',
    'closing time:',
    'finalized time',
    'finalized time:',
  ],

  serviceDate: [
    'service date',
    'service date:',
    'date of service',
    'date of service:',
    'served on',
    'served on:',
    'service day',
    'service day:',
    'visit date',
    'visit date:',
    'appointment date',
    'appointment date:',
    'meal date',
    'meal date:',
    'check date',
    'check date:',
  ],

  dueDate: [
    'due date',
    'due date:',
    'payment due date',
    'payment due date:',
    'payment due',
    'payment due:',
    'amount due by',
    'amount due by:',
    'pay by',
    'pay by:',
    'pay before',
    'pay before:',
    'pay on or before',
    'pay on or before:',
    'due on',
    'due on:',
    'date due',
    'date due:',
    'deadline',
    'deadline:',
  ],

  shippedDate: [
    'shipped date',
    'shipped date:',
    'ship date',
    'ship date:',
    'date shipped',
    'date shipped:',
    'shipping date',
    'shipping date:',
    'shipment date',
    'shipment date:',
    'dispatch date',
    'dispatch date:',
    'dispatched on',
    'dispatched on:',
    'fulfilled on',
    'fulfilled on:',
    'sent on',
    'sent on:',
  ],

  deliveryDate: [
    'delivery date',
    'delivery date:',
    'delivered date',
    'delivered date:',
    'date delivered',
    'date delivered:',
    'delivery day',
    'delivery day:',
    'estimated delivery date',
    'estimated delivery date:',
    'expected delivery date',
    'expected delivery date:',
    'arrival date',
    'arrival date:',
    'received date',
    'received date:',
    'date received',
    'date received:',
  ],

  // Service mode / venue context

  serviceMode: [],
  serviceTypeLabel: [],
  orderType: [],
  diningMode: [],
  dineIn: [],
  takeAway: [],
  takeaway: [],
  takeOut: [],
  eatIn: [],
  walkIn: [],
  onlineOrder: [],
  onlineStatus: [],
  pickup: [],
  curbsidePickup: [],
  deliveryMode: [],
  channel: [],
  salesChannel: [],
  sourcePlatform: [],
  diningRoom: [],
  section: [],
  room: [],
  area: [],
  table: [],
  tableNumber: [],
  tableName: [],
  seat: [],
  seatNumber: [],
  guestCount: [],
  guestNumber: [],
  guests: [],
  partySize: [],
  covers: [],
  pax: [],
  personNumber: [],
  guestReference: [],
  orderNote: [],
  note: [],
  remarks: [],

  // Payment / tender / card / settlement

  paymentMode: [],
  paymentTender: [],
  paymentProvider: [],
  tenderType: [],
  tenderedAmount: [],
  paidAmount: [],
  totalPaid: [],
  amountPaid: [],
  paymentAmount: [],
  amountReceived: [],
  received: [],
  receivedAmount: [],
  balanceDue: [],
  cashTendered: [],
  cashReceived: [],
  cash: [],
  change: [],
  changeDue: [],
  voucherAmount: [],
  chequeAmount: [],
  debitAmount: [],
  debitCardAmount: [],
  creditAmount: [],
  creditCardAmount: [],
  cardAmount: [],
  cardType: [],
  cardBrand: [],
  cardScheme: [],
  paymentCardNetwork: [],
  accountTailDigits: [],
  cardLast4: [],
  maskedPan: [],
  rrn: [],
  aid: [],
  entryMethod: [],
  tip: [],
  gratuity: [],
  suggestedGratuity: [],
  serviceCharge: [],

  // Totals / money / adjustments

  subtotal: [],
  subTotal: [],
  grossAmount: [],
  netAmount: [],
  grandTotal: [],
  total: [],
  finalTotal: [],
  amountDue: [],
  payable: [],
  totalAmount: [],
  totalAmountDue: [],
  totalExcludingTax: [],
  totalIncludingTax: [],
  totalExcludingGst: [],
  totalIncludingGst: [],
  totalSalesExcludingGst: [],
  totalSalesIncludingGst: [],
  totalSalesInclusive: [],
  totalSalesExclusive: [],
  minimumPayment: [],
  receivedTotal: [],
  netSales: [],
  grossSales: [],
  amountTendered: [],
  totalSaving: [],
  savings: [],
  savingAmount: [],
  discountAmount: [],
  discountSummary: [],
  lineDiscountAmount: [],
  rounding: [],
  roundAdjustment: [],
  roundingAdjustment: [],
  roundOff: [],

  // Tax fields / tax buckets

  tax: [],
  taxAmount: [],
  taxTotal: [],
  taxRate: [],
  taxPercent: [],
  taxCode: [],
  taxLabel: [],
  taxSummary: [],
  taxSummaryLabel: [],
  taxableAmount: [],
  taxIncluded: [],
  taxExcluded: [],
  gst: [],
  gstAmount: [],
  gstRate: [],
  gstPercent: [],
  gstIncluded: [],
  gstPayable: [],
  gstRegistrationId: [],
  gstSummaryAmount: [],
  gstSummaryTax: [],
  vat: [],
  vatAmount: [],
  vatRate: [],
  vatPercent: [],
  serviceTax: [],
  salesTax: [],
  foodTax: [],
  liquorTax: [],
  otherTaxes: [],
  taxBucket: [],
  taxBucketLabel: [],
  standardRatedAmount: [],
  zeroRatedAmount: [],
  reducedRatedAmount: [],
  nonTaxableAmount: [],
  inclusiveTaxAmount: [],
  exclusiveTaxAmount: [],

  // Quantity / count / measurement fields

  quantity: [],
  qty: [],
  itemCount: [],
  itemsCount: [],
  totalItems: [],
  totalItemCount: [],
  totalQuantity: [],
  totalQty: [],
  quantityUnit: [],
  unit: [],
  unitText: [],
  unitCode: [],
  unitPrice: [],
  uPrice: [],
  pricePerUnit: [],
  pricePerItem: [],
  linePrice: [],
  lineAmount: [],
  lineTotal: [],
  lineSubtotal: [],
  lineTaxAmount: [],
  basePrice: [],
  discountedPrice: [],
  priceBeforeDiscount: [],
  priceAfterDiscount: [],
  weightedQuantity: [],
  measuredQuantity: [],
  weight: [],
  weightUnit: [],
  weighedItem: [],
  volume: [],
  volumeUnit: [],
  litres: [],
  liters: [],
  pricePerKg: [],
  pricePerLb: [],
  pricePerLitre: [],
  pricePerLiter: [],
  eligibleQuantity: [],
  referenceQuantity: [],
  referenceUnit: [],
  minPrice: [],
  maxPrice: [],
  currencySymbol: [],

  // Item / line item / product detail

  itemCode: [],
  itemId: [],
  itemNumber: [],
  itemName: [],
  itemDescription: [],
  itemVariant: [],
  itemModifier: [],
  itemCategory: [],
  itemGroup: [],
  itemEntityType: [],
  itemLabel: [],
  barcode: [],
  plu: [],
  stockCode: [],
  catalogCode: [],
  productCode: [],
  productId: [],
  productName: [],
  productDescription: [],
  productLabel: [],
  menuItemName: [],
  serviceName: [],
  modifierText: [],
  modifierPrice: [],
  modifierGroup: [],
  size: [],
  color: [],
  flavor: [],
  modelNumber: [],
  batchNumber: [],
  lotNumber: [],
  serialCode: [],
  comboName: [],
  comboComponent: [],
  bundleLabel: [],
  bundleName: [],
  includedItem: [],
  addOnItem: [],
  complimentary: [],
  isFreeItem: [],
  freeItem: [],
  discountPercent: [],
  lineNote: [],

  // Fuel / weighed goods / specialty receipt fields

  pumpNumber: [],
  pumpId: [],
  nozzleNumber: [],
  fuelType: [],
  fuelGrade: [],
  octane: [],
  odometer: [],
  mileage: [],

  // Shipping / fulfillment / logistics

  shipmentNumber: [],
  shipmentId: [],
  shippingMethod: [],
  shippingMode: [],
  shippingCost: [],
  shippingFee: [],
  handlingFee: [],
  dispatchDate: [],
  expectedDeliveryDate: [],
  expectedShipDate: [],
  pickupDate: [],
  pickupTime: [],

  // Misc document content commonly seen on receipts / orders

  receiptType: [],
  documentType: [],
  copyType: [],
  customerCopy: [],
  merchantCopy: [],
  footerNote: [],
  headerNote: [],
  policyNote: [],
  refundPolicy: [],
  exchangePolicy: [],
  returnPolicy: [],
  promotionalMessage: [],
  campaignMessage: [],
  surveyMessage: [],
  surveyUrl: [],
  onlineOrderUrl: [],
  paymentLink: [],
  qrCodeValue: [],
  barcodeValue: [],
  couponCode: [],
  promoCode: [],
  promoDescription: [],
  branchTelephone: [],
  contactEmail: [],
  websiteUrl: [],
  socialPage: [],
  manager: [],
  managerName: [],
  attendant: [],
  attendantName: [],
  clerkName: [],
  openedBy: [],
  closedBy: [],
  preparedBy: [],
  fulfilledBy: [],
  servedBy: [],

  // High-level flat business info that still appears on orders

  merchantType: [],
  storeType: [],
  businessType: [],
  receiptLanguage: [],
  locale: [],
  regionCode: [],
  countryName: [],
}
