export default {
  // Core order / document identity

  acceptedOffer: [
    'Wireless Mouse',
    'USB-C Cable',
    'HDMI Adapter',
    'Laptop Stand',
    'Mechanical Keyboard',
    'Noise Cancelling Headphones',
    '27-inch Monitor',
    'Webcam',
    'Portable SSD',
    'External Hard Drive',
    'Phone Charger',
    'Power Bank',
    'Bluetooth Speaker',
    'Smart Watch',
    'Tablet Case',
    'Screen Protector',
    'Gaming Mouse Pad',
    'Ethernet Cable',
    'Router',
    'Wi-Fi Extender',
    'Printer Ink Cartridge',
    'Printer Paper',
    'Desk Lamp',
    'Office Chair',
    'Standing Desk',
    'Notebook Set',
    'Ballpoint Pen Pack',
    'Stapler',
    'Paper Clips',
    'Sticky Notes',
    'Backpack',
    'Laptop Sleeve',
    'Travel Mug',
    'Water Bottle',
    'Coffee Beans',
    'Green Tea Pack',
    'Organic Honey',
    'Protein Powder',
    'Vitamin C Tablets',
    'Daily Multivitamin',
    'Hand Soap',
    'Shampoo',
    'Conditioner',
    'Body Wash',
    'Face Moisturizer',
    'Sunscreen SPF 50',
    'Laundry Detergent',
    'Dish Soap',
    'Toilet Paper Pack',
    'Paper Towels',
    'Cleaning Spray',
    'Vacuum Cleaner',
    'Air Purifier Filter',
    'LED Light Bulb',
    'Batteries AA Pack',
    'Batteries AAA Pack',
    'Extension Cord',
    'Surge Protector',
    'Tool Kit',
    'Screwdriver Set',
    'Hammer',
    'Adjustable Wrench',
    'Cordless Drill',
    'Paint Brush Set',
    'Garden Hose',
    'Plant Fertilizer',
    'Flower Pot',
    'Indoor Plant',
    'Pet Food',
    'Dog Leash',
    'Cat Litter',
    'Pet Shampoo',
    'Baby Diapers',
    'Baby Wipes',
    'Infant Formula',
    'Stroller',
    'Car Seat',
    'Toy Building Blocks',
    'Board Game',
    'Puzzle Set',
    'Hardcover Notebook',
    'Sketchbook',
    'Watercolor Paint Set',
    'Yoga Mat',
    'Dumbbell Set',
    'Resistance Bands',
    'Running Shoes',
    'Hiking Backpack',
    'Camping Tent',
    'Sleeping Bag',
    'Travel Pillow',
    'Suitcase',
    'Passport Holder',
    'Gift Card',
    'Birthday Card',
    'Gift Wrap',
    'Flower Bouquet',
    'Chocolate Box',
    'Cheeseburger',
    'French Fries',
    'Chicken Nuggets',
    'Pepperoni Pizza',
    'Margherita Pizza',
    'Veggie Burger',
    'Caesar Salad',
    'Greek Salad',
    'Tomato Soup',
    'Grilled Chicken Sandwich',
    'Club Sandwich',
    'Turkey Wrap',
    'Ham and Cheese Panini',
    'Fish and Chips',
    'Chicken Alfredo Pasta',
    'Spaghetti Bolognese',
    'Mac and Cheese',
    'Beef Tacos',
    'Chicken Burrito',
    'Sushi Combo',
    'Salmon Nigiri',
    'California Roll',
    'Pad Thai',
    'Fried Rice',
    'Sweet and Sour Chicken',
    'Butter Chicken',
    'Garlic Naan',
    'Paneer Curry',
    'Falafel Wrap',
    'Hummus Plate',
    'Steak Dinner',
    'Roasted Vegetables',
    'Mashed Potatoes',
    'Breakfast Burrito',
    'Pancake Stack',
    'Waffle Combo',
    'Omelette',
    'Bacon and Eggs',
    'Avocado Toast',
    'Fruit Bowl',
    'Ice Cream Sundae',
    'Chocolate Cake Slice',
    'Blueberry Muffin',
    'Croissant',
    'Cappuccino',
    'Latte',
    'Espresso',
    'Iced Coffee',
    'Orange Juice',
    'Bottled Water',
    'Sparkling Water',
    'Soft Drink',
    'Family Meal Bundle',
    'Lunch Combo',
    'Dinner Combo',
    'Kids Meal',
    'Meal Deal',
    'Value Meal',
    'Combo Meal',
    'Add Extra Cheese',
    'Add Bacon',
    'Add Avocado',
    'Extra Sauce',
    'No Onions',
    'Large Size Upgrade',
    'Medium Size Upgrade',
    'Gift Wrapping Service',
    'Assembly Service',
    'Installation Service',
    'Express Shipping',
    'Standard Shipping',
    'Next Day Delivery',
    'Same Day Delivery',
    'Store Pickup',
    'Curbside Pickup',
    'White Glove Delivery',
    'Extended Warranty',
    'Accidental Damage Protection',
    'Premium Support',
    'Priority Support',
    'Setup Assistance',
    'Onsite Installation',
    'Remote Consultation',
    'Technical Support Session',
    'Home Cleaning Service',
    'Deep Cleaning Service',
    'Window Cleaning Service',
    'Car Wash',
    'Interior Detailing',
    'Oil Change',
    'Tire Rotation',
    'Brake Inspection',
    'Engine Diagnostic',
    'Haircut',
    'Hair Coloring',
    'Beard Trim',
    'Spa Treatment',
    'Massage Session',
    'Manicure',
    'Pedicure',
    'Dental Cleaning',
    'Eye Examination',
    'General Consultation',
    'Therapy Session',
    'Personal Training Session',
    'Yoga Class',
    'Pilates Class',
    'Swimming Lesson',
    'Music Lesson',
    'Language Course',
    'Online Workshop',
    'Webinar Access',
    'Conference Ticket',
    'VIP Pass',
    'General Admission Ticket',
    'Adult Ticket',
    'Child Ticket',
    'Student Ticket',
    'Senior Ticket',
    'Round Trip Flight',
    'One Way Flight',
    'Hotel Stay',
    'Room Reservation',
    'Car Rental',
    'Airport Transfer',
    'Travel Insurance',
    'Museum Entry',
    'Concert Ticket',
    'Cinema Ticket',
    'Theater Ticket',
    'Theme Park Pass',
    'Annual Membership',
    'Monthly Membership',
    'Basic Subscription',
    'Standard Subscription',
    'Premium Subscription',
    'Pro Subscription',
    'Enterprise Subscription',
    'Starter Plan',
    'Business Plan',
    'Team Plan',
    'Family Plan',
    'Unlimited Plan',
    'Data Add-on',
    'Cloud Storage Plan',
    'Email Hosting',
    'Domain Registration',
    'Website Hosting',
    'SSL Certificate',
    'Software License',
    'Antivirus License',
    'Productivity Suite',
    'Design Software License',
    'Developer Tool Subscription',
    'API Usage Package',
    'Compute Credits',
    'Support Retainer',
    'Consulting Package',
    'Audit Service',
    'Design Package',
    'Branding Package',
    'SEO Package',
    'Marketing Campaign Package',
    'Photography Session',
    'Video Editing Service',
    'Translation Service',
    'Copywriting Service',
    'Legal Review',
    'Accounting Service',
    'Bookkeeping Package',
    'Tax Filing Service',
    'Recruitment Service',
    'Background Check Service',
    'Security Monitoring',
    'Managed Hosting',
    'Backup Service',
    'Disaster Recovery Plan',
    'Maintenance Plan',
    'Service Contract',
    'Repair Service',
    'Replacement Part',
    'Battery Replacement',
    'Screen Replacement',
    'Inspection Fee',
    'Service Fee',
    'Handling Fee',
    'Convenience Fee',
    'Booking Fee',
    'Reservation Fee',
    'Processing Fee',
    'Membership Fee',
    'Activation Fee',
    'Cancellation Protection',
    'Late Checkout',
    'Early Check-in',
    'Seat Selection',
    'Extra Baggage',
    'Priority Boarding',
    'In-flight Meal',
    'Travel Add-on',
    'Insurance Add-on',
    'Rental Protection',
    'Fuel Service Option',
    'Roadside Assistance',
    'Subscription Renewal',
    'License Renewal',
    'Membership Renewal',
    'Upgrade to Premium',
    'Upgrade to Business',
    'Plan Upgrade',
    'Storage Upgrade',
    'Bandwidth Add-on',
    'Additional User Seat',
    'Extra Team Seat',
    'Admin Seat',
    'Viewer Seat',
    'Editor Seat',
    'Workshop Registration',
    'Training Package',
    'Certification Exam',
    'Exam Retake',
    'Course Material',
    'Study Guide',
    'Lab Access',
    'Practice Test Access',
    'eBook Download',
    'Audiobook',
    'Printed Book',
    'Magazine Subscription',
    'Newspaper Subscription',
    'Recipe Box',
    'Meal Kit',
    'Fresh Produce Box',
    'Snack Box',
    'Coffee Subscription',
    'Tea Subscription',
    'Wine Club Membership',
    'Cheese Selection Box',
    'Bakery Box',
    'Seasonal Gift Box',
    'Holiday Bundle',
    'Starter Bundle',
    'Essentials Bundle',
    'Premium Bundle',
    'Home Office Bundle',
    'Gaming Bundle',
    'Travel Bundle',
    'Wellness Bundle',
    'Beauty Bundle',
    'Baby Care Bundle',
    'Pet Care Bundle',
    'Cleaning Bundle',
    'Kitchen Bundle',
    'Bedroom Set',
    'Dining Set',
    'Sofa Set',
    'Coffee Table',
    'Bookshelf',
    'Mattress',
    'Bedsheet Set',
    'Blanket',
    'Towel Set',
    'Cookware Set',
    'Knife Set',
    'Blender',
    'Coffee Maker',
    'Air Fryer',
    'Microwave Oven',
    'Refrigerator',
    'Washing Machine',
    'Dryer',
    'Dishwasher',
    'Smart TV',
    'Streaming Device',
    'Game Console',
    'Video Game',
    'Controller',
    'VR Headset',
    'Camera Lens',
    'Tripod',
    'Memory Card',
    'Drone',
    'Smart Home Hub',
    'Smart Light',
    'Smart Plug',
    'Smart Lock',
    'Doorbell Camera',
    'Security Camera',
    'Thermostat',
    'Robot Vacuum',
    'Electric Toothbrush',
    'Hair Dryer',
    'Shaver',
    'Face Serum',
    'Lip Balm',
    'Perfume',
    'T-shirt',
    'Jeans',
    'Sneakers',
    'Jacket',
    'Winter Coat',
    'Dress Shirt',
    'Socks Pack',
    'Underwear Pack',
    'Hat',
    'Scarf',
    'Gloves',
    'Sunglasses',
    'Watch',
    'Wallet',
    'Handbag',
    'Belt',
    'Necklace',
    'Earrings',
    'Bracelet',
    'Ring',
    'Wedding Invitation Suite',
    'Event Decoration Package',
    'Catering Package',
    'Venue Booking',
    'Photography Package',
    'DJ Service',
    'Live Band Performance',
    'Floral Decoration Package',
    'Wedding Cake',
    'Party Supplies Pack',
    'Balloon Arrangement',
    'Custom Printed Banner',
    'Corporate Catering',
    'Team Lunch Package',
    'Office Snack Delivery',
    'Bulk Water Delivery',
    'Printing Service',
    'Poster Printing',
    'Business Card Printing',
    'Flyer Printing',
    'Sticker Printing',
    'Custom Merchandise',
    'Branded T-shirt',
    'Promotional Pen Set',
    'Mug Printing',
    'Embroidery Service',
    '3D Printing Service',
    'Prototype Fabrication',
    'CNC Machining Service',
    'Electronics Repair',
    'Phone Repair',
    'Laptop Repair',
    'Data Recovery Service',
    'Server Maintenance',
    'Network Installation',
    'Firewall Setup',
    'Website Design',
    'Website Development',
    'Mobile App Development',
    'UI Design Service',
    'UX Research Package',
    'Content Strategy Session',
    'Product Discovery Workshop',
    'Cloud Migration Service',
    'DevOps Setup',
    'Monitoring Setup',
    'Penetration Test',
    'Code Review Service',
    'Architecture Consultation',
    'Custom Integration',
    'CRM Setup',
    'ERP Implementation',
    'Migration Package',
    'Analytics Setup',
    'Ad Campaign Setup',
    'Social Media Management',
    'Newsletter Setup',
    'Lead Generation Package',
    'Virtual Assistant Package',
    'Customer Support Package',
    'Outbound Calling Package',
    'Answering Service',
    'Laundry Service',
    'Dry Cleaning Service',
    'Ironing Service',
    'Alteration Service',
    'Shoe Repair',
    'Key Cutting Service',
    'Locksmith Service',
    'Pest Control Service',
    'Plumbing Repair',
    'Electrical Repair',
    'Painting Service',
    'Moving Service',
    'Packing Service',
    'Storage Rental',
    'Self Storage Unit',
    'Warehouse Storage',
    'Cold Storage Service',
    'Freight Shipping',
    'Courier Delivery',
    'Messenger Service',
    'Parcel Insurance',
    'Customs Clearance Service',
    'Import Handling Service',
    'Export Documentation Service',
    'Brokerage Service',
    'Fuel Purchase',
    'Diesel Purchase',
    'Premium Gasoline',
    'Regular Unleaded',
    'Engine Oil',
    'Windshield Washer Fluid',
    'Car Battery',
    'Wiper Blades',
    'Car Accessories Kit',
    'Motorcycle Helmet',
    'Bicycle Repair Service',
    'Bike Rental',
    'Scooter Rental',
    'Boat Rental',
    'Equipment Rental',
    'Camera Rental',
    'Party Equipment Rental',
    'Projector Rental',
    'Sound System Rental',
    'Tent Rental',
    'Chair Rental',
    'Table Rental',
    'Medical Supply Kit',
    'First Aid Kit',
    'Prescription Refill',
    'OTC Medicine',
    'Bandage Pack',
    'Thermometer',
    'Blood Pressure Monitor',
    'Fitness Tracker',
    'Meal Prep Service',
    'Diet Consultation',
    'Nutrition Plan',
    'Meditation App Subscription',
    'Sleep Program Subscription',
    'Childcare Service',
    'Tutoring Session',
    'Homework Help Session',
    'Test Prep Course',
    'Driver Training Lesson',
    'Parking Pass',
    'Monthly Parking Permit',
    'Toll Pass Recharge',
    'Utility Bill Payment',
    'Internet Bill Payment',
    'Mobile Recharge',
    'Prepaid Top-up',
    'Donation',
    'Charity Contribution',
    'Deposit',
    'Security Deposit',
    'Partial Payment',
    'Final Payment',
    'Balance Payment',
    'Down Payment',
    'Installment 1',
    'Installment 2',
    'Installment 3',
    'Retainer Payment',
    'Milestone Payment',
    'Custom Order',
    'Special Order Item',
    'Pre-order Item',
    'Backorder Item',
    'Limited Edition Item',
    'Exclusive Offer',
    'Bundle Discount Offer',
    'Buy One Get One Offer',
    'Seasonal Promotion',
    'Loyalty Reward Item',
    'Member Exclusive Item',
    'Complimentary Dessert',
    'Free Gift',
    'Bonus Item',
    'Trial Subscription',
    'Introductory Plan',
    'Founders Plan',
    'Legacy Plan',
    'Beta Access',
    'Early Access Pass',
    'Reserved Seat',
    'Reserved Table',
    'Private Room Booking',
    'Catering Add-on',
    'Decoration Add-on',
    'Audio Visual Add-on',
    'Support Hours Package',
    'Consultation Hours Pack',
    'Premium Onboarding',
    'Implementation Package',
    'Migration Assistance',
    'Managed Service Package',
    'Custom Report Package',
    'Advanced Analytics Package',
    'Compliance Package',
    'Governance Package',
    'Training Credits',
    'Usage Credits',
    'Download Credits',
    'Scan Credits',
    'Token Package',
    'Compute Package',
    'Storage Package',
    'Monthly Box Subscription',
    'Annual Service Plan',
    'Prepaid Service Package',
    'Home Visit Service',
    'In-store Service',
    'Remote Service',
    'Onsite Service',
    'Emergency Service Call',
    'Weekend Service Call',
    'After Hours Service',
    'Priority Dispatch',
    'Replacement Unit',
    'Loaner Device',
    'Refurbished Device',
    'Open Box Item',
    'Certified Used Item',
    'Digital Download',
    'Downloadable Template',
    'Premium Template Pack',
    'Icon Pack',
    'Font License',
    'Plugin License',
    'Theme License',
    'Asset Pack',
    'Sound Effects Pack',
    'Video Template Pack',
    'Stock Photo Pack',
    'Illustration Pack',
    'Merchandise Pack',
    'Office Supplies Pack',
    'Starter Kit',
    'Welcome Kit',
    'Sample Pack',
    'Refill Pack',
    'Replacement Filter',
    'Refill Cartridge',
    'Subscription Box Refill',
    'Emergency Food Pack',
    'Water Filter Cartridge',
    'Air Filter Replacement',
    'Premium Roast Coffee',
    'Single Origin Coffee',
    'Loose Leaf Tea',
    'Energy Drink',
    'Sports Drink',
    'Protein Bar',
    'Granola Box',
    'Frozen Meal',
    'Fresh Salad Bowl',
    'Soup and Sandwich Combo',
    'Chicken Rice Bowl',
    'Beef Noodle Bowl',
    'Veggie Wrap Combo',
    'Party Platter',
    'Fruit Platter',
    'Cheese Platter',
    'Dessert Platter',
    'Family Pizza Deal',
    'Weekend Special',
    'Lunch Special',
    'Breakfast Combo',
    'Happy Hour Special',
    'Chef Special',
    'Seasonal Menu Item',
    'Limited Time Offer',
    'Signature Dish',
    'House Blend Coffee',
    'Premium Tea Selection',
    'Artisan Bread Loaf',
    'Gourmet Burger',
    'Handmade Pasta',
    'Roast Chicken Dinner',
    'BBQ Platter',
    'Seafood Platter',
    'Vegetarian Combo',
    'Vegan Bowl',
    'Gluten Free Meal',
    'Dairy Free Dessert',
    'Kids Activity Pack',
    'Museum Family Pass',
    'Workshop Seat',
    'Private Lesson',
    'Group Lesson',
    'Monthly Class Pass',
    'Drop-in Class',
    'Subscription Seat',
    'Workspace Access',
    'Coworking Day Pass',
    'Meeting Room Booking',
    'Conference Room Booking',
    'Virtual Office Plan',
    'Mail Handling Service',
    'Reception Service',
    'Document Scanning Service',
    'Shredding Service',
    'Archive Storage Service',
    'Proofreading Service',
    'Editing Service',
    'Resume Writing Service',
    'Portfolio Review',
    'Career Coaching Session',
    'Business Coaching Session',
    'Executive Coaching Package',
    'Mindfulness Session',
    'Telehealth Consultation',
    'Veterinary Consultation',
    'Pet Grooming Service',
    'Dog Walking Service',
    'Pet Boarding',
    'Pet Daycare',
    'Horse Riding Lesson',
    'Golf Lesson',
    'Tennis Lesson',
    'Court Booking',
    'Gym Day Pass',
    'Sauna Access',
    'Pool Access',
    'Spa Day Pass',
    'Massage Package',
    'Wellness Retreat Booking',
    'Retreat Deposit',
    'Festival Pass',
    'Exhibition Ticket',
    'Trade Show Pass',
    'Networking Event Ticket',
    'Workshop Bundle',
    'Course Bundle',
    'Product Bundle',
    'Service Bundle',
    'Starter Package',
    'Growth Package',
    'Scale Package',
    'Custom Package',
  ],
  billingAddress: [
    '[homeNumber] Baker Street, London, England, [postalCode], United Kingdom',
    '[homeNumber] Fleet Street, London, England, [postalCode], United Kingdom',
    "[homeNumber] King's Road, London, England, [postalCode], United Kingdom",
    '[homeNumber] Piccadilly, London, England, [postalCode], United Kingdom',
    '[homeNumber] Strand, London, England, [postalCode], United Kingdom',
    '[homeNumber] Abbey Road, London, England, [postalCode], United Kingdom',
    '[homeNumber] Portobello Road, London, England, [postalCode], United Kingdom',
    '[homeNumber] Carnaby Street, London, England, [postalCode], United Kingdom',
    '[homeNumber] Downshire Hill, London, England, [postalCode], United Kingdom',
    '[homeNumber] Notting Hill Gate, London, England, [postalCode], United Kingdom',
    '[homeNumber] High Street, Oxford, England, [postalCode], United Kingdom',
    '[homeNumber] Broad Street, Oxford, England, [postalCode], United Kingdom',
    '[homeNumber] Cornmarket Street, Oxford, England, [postalCode], United Kingdom',
    '[homeNumber] Merton Street, Oxford, England, [postalCode], United Kingdom',
    '[homeNumber] Princes Street, Edinburgh, Scotland, [postalCode], United Kingdom',
    '[homeNumber] George Street, Edinburgh, Scotland, [postalCode], United Kingdom',
    '[homeNumber] Royal Mile, Edinburgh, Scotland, [postalCode], United Kingdom',
    '[homeNumber] Sauchiehall Street, Glasgow, Scotland, [postalCode], United Kingdom',
    '[homeNumber] Byres Road, Glasgow, Scotland, [postalCode], United Kingdom',
    '[homeNumber] Cathedral Quarter, Belfast, Northern Ireland, [postalCode], United Kingdom',
    "[homeNumber] O'Connell Street, Dublin, Leinster, [postalCode], Ireland",
    '[homeNumber] Grafton Street, Dublin, Leinster, [postalCode], Ireland',
    '[homeNumber] Baggot Street, Dublin, Leinster, [postalCode], Ireland',
    '[homeNumber] Patrick Street, Cork, Munster, [postalCode], Ireland',
    '[homeNumber] Eyre Square, Galway, Connacht, [postalCode], Ireland',

    '[homeNumber] Main Street, Springfield, Illinois, [postalCode], United States',
    '[homeNumber] Elm Street, Dallas, Texas, [postalCode], United States',
    '[homeNumber] Oak Street, Seattle, Washington, [postalCode], United States',
    '[homeNumber] Pine Street, San Francisco, California, [postalCode], United States',
    '[homeNumber] Market Street, San Francisco, California, [postalCode], United States',
    '[homeNumber] Broadway, New York, New York, [postalCode], United States',
    '[homeNumber] Madison Avenue, New York, New York, [postalCode], United States',
    '[homeNumber] Lexington Avenue, New York, New York, [postalCode], United States',
    '[homeNumber] Fifth Avenue, New York, New York, [postalCode], United States',
    '[homeNumber] Wall Street, New York, New York, [postalCode], United States',
    '[homeNumber] Sunset Boulevard, Los Angeles, California, [postalCode], United States',
    '[homeNumber] Hollywood Boulevard, Los Angeles, California, [postalCode], United States',
    '[homeNumber] Mulholland Drive, Los Angeles, California, [postalCode], United States',
    '[homeNumber] Michigan Avenue, Chicago, Illinois, [postalCode], United States',
    '[homeNumber] Wacker Drive, Chicago, Illinois, [postalCode], United States',
    '[homeNumber] Bourbon Street, New Orleans, Louisiana, [postalCode], United States',
    '[homeNumber] Beale Street, Memphis, Tennessee, [postalCode], United States',
    '[homeNumber] Ocean Drive, Miami Beach, Florida, [postalCode], United States',
    '[homeNumber] Peachtree Street, Atlanta, Georgia, [postalCode], United States',
    '[homeNumber] Beacon Street, Boston, Massachusetts, [postalCode], United States',
    '[homeNumber] Commonwealth Avenue, Boston, Massachusetts, [postalCode], United States',
    '[homeNumber] Walnut Street, Philadelphia, Pennsylvania, [postalCode], United States',
    '[homeNumber] Canal Street, New Orleans, Louisiana, [postalCode], United States',
    '[homeNumber] Rodeo Drive, Beverly Hills, California, [postalCode], United States',
    '[homeNumber] Fremont Street, Las Vegas, Nevada, [postalCode], United States',

    '[homeNumber] King Street West, Toronto, Ontario, [postalCode], Canada',
    '[homeNumber] Queen Street West, Toronto, Ontario, [postalCode], Canada',
    '[homeNumber] Bay Street, Toronto, Ontario, [postalCode], Canada',
    '[homeNumber] Yonge Street, Toronto, Ontario, [postalCode], Canada',
    '[homeNumber] Granville Street, Vancouver, British Columbia, [postalCode], Canada',
    '[homeNumber] Robson Street, Vancouver, British Columbia, [postalCode], Canada',
    '[homeNumber] Hastings Street, Vancouver, British Columbia, [postalCode], Canada',
    '[homeNumber] Rue Sainte-Catherine, Montreal, Quebec, [postalCode], Canada',
    '[homeNumber] Sherbrooke Street, Montreal, Quebec, [postalCode], Canada',
    '[homeNumber] Saint Denis Street, Montreal, Quebec, [postalCode], Canada',
    '[homeNumber] Whyte Avenue, Edmonton, Alberta, [postalCode], Canada',
    '[homeNumber] Portage Avenue, Winnipeg, Manitoba, [postalCode], Canada',
    '[homeNumber] Spring Garden Road, Halifax, Nova Scotia, [postalCode], Canada',
    '[homeNumber] Sparks Street, Ottawa, Ontario, [postalCode], Canada',
    '[homeNumber] Jasper Avenue, Edmonton, Alberta, [postalCode], Canada',

    '[homeNumber] George Street, Sydney, New South Wales, [postalCode], Australia',
    '[homeNumber] Pitt Street, Sydney, New South Wales, [postalCode], Australia',
    '[homeNumber] Macquarie Street, Sydney, New South Wales, [postalCode], Australia',
    '[homeNumber] Collins Street, Melbourne, Victoria, [postalCode], Australia',
    '[homeNumber] Swanston Street, Melbourne, Victoria, [postalCode], Australia',
    '[homeNumber] Flinders Lane, Melbourne, Victoria, [postalCode], Australia',
    '[homeNumber] Queen Street, Brisbane, Queensland, [postalCode], Australia',
    '[homeNumber] Adelaide Street, Brisbane, Queensland, [postalCode], Australia',
    '[homeNumber] Rundle Mall, Adelaide, South Australia, [postalCode], Australia',
    '[homeNumber] Hay Street, Perth, Western Australia, [postalCode], Australia',
    '[homeNumber] Murray Street, Perth, Western Australia, [postalCode], Australia',
    '[homeNumber] Salamanca Place, Hobart, Tasmania, [postalCode], Australia',
    '[homeNumber] North Terrace, Adelaide, South Australia, [postalCode], Australia',
    '[homeNumber] St Georges Terrace, Perth, Western Australia, [postalCode], Australia',
    '[homeNumber] Queen Street, Auckland, Auckland, [postalCode], New Zealand',
    '[homeNumber] Karangahape Road, Auckland, Auckland, [postalCode], New Zealand',
    '[homeNumber] Cuba Street, Wellington, Wellington, [postalCode], New Zealand',
    '[homeNumber] Lambton Quay, Wellington, Wellington, [postalCode], New Zealand',
    '[homeNumber] Colombo Street, Christchurch, Canterbury, [postalCode], New Zealand',
    '[homeNumber] George Street, Dunedin, Otago, [postalCode], New Zealand',

    '[homeNumber] Orchard Road, Singapore, Singapore, [postalCode], Singapore',
    '[homeNumber] Raffles Place, Singapore, Singapore, [postalCode], Singapore',
    '[homeNumber] Robinson Road, Singapore, Singapore, [postalCode], Singapore',
    '[homeNumber] Shenton Way, Singapore, Singapore, [postalCode], Singapore',
    '[homeNumber] Bukit Timah Road, Singapore, Singapore, [postalCode], Singapore',
    '[homeNumber] Jalan Besar, Singapore, Singapore, [postalCode], Singapore',
    '[homeNumber] Nathan Road, Hong Kong, Hong Kong, [postalCode], Hong Kong',
    '[homeNumber] Connaught Road Central, Hong Kong, Hong Kong, [postalCode], Hong Kong',
    "[homeNumber] Queen's Road Central, Hong Kong, Hong Kong, [postalCode], Hong Kong",
    '[homeNumber] Des Voeux Road Central, Hong Kong, Hong Kong, [postalCode], Hong Kong',
    '[homeNumber] Canton Road, Hong Kong, Hong Kong, [postalCode], Hong Kong',
    '[homeNumber] Orchard Boulevard, Singapore, Singapore, [postalCode], Singapore',

    '[homeNumber] Sheikh Zayed Road, Dubai, Dubai, [postalCode], United Arab Emirates',
    '[homeNumber] Jumeirah Beach Road, Dubai, Dubai, [postalCode], United Arab Emirates',
    '[homeNumber] Al Wasl Road, Dubai, Dubai, [postalCode], United Arab Emirates',
    '[homeNumber] Khalifa Street, Abu Dhabi, Abu Dhabi, [postalCode], United Arab Emirates',
    '[homeNumber] Hamdan Street, Abu Dhabi, Abu Dhabi, [postalCode], United Arab Emirates',
    '[homeNumber] King Fahd Road, Riyadh, Riyadh Province, [postalCode], Saudi Arabia',
    '[homeNumber] Olaya Street, Riyadh, Riyadh Province, [postalCode], Saudi Arabia',
    '[homeNumber] Tahlia Street, Jeddah, Mecca Province, [postalCode], Saudi Arabia',
    '[homeNumber] Hamra Street, Beirut, Beirut, [postalCode], Lebanon',
    '[homeNumber] Bliss Street, Beirut, Beirut, [postalCode], Lebanon',
    '[homeNumber] Istiklal Avenue, Istanbul, Istanbul, [postalCode], Turkey',
    '[homeNumber] Bağdat Avenue, Istanbul, Istanbul, [postalCode], Turkey',

    '[homeNumber] MG Road, Bengaluru, Karnataka, [postalCode], India',
    '[homeNumber] Brigade Road, Bengaluru, Karnataka, [postalCode], India',
    '[homeNumber] Residency Road, Bengaluru, Karnataka, [postalCode], India',
    '[homeNumber] Anna Salai, Chennai, Tamil Nadu, [postalCode], India',
    '[homeNumber] Cathedral Road, Chennai, Tamil Nadu, [postalCode], India',
    '[homeNumber] Marine Drive, Mumbai, Maharashtra, [postalCode], India',
    '[homeNumber] Linking Road, Mumbai, Maharashtra, [postalCode], India',
    '[homeNumber] Janpath, New Delhi, Delhi, [postalCode], India',
    '[homeNumber] Connaught Place, New Delhi, Delhi, [postalCode], India',
    '[homeNumber] Park Street, Kolkata, West Bengal, [postalCode], India',
    '[homeNumber] Camac Street, Kolkata, West Bengal, [postalCode], India',
    '[homeNumber] Banjara Hills Road, Hyderabad, Telangana, [postalCode], India',
    '[homeNumber] FC Road, Pune, Maharashtra, [postalCode], India',
    '[homeNumber] Ashram Road, Ahmedabad, Gujarat, [postalCode], India',

    '[homeNumber] Sukhumvit Road, Bangkok, Bangkok, [postalCode], Thailand',
    '[homeNumber] Silom Road, Bangkok, Bangkok, [postalCode], Thailand',
    '[homeNumber] Khao San Road, Bangkok, Bangkok, [postalCode], Thailand',
    '[homeNumber] Jalan Sultan Ismail, Kuala Lumpur, Kuala Lumpur, [postalCode], Malaysia',
    '[homeNumber] Jalan Ampang, Kuala Lumpur, Kuala Lumpur, [postalCode], Malaysia',
    '[homeNumber] Jalan Bukit Bintang, Kuala Lumpur, Kuala Lumpur, [postalCode], Malaysia',
    '[homeNumber] Roxas Boulevard, Manila, Metro Manila, [postalCode], Philippines',
    '[homeNumber] Ayala Avenue, Makati, Metro Manila, [postalCode], Philippines',
    '[homeNumber] Bonifacio High Street, Taguig, Metro Manila, [postalCode], Philippines',
    '[homeNumber] Galle Road, Colombo, Western Province, [postalCode], Sri Lanka',
    '[homeNumber] Dhanmondi Road, Dhaka, Dhaka Division, [postalCode], Bangladesh',
    '[homeNumber] Kemang Raya, Jakarta, Jakarta, [postalCode], Indonesia',

    '[homeNumber] Avenida Paulista, São Paulo, São Paulo, [postalCode], Brazil',
    '[homeNumber] Rua Augusta, São Paulo, São Paulo, [postalCode], Brazil',
    '[homeNumber] Alameda Santos, São Paulo, São Paulo, [postalCode], Brazil',
    '[homeNumber] Avenida Atlântica, Rio de Janeiro, Rio de Janeiro, [postalCode], Brazil',
    '[homeNumber] Rua das Flores, Curitiba, Paraná, [postalCode], Brazil',
    '[homeNumber] Paseo de la Reforma, Mexico City, Mexico City, [postalCode], Mexico',
    '[homeNumber] Avenida Insurgentes, Mexico City, Mexico City, [postalCode], Mexico',
    '[homeNumber] Calle Madero, Mexico City, Mexico City, [postalCode], Mexico',
    '[homeNumber] Avenida Corrientes, Buenos Aires, Buenos Aires, [postalCode], Argentina',
    '[homeNumber] Florida Street, Buenos Aires, Buenos Aires, [postalCode], Argentina',
    '[homeNumber] Avenida Santa Fe, Buenos Aires, Buenos Aires, [postalCode], Argentina',
    '[homeNumber] Avenida Apoquindo, Santiago, Santiago Metropolitan Region, [postalCode], Chile',
    '[homeNumber] Calle Ocho, Miami, Florida, [postalCode], United States',
    '[homeNumber] Avenida Reforma, Guatemala City, Guatemala Department, [postalCode], Guatemala',
    '[homeNumber] Calle de Alcalá, Madrid, Community of Madrid, [postalCode], Spain',
    '[homeNumber] Gran Vía, Madrid, Community of Madrid, [postalCode], Spain',

    '[homeNumber] Passeig de Gràcia, Barcelona, Catalonia, [postalCode], Spain',
    '[homeNumber] La Rambla, Barcelona, Catalonia, [postalCode], Spain',
    '[homeNumber] Rua do Ouro, Lisbon, Lisbon District, [postalCode], Portugal',
    '[homeNumber] Avenida da Liberdade, Lisbon, Lisbon District, [postalCode], Portugal',
    '[homeNumber] Rua de Santa Catarina, Porto, Porto District, [postalCode], Portugal',
    '[homeNumber] Via Roma, Milan, Lombardy, [postalCode], Italy',
    '[homeNumber] Corso Vittorio Emanuele, Milan, Lombardy, [postalCode], Italy',
    '[homeNumber] Via del Corso, Rome, Lazio, [postalCode], Italy',
    '[homeNumber] Via Veneto, Rome, Lazio, [postalCode], Italy',
    '[homeNumber] Calle Larios, Málaga, Andalusia, [postalCode], Spain',
    '[homeNumber] Kurfürstendamm, Berlin, Berlin, [postalCode], Germany',
    '[homeNumber] Friedrichstraße, Berlin, Berlin, [postalCode], Germany',
    '[homeNumber] Unter den Linden, Berlin, Berlin, [postalCode], Germany',
    '[homeNumber] Königsallee, Düsseldorf, North Rhine-Westphalia, [postalCode], Germany',
    '[homeNumber] Zeil, Frankfurt, Hesse, [postalCode], Germany',
    '[homeNumber] Mariahilfer Straße, Vienna, Vienna, [postalCode], Austria',
    '[homeNumber] Kärntner Straße, Vienna, Vienna, [postalCode], Austria',
    '[homeNumber] Andrássy Avenue, Budapest, Central Hungary, [postalCode], Hungary',
    '[homeNumber] Váci Street, Budapest, Central Hungary, [postalCode], Hungary',
    '[homeNumber] Wenceslas Square, Prague, Prague, [postalCode], Czech Republic',
    '[homeNumber] Na Příkopě, Prague, Prague, [postalCode], Czech Republic',
    '[homeNumber] Rue de Rivoli, Paris, Île-de-France, [postalCode], France',
    '[homeNumber] Boulevard Saint-Germain, Paris, Île-de-France, [postalCode], France',
    '[homeNumber] Avenue des Champs-Élysées, Paris, Île-de-France, [postalCode], France',
    '[homeNumber] Rue de la Paix, Paris, Île-de-France, [postalCode], France',
    "[homeNumber] Cours Mirabeau, Aix-en-Provence, Provence-Alpes-Côte d'Azur, [postalCode], France",
    '[homeNumber] Avenue Louise, Brussels, Brussels-Capital Region, [postalCode], Belgium',
    '[homeNumber] Nieuwstraat, Brussels, Brussels-Capital Region, [postalCode], Belgium',
    '[homeNumber] Damrak, Amsterdam, North Holland, [postalCode], Netherlands',
    '[homeNumber] Herengracht, Amsterdam, North Holland, [postalCode], Netherlands',
    '[homeNumber] Kalverstraat, Amsterdam, North Holland, [postalCode], Netherlands',
    '[homeNumber] Lijnbaan, Rotterdam, South Holland, [postalCode], Netherlands',
    '[homeNumber] Storgata, Oslo, Oslo, [postalCode], Norway',
    '[homeNumber] Karl Johans gate, Oslo, Oslo, [postalCode], Norway',
    '[homeNumber] Drottninggatan, Stockholm, Stockholm County, [postalCode], Sweden',
    '[homeNumber] Strandvägen, Stockholm, Stockholm County, [postalCode], Sweden',
    '[homeNumber] Mannerheimintie, Helsinki, Uusimaa, [postalCode], Finland',
    '[homeNumber] Aleksanterinkatu, Helsinki, Uusimaa, [postalCode], Finland',
    '[homeNumber] Esplanadi, Helsinki, Uusimaa, [postalCode], Finland',
    '[homeNumber] Váci út, Budapest, Central Hungary, [postalCode], Hungary',
    '[homeNumber] Piotrkowska Street, Łódź, Łódź Voivodeship, [postalCode], Poland',
    '[homeNumber] Nowy Świat, Warsaw, Masovian Voivodeship, [postalCode], Poland',
    '[homeNumber] Bulevar Kralja Aleksandra, Belgrade, Belgrade, [postalCode], Serbia',
    '[homeNumber] Kneza Mihaila, Belgrade, Belgrade, [postalCode], Serbia',
    '[homeNumber] Vitosha Boulevard, Sofia, Sofia City Province, [postalCode], Bulgaria',
    '[homeNumber] Knez Mihailova, Belgrade, Belgrade, [postalCode], Serbia',
    '[homeNumber] Hlavná Street, Košice, Košice Region, [postalCode], Slovakia',
    '[homeNumber] Obchodná Street, Bratislava, Bratislava Region, [postalCode], Slovakia',
    '[homeNumber] Kralja Petra, Belgrade, Belgrade, [postalCode], Serbia',

    'Flat [unitNumber], [homeNumber] Baker Street, London, England, [postalCode], United Kingdom',
    'Apartment [unitNumber], [homeNumber] Rue de Rivoli, Paris, Île-de-France, [postalCode], France',
    'Suite [unitNumber], [homeNumber] Madison Avenue, New York, New York, [postalCode], United States',
    'Floor [floorNumber], [homeNumber] Collins Street, Melbourne, Victoria, [postalCode], Australia',
    'Level [floorNumber], [homeNumber] Orchard Road, Singapore, Singapore, [postalCode], Singapore',
    'Unit [unitNumber], [homeNumber] Avenida Paulista, São Paulo, São Paulo, [postalCode], Brazil',
    'PO Box [poBoxNumber], Wellington, Wellington, [postalCode], New Zealand',
    'PO Box [poBoxNumber], Dubai, Dubai, [postalCode], United Arab Emirates',
    'PO Box [poBoxNumber], Toronto, Ontario, [postalCode], Canada',
    'PO Box [poBoxNumber], Dublin, Leinster, [postalCode], Ireland',
    'Mailbox [poBoxNumber], Reykjavík, Capital Region, [postalCode], Iceland',
    'Flat [unitNumber], The Gables, [homeNumber] High Street, Oxford, England, [postalCode], United Kingdom',
    'Suite [unitNumber], Meridian House, [homeNumber] Bay Street, Toronto, Ontario, [postalCode], Canada',
    'Level [floorNumber], Harbour View Tower, [homeNumber] Queen Street, Auckland, Auckland, [postalCode], New Zealand',
    'Floor [floorNumber], Cedar Court, [homeNumber] Market Street, San Francisco, California, [postalCode], United States',
    'Unit [unitNumber], Riverside Chambers, [homeNumber] George Street, Sydney, New South Wales, [postalCode], Australia',
    'Apartment [unitNumber], Maple Residences, [homeNumber] Sukhumvit Road, Bangkok, Bangkok, [postalCode], Thailand',
    'Suite [unitNumber], Atlas House, [homeNumber] Sheikh Zayed Road, Dubai, Dubai, [postalCode], United Arab Emirates',
    'Floor [floorNumber], Lotus Plaza, [homeNumber] MG Road, Bengaluru, Karnataka, [postalCode], India',
    'Unit [unitNumber], Aurora Building, [homeNumber] Granville Street, Vancouver, British Columbia, [postalCode], Canada',

    'John Smith, [homeNumber] Beacon Street, Boston, Massachusetts, [postalCode], United States',
    'Emma Johnson, Suite [unitNumber], [homeNumber] Queen Street West, Toronto, Ontario, [postalCode], Canada',
    'Michael Brown, Flat [unitNumber], [homeNumber] Princes Street, Edinburgh, Scotland, [postalCode], United Kingdom',
    'Olivia Davis, Floor [floorNumber], [homeNumber] George Street, Sydney, New South Wales, [postalCode], Australia',
    'William Wilson, [homeNumber] Avenida da Liberdade, Lisbon, Lisbon District, [postalCode], Portugal',
    'Sophia Taylor, [homeNumber] Avenue Louise, Brussels, Brussels-Capital Region, [postalCode], Belgium',
    'James Anderson, [homeNumber] Kurfürstendamm, Berlin, Berlin, [postalCode], Germany',
    'Charlotte Thomas, [homeNumber] Via del Corso, Rome, Lazio, [postalCode], Italy',
    'Benjamin Moore, [homeNumber] Passeig de Gràcia, Barcelona, Catalonia, [postalCode], Spain',
    'Amelia Martin, [homeNumber] Robson Street, Vancouver, British Columbia, [postalCode], Canada',
    'Henry Walker, [homeNumber] Lambton Quay, Wellington, Wellington, [postalCode], New Zealand',
    'Isla White, [homeNumber] Anna Salai, Chennai, Tamil Nadu, [postalCode], India',
    'Lucas Harris, [homeNumber] Nathan Road, Hong Kong, Hong Kong, [postalCode], Hong Kong',
    'Mia Hall, [homeNumber] Jalan Ampang, Kuala Lumpur, Kuala Lumpur, [postalCode], Malaysia',
    'Alexander Young, [homeNumber] Tahlia Street, Jeddah, Mecca Province, [postalCode], Saudi Arabia',
    'Grace King, [homeNumber] Rue Sainte-Catherine, Montreal, Quebec, [postalCode], Canada',
    'Daniel Wright, [homeNumber] Peachtree Street, Atlanta, Georgia, [postalCode], United States',
    'Lily Green, [homeNumber] Avenida Corrientes, Buenos Aires, Buenos Aires, [postalCode], Argentina',
    'Samuel Scott, [homeNumber] Mannerheimintie, Helsinki, Uusimaa, [postalCode], Finland',
    'Ella Adams, [homeNumber] Karl Johans gate, Oslo, Oslo, [postalCode], Norway',

    'Acme Corporation, Accounts Payable, Suite [unitNumber], [homeNumber] Wall Street, New York, New York, [postalCode], United States',
    'Northstar Consulting, Finance Department, [homeNumber] Bay Street, Toronto, Ontario, [postalCode], Canada',
    'Bluebird Trading, Billing Office, Floor [floorNumber], [homeNumber] Collins Street, Melbourne, Victoria, [postalCode], Australia',
    'Evergreen Holdings, [homeNumber] Avenue des Champs-Élysées, Paris, Île-de-France, [postalCode], France',
    'Silver Oak Partners, [homeNumber] Orchard Road, Singapore, Singapore, [postalCode], Singapore',
    "Harbourlight Media, [homeNumber] Queen's Road Central, Hong Kong, Hong Kong, [postalCode], Hong Kong",
    'Redstone Logistics, [homeNumber] Paseo de la Reforma, Mexico City, Mexico City, [postalCode], Mexico',
    'Golden Horizon Group, [homeNumber] Sheikh Zayed Road, Dubai, Dubai, [postalCode], United Arab Emirates',
    'Maple Crest Ventures, [homeNumber] Granville Street, Vancouver, British Columbia, [postalCode], Canada',
    'Starlake Industries, [homeNumber] Via Roma, Milan, Lombardy, [postalCode], Italy',
    'Cedarbrook Systems, [homeNumber] Drottninggatan, Stockholm, Stockholm County, [postalCode], Sweden',
    'Ivory Lantern Studio, [homeNumber] Grafton Street, Dublin, Leinster, [postalCode], Ireland',
    'Ironwood Capital, [homeNumber] Madison Avenue, New York, New York, [postalCode], United States',
    'Willowbank Retail, [homeNumber] Broadway, New York, New York, [postalCode], United States',
    'Brightpath Analytics, [homeNumber] MG Road, Bengaluru, Karnataka, [postalCode], India',
    'Stonebridge Foods, [homeNumber] Queen Street, Auckland, Auckland, [postalCode], New Zealand',
    'Crownleaf Properties, [homeNumber] George Street, Edinburgh, Scotland, [postalCode], United Kingdom',
    'Mariner Housewares, [homeNumber] St Georges Terrace, Perth, Western Australia, [postalCode], Australia',
    'Pine & Ember Design, [homeNumber] Avenida Paulista, São Paulo, São Paulo, [postalCode], Brazil',
    'Harbour View Imports, [homeNumber] Hamra Street, Beirut, Beirut, [postalCode], Lebanon',

    'c/o Accounts Payable, [homeNumber] Michigan Avenue, Chicago, Illinois, [postalCode], United States',
    'Attn Billing Department, [homeNumber] King Street West, Toronto, Ontario, [postalCode], Canada',
    'Attention Finance Office, [homeNumber] Baker Street, London, England, [postalCode], United Kingdom',
    'Billing Office, Flat [unitNumber], [homeNumber] Rue de la Paix, Paris, Île-de-France, [postalCode], France',
    'Invoice Processing, Suite [unitNumber], [homeNumber] Queen Street, Brisbane, Queensland, [postalCode], Australia',
    'Accounts Team, Level [floorNumber], [homeNumber] Connaught Place, New Delhi, Delhi, [postalCode], India',
    'Remittance Office, [homeNumber] Raffles Place, Singapore, Singapore, [postalCode], Singapore',
    'Corporate Billing, [homeNumber] Bay Street, Toronto, Ontario, [postalCode], Canada',
    'Finance and Billing, [homeNumber] Paseo de Gràcia, Barcelona, Catalonia, [postalCode], Spain',
    'Head Office Billing, [homeNumber] Avenida Atlântica, Rio de Janeiro, Rio de Janeiro, [postalCode], Brazil',

    '[homeNumber] Baker Street\nLondon\nEngland [postalCode]\nUnited Kingdom',
    'Flat [unitNumber]\n[homeNumber] Baker Street\nLondon\nEngland [postalCode]\nUnited Kingdom',
    'Suite [unitNumber]\n[homeNumber] Madison Avenue\nNew York\nNew York [postalCode]\nUnited States',
    'Floor [floorNumber]\n[homeNumber] Collins Street\nMelbourne\nVictoria [postalCode]\nAustralia',
    'Level [floorNumber]\n[homeNumber] Orchard Road\nSingapore\nSingapore [postalCode]\nSingapore',
    'Unit [unitNumber]\n[homeNumber] Avenida Paulista\nSão Paulo\nSão Paulo [postalCode]\nBrazil',
    'PO Box [poBoxNumber]\nDublin\nLeinster [postalCode]\nIreland',
    'Meridian House\nSuite [unitNumber]\n[homeNumber] Bay Street\nToronto\nOntario [postalCode]\nCanada',
    'Atlas House\nFloor [floorNumber]\n[homeNumber] Sheikh Zayed Road\nDubai\nDubai [postalCode]\nUnited Arab Emirates',
    'Lotus Plaza\nLevel [floorNumber]\n[homeNumber] MG Road\nBengaluru\nKarnataka [postalCode]\nIndia',
    'John Smith\n[homeNumber] Beacon Street\nBoston\nMassachusetts [postalCode]\nUnited States',
    'Emma Johnson\nSuite [unitNumber], [homeNumber] Queen Street West\nToronto\nOntario [postalCode]\nCanada',
    'Acme Corporation\nAccounts Payable\n[homeNumber] Wall Street\nNew York\nNew York [postalCode]\nUnited States',
    'Northstar Consulting\nFinance Department\n[homeNumber] Bay Street\nToronto\nOntario [postalCode]\nCanada',
    "Harbourlight Media\nBilling Office\n[homeNumber] Queen's Road Central\nHong Kong\nHong Kong [postalCode]\nHong Kong",
  ],
  broker: [
    'John Smith',
    'Emma Johnson',
    'Michael Brown',
    'Olivia Davis',
    'William Wilson',
    'Sophia Taylor',
    'James Anderson',
    'Charlotte Thomas',
    'Benjamin Moore',
    'Amelia Martin',
    'Henry Walker',
    'Isla White',
    'Lucas Harris',
    'Mia Hall',
    'Alexander Young',
    'Grace King',
    'Daniel Wright',
    'Lily Green',
    'Samuel Scott',
    'Ella Adams',
    'Nathan Baker',
    'Zoe Carter',
    'Ethan Mitchell',
    'Ava Turner',
    'Leo Parker',
    'Chloe Evans',
    'Noah Collins',
    'Ruby Stewart',
    'Jack Morris',
    'Hannah Rogers',
    'Owen Reed',
    'Scarlett Cook',
    'Isaac Bell',
    'Harper Murphy',
    'Julian Foster',
    'Layla Bailey',
    'Gabriel Cooper',
    'Nora Richardson',
    'Thomas Cox',
    'Violet Howard',
    'Eleanor Price',
    'Martin Doyle',
    'Clara Bennett',
    'Juliette Mercer',
    'Graham Sutton',
    'Natalie Fraser',
    'Simon Caldwell',
    'Rebecca Nolan',
    'Victor Langley',
    'Alice Thornton',
    'Peter Whitmore',
    'Laura Hastings',
    'Richard Pembroke',
    'Sophie Ellison',
    'Andrew Lockwood',
    'Madeleine Pierce',
    'Christopher Hales',
    'Emily Sinclair',
    'Jonathan Wade',
    'Abigail Porter',
    'Anthony Miles',
    'Lucy Barrett',
    'David Holloway',
    'Rose Chandler',
    'Matthew Sterling',
    'Anna Livingston',
    'Stephen Mercer',
    'Julia Fairchild',
    'Robert Ashford',
    'Megan Whitfield',
    'Edward Sullivan',
    'Claire Donnelly',
    'Nicholas Harper',
    'Naomi Fletcher',
    'Thomas Avery',
    'Leah Montgomery',
    'Charles Grayson',
    'Phoebe Randall',
    'Daniel Whitaker',
    'Elena Brooks',
    'Joseph Bennett',
    'Amy Saunders',
    'Patrick Delaney',
    'Rachel Underwood',
    'George Crawford',
    'Sabrina Howell',
    'Harold Jensen',
    'Martha Coleman',
    'Ian Prescott',
    'Vanessa Gilbert',
    'Noel Harrington',
    'Tessa Armstrong',
    'Julian Rhodes',
    'Monica Farrow',
    'Elliot Vaughn',
    'Paige Hollowell',
    'Colin Mercer',
    'Bianca Ellwood',
    'Trevor Lang',
    'Katherine Dale',
    'Gideon Marsh',
    'Felicity Warren',
    'Miles Redwood',
    'Daphne Lowe',

    'Mr John Smith',
    'Ms Emma Johnson',
    'Mrs Olivia Davis',
    'Dr Michael Brown',
    'Agent William Wilson',
    'Broker Sophia Taylor',
    'Senior Agent James Anderson',
    'Lead Broker Charlotte Thomas',
    'Travel Agent Benjamin Moore',
    'Booking Agent Amelia Martin',
    'Sales Agent Henry Walker',
    'Account Broker Isla White',
    'Reservation Agent Lucas Harris',
    'Listing Agent Mia Hall',
    'Ticketing Agent Alexander Young',
    'Insurance Broker Grace King',
    'Freight Broker Daniel Wright',
    'Customs Broker Lily Green',
    'Mortgage Broker Samuel Scott',
    'Real Estate Broker Ella Adams',
    'Leasing Agent Nathan Baker',
    'Placement Agent Zoe Carter',
    'Introducer Ethan Mitchell',
    'Deal Facilitator Ava Turner',
    'Channel Partner Leo Parker',
    'Partner Agent Chloe Evans',
    'Broker Associate Noah Collins',
    'Associate Broker Ruby Stewart',
    'Senior Facilitator Jack Morris',
    'Principal Broker Hannah Rogers',

    'Northbridge Brokers',
    'Northbridge Brokerage',
    'Northbridge Agency',
    'Northbridge Partners',
    'Northbridge Intermediaries',
    'Northbridge Facilitation Group',
    'Northbridge Booking Services',
    'Northbridge Sales Agency',
    'Northbridge Account Brokerage',
    'Northbridge Travel Desk',
    'Northbridge Reservations',
    'Northbridge Placements',
    'Northbridge Introductions',
    'Northbridge Connect',
    'Northbridge Commercial Brokers',
    'Northbridge Realty Brokers',
    'Northbridge Insurance Brokers',
    'Northbridge Freight Brokers',
    'Northbridge Maritime Brokers',
    'Northbridge Aviation Brokers',

    'Blue Horizon Brokers',
    'Blue Horizon Agency',
    'Blue Horizon Travel',
    'Blue Horizon Bookings',
    'Blue Horizon Reservations',
    'Blue Horizon Facilitation',
    'Blue Horizon Intermediary Services',
    'Blue Horizon Sales Partners',
    'Blue Horizon Account Brokers',
    'Blue Horizon Deal Desk',

    'Cedarstone Brokerage',
    'Cedarstone Brokers',
    'Cedarstone Agency',
    'Cedarstone Advisory and Brokerage',
    'Cedarstone Booking Office',
    'Cedarstone Reservations Team',
    'Cedarstone Placement Services',
    'Cedarstone Transit Brokers',
    'Cedarstone Property Brokers',
    'Cedarstone Cover Brokers',

    'Silver Oak Brokers',
    'Silver Oak Agency',
    'Silver Oak Travel Agency',
    'Silver Oak Booking Services',
    'Silver Oak Intermediaries',
    'Silver Oak Partner Network',
    'Silver Oak Broker Network',
    'Silver Oak Sales Desk',
    'Silver Oak Accounts Brokerage',
    'Silver Oak Concierge Bookings',

    'Harborlight Brokers',
    'Harborlight Agency',
    'Harborlight Booking Agency',
    'Harborlight Reservation Partners',
    'Harborlight Facilitation Services',
    'Harborlight Brokerage House',
    'Harborlight Travel Partners',
    'Harborlight Shipping Brokers',
    'Harborlight Cargo Agents',
    'Harborlight Charter Brokers',

    'Redwood Brokerage',
    'Redwood Brokers',
    'Redwood Agency',
    'Redwood Travel Management',
    'Redwood Reservation Services',
    'Redwood Booking Office',
    'Redwood Insurance Intermediaries',
    'Redwood Capital Brokers',
    'Redwood Commercial Agents',
    'Redwood Sales Brokerage',

    'Evergreen Brokers',
    'Evergreen Agency',
    'Evergreen Bookings',
    'Evergreen Reservations',
    'Evergreen Arrangement Services',
    'Evergreen Intermediary Group',
    'Evergreen Sales Agency',
    'Evergreen Account Brokerage',
    'Evergreen Deal Facilitation',
    'Evergreen Partner Desk',

    'Atlas Brokerage',
    'Atlas Brokers',
    'Atlas Agency',
    'Atlas Booking Partners',
    'Atlas Travel Brokers',
    'Atlas Cargo Brokerage',
    'Atlas Transit Agents',
    'Atlas Accommodation Brokers',
    'Atlas Ticketing Services',
    'Atlas Placement Office',

    'Meridian Brokers',
    'Meridian Agency',
    'Meridian Booking Services',
    'Meridian Reservation Bureau',
    'Meridian Intermediaries',
    'Meridian Arrangement Office',
    'Meridian Sales Agents',
    'Meridian Realty Brokerage',
    'Meridian Loan Brokers',
    'Meridian Freight Agency',

    'Aurora Brokerage',
    'Aurora Brokers',
    'Aurora Agency',
    'Aurora Travel Agents',
    'Aurora Booking Bureau',
    'Aurora Facilitation Partners',
    'Aurora Sales Brokerage',
    'Aurora Account Intermediaries',
    'Aurora Charter Brokers',
    'Aurora Logistics Agents',

    'Willowbank Brokers',
    'Willowbank Agency',
    'Willowbank Bookings',
    'Willowbank Reservations',
    'Willowbank Partner Agents',
    'Willowbank Brokerage Services',
    'Willowbank Travel Facilitation',
    'Willowbank Property Agents',
    'Willowbank Insurance Desk',
    'Willowbank Client Brokerage',

    'Summit Brokerage',
    'Summit Brokers',
    'Summit Agency',
    'Summit Reservation Services',
    'Summit Booking Office',
    'Summit Intermediary Partners',
    'Summit Sales Agents',
    'Summit Placement Brokers',
    'Summit Commercial Brokerage',
    'Summit Relationship Desk',

    'Ironwood Brokers',
    'Ironwood Agency',
    'Ironwood Bookings',
    'Ironwood Travel Desk',
    'Ironwood Brokerage Partners',
    'Ironwood Account Brokers',
    'Ironwood Shipping Agents',
    'Ironwood Coverage Brokers',
    'Ironwood Lease Brokers',
    'Ironwood Sales Facilitation',

    'Crownleaf Brokerage',
    'Crownleaf Brokers',
    'Crownleaf Agency',
    'Crownleaf Bookings Office',
    'Crownleaf Reservation Agents',
    'Crownleaf Travel Services',
    'Crownleaf Deal Brokers',
    'Crownleaf Sales Network',
    'Crownleaf Placement Team',
    'Crownleaf Account Desk',

    'Brightpath Brokers',
    'Brightpath Agency',
    'Brightpath Booking Services',
    'Brightpath Reservation Centre',
    'Brightpath Intermediary Solutions',
    'Brightpath Facilitators',
    'Brightpath Sales Agents',
    'Brightpath Client Brokers',
    'Brightpath Property Brokerage',
    'Brightpath Logistics Brokerage',

    'Stonebridge Brokers',
    'Stonebridge Agency',
    'Stonebridge Booking Office',
    'Stonebridge Travel Services',
    'Stonebridge Partner Brokers',
    'Stonebridge Facilitation Office',
    'Stonebridge Deal Agents',
    'Stonebridge Account Brokerage',
    'Stonebridge Mortgage Brokers',
    'Stonebridge Cargo Brokers',

    'Mariner Brokers',
    'Mariner Agency',
    'Mariner Booking Partners',
    'Mariner Reservation Office',
    'Mariner Charter Brokers',
    'Mariner Marine Agents',
    'Mariner Freight Brokerage',
    'Mariner Travel Desk',
    'Mariner Sales Partners',
    'Mariner Intermediary House',

    'Pinecrest Brokers',
    'Pinecrest Agency',
    'Pinecrest Bookings',
    'Pinecrest Arrangement Services',
    'Pinecrest Reservation Partners',
    'Pinecrest Broker Group',
    'Pinecrest Sales Desk',
    'Pinecrest Client Intermediaries',
    'Pinecrest Insurance Brokerage',
    'Pinecrest Commercial Agents',

    'Westgate Brokers',
    'Westgate Agency',
    'Westgate Travel Agency',
    'Westgate Booking Services',
    'Westgate Reservation Desk',
    'Westgate Facilitators',
    'Westgate Sales Agents',
    'Westgate Property Brokers',
    'Westgate Lease Agents',
    'Westgate Account Brokers',

    'Fairview Brokerage',
    'Fairview Brokers',
    'Fairview Agency',
    'Fairview Booking Office',
    'Fairview Travel Partners',
    'Fairview Reservation Services',
    'Fairview Introducer Network',
    'Fairview Placement Agents',
    'Fairview Insurance Intermediaries',
    'Fairview Cargo Brokerage',

    'Bridgepoint Brokers',
    'Bridgepoint Agency',
    'Bridgepoint Booking Group',
    'Bridgepoint Travel Services',
    'Bridgepoint Reservation Bureau',
    'Bridgepoint Facilitation Partners',
    'Bridgepoint Sales Brokerage',
    'Bridgepoint Finance Brokers',
    'Bridgepoint Client Agents',
    'Bridgepoint Commercial Intermediaries',

    'Lighthouse Brokerage',
    'Lighthouse Brokers',
    'Lighthouse Agency',
    'Lighthouse Reservation Services',
    'Lighthouse Booking Centre',
    'Lighthouse Travel Desk',
    'Lighthouse Arrangement Office',
    'Lighthouse Placement Brokers',
    'Lighthouse Sales Partners',
    'Lighthouse Account Brokerage',

    'Broker Desk',
    'Broker Office',
    'Broker Team',
    'Broker Division',
    'Broker Department',
    'Broker Channel',
    'Broker Network',
    'Broker Services',
    'Broker Support',
    'Broker Operations',
    'Agent Desk',
    'Agent Office',
    'Agent Team',
    'Agent Division',
    'Agent Department',
    'Agent Channel',
    'Agent Network',
    'Agent Services',
    'Booking Desk',
    'Booking Office',
    'Booking Team',
    'Booking Department',
    'Reservations Desk',
    'Reservations Office',
    'Reservations Team',
    'Reservation Bureau',
    'Reservation Centre',
    'Reservation Channel',
    'Travel Desk',
    'Travel Office',
    'Travel Agency',
    'Travel Centre',
    'Travel Partners',
    'Sales Desk',
    'Sales Office',
    'Sales Agency',
    'Sales Partner Network',
    'Accounts Brokerage Desk',
    'Account Management Broker Desk',
    'Placement Office',
    'Placement Team',
    'Facilitation Desk',
    'Facilitation Office',
    'Intermediary Services',
    'Intermediary Desk',
    'Intermediary Office',
    'Arrangement Desk',
    'Arrangement Office',
    'Channel Sales Desk',
    'Partner Booking Desk',
    'Partner Agency',
    'Partner Sales Office',
    'Partner Reservations Team',
    'Deal Desk',
    'Deal Facilitation Office',
    'Client Placement Desk',
    'Commercial Brokerage Desk',
    'Corporate Booking Office',
    'Corporate Travel Desk',
    'Client Services Broker Desk',
    'Relationship Brokerage Team',

    'Travel Broker',
    'Travel Agent',
    'Reservation Agent',
    'Booking Agent',
    'Sales Agent',
    'Account Broker',
    'Client Broker',
    'Coverage Broker',
    'Policy Broker',
    'Real Estate Broker',
    'Property Broker',
    'Leasing Agent',
    'Letting Agent',
    'Mortgage Broker',
    'Loan Broker',
    'Finance Broker',
    'Investment Broker',
    'Securities Broker',
    'Stockbroker',
    'Insurance Broker',
    'Claims Broker',
    'Freight Broker',
    'Cargo Broker',
    'Shipping Broker',
    'Marine Broker',
    'Charter Broker',
    'Air Charter Broker',
    'Customs Broker',
    'Import Broker',
    'Export Broker',
    'Ticket Agent',
    'Ticketing Agent',
    'Event Agent',
    'Hospitality Agent',
    'Accommodation Broker',
    'Hotel Broker',
    'Venue Booking Agent',
    'Conference Agent',
    'Convention Agent',
    'Cruise Broker',
    'Tour Agent',
    'Tour Broker',
    'Wholesale Agent',
    'Retail Agent',
    'Distribution Agent',
    'Channel Agent',
    'Referral Agent',
    'Referral Partner',
    'Introducer',
    'Intermediary',
    'Facilitator',
    'Coordinator',
    'Arranger',
    'Placement Agent',
    'Account Executive',
    'Broker Associate',
    'Associate Broker',
    'Principal Broker',
    'Senior Broker',
    'Lead Agent',
    'Junior Agent',
    'Independent Broker',
    'Independent Agent',
    'Authorized Agent',
    'Licensed Broker',
    'Licensed Agent',
    'Accredited Broker',
    'Certified Broker',
    'Registered Agent',
    'Registered Broker',
    'Exclusive Agent',
    'Preferred Broker',
    'Preferred Agent',

    'Brokered by Northbridge Brokers',
    'Brokered by Blue Horizon Travel',
    'Brokered by Cedarstone Brokerage',
    'Brokered by Silver Oak Brokers',
    'Brokered by Harborlight Agency',
    'Brokered by Redwood Brokerage',
    'Arranged by Meridian Agency',
    'Arranged by Aurora Travel Agents',
    'Arranged by Westgate Travel Agency',
    'Arranged by Fairview Agency',
    'Facilitated by Bridgepoint Brokers',
    'Facilitated by Lighthouse Brokerage',
    'Facilitated by Summit Brokerage',
    'Facilitated by Pinecrest Brokers',
    'Booked through Northbridge Booking Services',
    'Booked through Atlas Booking Partners',
    'Booked through Evergreen Bookings',
    'Booked through Willowbank Bookings',
    'Reserved through Meridian Reservation Bureau',
    'Reserved through Brightpath Reservation Centre',
    'Handled by John Smith',
    'Handled by Emma Johnson',
    'Handled by Michael Brown',
    'Handled by Olivia Davis',
    'Managed by William Wilson',
    'Managed by Sophia Taylor',
    'Coordinated by James Anderson',
    'Coordinated by Charlotte Thomas',
    'Placed by Benjamin Moore',
    'Placed by Amelia Martin',
    'Introduced by Henry Walker',
    'Introduced by Isla White',
    'Referred by Lucas Harris',
    'Referred by Mia Hall',
    'Processed by Alexander Young',
    'Processed by Grace King',
    'Sold through Stonebridge Brokers',
    'Sold through Crownleaf Brokerage',
    'Sold through Brightpath Agency',
    'Sold through Mariner Brokers',
    'Through Northbridge Agency',
    'Through Harborlight Brokers',
    'Through Silver Oak Travel Agency',
    'Through Meridian Brokers',
    'Via Cedarstone Brokerage',
    'Via Redwood Agency',
    'Via Atlas Brokers',
    'Via Aurora Agency',
    'Via Willowbank Brokers',
    'Via Bridgepoint Agency',
    'Via a booking agent',
    'Via an intermediary',
    'Via a sales agent',
    'Via an account broker',
    'Through an independent broker',
    'Through an authorized agent',
    'Through a licensed broker',
    'Through a registered intermediary',
    'Through a travel facilitator',
    'Through a placement agent',
  ],
  confirmationNumber: [
    /**
    A confirmationNumber can be:
    a simple incrementing number like 10458291,
    a zero-padded sequence like 00018425,
    an alphanumeric booking code like AB7K29,
    a date-prefixed id like 20260321-18425,
    a partitioned code like CNF-AB12-9842,
    a random token,
    a hash-like short id,
    or a UUID if the system is lazy or internal-first.
    */
  ],
  customer: [
    'John Smith',
    'Emma Johnson',
    'Michael Brown',
    'Olivia Davis',
    'William Wilson',
    'Sophia Taylor',
    'James Anderson',
    'Charlotte Thomas',
    'Benjamin Moore',
    'Amelia Martin',
    'Henry Walker',
    'Isla White',
    'Lucas Harris',
    'Mia Hall',
    'Alexander Young',
    'Grace King',
    'Daniel Wright',
    'Lily Green',
    'Samuel Scott',
    'Ella Adams',
    'Nathan Baker',
    'Zoe Carter',
    'Ethan Mitchell',
    'Ava Turner',
    'Leo Parker',
    'Chloe Evans',
    'Noah Collins',
    'Ruby Stewart',
    'Jack Morris',
    'Hannah Rogers',
    'Owen Reed',
    'Scarlett Cook',
    'Isaac Bell',
    'Harper Murphy',
    'Julian Foster',
    'Layla Bailey',
    'Gabriel Cooper',
    'Nora Richardson',
    'Thomas Cox',
    'Violet Howard',
    'Eleanor Price',
    'Martin Doyle',
    'Clara Bennett',
    'Juliette Mercer',
    'Graham Sutton',
    'Natalie Fraser',
    'Simon Caldwell',
    'Rebecca Nolan',
    'Victor Langley',
    'Alice Thornton',
    'Peter Whitmore',
    'Laura Hastings',
    'Richard Pembroke',
    'Sophie Ellison',
    'Andrew Lockwood',
    'Madeleine Pierce',
    'Christopher Hales',
    'Emily Sinclair',
    'Jonathan Wade',
    'Abigail Porter',
    'Anthony Miles',
    'Lucy Barrett',
    'David Holloway',
    'Rose Chandler',
    'Matthew Sterling',
    'Anna Livingston',
    'Stephen Mercer',
    'Julia Fairchild',
    'Robert Ashford',
    'Megan Whitfield',
    'Edward Sullivan',
    'Claire Donnelly',
    'Nicholas Harper',
    'Naomi Fletcher',
    'Thomas Avery',
    'Leah Montgomery',
    'Charles Grayson',
    'Phoebe Randall',
    'Daniel Whitaker',
    'Elena Brooks',
    'Joseph Bennett',
    'Amy Saunders',
    'Patrick Delaney',
    'Rachel Underwood',
    'George Crawford',
    'Sabrina Howell',
    'Harold Jensen',
    'Martha Coleman',
    'Ian Prescott',
    'Vanessa Gilbert',
    'Noel Harrington',
    'Tessa Armstrong',
    'Julian Rhodes',
    'Monica Farrow',
    'Elliot Vaughn',
    'Paige Hollowell',
    'Colin Mercer',
    'Bianca Ellwood',
    'Trevor Lang',
    'Katherine Dale',
    'Gideon Marsh',
    'Felicity Warren',
    'Miles Redwood',
    'Daphne Lowe',

    'Aino Virtanen',
    'Juhani Korhonen',
    'Eero Nieminen',
    'Mikael Heikkinen',
    'Sofia Laine',
    'Veera Mäkinen',
    'Matias Koskinen',
    'Elias Järvinen',
    'Oskari Lehtonen',
    'Iida Hämäläinen',
    'Luca Rossi',
    'Giulia Bianchi',
    'Matteo Romano',
    'Chiara Greco',
    'Alessandro Conti',
    'Sofia Ferrara',
    'Marco Rinaldi',
    'Elisa Lombardi',
    'Hugo Dubois',
    'Camille Moreau',
    'Louis Laurent',
    'Manon Simon',
    'Jules Bernard',
    'Inès Fontaine',
    'Pablo García',
    'Lucía Fernández',
    'Diego Romero',
    'Valeria Navarro',
    'Mateo Herrera',
    'Sofía Vega',
    'Leonardo Costa',
    'Beatriz Nunes',
    'Tiago Martins',
    'Mariana Alves',
    'João Carvalho',
    'Inês Ribeiro',
    'Niklas Bergström',
    'Astrid Lindberg',
    'Erik Johansson',
    'Freja Nyström',
    'Mads Nielsen',
    'Ida Kristensen',
    'Lars Henriksen',
    'Selma Olesen',
    'Jakub Kowalski',
    'Zofia Nowak',
    'Marek Zieliński',
    'Julia Wiśniewska',
    'Tomasz Wójcik',
    'Ewa Kamińska',
    'Andrei Popescu',
    'Elena Ionescu',
    'Mihai Dumitrescu',
    'Ana Stan',
    'Yusuf Demir',
    'Elif Kaya',
    'Kerem Arslan',
    'Zeynep Aydın',
    'Ahmed Hassan',
    'Fatima El Amrani',
    'Omar Nasser',
    'Layla Haddad',
    'Rami Khoury',
    'Mona Salem',
    'Arjun Mehta',
    'Priya Sharma',
    'Rahul Verma',
    'Ananya Iyer',
    'Kabir Malhotra',
    'Diya Kapoor',
    'Rohan Desai',
    'Meera Nair',
    'Sanjay Bhatia',
    'Asha Menon',
    'Li Wei',
    'Wang Lei',
    'Chen Yu',
    'Zhang Min',
    'Lin Xiaoyu',
    'Liu Yifan',
    'Tan Mei Ling',
    'Ng Wei Han',
    'Lim Jia Hui',
    'Goh Xin Yi',
    'Haruto Sato',
    'Yui Tanaka',
    'Ren Nakamura',
    'Aoi Kobayashi',
    'Minho Kim',
    'Jiwoo Park',
    'Hyejin Lee',
    'Seojun Choi',
    'Nguyen Minh Anh',
    'Tran Quang Huy',
    'Le Thu Ha',
    'Phạm Gia Bảo',
    'Carlos Mendoza',
    'Isabella Torres',
    'Javier Castillo',
    'Valentina Cruz',
    'Miguel Andrade',
    'Camila Paredes',
    'Thiago Silva',
    'María Belén Rojas',
    'Andrés Salazar',
    'Renata Morales',
    'Kwame Mensah',
    'Ama Owusu',
    'Chinedu Okafor',
    'Ngozi Eze',
    'Tendai Moyo',
    'Naledi Khumalo',

    'Mr John Smith',
    'Ms Emma Johnson',
    'Mrs Olivia Davis',
    'Dr Michael Brown',
    'Prof Daniel Wright',
    'Sir Richard Pembroke',
    'Lady Claire Donnelly',
    'Attorney Julia Fairchild',
    'Councillor Martin Doyle',
    'Captain Henry Walker',
    'Pastor Samuel Scott',
    'Reverend Thomas Avery',
    'Nurse Emily Sinclair',
    'Doctor Priya Sharma',
    'Professor Luca Rossi',
    'Engineer Arjun Mehta',
    'Architect Sofia Laine',
    'Chef Marco Rinaldi',
    'Designer Chloe Evans',
    'Director Victor Langley',

    'The Smith Family',
    'The Johnson Family',
    'The Brown Household',
    'The Davis Household',
    'The Wilson Family',
    'The Taylor Family',
    'The Anderson Household',
    'The Thomas Family',
    'The Moore Family',
    'The Martin Family',
    'The Walker Family',
    'The Harris Family',
    'The Young Family',
    'The King Household',
    'The Bennett Household',
    'The Rossi Family',
    'The García Family',
    'The Mehta Family',
    'The Nguyen Family',
    'The Kim Household',
    'John and Emma Smith',
    'Michael and Olivia Brown',
    'Lucas Harris and Mia Hall',
    'Alexander Young and Grace King',
    'Arjun Mehta and Priya Sharma',
    'Li Wei and Chen Yu',
    'Haruto Sato and Yui Tanaka',
    'Carlos Mendoza and Isabella Torres',
    'Kwame Mensah and Ama Owusu',
    'Omar Nasser and Layla Haddad',

    'Acme Corporation',
    'Northwind Traders',
    'Bluebird Trading',
    'Evergreen Holdings',
    'Silver Oak Partners',
    'Cedarstone Logistics',
    'Harborlight Media',
    'Redwood Brokerage',
    'Aurora Dynamics',
    'Meridian Commerce',
    'Atlas Industrial Group',
    'Brightpath Analytics',
    'Stonebridge Foods',
    'Crownleaf Properties',
    'Willowbank Retail',
    'Northbridge Advisory',
    'Bridgepoint Capital',
    'Lighthouse Hospitality',
    'Mariner Supply Co',
    'Pinecrest Solutions',
    'Fairview Medical Group',
    'Westgate Manufacturing',
    'Summit Travel Collective',
    'Ironwood Construction',
    'Golden Horizon Imports',
    'Maple Crest Ventures',
    'Starlake Industries',
    'Riverstone Apparel',
    'Ivory Lantern Studio',
    'Oak & Ember Design',
    'Blue Horizon Travel',
    'Cedar Grove Market',
    'Urban Atlas Studio',
    'Polar Finch Systems',
    'Sunline Mobility',
    'Metroline Services',
    'Helios Energy Partners',
    'Nimbus Cloud Labs',
    'Orbit Commerce Platform',
    'Velvet Sparrow Events',

    'Acme Corporation Accounts Payable',
    'Northwind Traders Finance Department',
    'Bluebird Trading Billing Office',
    'Evergreen Holdings Procurement Team',
    'Silver Oak Partners Client Services',
    'Cedarstone Logistics Corporate Office',
    'Harborlight Media Subscription Desk',
    'Redwood Brokerage Customer Accounts',
    'Aurora Dynamics Enterprise Sales',
    'Meridian Commerce Marketplace Account',
    'Atlas Industrial Group Purchasing',
    'Brightpath Analytics Billing Team',
    'Stonebridge Foods Wholesale Account',
    'Crownleaf Properties Leasing Office',
    'Willowbank Retail Ecommerce Account',
    'Northbridge Advisory Accounts Department',
    'Bridgepoint Capital Investor Relations',
    'Lighthouse Hospitality Central Reservations',
    'Mariner Supply Co Trade Account',
    'Pinecrest Solutions Operations Team',

    'Accounts Payable',
    'Finance Department',
    'Billing Office',
    'Procurement Team',
    'Corporate Services',
    'Client Services',
    'Customer Success',
    'Purchasing Department',
    'Subscription Desk',
    'Central Reservations',
    'Trade Account',
    'Enterprise Account',
    'Wholesale Account',
    'Retail Account',
    'Commercial Account',
    'Marketplace Account',
    'Vendor Management Office',
    'Office of the Registrar',
    'Office of the Treasurer',
    'Property Management Office',

    'Springfield Public Library',
    'Westbrook Community Clinic',
    'Northshore School District',
    'City of Brighton',
    'Department of Public Works',
    'County Registrar Office',
    'Metropolitan Transit Authority',
    'Greenfield University',
    'St Anne Medical Centre',
    'Riverdale Arts Council',
    'Harbor City Museum',
    'Elmwood Book Club',
    'Oakridge Sports Association',
    'Westhaven Community Church',
    'Sunrise Animal Rescue',
    'Bluewater Sailing Club',
    'Hillcrest Tennis Academy',
    'Maple Grove Homeowners Association',
    'Crescent Youth Orchestra',
    'Northern Chamber of Commerce',

    'Reception Desk',
    'Front Office',
    'Main Office',
    'Head Office',
    'Regional Office',
    'Branch Office',
    'Campus Store',
    'Student Account',
    'Member Account',
    'Subscriber Account',
    'Business Account',
    'Corporate Account',
    'Premium Account',
    'Family Account',
    'House Account',
    'Guest Account',
    'Resident Account',
    'Tenant Account',
    'Patient Account',
    'Client Account',

    'Guest of Honour',
    'Primary Recipient',
    'Gift Recipient',
    'Shipment Recipient',
    'Invoice Recipient',
    'Order Recipient',
    'Membership Holder',
    'Account Holder',
    'Policy Holder',
    'Lease Holder',
    'Registrant',
    'Attendee',
    'Participant',
    'Beneficiary',
    'Consignee',
    'Subscriber',
    'Member',
    'Resident',
    'Tenant',
    'Purchasing Contact',

    'John Smith Enterprises',
    'Emma Johnson Consulting',
    'Michael Brown Studio',
    'Olivia Davis Design',
    'William Wilson & Co',
    'Sophia Taylor Advisory',
    'James Anderson Media',
    'Charlotte Thomas Interiors',
    'Benjamin Moore Workshop',
    'Amelia Martin Creative',
    'Henry Walker Trading',
    'Isla White Consulting Group',
    'Lucas Harris Ventures',
    'Mia Hall Events',
    'Alexander Young Capital',
    'Grace King Wellness',
    'Daniel Wright Engineering',
    'Lily Green Botanicals',
    'Samuel Scott Publishing',
    'Ella Adams Atelier',
  ],
  discount: [],
  discountCode: [],
  discountCurrency: [],
  isGift: [],
  orderDate: [],
  orderDelivery: [],
  orderNumber: [],
  orderStatus: [],
  orderedItem: [],
  partOfInvoice: [],
  paymentDueDate: [],
  paymentMethod: [],
  paymentMethodId: [],
  paymentUrl: [],
  seller: [],
  additionalType: [],
  alternateName: [],
  description: [],
  disambiguatingDescription: [],
  identifier: [],
  image: [],
  mainEntityOfPage: [],
  name: [],
  owner: [],
  potentialAction: [],
  sameAs: [],
  subjectOf: [],
  url: [],

  // Invoice / offer / delivery / item / address / party / product / service carry-over

  accountId: [],
  billingPeriod: [],
  minimumPaymentDue: [],
  paymentStatus: [],
  provider: [],
  referencesOrder: [],
  scheduledPaymentDate: [],
  totalPaymentDue: [],
  orderItemNumber: [],
  orderItemStatus: [],
  orderQuantity: [],
  acceptedPaymentMethod: [],
  addOn: [],
  additionalProperty: [],
  availability: [],
  businessFunction: [],
  itemCondition: [],
  itemOffered: [],
  price: [],
  priceCurrency: [],
  priceSpecification: [],
  priceValidUntil: [],
  sku: [],
  serialNumber: [],
  deliveryAddress: [],
  deliveryStatus: [],
  expectedArrivalFrom: [],
  expectedArrivalUntil: [],
  hasDeliveryMethod: [],
  itemShipped: [],
  originAddress: [],
  partOfOrder: [],
  trackingNumber: [],
  trackingUrl: [],
  addressCountry: [],
  addressLocality: [],
  addressRegion: [],
  extendedAddress: [],
  postOfficeBoxNumber: [],
  postalCode: [],
  streetAddress: [],
  address: [],
  email: [],
  legalName: [],
  taxID: [],
  telephone: [],
  familyName: [],
  givenName: [],
  brand: [],
  category: [],
  gtin: [],
  model: [],
  mpn: [],
  offers: [],
  areaServed: [],
  availableChannel: [],
  hoursAvailable: [],
  serviceOutput: [],
  serviceType: [],
  termsOfService: [],

  // Document identity / numbering variants

  invoiceNumber: [],
  receiptNumber: [],
  billNumber: [],
  cashDocNumber: [],
  cashSaleNumber: [],
  cashReceiptNumber: [],
  checkNumber: [],
  ticketNumber: [],
  documentNumber: [],
  docNo: [],
  billNo: [],
  invNo: [],
  receiptNo: [],
  invoiceNo: [],
  transactionNumber: [],
  transactionId: [],
  transactionCode: [],
  transactionReference: [],
  paymentReference: [],
  referenceNumber: [],
  referenceCode: [],
  approvalNumber: [],
  authorizationCode: [],
  authCode: [],
  serialNo: [],
  sequenceNumber: [],
  version: [],

  // Merchant / business / outlet info

  merchantName: [],
  merchantId: [],
  sellerName: [],
  sellerId: [],
  vendorName: [],
  vendorId: [],
  businessName: [],
  companyName: [],
  companyRegistrationNumber: [],
  businessRegistrationNumber: [],
  registrationNumber: [],
  registrationNo: [],
  gstId: [],
  gstNumber: [],
  gstRegistrationNumber: [],
  vatId: [],
  vatNumber: [],
  branch: [],
  branchCode: [],
  branchName: [],
  branchNumber: [],
  outletName: [],
  outletCode: [],
  storeName: [],
  storeNumber: [],
  storeCode: [],
  locationName: [],
  locationLabel: [],
  website: [],
  faxNumber: [],
  contactNumber: [],
  socialUrl: [],
  socialHandle: [],
  loyaltyProgram: [],
  memberNumber: [],
  membershipNumber: [],
  loyaltyCard: [],
  loyaltyCardNumber: [],
  pointsAwarded: [],
  pointsBalance: [],

  // Merchant / customer / ship-to addresses

  shippingAddress: [],
  shipToAddress: [],
  shipFromAddress: [],
  shipName: [],
  shipToName: [],
  customerAddress: [],
  merchantAddress: [],
  addressLine1: [],
  addressLine2: [],
  addressLine3: [],
  city: [],
  district: [],
  locality: [],
  region: [],
  state: [],
  province: [],
  county: [],
  country: [],
  countryCode: [],
  zip: [],
  zipCode: [],
  building: [],
  floor: [],
  unit: [],
  suite: [],

  // Customer / shipper / relationship info

  customerId: [],
  customerName: [],
  customerNumber: [],
  customerCode: [],
  customerReference: [],
  buyerName: [],
  buyerId: [],
  shipperId: [],
  shipperName: [],
  shipperCode: [],
  carrier: [],
  carrierName: [],
  carrierCode: [],
  deliveryProvider: [],
  courier: [],
  courierName: [],
  employeeName: [],
  salesperson: [],
  salespersonId: [],
  salespersonReference: [],

  // POS / cashier / terminal / operator context

  cashier: [],
  cashierName: [],
  cashierId: [],
  cashierNumber: [],
  operator: [],
  operatorName: [],
  operatorId: [],
  operatorNumber: [],
  clerk: [],
  clerkId: [],
  clerkNumber: [],
  server: [],
  serverName: [],
  serverId: [],
  serverNumber: [],
  waiter: [],
  waitress: [],
  register: [],
  registerNumber: [],
  registerId: [],
  registerLabel: [],
  regNumber: [],
  terminalNumber: [],
  terminalId: [],
  terminalCode: [],
  posId: [],
  posLocation: [],
  posNumber: [],
  station: [],
  stationId: [],
  stationNumber: [],
  stationName: [],
  machineNumber: [],
  machineId: [],
  counter: [],
  counterLabel: [],
  laneNumber: [],
  laneId: [],
  tillNumber: [],
  tillId: [],
  drawerNumber: [],
  device: [],
  deviceNumber: [],
  shift: [],
  shiftNumber: [],
  sessionId: [],
  sessionNumber: [],

  // Time / date fields

  date: [],
  time: [],
  dateTime: [],
  businessDate: [],
  businessTime: [],
  openedTime: [],
  openedAt: [],
  closedTime: [],
  closedAt: [],
  printedTime: [],
  printTime: [],
  printDate: [],
  settlementTime: [],
  serviceDate: [],
  dueDate: [],
  shippedDate: [],
  deliveryDate: [],

  // Service mode / venue context

  serviceMode: [],
  serviceTypeLabel: [],
  orderType: [],
  diningMode: [],
  dineIn: [],
  takeAway: [],
  takeaway: [],
  takeOut: [],
  eatIn: [],
  walkIn: [],
  onlineOrder: [],
  onlineStatus: [],
  pickup: [],
  curbsidePickup: [],
  deliveryMode: [],
  channel: [],
  salesChannel: [],
  sourcePlatform: [],
  diningRoom: [],
  section: [],
  room: [],
  area: [],
  table: [],
  tableNumber: [],
  tableName: [],
  seat: [],
  seatNumber: [],
  guestCount: [],
  guestNumber: [],
  guests: [],
  partySize: [],
  covers: [],
  pax: [],
  personNumber: [],
  guestReference: [],
  orderNote: [],
  note: [],
  remarks: [],

  // Payment / tender / card / settlement

  paymentMode: [],
  paymentTender: [],
  paymentProvider: [],
  tenderType: [],
  tenderedAmount: [],
  paidAmount: [],
  totalPaid: [],
  amountPaid: [],
  paymentAmount: [],
  amountReceived: [],
  received: [],
  receivedAmount: [],
  balanceDue: [],
  cashTendered: [],
  cashReceived: [],
  cash: [],
  change: [],
  changeDue: [],
  voucherAmount: [],
  chequeAmount: [],
  debitAmount: [],
  debitCardAmount: [],
  creditAmount: [],
  creditCardAmount: [],
  cardAmount: [],
  cardType: [],
  cardBrand: [],
  cardScheme: [],
  paymentCardNetwork: [],
  accountTailDigits: [],
  cardLast4: [],
  maskedPan: [],
  rrn: [],
  aid: [],
  entryMethod: [],
  tip: [],
  gratuity: [],
  suggestedGratuity: [],
  serviceCharge: [],

  // Totals / money / adjustments

  subtotal: [],
  subTotal: [],
  grossAmount: [],
  netAmount: [],
  grandTotal: [],
  total: [],
  finalTotal: [],
  amountDue: [],
  payable: [],
  totalAmount: [],
  totalAmountDue: [],
  totalExcludingTax: [],
  totalIncludingTax: [],
  totalExcludingGst: [],
  totalIncludingGst: [],
  totalSalesExcludingGst: [],
  totalSalesIncludingGst: [],
  totalSalesInclusive: [],
  totalSalesExclusive: [],
  minimumPayment: [],
  receivedTotal: [],
  netSales: [],
  grossSales: [],
  amountTendered: [],
  totalSaving: [],
  savings: [],
  savingAmount: [],
  discountAmount: [],
  discountSummary: [],
  lineDiscountAmount: [],
  rounding: [],
  roundAdjustment: [],
  roundingAdjustment: [],
  roundOff: [],

  // Tax fields / tax buckets

  tax: [],
  taxAmount: [],
  taxTotal: [],
  taxRate: [],
  taxPercent: [],
  taxCode: [],
  taxLabel: [],
  taxSummary: [],
  taxSummaryLabel: [],
  taxableAmount: [],
  taxIncluded: [],
  taxExcluded: [],
  gst: [],
  gstAmount: [],
  gstRate: [],
  gstPercent: [],
  gstIncluded: [],
  gstPayable: [],
  gstRegistrationId: [],
  gstSummaryAmount: [],
  gstSummaryTax: [],
  vat: [],
  vatAmount: [],
  vatRate: [],
  vatPercent: [],
  serviceTax: [],
  salesTax: [],
  foodTax: [],
  liquorTax: [],
  otherTaxes: [],
  taxBucket: [],
  taxBucketLabel: [],
  standardRatedAmount: [],
  zeroRatedAmount: [],
  reducedRatedAmount: [],
  nonTaxableAmount: [],
  inclusiveTaxAmount: [],
  exclusiveTaxAmount: [],

  // Quantity / count / measurement fields

  quantity: [],
  qty: [],
  itemCount: [],
  itemsCount: [],
  totalItems: [],
  totalItemCount: [],
  totalQuantity: [],
  totalQty: [],
  quantityUnit: [],
  unit: [],
  unitText: [],
  unitCode: [],
  unitPrice: [],
  uPrice: [],
  pricePerUnit: [],
  pricePerItem: [],
  linePrice: [],
  lineAmount: [],
  lineTotal: [],
  lineSubtotal: [],
  lineTaxAmount: [],
  basePrice: [],
  discountedPrice: [],
  priceBeforeDiscount: [],
  priceAfterDiscount: [],
  weightedQuantity: [],
  measuredQuantity: [],
  weight: [],
  weightUnit: [],
  weighedItem: [],
  volume: [],
  volumeUnit: [],
  litres: [],
  liters: [],
  pricePerKg: [],
  pricePerLb: [],
  pricePerLitre: [],
  pricePerLiter: [],
  eligibleQuantity: [],
  referenceQuantity: [],
  referenceUnit: [],
  minPrice: [],
  maxPrice: [],
  currencySymbol: [],

  // Item / line item / product detail

  itemCode: [],
  itemId: [],
  itemNumber: [],
  itemName: [],
  itemDescription: [],
  itemVariant: [],
  itemModifier: [],
  itemCategory: [],
  itemGroup: [],
  itemEntityType: [],
  itemLabel: [],
  barcode: [],
  plu: [],
  stockCode: [],
  catalogCode: [],
  productCode: [],
  productId: [],
  productName: [],
  productDescription: [],
  productLabel: [],
  menuItemName: [],
  serviceName: [],
  modifierText: [],
  modifierPrice: [],
  modifierGroup: [],
  size: [],
  color: [],
  flavor: [],
  modelNumber: [],
  batchNumber: [],
  lotNumber: [],
  serialCode: [],
  comboName: [],
  comboComponent: [],
  bundleLabel: [],
  bundleName: [],
  includedItem: [],
  addOnItem: [],
  complimentary: [],
  isFreeItem: [],
  freeItem: [],
  discountPercent: [],
  lineNote: [],

  // Fuel / weighed goods / specialty receipt fields

  pumpNumber: [],
  pumpId: [],
  nozzleNumber: [],
  fuelType: [],
  fuelGrade: [],
  octane: [],
  odometer: [],
  mileage: [],

  // Shipping / fulfillment / logistics

  shipmentNumber: [],
  shipmentId: [],
  shippingMethod: [],
  shippingMode: [],
  shippingCost: [],
  shippingFee: [],
  handlingFee: [],
  dispatchDate: [],
  expectedDeliveryDate: [],
  expectedShipDate: [],
  pickupDate: [],
  pickupTime: [],

  // Misc document content commonly seen on receipts / orders

  receiptType: [],
  documentType: [],
  copyType: [],
  customerCopy: [],
  merchantCopy: [],
  footerNote: [],
  headerNote: [],
  policyNote: [],
  refundPolicy: [],
  exchangePolicy: [],
  returnPolicy: [],
  promotionalMessage: [],
  campaignMessage: [],
  surveyMessage: [],
  surveyUrl: [],
  onlineOrderUrl: [],
  paymentLink: [],
  qrCodeValue: [],
  barcodeValue: [],
  couponCode: [],
  promoCode: [],
  promoDescription: [],
  branchTelephone: [],
  contactEmail: [],
  websiteUrl: [],
  socialPage: [],
  manager: [],
  managerName: [],
  attendant: [],
  attendantName: [],
  clerkName: [],
  openedBy: [],
  closedBy: [],
  preparedBy: [],
  fulfilledBy: [],
  servedBy: [],

  // High-level flat business info that still appears on orders

  merchantType: [],
  storeType: [],
  businessType: [],
  receiptLanguage: [],
  locale: [],
  regionCode: [],
  countryName: [],
}
