export default {
  // Core order / document identity

  acceptedOffer: [
    'Wireless Mouse',
    'USB-C Cable',
    'HDMI Adapter',
    'Laptop Stand',
    'Mechanical Keyboard',
    'Noise Cancelling Headphones',
    '27-inch Monitor',
    'Webcam',
    'Portable SSD',
    'External Hard Drive',
    'Phone Charger',
    'Power Bank',
    'Bluetooth Speaker',
    'Smart Watch',
    'Tablet Case',
    'Screen Protector',
    'Gaming Mouse Pad',
    'Ethernet Cable',
    'Router',
    'Wi-Fi Extender',
    'Printer Ink Cartridge',
    'Printer Paper',
    'Desk Lamp',
    'Office Chair',
    'Standing Desk',
    'Notebook Set',
    'Ballpoint Pen Pack',
    'Stapler',
    'Paper Clips',
    'Sticky Notes',
    'Backpack',
    'Laptop Sleeve',
    'Travel Mug',
    'Water Bottle',
    'Coffee Beans',
    'Green Tea Pack',
    'Organic Honey',
    'Protein Powder',
    'Vitamin C Tablets',
    'Daily Multivitamin',
    'Hand Soap',
    'Shampoo',
    'Conditioner',
    'Body Wash',
    'Face Moisturizer',
    'Sunscreen SPF 50',
    'Laundry Detergent',
    'Dish Soap',
    'Toilet Paper Pack',
    'Paper Towels',
    'Cleaning Spray',
    'Vacuum Cleaner',
    'Air Purifier Filter',
    'LED Light Bulb',
    'Batteries AA Pack',
    'Batteries AAA Pack',
    'Extension Cord',
    'Surge Protector',
    'Tool Kit',
    'Screwdriver Set',
    'Hammer',
    'Adjustable Wrench',
    'Cordless Drill',
    'Paint Brush Set',
    'Garden Hose',
    'Plant Fertilizer',
    'Flower Pot',
    'Indoor Plant',
    'Pet Food',
    'Dog Leash',
    'Cat Litter',
    'Pet Shampoo',
    'Baby Diapers',
    'Baby Wipes',
    'Infant Formula',
    'Stroller',
    'Car Seat',
    'Toy Building Blocks',
    'Board Game',
    'Puzzle Set',
    'Hardcover Notebook',
    'Sketchbook',
    'Watercolor Paint Set',
    'Yoga Mat',
    'Dumbbell Set',
    'Resistance Bands',
    'Running Shoes',
    'Hiking Backpack',
    'Camping Tent',
    'Sleeping Bag',
    'Travel Pillow',
    'Suitcase',
    'Passport Holder',
    'Gift Card',
    'Birthday Card',
    'Gift Wrap',
    'Flower Bouquet',
    'Chocolate Box',
    'Cheeseburger',
    'French Fries',
    'Chicken Nuggets',
    'Pepperoni Pizza',
    'Margherita Pizza',
    'Veggie Burger',
    'Caesar Salad',
    'Greek Salad',
    'Tomato Soup',
    'Grilled Chicken Sandwich',
    'Club Sandwich',
    'Turkey Wrap',
    'Ham and Cheese Panini',
    'Fish and Chips',
    'Chicken Alfredo Pasta',
    'Spaghetti Bolognese',
    'Mac and Cheese',
    'Beef Tacos',
    'Chicken Burrito',
    'Sushi Combo',
    'Salmon Nigiri',
    'California Roll',
    'Pad Thai',
    'Fried Rice',
    'Sweet and Sour Chicken',
    'Butter Chicken',
    'Garlic Naan',
    'Paneer Curry',
    'Falafel Wrap',
    'Hummus Plate',
    'Steak Dinner',
    'Roasted Vegetables',
    'Mashed Potatoes',
    'Breakfast Burrito',
    'Pancake Stack',
    'Waffle Combo',
    'Omelette',
    'Bacon and Eggs',
    'Avocado Toast',
    'Fruit Bowl',
    'Ice Cream Sundae',
    'Chocolate Cake Slice',
    'Blueberry Muffin',
    'Croissant',
    'Cappuccino',
    'Latte',
    'Espresso',
    'Iced Coffee',
    'Orange Juice',
    'Bottled Water',
    'Sparkling Water',
    'Soft Drink',
    'Family Meal Bundle',
    'Lunch Combo',
    'Dinner Combo',
    'Kids Meal',
    'Meal Deal',
    'Value Meal',
    'Combo Meal',
    'Add Extra Cheese',
    'Add Bacon',
    'Add Avocado',
    'Extra Sauce',
    'No Onions',
    'Large Size Upgrade',
    'Medium Size Upgrade',
    'Gift Wrapping Service',
    'Assembly Service',
    'Installation Service',
    'Express Shipping',
    'Standard Shipping',
    'Next Day Delivery',
    'Same Day Delivery',
    'Store Pickup',
    'Curbside Pickup',
    'White Glove Delivery',
    'Extended Warranty',
    'Accidental Damage Protection',
    'Premium Support',
    'Priority Support',
    'Setup Assistance',
    'Onsite Installation',
    'Remote Consultation',
    'Technical Support Session',
    'Home Cleaning Service',
    'Deep Cleaning Service',
    'Window Cleaning Service',
    'Car Wash',
    'Interior Detailing',
    'Oil Change',
    'Tire Rotation',
    'Brake Inspection',
    'Engine Diagnostic',
    'Haircut',
    'Hair Coloring',
    'Beard Trim',
    'Spa Treatment',
    'Massage Session',
    'Manicure',
    'Pedicure',
    'Dental Cleaning',
    'Eye Examination',
    'General Consultation',
    'Therapy Session',
    'Personal Training Session',
    'Yoga Class',
    'Pilates Class',
    'Swimming Lesson',
    'Music Lesson',
    'Language Course',
    'Online Workshop',
    'Webinar Access',
    'Conference Ticket',
    'VIP Pass',
    'General Admission Ticket',
    'Adult Ticket',
    'Child Ticket',
    'Student Ticket',
    'Senior Ticket',
    'Round Trip Flight',
    'One Way Flight',
    'Hotel Stay',
    'Room Reservation',
    'Car Rental',
    'Airport Transfer',
    'Travel Insurance',
    'Museum Entry',
    'Concert Ticket',
    'Cinema Ticket',
    'Theater Ticket',
    'Theme Park Pass',
    'Annual Membership',
    'Monthly Membership',
    'Basic Subscription',
    'Standard Subscription',
    'Premium Subscription',
    'Pro Subscription',
    'Enterprise Subscription',
    'Starter Plan',
    'Business Plan',
    'Team Plan',
    'Family Plan',
    'Unlimited Plan',
    'Data Add-on',
    'Cloud Storage Plan',
    'Email Hosting',
    'Domain Registration',
    'Website Hosting',
    'SSL Certificate',
    'Software License',
    'Antivirus License',
    'Productivity Suite',
    'Design Software License',
    'Developer Tool Subscription',
    'API Usage Package',
    'Compute Credits',
    'Support Retainer',
    'Consulting Package',
    'Audit Service',
    'Design Package',
    'Branding Package',
    'SEO Package',
    'Marketing Campaign Package',
    'Photography Session',
    'Video Editing Service',
    'Translation Service',
    'Copywriting Service',
    'Legal Review',
    'Accounting Service',
    'Bookkeeping Package',
    'Tax Filing Service',
    'Recruitment Service',
    'Background Check Service',
    'Security Monitoring',
    'Managed Hosting',
    'Backup Service',
    'Disaster Recovery Plan',
    'Maintenance Plan',
    'Service Contract',
    'Repair Service',
    'Replacement Part',
    'Battery Replacement',
    'Screen Replacement',
    'Inspection Fee',
    'Service Fee',
    'Handling Fee',
    'Convenience Fee',
    'Booking Fee',
    'Reservation Fee',
    'Processing Fee',
    'Membership Fee',
    'Activation Fee',
    'Cancellation Protection',
    'Late Checkout',
    'Early Check-in',
    'Seat Selection',
    'Extra Baggage',
    'Priority Boarding',
    'In-flight Meal',
    'Travel Add-on',
    'Insurance Add-on',
    'Rental Protection',
    'Fuel Service Option',
    'Roadside Assistance',
    'Subscription Renewal',
    'License Renewal',
    'Membership Renewal',
    'Upgrade to Premium',
    'Upgrade to Business',
    'Plan Upgrade',
    'Storage Upgrade',
    'Bandwidth Add-on',
    'Additional User Seat',
    'Extra Team Seat',
    'Admin Seat',
    'Viewer Seat',
    'Editor Seat',
    'Workshop Registration',
    'Training Package',
    'Certification Exam',
    'Exam Retake',
    'Course Material',
    'Study Guide',
    'Lab Access',
    'Practice Test Access',
    'eBook Download',
    'Audiobook',
    'Printed Book',
    'Magazine Subscription',
    'Newspaper Subscription',
    'Recipe Box',
    'Meal Kit',
    'Fresh Produce Box',
    'Snack Box',
    'Coffee Subscription',
    'Tea Subscription',
    'Wine Club Membership',
    'Cheese Selection Box',
    'Bakery Box',
    'Seasonal Gift Box',
    'Holiday Bundle',
    'Starter Bundle',
    'Essentials Bundle',
    'Premium Bundle',
    'Home Office Bundle',
    'Gaming Bundle',
    'Travel Bundle',
    'Wellness Bundle',
    'Beauty Bundle',
    'Baby Care Bundle',
    'Pet Care Bundle',
    'Cleaning Bundle',
    'Kitchen Bundle',
    'Bedroom Set',
    'Dining Set',
    'Sofa Set',
    'Coffee Table',
    'Bookshelf',
    'Mattress',
    'Bedsheet Set',
    'Blanket',
    'Towel Set',
    'Cookware Set',
    'Knife Set',
    'Blender',
    'Coffee Maker',
    'Air Fryer',
    'Microwave Oven',
    'Refrigerator',
    'Washing Machine',
    'Dryer',
    'Dishwasher',
    'Smart TV',
    'Streaming Device',
    'Game Console',
    'Video Game',
    'Controller',
    'VR Headset',
    'Camera Lens',
    'Tripod',
    'Memory Card',
    'Drone',
    'Smart Home Hub',
    'Smart Light',
    'Smart Plug',
    'Smart Lock',
    'Doorbell Camera',
    'Security Camera',
    'Thermostat',
    'Robot Vacuum',
    'Electric Toothbrush',
    'Hair Dryer',
    'Shaver',
    'Face Serum',
    'Lip Balm',
    'Perfume',
    'T-shirt',
    'Jeans',
    'Sneakers',
    'Jacket',
    'Winter Coat',
    'Dress Shirt',
    'Socks Pack',
    'Underwear Pack',
    'Hat',
    'Scarf',
    'Gloves',
    'Sunglasses',
    'Watch',
    'Wallet',
    'Handbag',
    'Belt',
    'Necklace',
    'Earrings',
    'Bracelet',
    'Ring',
    'Wedding Invitation Suite',
    'Event Decoration Package',
    'Catering Package',
    'Venue Booking',
    'Photography Package',
    'DJ Service',
    'Live Band Performance',
    'Floral Decoration Package',
    'Wedding Cake',
    'Party Supplies Pack',
    'Balloon Arrangement',
    'Custom Printed Banner',
    'Corporate Catering',
    'Team Lunch Package',
    'Office Snack Delivery',
    'Bulk Water Delivery',
    'Printing Service',
    'Poster Printing',
    'Business Card Printing',
    'Flyer Printing',
    'Sticker Printing',
    'Custom Merchandise',
    'Branded T-shirt',
    'Promotional Pen Set',
    'Mug Printing',
    'Embroidery Service',
    '3D Printing Service',
    'Prototype Fabrication',
    'CNC Machining Service',
    'Electronics Repair',
    'Phone Repair',
    'Laptop Repair',
    'Data Recovery Service',
    'Server Maintenance',
    'Network Installation',
    'Firewall Setup',
    'Website Design',
    'Website Development',
    'Mobile App Development',
    'UI Design Service',
    'UX Research Package',
    'Content Strategy Session',
    'Product Discovery Workshop',
    'Cloud Migration Service',
    'DevOps Setup',
    'Monitoring Setup',
    'Penetration Test',
    'Code Review Service',
    'Architecture Consultation',
    'Custom Integration',
    'CRM Setup',
    'ERP Implementation',
    'Migration Package',
    'Analytics Setup',
    'Ad Campaign Setup',
    'Social Media Management',
    'Newsletter Setup',
    'Lead Generation Package',
    'Virtual Assistant Package',
    'Customer Support Package',
    'Outbound Calling Package',
    'Answering Service',
    'Laundry Service',
    'Dry Cleaning Service',
    'Ironing Service',
    'Alteration Service',
    'Shoe Repair',
    'Key Cutting Service',
    'Locksmith Service',
    'Pest Control Service',
    'Plumbing Repair',
    'Electrical Repair',
    'Painting Service',
    'Moving Service',
    'Packing Service',
    'Storage Rental',
    'Self Storage Unit',
    'Warehouse Storage',
    'Cold Storage Service',
    'Freight Shipping',
    'Courier Delivery',
    'Messenger Service',
    'Parcel Insurance',
    'Customs Clearance Service',
    'Import Handling Service',
    'Export Documentation Service',
    'Brokerage Service',
    'Fuel Purchase',
    'Diesel Purchase',
    'Premium Gasoline',
    'Regular Unleaded',
    'Engine Oil',
    'Windshield Washer Fluid',
    'Car Battery',
    'Wiper Blades',
    'Car Accessories Kit',
    'Motorcycle Helmet',
    'Bicycle Repair Service',
    'Bike Rental',
    'Scooter Rental',
    'Boat Rental',
    'Equipment Rental',
    'Camera Rental',
    'Party Equipment Rental',
    'Projector Rental',
    'Sound System Rental',
    'Tent Rental',
    'Chair Rental',
    'Table Rental',
    'Medical Supply Kit',
    'First Aid Kit',
    'Prescription Refill',
    'OTC Medicine',
    'Bandage Pack',
    'Thermometer',
    'Blood Pressure Monitor',
    'Fitness Tracker',
    'Meal Prep Service',
    'Diet Consultation',
    'Nutrition Plan',
    'Meditation App Subscription',
    'Sleep Program Subscription',
    'Childcare Service',
    'Tutoring Session',
    'Homework Help Session',
    'Test Prep Course',
    'Driver Training Lesson',
    'Parking Pass',
    'Monthly Parking Permit',
    'Toll Pass Recharge',
    'Utility Bill Payment',
    'Internet Bill Payment',
    'Mobile Recharge',
    'Prepaid Top-up',
    'Donation',
    'Charity Contribution',
    'Deposit',
    'Security Deposit',
    'Partial Payment',
    'Final Payment',
    'Balance Payment',
    'Down Payment',
    'Installment 1',
    'Installment 2',
    'Installment 3',
    'Retainer Payment',
    'Milestone Payment',
    'Custom Order',
    'Special Order Item',
    'Pre-order Item',
    'Backorder Item',
    'Limited Edition Item',
    'Exclusive Offer',
    'Bundle Discount Offer',
    'Buy One Get One Offer',
    'Seasonal Promotion',
    'Loyalty Reward Item',
    'Member Exclusive Item',
    'Complimentary Dessert',
    'Free Gift',
    'Bonus Item',
    'Trial Subscription',
    'Introductory Plan',
    'Founders Plan',
    'Legacy Plan',
    'Beta Access',
    'Early Access Pass',
    'Reserved Seat',
    'Reserved Table',
    'Private Room Booking',
    'Catering Add-on',
    'Decoration Add-on',
    'Audio Visual Add-on',
    'Support Hours Package',
    'Consultation Hours Pack',
    'Premium Onboarding',
    'Implementation Package',
    'Migration Assistance',
    'Managed Service Package',
    'Custom Report Package',
    'Advanced Analytics Package',
    'Compliance Package',
    'Governance Package',
    'Training Credits',
    'Usage Credits',
    'Download Credits',
    'Scan Credits',
    'Token Package',
    'Compute Package',
    'Storage Package',
    'Monthly Box Subscription',
    'Annual Service Plan',
    'Prepaid Service Package',
    'Home Visit Service',
    'In-store Service',
    'Remote Service',
    'Onsite Service',
    'Emergency Service Call',
    'Weekend Service Call',
    'After Hours Service',
    'Priority Dispatch',
    'Replacement Unit',
    'Loaner Device',
    'Refurbished Device',
    'Open Box Item',
    'Certified Used Item',
    'Digital Download',
    'Downloadable Template',
    'Premium Template Pack',
    'Icon Pack',
    'Font License',
    'Plugin License',
    'Theme License',
    'Asset Pack',
    'Sound Effects Pack',
    'Video Template Pack',
    'Stock Photo Pack',
    'Illustration Pack',
    'Merchandise Pack',
    'Office Supplies Pack',
    'Starter Kit',
    'Welcome Kit',
    'Sample Pack',
    'Refill Pack',
    'Replacement Filter',
    'Refill Cartridge',
    'Subscription Box Refill',
    'Emergency Food Pack',
    'Water Filter Cartridge',
    'Air Filter Replacement',
    'Premium Roast Coffee',
    'Single Origin Coffee',
    'Loose Leaf Tea',
    'Energy Drink',
    'Sports Drink',
    'Protein Bar',
    'Granola Box',
    'Frozen Meal',
    'Fresh Salad Bowl',
    'Soup and Sandwich Combo',
    'Chicken Rice Bowl',
    'Beef Noodle Bowl',
    'Veggie Wrap Combo',
    'Party Platter',
    'Fruit Platter',
    'Cheese Platter',
    'Dessert Platter',
    'Family Pizza Deal',
    'Weekend Special',
    'Lunch Special',
    'Breakfast Combo',
    'Happy Hour Special',
    'Chef Special',
    'Seasonal Menu Item',
    'Limited Time Offer',
    'Signature Dish',
    'House Blend Coffee',
    'Premium Tea Selection',
    'Artisan Bread Loaf',
    'Gourmet Burger',
    'Handmade Pasta',
    'Roast Chicken Dinner',
    'BBQ Platter',
    'Seafood Platter',
    'Vegetarian Combo',
    'Vegan Bowl',
    'Gluten Free Meal',
    'Dairy Free Dessert',
    'Kids Activity Pack',
    'Museum Family Pass',
    'Workshop Seat',
    'Private Lesson',
    'Group Lesson',
    'Monthly Class Pass',
    'Drop-in Class',
    'Subscription Seat',
    'Workspace Access',
    'Coworking Day Pass',
    'Meeting Room Booking',
    'Conference Room Booking',
    'Virtual Office Plan',
    'Mail Handling Service',
    'Reception Service',
    'Document Scanning Service',
    'Shredding Service',
    'Archive Storage Service',
    'Proofreading Service',
    'Editing Service',
    'Resume Writing Service',
    'Portfolio Review',
    'Career Coaching Session',
    'Business Coaching Session',
    'Executive Coaching Package',
    'Mindfulness Session',
    'Telehealth Consultation',
    'Veterinary Consultation',
    'Pet Grooming Service',
    'Dog Walking Service',
    'Pet Boarding',
    'Pet Daycare',
    'Horse Riding Lesson',
    'Golf Lesson',
    'Tennis Lesson',
    'Court Booking',
    'Gym Day Pass',
    'Sauna Access',
    'Pool Access',
    'Spa Day Pass',
    'Massage Package',
    'Wellness Retreat Booking',
    'Retreat Deposit',
    'Festival Pass',
    'Exhibition Ticket',
    'Trade Show Pass',
    'Networking Event Ticket',
    'Workshop Bundle',
    'Course Bundle',
    'Product Bundle',
    'Service Bundle',
    'Starter Package',
    'Growth Package',
    'Scale Package',
    'Custom Package',
  ],
  billingAddress: [],
  broker: [],
  confirmationNumber: [],
  customer: [],
  discount: [],
  discountCode: [],
  discountCurrency: [],
  isGift: [],
  orderDate: [],
  orderDelivery: [],
  orderNumber: [],
  orderStatus: [],
  orderedItem: [],
  partOfInvoice: [],
  paymentDueDate: [],
  paymentMethod: [],
  paymentMethodId: [],
  paymentUrl: [],
  seller: [],
  additionalType: [],
  alternateName: [],
  description: [],
  disambiguatingDescription: [],
  identifier: [],
  image: [],
  mainEntityOfPage: [],
  name: [],
  owner: [],
  potentialAction: [],
  sameAs: [],
  subjectOf: [],
  url: [],

  // Invoice / offer / delivery / item / address / party / product / service carry-over

  accountId: [],
  billingPeriod: [],
  minimumPaymentDue: [],
  paymentStatus: [],
  provider: [],
  referencesOrder: [],
  scheduledPaymentDate: [],
  totalPaymentDue: [],
  orderItemNumber: [],
  orderItemStatus: [],
  orderQuantity: [],
  acceptedPaymentMethod: [],
  addOn: [],
  additionalProperty: [],
  availability: [],
  businessFunction: [],
  itemCondition: [],
  itemOffered: [],
  price: [],
  priceCurrency: [],
  priceSpecification: [],
  priceValidUntil: [],
  sku: [],
  serialNumber: [],
  deliveryAddress: [],
  deliveryStatus: [],
  expectedArrivalFrom: [],
  expectedArrivalUntil: [],
  hasDeliveryMethod: [],
  itemShipped: [],
  originAddress: [],
  partOfOrder: [],
  trackingNumber: [],
  trackingUrl: [],
  addressCountry: [],
  addressLocality: [],
  addressRegion: [],
  extendedAddress: [],
  postOfficeBoxNumber: [],
  postalCode: [],
  streetAddress: [],
  address: [],
  email: [],
  legalName: [],
  taxID: [],
  telephone: [],
  familyName: [],
  givenName: [],
  brand: [],
  category: [],
  gtin: [],
  model: [],
  mpn: [],
  offers: [],
  areaServed: [],
  availableChannel: [],
  hoursAvailable: [],
  serviceOutput: [],
  serviceType: [],
  termsOfService: [],

  // Document identity / numbering variants

  invoiceNumber: [],
  receiptNumber: [],
  billNumber: [],
  cashDocNumber: [],
  cashSaleNumber: [],
  cashReceiptNumber: [],
  checkNumber: [],
  ticketNumber: [],
  documentNumber: [],
  docNo: [],
  billNo: [],
  invNo: [],
  receiptNo: [],
  invoiceNo: [],
  transactionNumber: [],
  transactionId: [],
  transactionCode: [],
  transactionReference: [],
  paymentReference: [],
  referenceNumber: [],
  referenceCode: [],
  approvalNumber: [],
  authorizationCode: [],
  authCode: [],
  serialNo: [],
  sequenceNumber: [],
  version: [],

  // Merchant / business / outlet info

  merchantName: [],
  merchantId: [],
  sellerName: [],
  sellerId: [],
  vendorName: [],
  vendorId: [],
  businessName: [],
  companyName: [],
  companyRegistrationNumber: [],
  businessRegistrationNumber: [],
  registrationNumber: [],
  registrationNo: [],
  gstId: [],
  gstNumber: [],
  gstRegistrationNumber: [],
  vatId: [],
  vatNumber: [],
  branch: [],
  branchCode: [],
  branchName: [],
  branchNumber: [],
  outletName: [],
  outletCode: [],
  storeName: [],
  storeNumber: [],
  storeCode: [],
  locationName: [],
  locationLabel: [],
  website: [],
  faxNumber: [],
  contactNumber: [],
  socialUrl: [],
  socialHandle: [],
  loyaltyProgram: [],
  memberNumber: [],
  membershipNumber: [],
  loyaltyCard: [],
  loyaltyCardNumber: [],
  pointsAwarded: [],
  pointsBalance: [],

  // Merchant / customer / ship-to addresses

  shippingAddress: [],
  shipToAddress: [],
  shipFromAddress: [],
  shipName: [],
  shipToName: [],
  customerAddress: [],
  merchantAddress: [],
  addressLine1: [],
  addressLine2: [],
  addressLine3: [],
  city: [],
  district: [],
  locality: [],
  region: [],
  state: [],
  province: [],
  county: [],
  country: [],
  countryCode: [],
  zip: [],
  zipCode: [],
  building: [],
  floor: [],
  unit: [],
  suite: [],

  // Customer / shipper / relationship info

  customerId: [],
  customerName: [],
  customerNumber: [],
  customerCode: [],
  customerReference: [],
  buyerName: [],
  buyerId: [],
  shipperId: [],
  shipperName: [],
  shipperCode: [],
  carrier: [],
  carrierName: [],
  carrierCode: [],
  deliveryProvider: [],
  courier: [],
  courierName: [],
  employeeName: [],
  salesperson: [],
  salespersonId: [],
  salespersonReference: [],

  // POS / cashier / terminal / operator context

  cashier: [],
  cashierName: [],
  cashierId: [],
  cashierNumber: [],
  operator: [],
  operatorName: [],
  operatorId: [],
  operatorNumber: [],
  clerk: [],
  clerkId: [],
  clerkNumber: [],
  server: [],
  serverName: [],
  serverId: [],
  serverNumber: [],
  waiter: [],
  waitress: [],
  register: [],
  registerNumber: [],
  registerId: [],
  registerLabel: [],
  regNumber: [],
  terminalNumber: [],
  terminalId: [],
  terminalCode: [],
  posId: [],
  posLocation: [],
  posNumber: [],
  station: [],
  stationId: [],
  stationNumber: [],
  stationName: [],
  machineNumber: [],
  machineId: [],
  counter: [],
  counterLabel: [],
  laneNumber: [],
  laneId: [],
  tillNumber: [],
  tillId: [],
  drawerNumber: [],
  device: [],
  deviceNumber: [],
  shift: [],
  shiftNumber: [],
  sessionId: [],
  sessionNumber: [],

  // Time / date fields

  date: [],
  time: [],
  dateTime: [],
  businessDate: [],
  businessTime: [],
  openedTime: [],
  openedAt: [],
  closedTime: [],
  closedAt: [],
  printedTime: [],
  printTime: [],
  printDate: [],
  settlementTime: [],
  serviceDate: [],
  dueDate: [],
  shippedDate: [],
  deliveryDate: [],

  // Service mode / venue context

  serviceMode: [],
  serviceTypeLabel: [],
  orderType: [],
  diningMode: [],
  dineIn: [],
  takeAway: [],
  takeaway: [],
  takeOut: [],
  eatIn: [],
  walkIn: [],
  onlineOrder: [],
  onlineStatus: [],
  pickup: [],
  curbsidePickup: [],
  deliveryMode: [],
  channel: [],
  salesChannel: [],
  sourcePlatform: [],
  diningRoom: [],
  section: [],
  room: [],
  area: [],
  table: [],
  tableNumber: [],
  tableName: [],
  seat: [],
  seatNumber: [],
  guestCount: [],
  guestNumber: [],
  guests: [],
  partySize: [],
  covers: [],
  pax: [],
  personNumber: [],
  guestReference: [],
  orderNote: [],
  note: [],
  remarks: [],

  // Payment / tender / card / settlement

  paymentMode: [],
  paymentTender: [],
  paymentProvider: [],
  tenderType: [],
  tenderedAmount: [],
  paidAmount: [],
  totalPaid: [],
  amountPaid: [],
  paymentAmount: [],
  amountReceived: [],
  received: [],
  receivedAmount: [],
  balanceDue: [],
  cashTendered: [],
  cashReceived: [],
  cash: [],
  change: [],
  changeDue: [],
  voucherAmount: [],
  chequeAmount: [],
  debitAmount: [],
  debitCardAmount: [],
  creditAmount: [],
  creditCardAmount: [],
  cardAmount: [],
  cardType: [],
  cardBrand: [],
  cardScheme: [],
  paymentCardNetwork: [],
  accountTailDigits: [],
  cardLast4: [],
  maskedPan: [],
  rrn: [],
  aid: [],
  entryMethod: [],
  tip: [],
  gratuity: [],
  suggestedGratuity: [],
  serviceCharge: [],

  // Totals / money / adjustments

  subtotal: [],
  subTotal: [],
  grossAmount: [],
  netAmount: [],
  grandTotal: [],
  total: [],
  finalTotal: [],
  amountDue: [],
  payable: [],
  totalAmount: [],
  totalAmountDue: [],
  totalExcludingTax: [],
  totalIncludingTax: [],
  totalExcludingGst: [],
  totalIncludingGst: [],
  totalSalesExcludingGst: [],
  totalSalesIncludingGst: [],
  totalSalesInclusive: [],
  totalSalesExclusive: [],
  minimumPayment: [],
  receivedTotal: [],
  netSales: [],
  grossSales: [],
  amountTendered: [],
  totalSaving: [],
  savings: [],
  savingAmount: [],
  discountAmount: [],
  discountSummary: [],
  lineDiscountAmount: [],
  rounding: [],
  roundAdjustment: [],
  roundingAdjustment: [],
  roundOff: [],

  // Tax fields / tax buckets

  tax: [],
  taxAmount: [],
  taxTotal: [],
  taxRate: [],
  taxPercent: [],
  taxCode: [],
  taxLabel: [],
  taxSummary: [],
  taxSummaryLabel: [],
  taxableAmount: [],
  taxIncluded: [],
  taxExcluded: [],
  gst: [],
  gstAmount: [],
  gstRate: [],
  gstPercent: [],
  gstIncluded: [],
  gstPayable: [],
  gstRegistrationId: [],
  gstSummaryAmount: [],
  gstSummaryTax: [],
  vat: [],
  vatAmount: [],
  vatRate: [],
  vatPercent: [],
  serviceTax: [],
  salesTax: [],
  foodTax: [],
  liquorTax: [],
  otherTaxes: [],
  taxBucket: [],
  taxBucketLabel: [],
  standardRatedAmount: [],
  zeroRatedAmount: [],
  reducedRatedAmount: [],
  nonTaxableAmount: [],
  inclusiveTaxAmount: [],
  exclusiveTaxAmount: [],

  // Quantity / count / measurement fields

  quantity: [],
  qty: [],
  itemCount: [],
  itemsCount: [],
  totalItems: [],
  totalItemCount: [],
  totalQuantity: [],
  totalQty: [],
  quantityUnit: [],
  unit: [],
  unitText: [],
  unitCode: [],
  unitPrice: [],
  uPrice: [],
  pricePerUnit: [],
  pricePerItem: [],
  linePrice: [],
  lineAmount: [],
  lineTotal: [],
  lineSubtotal: [],
  lineTaxAmount: [],
  basePrice: [],
  discountedPrice: [],
  priceBeforeDiscount: [],
  priceAfterDiscount: [],
  weightedQuantity: [],
  measuredQuantity: [],
  weight: [],
  weightUnit: [],
  weighedItem: [],
  volume: [],
  volumeUnit: [],
  litres: [],
  liters: [],
  pricePerKg: [],
  pricePerLb: [],
  pricePerLitre: [],
  pricePerLiter: [],
  eligibleQuantity: [],
  referenceQuantity: [],
  referenceUnit: [],
  minPrice: [],
  maxPrice: [],
  currencySymbol: [],

  // Item / line item / product detail

  itemCode: [],
  itemId: [],
  itemNumber: [],
  itemName: [],
  itemDescription: [],
  itemVariant: [],
  itemModifier: [],
  itemCategory: [],
  itemGroup: [],
  itemEntityType: [],
  itemLabel: [],
  barcode: [],
  plu: [],
  stockCode: [],
  catalogCode: [],
  productCode: [],
  productId: [],
  productName: [],
  productDescription: [],
  productLabel: [],
  menuItemName: [],
  serviceName: [],
  modifierText: [],
  modifierPrice: [],
  modifierGroup: [],
  size: [],
  color: [],
  flavor: [],
  modelNumber: [],
  batchNumber: [],
  lotNumber: [],
  serialCode: [],
  comboName: [],
  comboComponent: [],
  bundleLabel: [],
  bundleName: [],
  includedItem: [],
  addOnItem: [],
  complimentary: [],
  isFreeItem: [],
  freeItem: [],
  discountPercent: [],
  lineNote: [],

  // Fuel / weighed goods / specialty receipt fields

  pumpNumber: [],
  pumpId: [],
  nozzleNumber: [],
  fuelType: [],
  fuelGrade: [],
  octane: [],
  odometer: [],
  mileage: [],

  // Shipping / fulfillment / logistics

  shipmentNumber: [],
  shipmentId: [],
  shippingMethod: [],
  shippingMode: [],
  shippingCost: [],
  shippingFee: [],
  handlingFee: [],
  dispatchDate: [],
  expectedDeliveryDate: [],
  expectedShipDate: [],
  pickupDate: [],
  pickupTime: [],

  // Misc document content commonly seen on receipts / orders

  receiptType: [],
  documentType: [],
  copyType: [],
  customerCopy: [],
  merchantCopy: [],
  footerNote: [],
  headerNote: [],
  policyNote: [],
  refundPolicy: [],
  exchangePolicy: [],
  returnPolicy: [],
  promotionalMessage: [],
  campaignMessage: [],
  surveyMessage: [],
  surveyUrl: [],
  onlineOrderUrl: [],
  paymentLink: [],
  qrCodeValue: [],
  barcodeValue: [],
  couponCode: [],
  promoCode: [],
  promoDescription: [],
  branchTelephone: [],
  contactEmail: [],
  websiteUrl: [],
  socialPage: [],
  manager: [],
  managerName: [],
  attendant: [],
  attendantName: [],
  clerkName: [],
  openedBy: [],
  closedBy: [],
  preparedBy: [],
  fulfilledBy: [],
  servedBy: [],

  // High-level flat business info that still appears on orders

  merchantType: [],
  storeType: [],
  businessType: [],
  receiptLanguage: [],
  locale: [],
  regionCode: [],
  countryName: [],
}
