#!/usr/bin/env node
import { dirname } from 'path'
import { mkdir, readdir, readFile, writeFile } from 'fs/promises'
import { toCompressed, toBase64String } from '@sovereignbase/bytecodec'

const tokenizersRoot = './src/06_fp32_export_onnx_models'
const gpuModelsRoot = './src/07_mixed-fp16_gpu_onnx_models'
const cpuModelsRoot = './src/08_uint8_cpu_onnx_models'
const outRoot = './src/09_autogenerated_typescript_project'

async function getLanguages() {
  const tokenizerLanguages = new Set(await readdir(tokenizersRoot))
  const gpuModelLanguages = new Set(await readdir(gpuModelsRoot))
  const cpuModelLanguages = new Set(await readdir(cpuModelsRoot))

  return [...tokenizerLanguages].filter(
    (language) =>
      gpuModelLanguages.has(language) && cpuModelLanguages.has(language)
  )
}

async function writeEntrypoint(outRoot, languages) {
  let file = ``
  const outPath = `${outRoot}/${'index.ts'}`
  for (const language of languages) {
    file += `export { tokenizer${language.toUpperCase()}, gpuModel${language.toUpperCase()}, cpuModel${language.toUpperCase()} } from './models/${language}/index.js'`
  }
  await mkdir(dirname(outRoot), { recursive: true })
  await writeFile(outPath, file)
}

async function main() {
  const languages = await getLanguages()
  for (const language of languages) {
    const tokenizerPath = `${tokenizersRoot}/${language}/tokenizer.model`
    const gpuModelPath = `${gpuModelsRoot}/${language}/model.mixed-fp16.onnx`
    const cpuModelPath = `${cpuModelsRoot}/${language}/model.uint8.onnx`
    const languageOutPath = `${outRoot}/models/${language}/${'index.ts'}`

    const [tokenizer, gpuModel, cpuModel] = await Promise.all([
      readFile(tokenizerPath),
      readFile(gpuModelPath),
      readFile(cpuModelPath),
    ])

    const tokenizerBase64 = JSON.stringify(
      toBase64String(await toCompressed(tokenizer))
    )
    const gpuModelBase64 = JSON.stringify(
      toBase64String(await toCompressed(gpuModel))
    )
    const cpuModelBase64 = JSON.stringify(
      toBase64String(await toCompressed(cpuModel))
    )

    const ts = `
  import { fromCompressed, fromBase64String } from '@sovereignbase/bytecodec'

  export async function tokenizer${language.toUpperCase()}(): Promise<Uint8Array> {
        return  await fromCompressed(fromBase64String(${tokenizerBase64}))
  }
   export async function gpuModel${language.toUpperCase()}(): Promise<Uint8Array> {
        return  await fromCompressed(fromBase64String(${gpuModelBase64}))
  }
   export async function cpuModel${language.toUpperCase()}(): Promise<Uint8Array> {
        return  await fromCompressed(fromBase64String(${cpuModelBase64}))
  }

`.trimStart()

    await mkdir(dirname(languageOutPath), { recursive: true })
    await writeFile(languageOutPath, ts, 'utf8')
  }
  await writeEntrypoint(outRoot, languages)
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
