#!/usr/bin/env node
import { dirname } from 'path'
import {getArgs} from "../utils/getArgs"
import { mkdir, readFile, writeFile } from 'fs/promises'
import { toCompressed, toBase64UrlString } from '@z-base/bytecodec'

const js = String.raw

async function main() {
const { languages } = getArgs()
for (const language of languages) {

const tokenizerModelPath = `./src/03_tokenizers/${language}/tokenizer.model`
const webgpuModelPath = `./src/07_mixed-fp16_gpu_onnx_models/${language}/tokenizer.model`
const wasmModelPath = `./src/08_uint8_cpu_onnx_models/${language}/model.int4.onnx`


const outPath = './src/09_autogenerated_typescript_project/index.ts'

const [model tokenizerModel] = await Promise.all([
  readFile(modelPath),
  readFile(tokenizerModelPath),
])

const modelBase64Url = JSON.stringify(
  toBase64UrlString(await toCompressed(model))
)
const modelDataBase64Url = JSON.stringify(
  toBase64UrlString(await toCompressed(modelData))
)
const tokenizerModelBase64 = JSON.stringify(tokenizerModel.toString('base64'))

const ts = js`
  import * as ort from "onnxruntime-web";
  import { SentencePieceProcessor } from "@sctg/sentencepiece-js";
  import { fromCompressed, fromBase64UrlString } from "@z-base/bytecodec";

  export async function createInferenceSession(): Promise<ort.InferenceSession> {
    return ort.InferenceSession.create(
      await fromCompressed(fromBase64UrlString(${modelBase64Url})),
      {
        externalData: [
          {
            path: "model.int4.onnx.data",
            data: await fromCompressed(
              fromBase64UrlString(${modelDataBase64Url})
            )
          }
        ]
      }
    );
  }

  export async function createTokenProcessor(): Promise<SentencePieceProcessor> {
    const tokenProcessor = new SentencePieceProcessor();
    await tokenProcessor.loadFromB64StringModel(${tokenizerModelBase64});
    return tokenProcessor;
  }
`.trimStart()

await mkdir(dirname(outPath), { recursive: true })
await writeFile(outPath, ts, 'utf8')
}
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})